import { CityPantry } from '@/lib/types';

export const assisi: CityPantry = {
  id: 'assisi',
  name: 'Assisi',
  neighbourhoods: ['Centro Storico', 'San Francesco', 'Santa Chiara', 'Rocca Maggiore'],
  places: [
    // BARS/CAFÉS (3)
    {
      id: 'caffe-duomo',
      name: 'Caffè del Duomo',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'marco-bartoli',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional Italian café with outdoor tables overlooking the cathedral, warm ochre and cream building facade, green awning, morning light casting gentle shadows, potted geraniums, textured stone walls',
    },
    {
      id: 'bar-senso',
      name: 'Bar Senso',
      kind: 'bar',
      neighbourhood: 'San Francesco',
      real: true,
      characterId: 'giulia-rossi',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy neighborhood bar with vintage coffee machine visible through window, soft pink and beige tones, wooden door, chalkboard menu, inviting warm glow from interior',
    },
    {
      id: 'caffe-santa-chiara',
      name: 'Caffè Santa Chiara',
      kind: 'bar',
      neighbourhood: 'Santa Chiara',
      real: false,
      characterId: 'alessandro-bianchi',
      imagePrompt: 'Soft pastel sketch on white paper of a corner café with arched doorway, terracotta and cream colors, hanging baskets of flowers, small round tables outside, view of basilica in background, atmospheric morning mist',
    },
    
    // BAKERIES (2)
    {
      id: 'forno-santa-maria',
      name: 'Forno Santa Maria',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'teresa-mancini',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional stone bakery with wooden shelves visible through window, golden wheat and warm brown tones, bread loaves in display, ancient archway entrance, rustic charm',
    },
    {
      id: 'pasticceria-san-francesco',
      name: 'Pasticceria San Francesco',
      kind: 'bakery',
      neighbourhood: 'San Francesco',
      real: false,
      characterId: 'roberto-falchi',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant pastry shop with glass display cases, soft pink and gold tones, decorative window with sweets, medieval stone street setting, inviting and sweet atmosphere',
    },
    
    // MARKETS (3)
    {
      id: 'mercato-coperto',
      name: 'Mercato Coperto di Assisi',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'vincenzo-monti',
      imagePrompt: 'Soft pastel sketch on white paper of a covered market hall with stone arches, vibrant fruit and vegetable stalls, warm terracotta roof, baskets of produce, dappled light through openings, bustling atmosphere',
    },
    {
      id: 'mercato-piazza',
      name: 'Mercato del Sabato',
      kind: 'market',
      neighbourhood: 'Santa Chiara',
      real: false,
      characterId: 'anna-sabatini',
      imagePrompt: 'Soft pastel sketch on white paper of an open-air Saturday market in historic piazza, colorful vendor stalls with striped awnings, fresh produce displays, medieval buildings surrounding, lively morning scene',
    },
    {
      id: 'bottega-umbra',
      name: 'Bottega Umbra',
      kind: 'market',
      neighbourhood: 'San Francesco',
      real: false,
      characterId: 'franco-neri',
      imagePrompt: 'Soft pastel sketch on white paper of a specialty food shop with hanging salumi, shelves of local products, warm amber lighting, stone interior, jars of preserves, authentic Umbrian atmosphere',
    },
    
    // RESTAURANTS (2)
    {
      id: 'ristorante-metastasio',
      name: 'Ristorante Metastasio',
      kind: 'ristorante',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'lucia-greco',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant restaurant entrance with stone archway, white tablecloths visible through windows, soft golden light, climbing vines, sophisticated yet warm atmosphere',
    },
    {
      id: 'ristorante-fortezza',
      name: 'Ristorante La Fortezza',
      kind: 'ristorante',
      neighbourhood: 'Rocca Maggiore',
      real: false,
      characterId: 'paolo-moretti',
      imagePrompt: 'Soft pastel sketch on white paper of a hillside restaurant with panoramic terrace, soft purple and pink sunset tones, medieval fortress visible above, outdoor seating, romantic atmospheric lighting',
    },
    
    // SPECIALTY FOOD (2)
    {
      id: 'trattoria-erminio',
      name: 'Trattoria Erminio',
      kind: 'trattoria',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'erminio-bruschi',
      imagePrompt: 'Soft pastel sketch on white paper of a rustic trattoria with wooden beams, checked tablecloths, warm terracotta walls, family photos on walls, cozy intimate setting, traditional charm',
    },
    {
      id: 'osteria-fontemaggiore',
      name: 'Osteria Fontemaggiore',
      kind: 'osteria',
      neighbourhood: 'Santa Chiara',
      real: false,
      characterId: 'silvia-fontana',
      imagePrompt: 'Soft pastel sketch on white paper of a casual osteria with stone walls, wine barrels, strings of garlic and peppers, wooden tables, warm candlelight, authentic local atmosphere',
    },
    
    // MAJOR LANDMARK (1)
    {
      id: 'basilica-san-francesco',
      name: 'Basilica di San Francesco',
      kind: 'church',
      neighbourhood: 'San Francesco',
      real: true,
      characterId: 'padre-giovanni',
      imagePrompt: 'Soft pastel sketch on white paper of the grand basilica complex with distinctive architecture, pink and white stone, multiple levels, soft afternoon light, cypress trees, spiritual and majestic atmosphere',
    },
    
    // CHURCHES/CULTURAL SITES (2)
    {
      id: 'basilica-santa-chiara',
      name: 'Basilica di Santa Chiara',
      kind: 'church',
      neighbourhood: 'Santa Chiara',
      real: true,
      characterId: 'suor-maria',
      imagePrompt: 'Soft pastel sketch on white paper of the pink-stone basilica with flying buttresses, rose window, piazza in front, soft rose and cream tones, peaceful sacred atmosphere',
    },
    {
      id: 'tempio-minerva',
      name: 'Tempio di Minerva',
      kind: 'landmark',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'dottore-alberti',
      imagePrompt: 'Soft pastel sketch on white paper of ancient Roman temple with Corinthian columns, warm honey-colored stone, Piazza del Comune setting, historical layers visible, timeless atmosphere',
    },
    
    // PARK/GARDEN (1)
    {
      id: 'giardini-santa-chiara',
      name: 'Giardini di Santa Chiara',
      kind: 'park',
      neighbourhood: 'Santa Chiara',
      real: false,
      characterId: 'giorgio-benedetti',
      imagePrompt: 'Soft pastel sketch on white paper of peaceful garden terraces with olive trees, panoramic valley views, stone benches, lavender and rosemary bushes, soft green and purple tones, serene atmosphere',
    },
    
    // PIAZZAS (2)
    {
      id: 'piazza-comune',
      name: 'Piazza del Comune',
      kind: 'piazza',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'isabella-conti',
      imagePrompt: 'Soft pastel sketch on white paper of the main medieval square with ancient buildings, outdoor cafés, people strolling, warm evening light on stone pavement, fountain, vibrant social hub',
    },
    {
      id: 'piazza-san-rufino',
      name: 'Piazza San Rufino',
      kind: 'piazza',
      neighbourhood: 'Rocca Maggiore',
      real: true,
      characterId: 'matteo-galli',
      imagePrompt: 'Soft pastel sketch on white paper of a quieter square with cathedral facade, stone well, locals chatting, dappled shade from trees, peaceful neighborhood atmosphere',
    },
    
    // WINE BARS/APERITIVO (2)
    {
      id: 'enoteca-properzio',
      name: 'Enoteca Properzio',
      kind: 'enoteca',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'andrea-carli',
      imagePrompt: 'Soft pastel sketch on white paper of an intimate wine bar with vaulted brick ceiling, wooden wine racks, soft amber lighting, small tasting tables, sophisticated yet welcoming atmosphere',
    },
    {
      id: 'wine-bar-bibendum',
      name: 'Bibendum Wine Bar',
      kind: 'wine_bar',
      neighbourhood: 'Santa Chiara',
      real: false,
      characterId: 'valentina-toscano',
      imagePrompt: 'Soft pastel sketch on white paper of a modern wine bar with stone walls, contemporary lighting, bottles displayed artistically, aperitivo spread visible, elegant evening atmosphere',
    },
    
    // BOOKSHOP/CULTURAL (1)
    {
      id: 'libreria-san-francesco',
      name: 'Libreria San Francesco',
      kind: 'bookshop',
      neighbourhood: 'San Francesco',
      real: false,
      characterId: 'elena-marchetti',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy bookshop with wooden shelves floor to ceiling, reading nook by window, warm lamp light, religious and literary books, peaceful scholarly atmosphere',
    },
    
    // PRACTICAL (2)
    {
      id: 'farmacia-centrale',
      name: 'Farmacia Centrale',
      kind: 'pharmacy',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'dottoressa-martini',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional pharmacy with green cross sign, antique wooden cabinets, modern counter, professional yet warm atmosphere, medieval building setting',
    },
    {
      id: 'tabaccheria-assisi',
      name: 'Tabaccheria del Centro',
      kind: 'shop',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'giuseppe-ricci',
      imagePrompt: 'Soft pastel sketch on white paper of a small tobacco shop with newspapers displayed, lottery tickets, stamps, local character gathering spot, warm neighborhood feel',
    },
    
    // CITY CHARACTER (3 unique to Assisi)
    {
      id: 'rocca-maggiore',
      name: 'Rocca Maggiore',
      kind: 'landmark',
      neighbourhood: 'Rocca Maggiore',
      real: true,
      characterId: 'alberto-ferretti',
      imagePrompt: 'Soft pastel sketch on white paper of medieval fortress on hilltop, stone walls and towers, panoramic views over valley, soft golden sunset light, commanding presence, historical majesty',
    },
    {
      id: 'eremo-carceri',
      name: 'Eremo delle Carceri',
      kind: 'church',
      neighbourhood: 'Rocca Maggiore',
      real: true,
      characterId: 'fra-antonio',
      imagePrompt: 'Soft pastel sketch on white paper of hermitage nestled in wooded mountainside, ancient oak trees, stone chapel, peaceful forest setting, soft green and gray tones, spiritual retreat atmosphere',
    },
    {
      id: 'museo-diocesano',
      name: 'Museo Diocesano',
      kind: 'landmark',
      neighbourhood: 'San Francesco',
      real: true,
      characterId: 'clara-russo',
      imagePrompt: 'Soft pastel sketch on white paper of museum entrance in historic building, religious artworks visible, vaulted corridors, soft gallery lighting, cultural treasure atmosphere',
    },
    {
      id: 'laboratorio-ceramiche',
      name: 'Laboratorio Ceramiche Assisi',
      kind: 'shop',
      neighbourhood: 'Santa Chiara',
      real: false,
      characterId: 'marco-angelini',
      imagePrompt: 'Soft pastel sketch on white paper of artisan ceramic workshop with colorful pottery displayed, traditional Deruta patterns, work table with clay, bright Mediterranean colors, creative artisan atmosphere',
    },
    {
      id: 'frantoi-assisi',
      name: 'Frantoio Assisi',
      kind: 'market',
      neighbourhood: 'Rocca Maggiore',
      real: false,
      characterId: 'domenico-petrucci',
      imagePrompt: 'Soft pastel sketch on white paper of olive oil mill with large stone press, bottles of golden-green oil, rustic interior, wooden beams, authentic Umbrian agricultural tradition',
    },
    {
      id: 'gelateria-santa-maria',
      name: 'Gelateria Santa Maria',
      kind: 'gelateria',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'federica-lenti',
      imagePrompt: 'Soft pastel sketch on white paper of charming gelato shop with colorful display cases, pastel pink and mint green decor, medieval stone archway, customers enjoying cones, sweet summer atmosphere',
    },
  ],
  characters: [
    {
      id: 'marco-bartoli',
      name: 'Marco Bartoli',
      age: 42,
      role: 'barista',
      placeId: 'caffe-duomo',
      personality: ['philosophical', 'observant', 'warm'],
      portraitPrompt: 'Pen and ink portrait on white paper of a man in his forties with salt-and-pepper hair, kind eyes with smile lines, wearing casual button-down shirt, minimal sepia watercolor wash, detailed cross-hatching, wise expression',
    },
    {
      id: 'giulia-rossi',
      name: 'Giulia Rossi',
      age: 29,
      role: 'barista',
      placeId: 'bar-senso',
      personality: ['energetic', 'friendly', 'chatty'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with dark wavy hair pulled back, bright smile, wearing apron, minimal warm watercolor wash on cheeks, expressive eyebrows, welcoming demeanor',
    },
    {
      id: 'alessandro-bianchi',
      name: 'Alessandro Bianchi',
      age: 55,
      role: 'proprietor',
      placeId: 'caffe-santa-chiara',
      personality: ['traditional', 'dignified', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished older man with graying hair, weathered face, wearing vest and tie, minimal gray watercolor wash, detailed fine lines, confident posture',
    },
    {
      id: 'teresa-mancini',
      name: 'Teresa Mancini',
      age: 38,
      role: 'baker',
      placeId: 'forno-santa-maria',
      personality: ['nurturing', 'skilled', 'early-riser'],
      portraitPrompt: 'Pen and ink portrait on white paper of a woman with flour-dusted apron, hair in practical bun, strong capable hands, minimal wheat-gold watercolor wash, warm smile, hardworking expression',
    },
    {
      id: 'roberto-falchi',
      name: 'Roberto Falchi',
      age: 46,
      role: 'pastry chef',
      placeId: 'pasticceria-san-francesco',
      personality: ['perfectionist', 'artistic', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a man with focused eyes, chef whites, slight smirk of pride, minimal pale watercolor wash, detailed shading, artistic temperament visible',
    },
    {
      id: 'vincenzo-monti',
      name: 'Vincenzo Monti',
      age: 62,
      role: 'produce vendor',
      placeId: 'mercato-coperto',
      personality: ['jovial', 'loud', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of an older man with weathered face, cap, full expressive features, minimal earth-tone watercolor wash, laugh lines, hands gesturing, robust presence',
    },
    {
      id: 'anna-sabatini',
      name: 'Anna Sabatini',
      age: 51,
      role: 'market vendor',
      placeId: 'mercato-piazza',
      personality: ['shrewd', 'fair', 'storyteller'],
      portraitPrompt: 'Pen and ink portrait on white paper of a woman with sharp intelligent eyes, headscarf, knowing smile, minimal terracotta watercolor wash, detailed expression lines, commanding presence',
    },
    {
      id: 'franco-neri',
      name: 'Franco Neri',
      age: 58,
      role: 'shopkeeper',
      placeId: 'bottega-umbra',
      personality: ['expert', 'passionate', 'local-proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy man with thick mustache, apron, holding salami, minimal warm brown watercolor wash, detailed facial hair, authentic character',
    },
    {
      id: 'lucia-greco',
      name: 'Lucia Greco',
      age: 44,
      role: 'chef',
      placeId: 'ristorante-metastasio',
      personality: ['refined', 'demanding', 'creative'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant woman with pulled-back hair, chef jacket, intense focused eyes, minimal cool watercolor wash, strong features, artistic authority',
    },
    {
      id: 'paolo-moretti',
      name: 'Paolo Moretti',
      age: 50,
      role: 'chef-owner',
      placeId: 'ristorante-fortezza',
      personality: ['romantic', 'hospitable', 'ambitious'],
      portraitPrompt: 'Pen and ink portrait on white paper of a handsome man with graying temples, warm smile, professional attire, minimal sunset-tone watercolor wash, welcoming expression, sophisticated air',
    },
    {
      id: 'erminio-bruschi',
      name: 'Erminio Bruschi',
      age: 71,
      role: 'owner',
      placeId: 'trattoria-erminio',
      personality: ['traditional', 'gruff-but-kind', 'family-oriented'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly man with deeply lined face, white hair, suspenders, minimal sepia watercolor wash, gentle eyes despite stern expression, grandfatherly',
    },
    {
      id: 'silvia-fontana',
      name: 'Silvia Fontana',
      age: 36,
      role: 'chef',
      placeId: 'osteria-fontemaggiore',
      personality: ['earthy', 'humorous', 'authentic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a woman with natural beauty, casual chef attire, genuine laugh, minimal rose watercolor wash, expressive face, down-to-earth charm',
    },
    {
      id: 'padre-giovanni',
      name: 'Padre Giovanni',
      age: 67,
      role: 'friar',
      placeId: 'basilica-san-francesco',
      personality: ['serene', 'wise', 'multilingual'],
      portraitPrompt: 'Pen and ink portrait on white paper of a gentle-faced friar in brown Franciscan robes, peaceful expression, kind eyes, minimal earth-tone watercolor wash, detailed habit folds, spiritual presence',
    },
    {
      id: 'suor-maria',
      name: 'Suor Maria Chiara',
      age: 45,
      role: 'nun',
      placeId: 'basilica-santa-chiara',
      personality: ['devoted', 'quiet', 'compassionate'],
      portraitPrompt: 'Pen and ink portrait on white paper of a nun in traditional habit, serene face, gentle smile, minimal soft gray watercolor wash, delicate features, peaceful demeanor',
    },
    {
      id: 'dottore-alberti',
      name: 'Dott. Stefano Alberti',
      age: 53,
      role: 'historian',
      placeId: 'tempio-minerva',
      personality: ['academic', 'enthusiastic', 'detailed'],
      portraitPrompt: 'Pen and ink portrait on white paper of a scholarly man with glasses, thoughtful expression, tweed jacket, minimal amber watercolor wash, intelligent eyes, professorial bearing',
    },
    {
      id: 'giorgio-benedetti',
      name: 'Giorgio Benedetti',
      age: 60,
      role: 'gardener',
      placeId: 'giardini-santa-chiara',
      personality: ['patient', 'contemplative', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a weathered man with sun-worn face, work clothes, calloused hands, minimal green watercolor wash, peaceful eyes, connected to earth',
    },
    {
      id: 'isabella-conti',
      name: 'Isabella Conti',
      age: 33,
      role: 'street performer',
      placeId: 'piazza-comune',
      personality: ['artistic', 'free-spirited', 'engaging'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with expressive features, flowing hair, artistic clothing, minimal vibrant watercolor wash, creative energy, bohemian charm',
    },
    {
      id: 'matteo-galli',
      name: 'Matteo Galli',
      age: 28,
      role: 'local guide',
      placeId: 'piazza-san-rufino',
      personality: ['outgoing', 'informative', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with friendly face, casual professional attire, enthusiastic expression, minimal warm watercolor wash, open demeanor',
    },
    {
      id: 'andrea-carli',
      name: 'Andrea Carli',
      age: 41,
      role: 'sommelier',
      placeId: 'enoteca-properzio',
      personality: ['sophisticated', 'passionate', 'discerning'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined man holding wine glass, thoughtful expression, stylish attire, minimal burgundy watercolor wash, connoisseur bearing',
    },
    {
      id: 'valentina-toscano',
      name: 'Valentina Toscano',
      age: 31,
      role: 'wine bar manager',
      placeId: 'wine-bar-bibendum',
      personality: ['modern', 'sociable', 'trendsetting'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stylish young woman with contemporary hairstyle, elegant but approachable, minimal wine-red watercolor wash, confident smile',
    },
    {
      id: 'elena-marchetti',
      name: 'Elena Marchetti',
      age: 56,
      role: 'bookseller',
      placeId: 'libreria-san-francesco',
      personality: ['literary', 'gentle', 'thoughtful'],
      portraitPrompt: 'Pen and ink portrait on white paper of a woman with reading glasses on chain, cardigan, holding book, minimal soft blue watercolor wash, intelligent kind eyes, scholarly warmth',
    },
    {
      id: 'dottoressa-martini',
      name: 'Dott.ssa Carla Martini',
      age: 48,
      role: 'pharmacist',
      placeId: 'farmacia-centrale',
      personality: ['professional', 'caring', 'precise'],
      portraitPrompt: 'Pen and ink portrait on white paper of a woman in white coat, neat hair, professional but warm expression, minimal green watercolor wash, competent demeanor',
    },
    {
      id: 'giuseppe-ricci',
      name: 'Giuseppe Ricci',
      age: 65,
      role: 'shopkeeper',
      placeId: 'tabaccheria-assisi',
      personality: ['gossipy', 'cheerful', 'informed'],
      portraitPrompt: 'Pen and ink portrait on white paper of an older man with expressive face, casual shirt, knowing smile, minimal warm watercolor wash, neighborhood character, twinkling eyes',
    },
    {
      id: 'alberto-ferretti',
      name: 'Alberto Ferretti',
      age: 39,
      role: 'castle guide',
      placeId: 'rocca-maggiore',
      personality: ['dramatic', 'historical', 'engaging'],
      portraitPrompt: 'Pen and ink portrait on white paper of a man with animated expression, gesturing hand, period-appropriate vest, minimal stone-gray watercolor wash, storyteller energy',
    },
    {
      id: 'fra-antonio',
      name: 'Fra Antonio',
      age: 52,
      role: 'hermit friar',
      placeId: 'eremo-carceri',
      personality: ['contemplative', 'sparse-spoken', 'spiritual'],
      portraitPrompt: 'Pen and ink portrait on white paper of a friar with deep contemplative eyes, simple robes, peaceful weathered face, minimal forest-green watercolor wash, meditative presence',
    },
    {
      id: 'clara-russo',
      name: 'Clara Russo',
      age: 43,
      role: 'museum curator',
      placeId: 'museo-diocesano',
      personality: ['knowledgeable', 'passionate', 'precise'],
      portraitPrompt: 'Pen and ink portrait on white paper of a woman with intellectual bearing, elegant professional attire, glasses, minimal museum-gold watercolor wash, cultured expression',
    },
    {
      id: 'marco-angelini',
      name: 'Marco Angelini',
      age: 37,
      role: 'ceramicist',
      placeId: 'laboratorio-ceramiche',
      personality: ['artistic', 'traditional', 'patient'],
      portraitPrompt: 'Pen and ink portrait on white paper of a man with clay-stained hands, artisan apron, focused creative eyes, minimal blue-and-yellow watercolor wash, craftsman pride',
    },
    {
      id: 'domenico-petrucci',
      name: 'Domenico Petrucci',
      age: 59,
      role: 'olive oil producer',
      placeId: 'frantoi-assisi',
      personality: ['traditional', 'quality-focused', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy man with work-worn hands, holding olive branch, minimal golden-green watercolor wash, generations of knowledge in face',
    },
    {
      id: 'federica-lenti',
      name: 'Federica Lenti',
      age: 26,
      role: 'gelato maker',
      placeId: 'gelateria-santa-maria',
      personality: ['sweet', 'creative', 'cheerful'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with bright smile, colorful apron, holding gelato scoop, minimal pastel watercolor wash, joyful energy, youthful charm',
    },
  ],
  food: [
    'torta al testo',
    'strangozzi al tartufo',
    'piccione alla leccarda',
    'crescia',
    'rocciata di Assisi',
    'friccò',
    'lenticchie di Castelluccio',
    'pane di San Francesco',
    'salame corallina',
    'pecorino umbro',
    'pasta alla norcina',
    'porchetta',
    'bruschetta al tartufo',
    'ciauscolo',
    'fave dei morti',
    'pinoccate',
  ],
  customs: [
    'Festa di San Francesco on October 4th with processions and candles',
    'Calendimaggio medieval spring festival with neighborhood competitions',
    'Evening passeggiata through Piazza del Comune',
    'Blessing of animals at San Francesco',
    'Silent respect when entering basilicas',
    'Pilgrimage walks to Eremo delle Carceri',
    'Truffle hunting season in autumn',
    'Olive harvest and pressing in November',
    'Afternoon riposo when shops close',
  ],
  localTouches: [
    '"Ecco qua!" - here we are (common greeting)',
    '"Poveretto" - poor thing (Franciscan influence)',
    '"Aho!" - hey! (local exclamation)',
    'Umbrian dialect softens standard Italian',
    '"Fà nà magna" - let\'s eat (dialectal)',
    '"Bella lì!" - nice there/well done',
    'Religious references in everyday speech',
    '"Dio bòna" - good God (local expression)',
    'Slower, melodic speech pattern',
    '"Sai" ending sentences - you know',
  ],
};
