import { CityPantry } from '@/lib/types';

export const bergamo: CityPantry = {
  id: 'bergamo',
  name: 'Bergamo',
  neighbourhoods: ['Città Alta', 'Città Bassa', 'Borgo Palazzo', 'Longuelo'],
  places: [
    // BARS & CAFÉS (9)
    {
      id: 'caffe-del-tasso',
      name: 'Caffè del Tasso',
      kind: 'bar',
      neighbourhood: 'Città Alta',
      real: true,
      characterId: 'marco-villa',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant historic café with arched portico, outdoor tables under cream-colored umbrellas, warm golden and terracotta tones, textured stone columns, inviting morning light filtering through, loose brushstrokes suggesting bustling atmosphere',
    },
    {
      id: 'bar-donizetti',
      name: 'Bar Donizetti',
      kind: 'bar',
      neighbourhood: 'Città Bassa',
      real: false,
      characterId: 'lucia-ferri',
      imagePrompt: 'Soft pastel sketch on white paper of a modern corner café with large windows, chrome espresso machine visible inside, warm amber and cream colors, textured sidewalk tables, morning sunlight, inviting neighborhood atmosphere with soft shadows',
    },
    {
      id: 'caffe-balzer',
      name: 'Caffè Balzer',
      kind: 'bar',
      neighbourhood: 'Città Alta',
      real: true,
      characterId: 'giuseppe-carrara',
      imagePrompt: 'Soft pastel sketch on white paper of a refined café with vintage wooden interior, pastel green and gold accents, textured marble countertop, warm intimate lighting, classic Bergamo elegance, inviting corner atmosphere',
    },
    {
      id: 'bar-milano',
      name: 'Bar Milano',
      kind: 'bar',
      neighbourhood: 'Borgo Palazzo',
      real: false,
      characterId: 'angela-rossi',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood bar with red awning, simple wooden chairs outside, warm ochre and cream tones, textured cobblestones, morning light, locals chatting, welcoming working-class atmosphere',
    },
    {
      id: 'pasticceria-caffe-nessi',
      name: 'Pasticceria Caffè Nessi',
      kind: 'bar',
      neighbourhood: 'Città Bassa',
      real: true,
      characterId: 'stefano-moretti',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant pasticceria café with display cases full of pastries, soft pink and cream colors, textured Art Nouveau details, warm inviting glow from within, morning atmosphere with delicate brushstrokes',
    },
    {
      id: 'bar-centrale',
      name: 'Bar Centrale',
      kind: 'bar',
      neighbourhood: 'Longuelo',
      real: false,
      characterId: 'rosa-colombo',
      imagePrompt: 'Soft pastel sketch on white paper of a simple local bar with newspaper rack outside, warm yellow and brown tones, textured brick facade, morning regulars visible through windows, authentic neighborhood feel',
    },
    {
      id: 'caffe-della-funicolare',
      name: 'Caffè della Funicolare',
      kind: 'bar',
      neighbourhood: 'Città Alta',
      real: false,
      characterId: 'alberto-bergamini',
      imagePrompt: 'Soft pastel sketch on white paper of a charming café near the funicular station, stone archways, warm amber and sage green tones, textured old walls, tourists and locals mixing, panoramic view hints in background',
    },
    {
      id: 'bar-sant-alessandro',
      name: "Bar Sant'Alessandro",
      kind: 'bar',
      neighbourhood: 'Città Bassa',
      real: false,
      characterId: 'chiara-galli',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy corner bar with plants in windows, soft green and cream palette, textured stucco walls, morning light through lace curtains, intimate neighborhood gathering spot',
    },
    {
      id: 'bar-polo',
      name: 'Bar Polo',
      kind: 'bar',
      neighbourhood: 'Borgo Palazzo',
      real: false,
      characterId: 'mario-biffi',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional workers bar with zinc counter visible, warm brown and red tones, textured tile floor, morning espresso rush atmosphere, authentic local character',
    },

    // BAKERIES (4)
    {
      id: 'panificio-tresoldi',
      name: 'Panificio Tresoldi',
      kind: 'bakery',
      neighbourhood: 'Città Alta',
      real: false,
      characterId: 'elena-tresoldi',
      imagePrompt: 'Soft pastel sketch on white paper of a rustic bakery with wooden shelves full of golden bread loaves, warm wheat and honey tones, textured flour-dusted surfaces, stone walls, inviting aroma suggested by warm colors',
    },
    {
      id: 'forno-san-lorenzo',
      name: 'Forno San Lorenzo',
      kind: 'bakery',
      neighbourhood: 'Città Bassa',
      real: false,
      characterId: 'franco-locatelli',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood bakery with tiled display window, crusty bread visible, warm amber and cream tones, textured brick oven glow, morning queue of locals, welcoming atmosphere',
    },
    {
      id: 'panificio-moderno',
      name: 'Panificio Moderno',
      kind: 'bakery',
      neighbourhood: 'Longuelo',
      real: false,
      characterId: 'silvia-pesenti',
      imagePrompt: 'Soft pastel sketch on white paper of a clean modern bakery with glass cases, focaccia and breadsticks visible, soft yellow and white palette, textured fresh-baked goods, bright morning light, family-friendly feel',
    },
    {
      id: 'pasticceria-cavour',
      name: 'Pasticceria Cavour',
      kind: 'bakery',
      neighbourhood: 'Città Bassa',
      real: true,
      characterId: 'paolo-cavalli',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant historic pasticceria with ornate display cases, delicate pastries, soft pink and gold tones, textured vintage details, morning light on sugar-dusted treats, refined atmosphere',
    },

    // MARKETS (3)
    {
      id: 'mercato-citta-alta',
      name: 'Mercato di Città Alta',
      kind: 'market',
      neighbourhood: 'Città Alta',
      real: false,
      characterId: 'giovanni-rota',
      imagePrompt: 'Soft pastel sketch on white paper of a small piazza market with colorful vegetable stalls, striped awnings, warm green and red produce tones, textured cobblestones, morning shoppers, medieval buildings in background',
    },
    {
      id: 'mercato-borgo-palazzo',
      name: 'Mercato di Borgo Palazzo',
      kind: 'market',
      neighbourhood: 'Borgo Palazzo',
      real: true,
      characterId: 'carla-ghisleni',
      imagePrompt: 'Soft pastel sketch on white paper of a bustling neighborhood market with fruit and vegetable stands, vibrant colors of produce, textured tarps and crates, morning light, locals with shopping bags, authentic working atmosphere',
    },
    {
      id: 'alimentari-donato',
      name: 'Alimentari Donato',
      kind: 'market',
      neighbourhood: 'Longuelo',
      real: false,
      characterId: 'donato-zonca',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional corner grocery with hanging salami, cheese wheels, shelves of pasta, warm ochre and red tones, textured wooden fixtures, neighborhood gathering spot atmosphere',
    },

    // RESTAURANTS (2)
    {
      id: 'ristorante-da-vittorio',
      name: 'Ristorante Da Vittorio',
      kind: 'ristorante',
      neighbourhood: 'Città Bassa',
      real: true,
      characterId: 'vittorio-cerea',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant restaurant exterior with sophisticated signage, warm golden lighting from windows, cream and burgundy tones, textured refined details, evening ambiance, Michelin-starred atmosphere',
    },
    {
      id: 'ristorante-colleoni',
      name: 'Ristorante Colleoni & DellAngelo',
      kind: 'ristorante',
      neighbourhood: 'Città Alta',
      real: true,
      characterId: 'massimo-villa',
      imagePrompt: 'Soft pastel sketch on white paper of a refined restaurant in historic setting, arched doorway, tables with white linens visible, warm amber and cream tones, textured ancient stone walls, Piazza Vecchia atmosphere',
    },

    // SPECIALTY FOOD (3)
    {
      id: 'trattoria-del-teatro',
      name: 'Trattoria del Teatro',
      kind: 'trattoria',
      neighbourhood: 'Città Alta',
      real: false,
      characterId: 'ornella-togni',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy trattoria with red-checked tablecloths, warm terracotta and cream colors, textured rustic walls, casoncelli posters, intimate neighborhood dining atmosphere',
    },
    {
      id: 'osteria-del-borgo',
      name: 'Osteria del Borgo',
      kind: 'osteria',
      neighbourhood: 'Borgo Palazzo',
      real: false,
      characterId: 'fabio-previtali',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional osteria with wooden beams, wine bottles lining walls, warm brown and ruby tones, textured stone interior, locals dining, authentic Bergamasque character',
    },
    {
      id: 'polenteria-valtellina',
      name: 'Polenteria Valtellina',
      kind: 'trattoria',
      neighbourhood: 'Città Bassa',
      real: false,
      characterId: 'bruno-arrigoni',
      imagePrompt: 'Soft pastel sketch on white paper of a rustic polenta specialist restaurant, copper pots visible, warm yellow and brown tones, textured mountain lodge atmosphere, steaming polenta suggested, hearty welcoming feel',
    },

    // LANDMARKS & CULTURAL (6)
    {
      id: 'piazza-vecchia',
      name: 'Piazza Vecchia',
      kind: 'piazza',
      neighbourhood: 'Città Alta',
      real: true,
      characterId: 'leonardo-marchesi',
      imagePrompt: 'Soft pastel sketch on white paper of the magnificent main piazza with Palazzo della Ragione, fountain in center, warm honey-colored stone buildings, textured Renaissance architecture, evening light, people gathering, iconic Bergamo beauty',
    },
    {
      id: 'basilica-santa-maria-maggiore',
      name: 'Basilica di Santa Maria Maggiore',
      kind: 'church',
      neighbourhood: 'Città Alta',
      real: true,
      characterId: 'padre-francesco',
      imagePrompt: 'Soft pastel sketch on white paper of an ornate Romanesque basilica facade, warm cream and rose marble tones, textured intricate carvings, arched doorways, spiritual atmosphere, ancient beauty in soft light',
    },
    {
      id: 'cappella-colleoni',
      name: 'Cappella Colleoni',
      neighbourhood: 'Città Alta',
      kind: 'church',
      real: true,
      characterId: 'anna-santoro',
      imagePrompt: 'Soft pastel sketch on white paper of an elaborate Renaissance chapel with colorful marble facade, pink and white geometric patterns, textured sculptural details, jewel-box beauty, warm afternoon light',
    },
    {
      id: 'rocca-di-bergamo',
      name: 'Rocca di Bergamo',
      kind: 'landmark',
      neighbourhood: 'Città Alta',
      real: true,
      characterId: 'pietro-conti',
      imagePrompt: 'Soft pastel sketch on white paper of a hilltop fortress with Venetian walls, panoramic city views, warm stone and green landscape tones, textured ancient fortifications, cypress trees, commanding presence',
    },
    {
      id: 'parco-della-trucca',
      name: 'Parco della Trucca',
      kind: 'park',
      neighbourhood: 'Città Alta',
      real: true,
      characterId: 'giulia-mazzoleni',
      imagePrompt: 'Soft pastel sketch on white paper of a terraced hillside park with walking paths, flowering trees, warm green and pink spring tones, textured grass and stonework, views of lower city, peaceful atmospheric quality',
    },
    {
      id: 'sentierone',
      name: 'Il Sentierone',
      kind: 'piazza',
      neighbourhood: 'Città Bassa',
      real: true,
      characterId: 'federico-ruggeri',
      imagePrompt: 'Soft pastel sketch on white paper of a tree-lined urban promenade with café tables, warm dappled sunlight, green and cream tones, textured pavement, people strolling, modern city heart atmosphere',
    },

    // WINE BARS & EVENING (2)
    {
      id: 'enoteca-del-malpaga',
      name: 'Enoteca del Malpaga',
      kind: 'enoteca',
      neighbourhood: 'Città Alta',
      real: false,
      characterId: 'luca-belotti',
      imagePrompt: 'Soft pastel sketch on white paper of an intimate wine bar with bottles lining brick walls, warm amber and burgundy tones, textured wooden bar, soft evening candlelight, aperitivo spread visible, sophisticated atmosphere',
    },
    {
      id: 'vineria-cozzi',
      name: 'Vineria Cozzi',
      kind: 'enoteca',
      neighbourhood: 'Città Bassa',
      real: true,
      characterId: 'antonio-cozzi',
      imagePrompt: 'Soft pastel sketch on white paper of a historic wine shop with vintage bottles, wood paneling, warm sepia and wine-red tones, textured aged interior, evening aperitivo crowd, traditional Bergamo character',
    },

    // CULTURAL SHOPS (1)
    {
      id: 'libreria-sant-agostino',
      name: "Libreria Sant'Agostino",
      kind: 'bookshop',
      neighbourhood: 'Città Bassa',
      real: false,
      characterId: 'beatrice-castelli',
      imagePrompt: 'Soft pastel sketch on white paper of an independent bookshop with wooden shelves, book-lined walls, warm ochre and forest green tones, textured vintage atmosphere, reading nook visible, intellectual cozy feel',
    },

    // PRACTICAL (2)
    {
      id: 'farmacia-centrale',
      name: 'Farmacia Centrale',
      kind: 'pharmacy',
      neighbourhood: 'Città Bassa',
      real: false,
      characterId: 'dottoressa-marini',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional pharmacy with green cross sign, wooden cabinets visible through window, clean white and green tones, textured professional atmosphere, neighborhood healthcare hub',
    },
    {
      id: 'funicolare-bergamo-alta',
      name: 'Funicolare Bergamo Alta',
      kind: 'transport',
      neighbourhood: 'Città Alta',
      real: true,
      characterId: 'michele-pezzotta',
      imagePrompt: 'Soft pastel sketch on white paper of the historic funicular station with red cable car, Art Nouveau details, warm red and cream tones, textured vintage railway charm, tourists and locals waiting, iconic connection between cities',
    },

    // CITY CHARACTER (2)
    {
      id: 'teatro-donizetti',
      name: 'Teatro Donizetti',
      kind: 'landmark',
      neighbourhood: 'Città Bassa',
      real: true,
      characterId: 'maestro-grassi',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant neoclassical theater facade, columns and archways, warm golden and cream tones, textured ornate details, evening cultural life, Bergamo\'s operatic heritage visible',
    },
    {
      id: 'accademia-carrara',
      name: 'Accademia Carrara',
      kind: 'landmark',
      neighbourhood: 'Città Bassa',
      real: true,
      characterId: 'clara-bellini',
      imagePrompt: 'Soft pastel sketch on white paper of a distinguished art museum building, neoclassical architecture, warm stone and terracotta tones, textured elegant facade, masterpiece collection atmosphere, cultural pride of Bergamo',
    },
  ],
  
  characters: [
    {
      id: 'marco-villa',
      name: 'Marco Villa',
      age: 52,
      role: 'proprietario',
      placeId: 'caffe-del-tasso',
      personality: ['tradizionale', 'orgoglioso', 'filosofico'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man in his fifties with salt-and-pepper hair, strong nose, wearing a vest and tie, minimal sepia watercolor wash on face, detailed crosshatching, warm wise eyes, proud Bergamasco expression',
    },
    {
      id: 'lucia-ferri',
      name: 'Lucia Ferri',
      age: 28,
      role: 'barista',
      placeId: 'bar-donizetti',
      personality: ['energica', 'moderna', 'chiacchierona'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with short dark hair, bright eyes, wearing modern barista apron, minimal coffee-toned watercolor wash, detailed expressive linework, friendly smile, contemporary Bergamo spirit',
    },
    {
      id: 'giuseppe-carrara',
      name: 'Giuseppe Carrara',
      age: 67,
      role: 'cameriere storico',
      placeId: 'caffe-balzer',
      personality: ['elegante', 'discreto', 'memorabile'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly refined waiter with white hair, impeccable posture, bow tie, minimal gray watercolor wash, detailed dignified features, knowing eyes, old-school service excellence',
    },
    {
      id: 'angela-rossi',
      name: 'Angela Rossi',
      age: 45,
      role: 'proprietaria',
      placeId: 'bar-milano',
      personality: ['materna', 'pratica', 'affettuosa'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warm middle-aged woman with pulled-back hair, laugh lines, wearing simple work clothes, minimal warm watercolor wash, detailed caring expression, neighborhood mother figure',
    },
    {
      id: 'stefano-moretti',
      name: 'Stefano Moretti',
      age: 38,
      role: 'pasticciere',
      placeId: 'pasticceria-caffe-nessi',
      personality: ['perfezionista', 'creativo', 'ambizioso'],
      portraitPrompt: 'Pen and ink portrait on white paper of a focused man in his thirties with chef whites, intense eyes, slight flour dusting suggested, minimal warm watercolor wash, detailed precise features, artistic pastry chef concentration',
    },
    {
      id: 'rosa-colombo',
      name: 'Rosa Colombo',
      age: 59,
      role: 'barista',
      placeId: 'bar-centrale',
      personality: ['diretta', 'generosa', 'curiosa'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy woman with short graying hair, strong features, wearing work apron, minimal earth-toned watercolor wash, detailed expressive face, no-nonsense neighborhood character',
    },
    {
      id: 'alberto-bergamini',
      name: 'Alberto Bergamini',
      age: 31,
      role: 'barista',
      placeId: 'caffe-della-funicolare',
      personality: ['cosmopolita', 'paziente', 'informato'],
      portraitPrompt: 'Pen and ink portrait on white paper of a friendly young man with modern glasses, neat beard, casual style, minimal blue watercolor wash, detailed open expression, helpful tourist-friendly demeanor',
    },
    {
      id: 'chiara-galli',
      name: 'Chiara Galli',
      age: 26,
      role: 'barista',
      placeId: 'bar-sant-alessandro',
      personality: ['artistica', 'tranquilla', 'pensierosa'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with long wavy hair, gentle features, wearing simple linen, minimal green watercolor wash, detailed dreamy eyes, artistic café worker sensibility',
    },
    {
      id: 'mario-biffi',
      name: 'Mario Biffi',
      age: 55,
      role: 'proprietario',
      placeId: 'bar-polo',
      personality: ['schietto', 'leale', 'lavoratore'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stocky man with receding hair, strong hands, work shirt, minimal sepia watercolor wash, detailed working-class dignity, straightforward honest Bergamasco face',
    },
    {
      id: 'elena-tresoldi',
      name: 'Elena Tresoldi',
      age: 42,
      role: 'fornaia',
      placeId: 'panificio-tresoldi',
      personality: ['allegra', 'tradizionale', 'premurosa'],
      portraitPrompt: 'Pen and ink portrait on white paper of a cheerful woman with flour-dusted apron, warm smile, hair in bun, minimal wheat-toned watercolor wash, detailed laugh lines, welcoming baker warmth',
    },
    {
      id: 'franco-locatelli',
      name: 'Franco Locatelli',
      age: 61,
      role: 'fornaio',
      placeId: 'forno-san-lorenzo',
      personality: ['rigoroso', 'esperto', 'orgoglioso'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy older man with strong forearms, baker cap, flour on clothes, minimal warm watercolor wash, detailed weathered hands, master baker authority',
    },
    {
      id: 'silvia-pesenti',
      name: 'Silvia Pesenti',
      age: 34,
      role: 'fornaia',
      placeId: 'panificio-moderno',
      personality: ['efficiente', 'sorridente', 'attenta'],
      portraitPrompt: 'Pen and ink portrait on white paper of a confident woman with practical short hair, modern hygiene cap, bright eyes, minimal yellow watercolor wash, detailed professional but warm expression',
    },
    {
      id: 'paolo-cavalli',
      name: 'Paolo Cavalli',
      age: 49,
      role: 'pasticciere maestro',
      placeId: 'pasticceria-cavour',
      personality: ['raffinato', 'esigente', 'rispettato'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant man in pristine chef whites, distinguished features, neat appearance, minimal gold watercolor wash, detailed refined expression, master pastry chef pride',
    },
    {
      id: 'giovanni-rota',
      name: 'Giovanni Rota',
      age: 58,
      role: 'fruttivendolo',
      placeId: 'mercato-citta-alta',
      personality: ['vivace', 'scherzoso', 'generoso'],
      portraitPrompt: 'Pen and ink portrait on white paper of a jovial man with weathered face, work vest over shirt, hands like tree roots, minimal green watercolor wash, detailed character-filled features, market vendor vitality',
    },
    {
      id: 'carla-ghisleni',
      name: 'Carla Ghisleni',
      age: 52,
      role: 'commerciante',
      placeId: 'mercato-borgo-palazzo',
      personality: ['forte', 'competente', 'rispettata'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust woman with pulled-back hair, market apron, confident stance, minimal red watercolor wash, detailed strong features, marketplace authority',
    },
    {
      id: 'donato-zonca',
      name: 'Donato Zonca',
      age: 71,
      role: 'negoziante',
      placeId: 'alimentari-donato',
      personality: ['saggio', 'paziente', 'narratore'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly shopkeeper with kind eyes, apron over cardigan, gentle smile, minimal warm watercolor wash, detailed wise weathered face, neighborhood historian presence',
    },
    {
      id: 'vittorio-cerea',
      name: 'Vittorio Cerea',
      age: 56,
      role: 'chef stellato',
      placeId: 'ristorante-da-vittorio',
      personality: ['visionario', 'appassionato', 'esigente'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished chef with penetrating gaze, chef whites, confident bearing, minimal burgundy watercolor wash, detailed intense features, Michelin-starred excellence',
    },
    {
      id: 'massimo-villa',
      name: 'Massimo Villa',
      age: 47,
      role: 'chef proprietario',
      placeId: 'ristorante-colleoni',
      personality: ['elegante', 'colto', 'diplomatico'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined man with neat appearance, chef coat, sophisticated air, minimal cream watercolor wash, detailed intelligent features, historic restaurant dignity',
    },
    {
      id: 'ornella-togni',
      name: 'Ornella Togni',
      age: 63,
      role: 'cuoca e proprietaria',
      placeId: 'trattoria-del-teatro',
      personality: ['materna', 'tradizionale', 'accogliente'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warm grandmother figure with ample form, apron with stains of cooking, loving expression, minimal terracotta watercolor wash, detailed nurturing face, home cooking embodied',
    },
    {
      id: 'fabio-previtali',
      name: 'Fabio Previtali',
      age: 44,
      role: 'oste',
      placeId: 'osteria-del-borgo',
      personality: ['conviviale', 'generoso', 'storyteller'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust man with ready laugh, wine-stained apron, expressive hands, minimal wine-red watercolor wash, detailed jovial features, osteria host warmth',
    },
    {
      id: 'bruno-arrigoni',
      name: 'Bruno Arrigoni',
      age: 66,
      role: 'cuoco specializzato',
      placeId: 'polenteria-valtellina',
      personality: ['rustico', 'autentico', 'diretto'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy mountain man type with strong hands, simple cook attire, honest face, minimal yellow watercolor wash, detailed rugged features, polenta master character',
    },
    {
      id: 'leonardo-marchesi',
      name: 'Leonardo Marchesi',
      age: 35,
      role: 'guida turistica',
      placeId: 'piazza-vecchia',
      personality: ['eloquente', 'appassionato', 'erudito'],
      portraitPrompt: 'Pen and ink portrait on white paper of an animated young man with expressive gestures captured, stylish casual clothes, intelligent eyes, minimal amber watercolor wash, detailed enthusiastic features, passionate guide energy',
    },
    {
      id: 'padre-francesco',
      name: 'Padre Francesco',
      age: 69,
      role: 'sacerdote',
      placeId: 'basilica-santa-maria-maggiore',
      personality: ['sereno', 'contemplativo', 'accogliente'],
      portraitPrompt: 'Pen and ink portrait on white paper of a gentle elderly priest with white hair, simple cassock, peaceful expression, minimal soft gray watercolor wash, detailed kind spiritual face, quiet devotion',
    },
    {
      id: 'anna-santoro',
      name: 'Anna Santoro',
      age: 41,
      role: 'storica dell\'arte',
      placeId: 'cappella-colleoni',
      personality: ['precisa', 'entusiasta', 'educatrice'],
      portraitPrompt: 'Pen and ink portrait on white paper of a scholarly woman with glasses, elegant scarf, notebook in hand suggested, minimal rose watercolor wash, detailed intelligent animated features, art historian passion',
    },
    {
      id: 'pietro-conti',
      name: 'Pietro Conti',
      age: 57,
      role: 'custode',
      placeId: 'rocca-di-bergamo',
      personality: ['protettivo', 'fiero', 'informato'],
      portraitPrompt: 'Pen and ink portrait on white paper of a solid man with weathered face, utility jacket, watchful eyes, minimal stone-gray watercolor wash, detailed guardian features, fortress keeper bearing',
    },
    {
      id: 'giulia-mazzoleni',
      name: 'Giulia Mazzoleni',
      age: 29,
      role: 'giardiniera comunale',
      placeId: 'parco-della-trucca',
      personality: ['attiva', 'naturalista', 'solare'],
      portraitPrompt: 'Pen and ink portrait on white paper of a fit young woman in work clothes, sun-touched face, gardening gloves suggested, minimal green watercolor wash, detailed outdoor worker vitality, love of nature evident',
    },
    {
      id: 'federico-ruggeri',
      name: 'Federico Ruggeri',
      age: 33,
      role: 'musicista di strada',
      placeId: 'sentierone',
      personality: ['artistico', 'libero', 'socievole'],
      portraitPrompt: 'Pen and ink portrait on white paper of a bohemian young man with slightly long hair, casual artistic style, guitar strap suggested, minimal blue watercolor wash, detailed creative expressive face, street musician soul',
    },
    {
      id: 'luca-belotti',
      name: 'Luca Belotti',
      age: 39,
      role: 'sommelier',
      placeId: 'enoteca-del-malpaga',
      personality: ['raffinato', 'appassionato', 'conoscitore'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sophisticated man with neat beard, wine-tasting medallion suggested, discerning eyes, minimal burgundy watercolor wash, detailed refined features, sommelier expertise',
    },
    {
      id: 'antonio-cozzi',
      name: 'Antonio Cozzi',
      age: 68,
      role: 'proprietario storico',
      placeId: 'vineria-cozzi',
      personality: ['tradizionale', 'esperto', 'nostalgico'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly wine merchant with gentle features, vest and rolled sleeves, lifetime of wine knowledge in eyes, minimal wine-red watercolor wash, detailed venerable face',
    },
    {
      id: 'beatrice-castelli',
      name: 'Beatrice Castelli',
      age: 36,
      role: 'libraia',
      placeId: 'libreria-sant-agostino',
      personality: ['colta', 'consigliosa', 'riservata'],
      portraitPrompt: 'Pen and ink portrait on white paper of an intellectual woman with reading glasses, book in hand suggested, thoughtful expression, minimal sepia watercolor wash, detailed literary sensibility, bookseller wisdom',
    },
    {
      id: 'dottoressa-marini',
      name: 'Dottoressa Marini',
      age: 48,
      role: 'farmacista',
      placeId: 'farmacia-centrale',
      personality: ['professionale', 'attenta', 'rassicurante'],
      portraitPrompt: 'Pen and ink portrait on white paper of a composed woman in white coat, hair neatly arranged, caring but professional expression, minimal white-green watercolor wash, detailed trustworthy features, pharmacist competence',
    },
    {
      id: 'michele-pezzotta',
      name: 'Michele Pezzotta',
      age: 51,
      role: 'macchinista della funicolare',
      placeId: 'funicolare-bergamo-alta',
      personality: ['preciso', 'orgoglioso', 'puntuale'],
      portraitPrompt: 'Pen and ink portrait on white paper of a neat man in uniform cap, steady hands suggested, responsible expression, minimal red watercolor wash, detailed trustworthy features, funicular operator pride',
    },
    {
      id: 'maestro-grassi',
      name: 'Maestro Grassi',
      age: 64,
      role: 'direttore d\'orchestra',
      placeId: 'teatro-donizetti',
      personality: ['drammatico', 'esigente', 'appassionato'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished conductor with expressive hands mid-gesture, formal concert attire, intense musical gaze, minimal gold watercolor wash, detailed dramatic features, operatic passion',
    },
    {
      id: 'clara-bellini',
      name: 'Clara Bellini',
      age: 43,
      role: 'curatrice museale',
      placeId: 'accademia-carrara',
      personality: ['elegante', 'colta', 'precisa'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined woman with sophisticated style, art catalog suggested, discerning eyes, minimal terracotta watercolor wash, detailed cultured features, museum curator authority',
    },
  ],

  food: [
    'casoncelli alla bergamasca',
    'polenta e osei',
    'polenta taragna',
    'scarpinocc',
    'polenta e coniglio',
    'stracciatella bergamasca',
    'formai de mut',
    'taleggio',
    'salame bergamasco',
    'polenta con burro e formaggio',
    'tortelli cremaschi',
    'brasato di manzo',
    'rosticiada',
    'polenta fritta',
    'pizzoccheri',
    'cotoletta alla milanese',
    'risotto alla bergamasca',
    'donizetti (dolce)',
    'polenta e latte',
    'missoltini',
  ],

  customs: [
    'Taking the funicolare between Città Alta and Città Bassa',
    'Evening passeggiata along Il Sentierone',
    'Aperitivo time at 7pm with local wines',
    'Sunday market shopping in Borgo Palazzo',
    'Attending opera at Teatro Donizetti during the season',
    'Walking the Venetian walls at sunset',
    'Coffee at historic bars in Piazza Vecchia',
    'Weekend lunch with polenta and game meat',
    'Celebrating Sant\'Alessandro, patron saint (August 26)',
    'Festival Donizetti in autumn',
    'Shopping for cheese at neighborhood alimentari',
    'Traditional Sunday pranzo with extended family',
  ],

  localTouches: [
    'Saying "Olà" as a greeting (Bergamasco dialect)',
    'Using "ü" sound characteristic of Bergamasco',
    'Calling upper city "Sità Alta" in dialect',
    'Referring to polenta as the soul of Bergamo',
    'Pride in being "bergamaschi" - known for hard work',
    'Saying "ciao bèi" (hello beautiful) casually',
    'Mentioning "i öcc" (the eyes) in expressions',
    'Using "amò" (ancora/still)',
    'Strong local pride in Atalanta football club',
    'Reference to "l\'Éco di Bergamo" local newspaper',
    'Bergamasco saying: "Polénta e öcc tórt" (polenta and birds)',
    'Distinction between "de sóra" (up high) and "de sóta" (down low)',
  ],
};
