import { CityPantry } from '@/lib/types';

export const bologna: CityPantry = {
  id: 'bologna',
  name: 'Bologna',
  neighbourhoods: ['Centro Storico', 'Quartiere Universitario', 'Santo Stefano', 'Saragozza'],
  places: [
    // BARS & CAFÉS (3)
    {
      id: 'caffe-terzi',
      name: 'Caffè Terzi',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'marco-terzi',
      imagePrompt: 'Soft pastel sketch on white paper of a historic coffee bar with gleaming espresso machines, shelves of coffee beans in burlap sacks, marble counter with pastries under glass domes, warm amber and cream tones, morning light streaming through large windows, textured walls with vintage coffee posters, inviting and aromatic atmosphere',
    },
    {
      id: 'bar-senza-nome',
      name: 'Bar Senza Nome',
      kind: 'bar',
      neighbourhood: 'Quartiere Universitario',
      real: false,
      characterId: 'giulia-morandi',
      imagePrompt: 'Soft pastel sketch on white paper of a student-favorite café with mismatched chairs, chalkboard menu, bicycle parked outside, books and newspapers scattered on wooden tables, warm terracotta and sage green colors, exposed brick walls, sunlight filtering through ivy-covered windows, bohemian and welcoming feel',
    },
    {
      id: 'pasticceria-regina',
      name: 'Pasticceria Regina di Quadri',
      kind: 'bar',
      neighbourhood: 'Santo Stefano',
      real: false,
      characterId: 'elena-quadri',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant pasticceria with ornate display cases filled with colorful pastries, small marble tables, art nouveau details, soft pink and gold tones, afternoon light creating gentle shadows, vintage chandelier, refined and sweet atmosphere',
    },
    
    // BAKERIES (2)
    {
      id: 'forno-brisa',
      name: 'Forno Brisa',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'roberto-brisa',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional bakery with wood-fired oven visible in back, shelves lined with golden bread loaves, focaccia and tigelle on display, flour-dusted wooden counters, warm ochre and wheat tones, early morning steam rising, rustic and authentic atmosphere',
    },
    {
      id: 'panificio-atti',
      name: 'Panificio Atti',
      kind: 'bakery',
      neighbourhood: 'Saragozza',
      real: false,
      characterId: 'simona-atti',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood bakery with baskets of ciabatta and pane bolognese, window display of breakfast pastries, vintage scales on counter, soft cream and brown tones, morning sunlight, handwritten price tags, homey and comforting feel',
    },
    
    // MARKETS (3)
    {
      id: 'mercato-mezzo',
      name: 'Mercato di Mezzo',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'paolo-venturi',
      imagePrompt: 'Soft pastel sketch on white paper of a historic covered market with food stalls, hanging mortadella and prosciutto, colorful produce displays, medieval arches overhead, vibrant reds and greens, market vendors calling out, bustling and lively atmosphere with warm golden lighting',
    },
    {
      id: 'mercato-erbe',
      name: 'Mercato delle Erbe',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'franca-colombi',
      imagePrompt: 'Soft pastel sketch on white paper of a two-story market hall with vegetable stalls on ground floor, fresh herbs bundled together, seasonal fruits in wooden crates, modern food court above, bright greens and earthy tones, afternoon crowds, contemporary meets traditional atmosphere',
    },
    {
      id: 'mercatino-santo-stefano',
      name: 'Mercatino di Santo Stefano',
      kind: 'market',
      neighbourhood: 'Santo Stefano',
      real: false,
      characterId: 'antonio-bassi',
      imagePrompt: 'Soft pastel sketch on white paper of a small neighborhood market with artisan cheese vendor, local honey jars, fresh pasta displayed on tables, cobblestone square setting, warm afternoon light, soft yellows and creams, intimate and charming atmosphere',
    },
    
    // RESTAURANTS (2)
    {
      id: 'ristorante-pappagallo',
      name: 'Ristorante I Carracci',
      kind: 'ristorante',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'chef-matteo-ricci',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant restaurant dining room with white tablecloths, frescoed ceiling details, wine glasses catching candlelight, classic Bolognese decor, deep burgundy and cream tones, intimate evening lighting, sophisticated and traditional atmosphere',
    },
    {
      id: 'ristorante-da-nello',
      name: 'Ristorante da Nello',
      kind: 'ristorante',
      neighbourhood: 'Quartiere Universitario',
      real: true,
      characterId: 'nello-ferrari',
      imagePrompt: 'Soft pastel sketch on white paper of a classic Bolognese restaurant with checkered floor, bottles of wine lining walls, handwritten menu board, pasta being plated in background, warm amber lighting, terracotta and cream colors, timeless and welcoming feel',
    },
    
    // SPECIALTY FOOD - Trattorias/Osterias (2)
    {
      id: 'trattoria-meloncello',
      name: 'Trattoria dal Meloncello',
      kind: 'trattoria',
      neighbourhood: 'Saragozza',
      real: false,
      characterId: 'margherita-rossi',
      imagePrompt: 'Soft pastel sketch on white paper of a family-run trattoria with handmade tortellini being prepared, mama in kitchen visible through window, wooden tables with paper placemats, hanging copper pots, warm red and gold tones, homestyle and authentic atmosphere',
    },
    {
      id: 'osteria-bottega',
      name: 'Osteria del Sole',
      kind: 'osteria',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'luca-montanari',
      imagePrompt: 'Soft pastel sketch on white paper of Bologna\'s oldest osteria with standing-room only space, locals with wine glasses and brought-from-home food, vintage photographs on walls, wooden barrel tables, deep amber tones, late afternoon light, historic and convivial atmosphere',
    },
    
    // LANDMARKS (1 major)
    {
      id: 'due-torri',
      name: 'Le Due Torri',
      kind: 'landmark',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'professor-alberti',
      imagePrompt: 'Soft pastel sketch on white paper of the two iconic medieval towers rising into sky, Asinelli and Garisenda leaning slightly, terracotta rooftops surrounding them, tourists and locals at base, warm sienna and ochre tones, afternoon light casting long shadows, majestic and historic atmosphere',
    },
    
    // CHURCHES/CULTURAL SITES (2)
    {
      id: 'santo-stefano',
      name: 'Basilica di Santo Stefano',
      kind: 'church',
      neighbourhood: 'Santo Stefano',
      real: true,
      characterId: 'don-giuseppe',
      imagePrompt: 'Soft pastel sketch on white paper of the seven churches complex with Romanesque arches, peaceful courtyard with well, ancient brickwork, pilgrims walking through cloisters, soft rose and stone gray tones, dappled sunlight, serene and sacred atmosphere',
    },
    {
      id: 'san-petronio',
      name: 'Basilica di San Petronio',
      neighbourhood: 'Centro Storico',
      kind: 'church',
      real: true,
      characterId: 'maria-custode',
      imagePrompt: 'Soft pastel sketch on white paper of massive unfinished basilica facade in Piazza Maggiore, Gothic marble portal, vast interior with meridian line on floor, visitors gazing up at vaulted ceiling, cream and terracotta tones, dramatic light through high windows, grand and imposing feel',
    },
    
    // PARKS/GARDENS (1)
    {
      id: 'giardini-margherita',
      name: 'Giardini Margherita',
      kind: 'park',
      neighbourhood: 'Santo Stefano',
      real: true,
      characterId: 'giorgio-giardiniere',
      imagePrompt: 'Soft pastel sketch on white paper of sprawling city park with tree-lined paths, small lake with ducks, students lounging on grass, joggers passing by, gelato cart under trees, fresh greens and sky blues, late afternoon golden light, relaxed and natural atmosphere',
    },
    
    // PIAZZAS (2)
    {
      id: 'piazza-maggiore',
      name: 'Piazza Maggiore',
      kind: 'piazza',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'street-musician-franco',
      imagePrompt: 'Soft pastel sketch on white paper of Bologna\'s grand central square with Palazzo d\'Accursio, Neptune fountain, people gathered on steps, students crossing through, pigeons taking flight, warm stone colors and blue sky, afternoon bustle, heart of the city atmosphere',
    },
    {
      id: 'piazza-verdi',
      name: 'Piazza Verdi',
      kind: 'piazza',
      neighbourhood: 'Quartiere Universitario',
      real: true,
      characterId: 'student-clara',
      imagePrompt: 'Soft pastel sketch on white paper of lively university square with students sitting on low walls, Teatro Comunale in background, bicycles parked everywhere, young people with books and coffee, vibrant greens and warm tones, evening light, youthful and energetic feel',
    },
    
    // WINE BARS/APERITIVO (2)
    {
      id: 'enoteca-italiana',
      name: 'Enoteca Italiana',
      kind: 'enoteca',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'sommelier-andrea',
      imagePrompt: 'Soft pastel sketch on white paper of sophisticated wine bar with floor-to-ceiling wine bottles, wooden wine racks, small marble-topped tables, plates of mortadella and parmigiano, deep wine red and oak tones, soft evening lighting, refined and cozy atmosphere',
    },
    {
      id: 'cantina-bentivoglio',
      name: 'Cantina Bentivoglio',
      kind: 'wine bar',
      neighbourhood: 'Quartiere Universitario',
      real: true,
      characterId: 'jazz-owner-stefano',
      imagePrompt: 'Soft pastel sketch on white paper of atmospheric wine cellar bar with jazz stage in corner, intimate candlelit tables, brick vaulted ceilings, wine barrels as decoration, warm amber and burgundy tones, evening ambiance with saxophone silhouette, musical and romantic feel',
    },
    
    // BOOKSHOP/CULTURAL (1)
    {
      id: 'libreria-nanni',
      name: 'Libreria Nanni',
      kind: 'bookshop',
      neighbourhood: 'Quartiere Universitario',
      real: false,
      characterId: 'anna-nanni',
      imagePrompt: 'Soft pastel sketch on white paper of independent bookshop with floor-to-ceiling shelves, rolling ladder, cozy reading nook with armchair, university textbooks and Italian literature, students browsing, warm cream and forest green tones, afternoon light through windows, intellectual and intimate atmosphere',
    },
    
    // SPECIALTY SHOPS (2)
    {
      id: 'salumeria-simoni',
      name: 'Salumeria Simoni',
      kind: 'salumeria',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'bruno-simoni',
      imagePrompt: 'Soft pastel sketch on white paper of traditional salumeria with hanging mortadella and prosciutto, wheels of Parmigiano-Reggiano stacked high, glass cases of fresh pasta and tortellini, vintage slicer on counter, rich pinks and golds, aromatic and traditional feel',
    },
    {
      id: 'bottega-portici',
      name: 'Bottega dei Portici',
      kind: 'bottega',
      neighbourhood: 'Santo Stefano',
      real: false,
      characterId: 'carla-gentile',
      imagePrompt: 'Soft pastel sketch on white paper of artisan shop under the porticoes selling local products, handmade pasta, bottles of aceto balsamico, regional preserves, woven baskets, soft earth tones and warm lighting, intimate under archways, authentic craftsmanship atmosphere',
    },
    
    // GELATO (Bologna specialty)
    {
      id: 'cremeria-funivia',
      name: 'Cremeria Funivia',
      kind: 'gelateria',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'michele-gelataio',
      imagePrompt: 'Soft pastel sketch on white paper of artisanal gelato shop with display case of colorful gelato, metal pozzetti containers, customers at counter choosing flavors, vintage gelato-making equipment, pastel rainbow of colors, summer afternoon light, sweet and cheerful atmosphere',
    },
    
    // PRACTICAL - Pharmacy (1)
    {
      id: 'farmacia-comunale',
      name: 'Farmacia Comunale',
      kind: 'pharmacy',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'dottoressa-lombardi',
      imagePrompt: 'Soft pastel sketch on white paper of traditional Italian pharmacy with dark wood cabinets, ceramic apothecary jars, green cross sign, organized shelves of medicines, professional counter, clinical white and forest green tones, morning light, trusted and orderly atmosphere',
    },
    
    // TRANSPORTATION (1)
    {
      id: 'stazione-centrale',
      name: 'Stazione di Bologna Centrale',
      kind: 'station',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'conductor-davide',
      imagePrompt: 'Soft pastel sketch on white paper of grand railway station with vaulted iron and glass ceiling, departure boards clicking, travelers with luggage, newsstand and café visible, trains on platforms, industrial grays and warm lighting, busy travel atmosphere',
    },
    
    // CITY CHARACTER - Porticoes (unique to Bologna)
    {
      id: 'portici-san-luca',
      name: 'Portici di San Luca',
      kind: 'landmark',
      neighbourhood: 'Saragozza',
      real: true,
      characterId: 'pilgrim-angela',
      imagePrompt: 'Soft pastel sketch on white paper of the world\'s longest portico winding up hillside, 666 arches stretching into distance, pilgrims and walkers ascending, terracotta and cream arches, dappled sunlight through columns, peaceful views over Bologna, meditative and grand atmosphere',
    },
    
    // PASTA SHOP (Bologna specialty - fresh pasta)
    {
      id: 'sfoglia-rina',
      name: 'Sfoglia Rina',
      kind: 'pasta shop',
      neighbourhood: 'Quartiere Universitario',
      real: false,
      characterId: 'nonna-rina',
      imagePrompt: 'Soft pastel sketch on white paper of fresh pasta laboratory with sfoglina rolling out pasta dough with long rolling pin, trays of handmade tortellini, tagliatelle hanging to dry, flour-dusted marble table, golden pasta colors and warm wood tones, artisanal and authentic feel',
    },
    
    // UNIVERSITY (City character)
    {
      id: 'archiginnasio',
      name: 'Archiginnasio',
      kind: 'landmark',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'librarian-dottore-bianchi',
      imagePrompt: 'Soft pastel sketch on white paper of historic university building with coat-of-arms covered walls, ancient anatomical theater with wooden tiers, Renaissance courtyard, students studying in reading room, scholarly atmosphere, warm parchment and wood tones, intellectual and reverent feel',
    },
    
    // ADDITIONAL CULTURAL - Museum
    {
      id: 'museo-morandi',
      name: 'Museo Morandi',
      kind: 'museum',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'curator-valentina',
      imagePrompt: 'Soft pastel sketch on white paper of intimate art museum with Morandi\'s still life paintings, simple bottles and vases on canvas, minimalist gallery walls, visitors contemplating quietly, muted grays and earth tones, natural gallery lighting, contemplative and artistic atmosphere',
    },
  ],
  
  characters: [
    {
      id: 'marco-terzi',
      name: 'Marco Terzi',
      age: 52,
      role: 'coffee roaster',
      placeId: 'caffe-terzi',
      personality: ['passionate', 'precise', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished middle-aged man with salt-and-pepper hair, strong features, wearing apron over button-down shirt, holding coffee cup, slight smile showing pride in craft, minimal sepia watercolor wash for warmth, detailed cross-hatching, capturing dedication of master roaster',
    },
    {
      id: 'giulia-morandi',
      name: 'Giulia Morandi',
      age: 28,
      role: 'barista',
      placeId: 'bar-senza-nome',
      personality: ['friendly', 'artistic', 'energetic'],
      portraitPrompt: 'Pen and ink portrait on white paper of young woman with shoulder-length wavy hair, bright eyes, casual style with scarf, genuine smile, holding espresso cup, minimal watercolor wash in warm earth tones, fine line work, expressing warmth and creativity of student quarter',
    },
    {
      id: 'elena-quadri',
      name: 'Elena Quadri',
      age: 45,
      role: 'pastry chef',
      placeId: 'pasticceria-regina',
      personality: ['elegant', 'perfectionist', 'gracious'],
      portraitPrompt: 'Pen and ink portrait on white paper of refined woman with upswept hair, delicate features, wearing chef whites with subtle jewelry, holding pastry tool, composed expression, minimal pink and gold watercolor accents, detailed pen work, capturing sophistication and artistry',
    },
    {
      id: 'roberto-brisa',
      name: 'Roberto Brisa',
      age: 58,
      role: 'baker',
      placeId: 'forno-brisa',
      personality: ['traditional', 'warm-hearted', 'early-riser'],
      portraitPrompt: 'Pen and ink portrait on white paper of sturdy man with flour in hair and on apron, strong hands, weathered kind face, holding loaf of bread, gentle smile, minimal wheat-toned watercolor wash, bold ink strokes, showing strength and tradition of generational baker',
    },
    {
      id: 'simona-atti',
      name: 'Simona Atti',
      age: 36,
      role: 'baker',
      placeId: 'panificio-atti',
      personality: ['cheerful', 'community-minded', 'hardworking'],
      portraitPrompt: 'Pen and ink portrait on white paper of woman with curly hair tied back, bright smile, flour-dusted apron, holding basket of bread, warm expression, minimal amber watercolor wash, energetic line work, capturing joy of neighborhood baker',
    },
    {
      id: 'paolo-venturi',
      name: 'Paolo Venturi',
      age: 62,
      role: 'mortadella vendor',
      placeId: 'mercato-mezzo',
      personality: ['boisterous', 'generous', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of robust man with mustache, animated expression, wearing striped apron, holding slicing knife, laughing eyes, minimal rose and cream watercolor for mortadella tones, expressive ink work, showing character of classic market vendor',
    },
    {
      id: 'franca-colombi',
      name: 'Franca Colombi',
      age: 55,
      role: 'produce vendor',
      placeId: 'mercato-erbe',
      personality: ['sharp', 'fair', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of woman with practical short hair, discerning eyes, wearing work apron over sweater, holding fresh vegetables, confident expression, minimal green watercolor wash, precise line work, capturing wisdom of market expert',
    },
    {
      id: 'antonio-bassi',
      name: 'Antonio Bassi',
      age: 48,
      role: 'cheese maker',
      placeId: 'mercatino-santo-stefano',
      personality: ['artisanal', 'patient', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of lean man with gentle features, wearing work coat, holding wheel of Parmigiano, thoughtful expression, minimal golden watercolor wash, detailed cross-hatching, showing dedication to traditional craft',
    },
    {
      id: 'chef-matteo-ricci',
      name: 'Matteo Ricci',
      age: 44,
      role: 'chef',
      placeId: 'ristorante-pappagallo',
      personality: ['refined', 'demanding', 'creative'],
      portraitPrompt: 'Pen and ink portrait on white paper of distinguished chef with sharp features, chef whites impeccable, tasting spoon in hand, intense focused expression, minimal burgundy watercolor accent, fine detailed work, capturing excellence of high-end chef',
    },
    {
      id: 'nello-ferrari',
      name: 'Nello Ferrari',
      age: 71,
      role: 'owner',
      placeId: 'ristorante-da-nello',
      personality: ['charismatic', 'storyteller', 'welcoming'],
      portraitPrompt: 'Pen and ink portrait on white paper of elderly gentleman with white hair, expressive face, wearing bow tie and vest, holding wine bottle, warm smile with character lines, minimal warm watercolor tones, bold confident strokes, showing lifetime of hospitality',
    },
    {
      id: 'margherita-rossi',
      name: 'Margherita Rossi',
      age: 67,
      role: 'cook',
      placeId: 'trattoria-meloncello',
      personality: ['maternal', 'no-nonsense', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of grandmother with hair in bun, aproned, strong hands rolling pasta, loving but firm expression, glasses on chain, minimal terracotta watercolor wash, expressive ink lines, capturing essence of nonna in kitchen',
    },
    {
      id: 'luca-montanari',
      name: 'Luca Montanari',
      age: 39,
      role: 'owner',
      placeId: 'osteria-bottega',
      personality: ['convivial', 'traditionalist', 'jovial'],
      portraitPrompt: 'Pen and ink portrait on white paper of friendly man with stubble, casual shirt, pouring wine, easy smile, holding glass, minimal red wine watercolor accent, loose energetic line work, capturing spirit of historic osteria keeper',
    },
    {
      id: 'professor-alberti',
      name: 'Professor Alberti',
      age: 68,
      role: 'historian',
      placeId: 'due-torri',
      personality: ['scholarly', 'passionate', 'eloquent'],
      portraitPrompt: 'Pen and ink portrait on white paper of distinguished elderly academic with white beard, glasses, wearing tweed jacket, gesturing while explaining, animated scholarly expression, minimal sepia wash, detailed refined line work, showing learned guide',
    },
    {
      id: 'don-giuseppe',
      name: 'Don Giuseppe',
      age: 59,
      role: 'priest',
      placeId: 'santo-stefano',
      personality: ['contemplative', 'gentle', 'learned'],
      portraitPrompt: 'Pen and ink portrait on white paper of priest with kind face, clerical collar, serene expression, hands folded, wise eyes, minimal gray watercolor wash, soft careful line work, capturing peaceful spiritual presence',
    },
    {
      id: 'maria-custode',
      name: 'Maria Custode',
      age: 64,
      role: 'church custodian',
      placeId: 'san-petronio',
      personality: ['devoted', 'observant', 'protective'],
      portraitPrompt: 'Pen and ink portrait on white paper of dignified woman with hair covered, simple dark clothing, holding keys, watchful caring eyes, peaceful expression, minimal stone gray watercolor, precise line work, showing guardian of sacred space',
    },
    {
      id: 'giorgio-giardiniere',
      name: 'Giorgio Bellini',
      age: 53,
      role: 'gardener',
      placeId: 'giardini-margherita',
      personality: ['patient', 'outdoorsy', 'contented'],
      portraitPrompt: 'Pen and ink portrait on white paper of weathered man with sun-lined face, work clothes, holding pruning shears, peaceful smile, connected to nature, minimal green watercolor wash, earthy line work, showing dedication to green spaces',
    },
    {
      id: 'street-musician-franco',
      name: 'Franco Melodia',
      age: 42,
      role: 'street musician',
      placeId: 'piazza-maggiore',
      personality: ['artistic', 'free-spirited', 'talented'],
      portraitPrompt: 'Pen and ink portrait on white paper of man with longer hair, expressive face, holding guitar, wearing scarf and weathered jacket, soulful eyes, minimal warm watercolor accents, flowing musical line work, capturing street artist spirit',
    },
    {
      id: 'student-clara',
      name: 'Clara Martinelli',
      age: 22,
      role: 'student',
      placeId: 'piazza-verdi',
      personality: ['studious', 'social', 'idealistic'],
      portraitPrompt: 'Pen and ink portrait on white paper of young woman with long hair, intelligent eyes, casual student style, holding books, bright engaged expression, minimal blue watercolor accent, fresh clean line work, capturing university life energy',
    },
    {
      id: 'sommelier-andrea',
      name: 'Andrea Sarti',
      age: 37,
      role: 'sommelier',
      placeId: 'enoteca-italiana',
      personality: ['knowledgeable', 'sophisticated', 'passionate'],
      portraitPrompt: 'Pen and ink portrait on white paper of refined man in smart casual attire, holding wine glass to light, discerning expression, sommelier pin visible, minimal burgundy watercolor wash, elegant line work, showing wine expertise',
    },
    {
      id: 'jazz-owner-stefano',
      name: 'Stefano Bentivoglio',
      age: 56,
      role: 'owner',
      placeId: 'cantina-bentivoglio',
      personality: ['musical', 'atmospheric', 'cultured'],
      portraitPrompt: 'Pen and ink portrait on white paper of distinguished man with artistic flair, wearing dark turtleneck, holding saxophone, jazz lover expression, minimal deep blue watercolor wash, rhythmic expressive lines, capturing music venue soul',
    },
    {
      id: 'anna-nanni',
      name: 'Anna Nanni',
      age: 33,
      role: 'bookseller',
      placeId: 'libreria-nanni',
      personality: ['literary', 'helpful', 'curious'],
      portraitPrompt: 'Pen and ink portrait on white paper of young woman with glasses, intelligent kind face, holding book, thoughtful expression, surrounded by literary atmosphere, minimal warm watercolor wash, delicate line work, showing book lover dedication',
    },
    {
      id: 'bruno-simoni',
      name: 'Bruno Simoni',
      age: 61,
      role: 'salumiere',
      placeId: 'salumeria-simoni',
      personality: ['proud', 'expert', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of solid man in striped apron, holding mortadella slicer, confident craftsman expression, mustache, minimal pink and gold watercolor for meats, strong bold strokes, capturing master salumiere',
    },
    {
      id: 'carla-gentile',
      name: 'Carla Gentile',
      age: 50,
      role: 'shop keeper',
      placeId: 'bottega-portici',
      personality: ['artisanal', 'welcoming', 'local-expert'],
      portraitPrompt: 'Pen and ink portrait on white paper of warm woman with kind smile, elegant scarf, holding jar of preserves, genuine welcoming expression, minimal earth tone watercolor, graceful line work, showing artisan shop dedication',
    },
    {
      id: 'michele-gelataio',
      name: 'Michele Vestrucci',
      age: 31,
      role: 'gelato maker',
      placeId: 'cremeria-funivia',
      personality: ['creative', 'perfectionist', 'cheerful'],
      portraitPrompt: 'Pen and ink portrait on white paper of young man with bright eyes, white gelato uniform, holding spatula, enthusiastic smile, minimal pastel watercolor accents, clean fresh line work, capturing artisan gelato passion',
    },
    {
      id: 'dottoressa-lombardi',
      name: 'Dottoressa Lombardi',
      age: 47,
      role: 'pharmacist',
      placeId: 'farmacia-comunale',
      personality: ['professional', 'caring', 'precise'],
      portraitPrompt: 'Pen and ink portrait on white paper of professional woman with pulled-back hair, white coat, compassionate but competent expression, holding prescription, minimal clinical watercolor wash, clean precise lines, showing trusted healthcare provider',
    },
    {
      id: 'conductor-davide',
      name: 'Davide Treni',
      age: 44,
      role: 'train conductor',
      placeId: 'stazione-centrale',
      personality: ['punctual', 'helpful', 'experienced'],
      portraitPrompt: 'Pen and ink portrait on white paper of man in conductor uniform with cap, whistle around neck, checking watch, professional friendly expression, minimal navy blue watercolor accent, structured line work, showing railway expertise',
    },
    {
      id: 'pilgrim-angela',
      name: 'Angela Peregrino',
      age: 58,
      role: 'pilgrim guide',
      placeId: 'portici-san-luca',
      personality: ['spiritual', 'enduring', 'inspiring'],
      portraitPrompt: 'Pen and ink portrait on white paper of serene woman with walking stick, comfortable walking clothes, peaceful meditative expression, gentle eyes, minimal terracotta watercolor wash, flowing contemplative lines, capturing pilgrim spirit',
    },
    {
      id: 'nonna-rina',
      name: 'Nonna Rina',
      age: 74,
      role: 'sfoglina',
      placeId: 'sfoglia-rina',
      personality: ['masterful', 'exacting', 'loving'],
      portraitPrompt: 'Pen and ink portrait on white paper of elderly woman with weathered hands, flour-dusted apron, hair in traditional style, holding rolling pin, wise experienced expression, minimal golden watercolor for pasta, detailed reverent line work, showing pasta-making mastery',
    },
    {
      id: 'librarian-dottore-bianchi',
      name: 'Dottore Bianchi',
      age: 65,
      role: 'librarian',
      placeId: 'archiginnasio',
      personality: ['erudite', 'meticulous', 'dignified'],
      portraitPrompt: 'Pen and ink portrait on white paper of distinguished scholar with gray hair, glasses, formal academic attire, holding ancient book, intellectual authoritative expression, minimal sepia watercolor wash, refined scholarly line work, capturing academic tradition',
    },
    {
      id: 'curator-valentina',
      name: 'Valentina Morandi',
      age: 40,
      role: 'curator',
      placeId: 'museo-morandi',
      personality: ['artistic', 'insightful', 'contemplative'],
      portraitPrompt: 'Pen and ink portrait on white paper of elegant woman with modern style, wearing museum badge, gesturing toward art, intelligent thoughtful expression, minimal muted watercolor wash matching Morandi palette, sophisticated line work, showing art world refinement',
    },
  ],
  
  food: [
    'tortellini in brodo',
    'tagliatelle al ragù',
    'lasagne verdi',
    'mortadella',
    'gramigna con salsiccia',
    'crescentine',
    'tigelle',
    'cotoletta alla bolognese',
    'friggione',
    'certosino',
    'raviole',
    'Parmigiano-Reggiano',
    'prosciutto di Parma',
    'aceto balsamico',
    'pasta fresca',
    'tortelloni',
    'passatelli',
    'zuppa imperiale',
  ],
  
  customs: [
    'Walking under the porticoes in any weather',
    'Sunday passeggiata in Piazza Maggiore',
    'Aperitivo hour with wine and mortadella',
    'Making fresh pasta by hand with the sfoglina',
    'Climbing the Torre degli Asinelli for the view',
    'University students gathering in Piazza Verdi',
    'Shopping at the morning markets',
    'Evening stroll to see the illuminated towers',
    'Coffee standing at the bar, not sitting',
    'Pilgrimage walk up the Portico di San Luca',
  ],
  
  localTouches: [
    '"La dotta, la grassa, la rossa" - the learned, the fat, the red',
    'Calling Bologna "la grassa" for its rich cuisine',
    '"Petroniano" - relating to San Petronio, patron saint',
    'Pride in the oldest university in the Western world',
    'The art of "tirare la sfoglia" - rolling pasta dough',
    '"Fare quattro passi sotto i portici" - taking a walk under the porticoes',
    'Respect for traditional Bolognese ragù recipe',
    'The leaning towers as symbols of medieval family power',
    '"Crescentina" or "tigella" - traditional fried bread',
    'Bolognese dialect softening of consonants',
  ],
};
