import { CityPantry } from '@/lib/types';

export const firenze: CityPantry = {
  id: 'firenze',
  name: 'Firenze',
  neighbourhoods: ['Oltrarno', 'San Lorenzo', 'Santa Croce', 'Santo Spirito'],
  places: [
    // DAILY ROUTINE - Bars/Cafés
    {
      id: 'caffe-rivoire',
      name: 'Caffè Rivoire',
      kind: 'bar',
      neighbourhood: 'Santa Croce',
      real: true,
      characterId: 'marco-rivoire',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant historic Florentine café with marble-topped tables, vintage espresso machine gleaming in warm golden light, red velvet chairs, and tall windows overlooking Piazza della Signoria, warm ochre and cream tones, textured strokes, inviting atmosphere',
    },
    {
      id: 'bar-del-moro',
      name: 'Bar del Moro',
      kind: 'bar',
      neighbourhood: 'Oltrarno',
      real: true,
      characterId: 'simona-moro',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy neighborhood bar with worn wooden counter, colorful bottles on shelves, vintage Campari posters, locals standing at the bar, morning light streaming through small windows, terracotta and sage green tones, warm and welcoming',
    },
    {
      id: 'ditta-artigianale',
      name: 'Ditta Artigianale',
      kind: 'bar',
      neighbourhood: 'Santo Spirito',
      real: true,
      characterId: 'francesco-barista',
      imagePrompt: 'Soft pastel sketch on white paper of a modern artisan coffee bar with industrial-chic design, exposed brick walls, professional espresso equipment, hanging Edison bulbs, wooden communal table, soft grays and warm browns, inviting contemporary feel',
    },
    
    // DAILY ROUTINE - Bakeries
    {
      id: 'forno-galli',
      name: 'Forno Galli',
      kind: 'bakery',
      neighbourhood: 'San Lorenzo',
      real: false,
      characterId: 'alberto-galli',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional Florentine bakery with stone oven visible in back, shelves filled with schiacciata and bread loaves, wooden display case with cantuccini, flour dust in the air, warm amber and golden tones, rustic and aromatic',
    },
    {
      id: 'pasticceria-nencioni',
      name: 'Pasticceria Nencioni',
      kind: 'bakery',
      neighbourhood: 'Oltrarno',
      real: true,
      characterId: 'giulia-nencioni',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant pastry shop with glass cases displaying colorful pastries, zuccotto cakes, and biscotti, delicate lighting, cream and pink tones, gold accents, refined and sweet atmosphere',
    },
    
    // FOOD & SHOPPING - Markets
    {
      id: 'mercato-centrale',
      name: 'Mercato Centrale',
      kind: 'market',
      neighbourhood: 'San Lorenzo',
      real: true,
      characterId: 'paolo-verdura',
      imagePrompt: 'Soft pastel sketch on white paper of a bustling covered market with iron and glass structure, colorful produce stands, hanging salumi, flower stalls, crowds of shoppers, vibrant greens, reds, and yellows, lively energetic atmosphere',
    },
    {
      id: 'mercato-santambrogio',
      name: 'Mercato di Sant\'Ambrogio',
      kind: 'market',
      neighbourhood: 'Santa Croce',
      real: true,
      characterId: 'rosa-fruttivendola',
      imagePrompt: 'Soft pastel sketch on white paper of an authentic neighborhood market square with canvas-covered stalls, pyramids of seasonal fruit, vegetable crates, locals with shopping bags, morning sunlight, earthy greens and terracotta tones, genuine community feel',
    },
    {
      id: 'mercatino-santo-spirito',
      name: 'Mercatino di Santo Spirito',
      kind: 'market',
      neighbourhood: 'Santo Spirito',
      real: true,
      characterId: 'dario-artigiano',
      imagePrompt: 'Soft pastel sketch on white paper of an open-air artisan market in a Renaissance piazza, white tents with handmade goods, leather crafts, vintage items, plane trees providing shade, warm stone buildings backdrop, ochre and cream palette, bohemian artistic vibe',
    },
    
    // FOOD & SHOPPING - Restaurants
    {
      id: 'trattoria-mario',
      name: 'Trattoria Mario',
      kind: 'trattoria',
      neighbourhood: 'San Lorenzo',
      real: true,
      characterId: 'mario-trattore',
      imagePrompt: 'Soft pastel sketch on white paper of a tiny traditional trattoria with shared wooden tables, handwritten menu on chalkboard, kitchen visible through serving window, bottles of house wine, checkered tablecloths, warm reds and whites, authentic bustling atmosphere',
    },
    {
      id: 'osteria-santo-spirito',
      name: 'Osteria Santo Spirito',
      kind: 'osteria',
      neighbourhood: 'Santo Spirito',
      real: false,
      characterId: 'benedetta-cuoca',
      imagePrompt: 'Soft pastel sketch on white paper of a charming osteria with tables spilling onto cobblestone piazza, string lights overhead, wine bottles lining walls, open kitchen with copper pots, outdoor diners enjoying evening, golden hour lighting, warm inviting tones',
    },
    
    // FOOD & SHOPPING - Specialty Food
    {
      id: 'lampredotto-stand',
      name: 'Il Trippaio di San Lorenzo',
      kind: 'street food',
      neighbourhood: 'San Lorenzo',
      real: false,
      characterId: 'vincenzo-trippaio',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional lampredotto cart with green and white striped awning, steaming pots, rolls ready for filling, locals queuing, surrounding market atmosphere, greens and whites with steam effects, authentic street food character',
    },
    {
      id: 'gelateria-vivoli',
      name: 'Gelateria Vivoli',
      kind: 'gelateria',
      neighbourhood: 'Santa Croce',
      real: true,
      characterId: 'elena-gelataia',
      imagePrompt: 'Soft pastel sketch on white paper of a famous gelato shop interior with display cases of colorful gelato, vintage tile walls, family photos, customers with cups, soft pastel rainbow colors, cool creamy tones, sweet nostalgic atmosphere',
    },
    
    // CULTURAL/LANDMARK
    {
      id: 'duomo',
      name: 'Cattedrale di Santa Maria del Fiore',
      kind: 'landmark',
      neighbourhood: 'San Lorenzo',
      real: true,
      characterId: 'padre-giovanni',
      imagePrompt: 'Soft pastel sketch on white paper of the magnificent Duomo with Brunelleschi\'s dome dominating the skyline, marble façade in pink, white and green, surrounding terracotta rooftops, distant Tuscan hills, majestic scale, warm Italian sunlight, iconic architectural beauty',
    },
    {
      id: 'ponte-vecchio',
      name: 'Ponte Vecchio',
      kind: 'landmark',
      neighbourhood: 'Oltrarno',
      real: true,
      characterId: 'matteo-orafo',
      imagePrompt: 'Soft pastel sketch on white paper of the ancient bridge with jewelry shops built along it, golden displays in windows, Arno river flowing beneath, reflections in water, sunset warm light, ochre and gold tones, romantic historic atmosphere',
    },
    {
      id: 'basilica-santa-croce',
      name: 'Basilica di Santa Croce',
      kind: 'church',
      neighbourhood: 'Santa Croce',
      real: true,
      characterId: 'suor-teresa',
      imagePrompt: 'Soft pastel sketch on white paper of the grand Gothic basilica façade with marble geometric patterns, wide piazza in front, pigeons gathering, tourists and locals, white and earth-tone marble, peaceful spiritual presence',
    },
    {
      id: 'giardino-boboli',
      name: 'Giardino di Boboli',
      kind: 'park',
      neighbourhood: 'Oltrarno',
      real: true,
      characterId: 'giuseppe-giardiniere',
      imagePrompt: 'Soft pastel sketch on white paper of Renaissance gardens with geometric hedges, classical statues, gravel paths, cypress trees, fountain in distance, Palazzo Pitti visible, soft greens and stone grays, serene manicured beauty',
    },
    {
      id: 'piazza-signoria',
      name: 'Piazza della Signoria',
      kind: 'piazza',
      neighbourhood: 'Santa Croce',
      real: true,
      characterId: 'carlo-guida',
      imagePrompt: 'Soft pastel sketch on white paper of the grand civic square with Palazzo Vecchio tower, outdoor sculpture gallery, Neptune fountain, café tables at edges, tourists and locals mingling, warm stone pavement, dramatic Renaissance architecture',
    },
    {
      id: 'piazza-santo-spirito',
      name: 'Piazza Santo Spirito',
      kind: 'piazza',
      neighbourhood: 'Santo Spirito',
      real: true,
      characterId: 'alessia-studente',
      imagePrompt: 'Soft pastel sketch on white paper of a lively neighborhood square with church façade, locals sitting on steps, children playing, plane trees, cafés with outdoor seating, bohemian relaxed atmosphere, golden afternoon light, community gathering place',
    },
    
    // SOCIAL/EVENING - Wine bars
    {
      id: 'enoteca-alessi',
      name: 'Enoteca Alessi',
      kind: 'enoteca',
      neighbourhood: 'Santa Croce',
      real: true,
      characterId: 'leonardo-sommelier',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional wine shop with floor-to-ceiling bottles, wooden shelving, small tasting bar, wine barrels, dim warm lighting, deep reds and browns, intimate knowledgeable atmosphere',
    },
    {
      id: 'volume',
      name: 'Volume',
      kind: 'wine bar',
      neighbourhood: 'Santo Spirito',
      real: true,
      characterId: 'chiara-volume',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy aperitivo bar with exposed stone walls, vintage furniture, wine glasses hanging, cheese and salumi boards, soft candlelight, customers in conversation, warm intimate evening setting',
    },
    
    // SOCIAL/EVENING - Bookshop
    {
      id: 'libreria-brac',
      name: 'Libreria BRAC',
      kind: 'bookshop',
      neighbourhood: 'Oltrarno',
      real: true,
      characterId: 'sofia-libraia',
      imagePrompt: 'Soft pastel sketch on white paper of an independent bookshop-café with floor-to-ceiling bookshelves, cozy reading nooks, small tables with coffee cups, art books displayed, plants, soft lighting, creative bohemian atmosphere',
    },
    {
      id: 'paperback-exchange',
      name: 'Paperback Exchange',
      kind: 'bookshop',
      neighbourhood: 'Santa Croce',
      real: true,
      characterId: 'james-libraio',
      imagePrompt: 'Soft pastel sketch on white paper of a used English bookstore with stacks of books, narrow aisles, overfilled shelves, reading cat, armchair in corner, warm yellowed paper tones, literary sanctuary feel',
    },
    
    // PRACTICAL
    {
      id: 'farmacia-molteni',
      name: 'Farmacia Molteni',
      kind: 'pharmacy',
      neighbourhood: 'San Lorenzo',
      real: false,
      characterId: 'dottoressa-molteni',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional Italian pharmacy with wooden cabinets, glass bottles, green cross sign, white-coated pharmacist, organized shelves, clean whites and greens, professional trustworthy atmosphere',
    },
    {
      id: 'stazione-smn',
      name: 'Stazione Santa Maria Novella',
      kind: 'train station',
      neighbourhood: 'San Lorenzo',
      real: true,
      characterId: 'antonio-bigliettaio',
      imagePrompt: 'Soft pastel sketch on white paper of a modernist train station interior with clean lines, large windows, departure boards, travelers with luggage, geometric architecture, functional beauty, sense of movement and journeys',
    },
    
    // CITY CHARACTER
    {
      id: 'officina-profumo',
      name: 'Officina Profumo-Farmaceutica di Santa Maria Novella',
      kind: 'historic shop',
      neighbourhood: 'San Lorenzo',
      real: true,
      characterId: 'isabella-profumiera',
      imagePrompt: 'Soft pastel sketch on white paper of an ancient apothecary with frescoed ceilings, antique wooden cabinets, glass perfume bottles, ornate mirrors, Renaissance atmosphere, rich golds and deep greens, timeless elegant beauty',
    },
    {
      id: 'scuola-cuoio',
      name: 'Scuola del Cuoio',
      kind: 'artisan workshop',
      neighbourhood: 'Santa Croce',
      real: true,
      characterId: 'marcello-artigiano',
      imagePrompt: 'Soft pastel sketch on white paper of a leather workshop with craftsmen at work benches, hanging leather goods, tools, smell of tanned leather suggested, behind Santa Croce basilica, warm browns and tans, artisan tradition alive',
    },
    {
      id: 'bottega-orafa',
      name: 'Bottega Orafa',
      kind: 'artisan workshop',
      neighbourhood: 'Oltrarno',
      real: false,
      characterId: 'sergio-orafo',
      imagePrompt: 'Soft pastel sketch on white paper of a gold workshop with jeweler at workbench, magnifying glass, tiny tools, precious metals, designs sketched, window overlooking Arno, golden warm light, meticulous craftsmanship atmosphere',
    },
    {
      id: 'all-antico-vinaio',
      name: 'All\'Antico Vinaio',
      kind: 'sandwich shop',
      neighbourhood: 'Santa Croce',
      real: true,
      characterId: 'tommaso-vinaio',
      imagePrompt: 'Soft pastel sketch on white paper of a famous schiacciata shop with enormous sandwiches, hanging salumi, wheels of pecorino, crowds queuing outside, chalkboard menus, wine bottles, vibrant busy energy, delicious abundance',
    },
    {
      id: 'le-volpi-uva',
      name: 'Le Volpi e l\'Uva',
      kind: 'enoteca',
      neighbourhood: 'Oltrarno',
      real: true,
      characterId: 'emilio-vinaio',
      imagePrompt: 'Soft pastel sketch on white paper of a tiny wine bar near Ponte Vecchio with small outdoor tables, wine bottles, cheese platters, intimate setting, stone walls, evening aperitivo scene, warm convivial atmosphere',
    },
  ],
  characters: [
    {
      id: 'marco-rivoire',
      name: 'Marco Guidotti',
      age: 42,
      role: 'barista',
      placeId: 'caffe-rivoire',
      personality: ['refined', 'professional', 'proud of tradition'],
      portraitPrompt: 'Pen and ink portrait on white paper of a dignified middle-aged Italian barista with salt-and-pepper hair, wearing crisp white shirt and black vest, slight smile, competent hands, minimal sepia watercolor wash on face, detailed crosshatching, elegant bearing',
    },
    {
      id: 'simona-moro',
      name: 'Simona Martini',
      age: 38,
      role: 'bartender',
      placeId: 'bar-del-moro',
      personality: ['warm', 'chatty', 'knows everyone'],
      portraitPrompt: 'Pen and ink portrait on white paper of a friendly woman with curly dark hair pulled back, bright eyes, welcoming smile, apron tied at waist, minimal warm watercolor wash, expressive face showing genuine warmth',
    },
    {
      id: 'francesco-barista',
      name: 'Francesco Sartiani',
      age: 29,
      role: 'barista',
      placeId: 'ditta-artigianale',
      personality: ['innovative', 'passionate about coffee', 'hipster'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young bearded barista with modern style, tattoo visible on forearm, focused expression, hands holding portafilter, minimal cool-toned watercolor wash, contemporary artisan aesthetic',
    },
    {
      id: 'alberto-galli',
      name: 'Alberto Galli',
      age: 56,
      role: 'baker',
      placeId: 'forno-galli',
      personality: ['gruff but kind', 'early riser', 'master of schiacciata'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stocky baker with flour-dusted apron, strong arms, weathered face, slight smile beneath mustache, minimal warm watercolor wash, hardworking hands detailed',
    },
    {
      id: 'giulia-nencioni',
      name: 'Giulia Nencioni',
      age: 33,
      role: 'pastry chef',
      placeId: 'pasticceria-nencioni',
      personality: ['artistic', 'perfectionist', 'sweet-natured'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant woman with hair in neat bun, delicate features, chef\'s whites, gentle concentrated expression, minimal pink watercolor wash, refined artistic presence',
    },
    {
      id: 'paolo-verdura',
      name: 'Paolo Benedetti',
      age: 61,
      role: 'vegetable vendor',
      placeId: 'mercato-centrale',
      personality: ['loud', 'jovial', 'generous with samples'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust man with weathered face from outdoor work, cap on head, wide smile, strong hands, minimal earth-tone watercolor wash, vibrant energetic character',
    },
    {
      id: 'rosa-fruttivendola',
      name: 'Rosa Lombardi',
      age: 54,
      role: 'fruit vendor',
      placeId: 'mercato-santambrogio',
      personality: ['sharp-witted', 'fair', 'neighborhood institution'],
      portraitPrompt: 'Pen and ink portrait on white paper of a confident woman with practical short hair, knowing eyes, hands on hips, apron with pockets, minimal warm watercolor wash, authoritative but approachable',
    },
    {
      id: 'dario-artigiano',
      name: 'Dario Rossi',
      age: 44,
      role: 'artisan vendor',
      placeId: 'mercatino-santo-spirito',
      personality: ['creative', 'bohemian', 'storyteller'],
      portraitPrompt: 'Pen and ink portrait on white paper of an artistic man with longish hair, scarf, expressive hands gesturing, leather tools visible, minimal earthy watercolor wash, creative free-spirited energy',
    },
    {
      id: 'mario-trattore',
      name: 'Mario Falorni',
      age: 68,
      role: 'trattoria owner',
      placeId: 'trattoria-mario',
      personality: ['no-nonsense', 'quick service', 'heart of gold'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly restaurateur with lined face, wise eyes, white apron, commanding presence, minimal sepia watercolor wash, decades of experience showing',
    },
    {
      id: 'benedetta-cuoca',
      name: 'Benedetta Conti',
      age: 41,
      role: 'chef',
      placeId: 'osteria-santo-spirito',
      personality: ['passionate', 'traditional', 'maternal'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warm-faced chef with gentle eyes, tasting spoon in hand, apron stained from cooking, minimal warm watercolor wash, nurturing strength evident',
    },
    {
      id: 'vincenzo-trippaio',
      name: 'Vincenzo Bianchi',
      age: 47,
      role: 'street food vendor',
      placeId: 'lampredotto-stand',
      personality: ['fast-talking', 'proud', 'authentic Florentine'],
      portraitPrompt: 'Pen and ink portrait on white paper of a street vendor with animated expression, chef\'s cap, ladle in hand, calling out to customers, minimal warm watercolor wash, energetic local character',
    },
    {
      id: 'elena-gelataia',
      name: 'Elena Vivoli',
      age: 36,
      role: 'gelato maker',
      placeId: 'gelateria-vivoli',
      personality: ['cheerful', 'family-proud', 'precise with portions'],
      portraitPrompt: 'Pen and ink portrait on white paper of a smiling woman with bright eyes, gelato scoop in hand, white uniform, hair covered, minimal cool pastel watercolor wash, sweet genuine happiness',
    },
    {
      id: 'padre-giovanni',
      name: 'Padre Giovanni Bardi',
      age: 59,
      role: 'priest',
      placeId: 'duomo',
      personality: ['scholarly', 'welcoming', 'loves architecture'],
      portraitPrompt: 'Pen and ink portrait on white paper of a dignified priest with gentle face, glasses, clerical collar, kind expression, minimal dark watercolor wash, intellectual warmth',
    },
    {
      id: 'matteo-orafo',
      name: 'Matteo Cellini',
      age: 52,
      role: 'jeweler',
      placeId: 'ponte-vecchio',
      personality: ['meticulous', 'reserved', 'master craftsman'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined jeweler with careful eyes, magnifying loupe around neck, skilled hands, formal attire, minimal golden watercolor wash, quiet expertise',
    },
    {
      id: 'suor-teresa',
      name: 'Suor Teresa Alberti',
      age: 45,
      role: 'nun',
      placeId: 'basilica-santa-croce',
      personality: ['serene', 'helpful', 'loves art history'],
      portraitPrompt: 'Pen and ink portrait on white paper of a gentle-faced nun in traditional habit, peaceful expression, hands folded, kind eyes, minimal soft watercolor wash, spiritual calm presence',
    },
    {
      id: 'giuseppe-giardiniere',
      name: 'Giuseppe Bardini',
      age: 63,
      role: 'head gardener',
      placeId: 'giardino-boboli',
      personality: ['patient', 'knowledgeable', 'speaks to plants'],
      portraitPrompt: 'Pen and ink portrait on white paper of an older gardener with sun-weathered face, cap, work shirt, gentle smile, earth under fingernails, minimal green watercolor wash, connection to nature evident',
    },
    {
      id: 'carlo-guida',
      name: 'Carlo Medici',
      age: 35,
      role: 'tour guide',
      placeId: 'piazza-signoria',
      personality: ['enthusiastic', 'theatrical', 'history buff'],
      portraitPrompt: 'Pen and ink portrait on white paper of an animated young guide with expressive face, gesturing hand, casual professional attire, energetic eyes, minimal warm watercolor wash, passionate storyteller',
    },
    {
      id: 'alessia-studente',
      name: 'Alessia Torelli',
      age: 23,
      role: 'art student',
      placeId: 'piazza-santo-spirito',
      personality: ['creative', 'social', 'always sketching'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with artistic style, sketchbook under arm, curious eyes, casual bohemian clothing, minimal loose watercolor wash, creative spirit',
    },
    {
      id: 'leonardo-sommelier',
      name: 'Leonardo Antinori',
      age: 49,
      role: 'sommelier',
      placeId: 'enoteca-alessi',
      personality: ['knowledgeable', 'sophisticated', 'patient teacher'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished sommelier with refined features, wine glass in hand, thoughtful expression, formal attire, minimal wine-red watercolor wash, cultured expertise',
    },
    {
      id: 'chiara-volume',
      name: 'Chiara Ferretti',
      age: 31,
      role: 'wine bar owner',
      placeId: 'volume',
      personality: ['hip', 'welcoming', 'curates natural wines'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stylish young woman with modern aesthetic, friendly smile, wine bottle in background, minimal cool watercolor wash, contemporary confident energy',
    },
    {
      id: 'sofia-libraia',
      name: 'Sofia Doni',
      age: 39,
      role: 'bookshop owner',
      placeId: 'libreria-brac',
      personality: ['intellectual', 'warm', 'recommends perfect books'],
      portraitPrompt: 'Pen and ink portrait on white paper of a thoughtful woman with reading glasses, book in hand, gentle smile, cardigan, minimal warm watercolor wash, literary wisdom and kindness',
    },
    {
      id: 'james-libraio',
      name: 'James Cooper',
      age: 58,
      role: 'bookshop owner',
      placeId: 'paperback-exchange',
      personality: ['expat', 'literary', 'tea drinker'],
      portraitPrompt: 'Pen and ink portrait on white paper of a British expat with graying hair, reading glasses on chain, sweater, surrounded by books, minimal sepia watercolor wash, gentle scholarly presence',
    },
    {
      id: 'dottoressa-molteni',
      name: 'Dott.ssa Anna Molteni',
      age: 51,
      role: 'pharmacist',
      placeId: 'farmacia-molteni',
      personality: ['professional', 'caring', 'trusted advisor'],
      portraitPrompt: 'Pen and ink portrait on white paper of a composed pharmacist with neat hair, white coat, attentive expression, professional demeanor, minimal cool watercolor wash, competent trustworthy presence',
    },
    {
      id: 'antonio-bigliettaio',
      name: 'Antonio Rosselli',
      age: 44,
      role: 'ticket agent',
      placeId: 'stazione-smn',
      personality: ['helpful', 'multilingual', 'patient with tourists'],
      portraitPrompt: 'Pen and ink portrait on white paper of a friendly station agent with neat uniform, helpful expression, hands ready to assist, minimal blue watercolor wash, service-oriented warmth',
    },
    {
      id: 'isabella-profumiera',
      name: 'Isabella Stefani',
      age: 46,
      role: 'perfume specialist',
      placeId: 'officina-profumo',
      personality: ['elegant', 'knowledgeable', 'speaks in whispers'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined woman with classic beauty, holding perfume bottle, serene expression, elegant attire, minimal lavender watercolor wash, timeless grace',
    },
    {
      id: 'marcello-artigiano',
      name: 'Marcello Gori',
      age: 57,
      role: 'leather artisan',
      placeId: 'scuola-cuoio',
      personality: ['master craftsman', 'quiet', 'takes pride in teaching'],
      portraitPrompt: 'Pen and ink portrait on white paper of a skilled artisan with leather apron, tools in hand, concentrated expression, strong capable hands detailed, minimal brown watercolor wash, craftsman dignity',
    },
    {
      id: 'sergio-orafo',
      name: 'Sergio Benvenuti',
      age: 64,
      role: 'goldsmith',
      placeId: 'bottega-orafa',
      personality: ['perfectionist', 'traditional', 'family secrets'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly goldsmith with magnifier on head, delicate tools, wise eyes, jeweler\'s precision in posture, minimal gold watercolor wash, generations of skill',
    },
    {
      id: 'tommaso-vinaio',
      name: 'Tommaso Mazzanti',
      age: 34,
      role: 'sandwich maker',
      placeId: 'all-antico-vinaio',
      personality: ['fast-working', 'charismatic', 'generous portions'],
      portraitPrompt: 'Pen and ink portrait on white paper of an energetic young man with broad smile, knife in hand, flour on apron, calling to customers, minimal warm watercolor wash, infectious enthusiasm',
    },
    {
      id: 'emilio-vinaio',
      name: 'Emilio Cioni',
      age: 53,
      role: 'wine bar owner',
      placeId: 'le-volpi-uva',
      personality: ['discerning', 'intimate knowledge of wine', 'creates pairings'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sophisticated wine expert with thoughtful expression, tasting glass, refined casual attire, minimal deep red watercolor wash, connoisseur expertise and passion',
    },
  ],
  food: [
    'bistecca alla fiorentina',
    'lampredotto',
    'ribollita',
    'pappa al pomodoro',
    'schiacciata fiorentina',
    'crostini toscani',
    'trippa',
    'panzanella',
    'fagioli all\'uccelletto',
    'cacciucco',
    'cantuccini',
    'pan di ramerino',
    'schiacciata con l\'uva',
    'castagnaccio',
    'zuccotto',
    'biscotti di Prato',
    'pecorino toscano',
    'finocchiona',
    'lardo di colonnata',
    'vin santo',
  ],
  customs: [
    'Taking passeggiata along the Arno at sunset',
    'Eating lampredotto from street vendors as a quick lunch',
    'Ordering caffè corretto (espresso with grappa) in the morning',
    'Standing at the bar rather than sitting for cheaper coffee',
    'Shopping daily at neighborhood markets',
    'Aperitivo hour around 6-7pm with snacks included',
    'Sharing communal tables at traditional trattorie',
    'Greeting shopkeepers when entering any store',
    'Closing businesses for riposo (afternoon rest)',
    'Celebrating Calcio Storico in Piazza Santa Croce',
    'Attending concerts in historic churches',
    'Meeting friends in piazzas, not at homes',
    'Buying fresh schiacciata still warm from the oven',
    'Dunking cantuccini in vin santo after dinner',
    'Queueing at All\'Antico Vinaio despite the wait',
  ],
  localTouches: [
    'Using "un bel niente" (a beautiful nothing) when asked what you\'re doing',
    'Saying "la\' " instead of "lì" (there) in Florentine dialect',
    'Pronouncing "c" as "h" - "hasa" instead of "casa" (house)',
    'Calling panino "schiacciata" or just "un\' schiaccia"',
    'Using "babbo" instead of "papà" for father',
    'Saying "icché" instead of "che cosa" (what)',
    'Responding "nulla" when asked how are you (typical understatement)',
    'Using "la\' " to point - "Guarda la\'!" (Look there!)',
    'Calling fountain "fontana" but pronouncing it "hontana"',
    'Saying "mi garba" (I like it) instead of "mi piace"',
    'Using "egli" for he in conversation (old-fashioned but Florentine)',
    'Dropping final vowels - "volentier" not "volentieri"',
    'Referring to outsiders affectionately as "forestieri"',
    'Using "a me mi" (to me to-me) construction despite being "wrong"',
    'Saying "bischero" as a mild insult (fool)',
  ],
};
