import { CityPantry } from '@/lib/types';

export const genova: CityPantry = {
  id: 'genova',
  name: 'Genova',
  neighbourhoods: ['Centro Storico', 'Caruggi', 'Boccadasse', 'Castelletto'],
  places: [
    {
      id: 'caffe-degli-specchi',
      name: 'Caffè degli Specchi',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'marco-venturi',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant Genovese café with tall mirrors, marble-topped bar counter, brass espresso machine gleaming in morning light, small round tables with bentwood chairs, warm amber and cream tones, textured walls, inviting atmosphere',
    },
    {
      id: 'bar-boccadasse',
      name: 'Bar Marinella',
      kind: 'bar',
      neighbourhood: 'Boccadasse',
      real: false,
      characterId: 'giulia-costa',
      imagePrompt: 'Soft pastel sketch on white paper of a seaside bar with pale blue shutters, outdoor tables overlooking colorful fishing boats, weathered wooden door, potted geraniums, soft Mediterranean blues and whites, sandy beige tones, gentle watercolor texture',
    },
    {
      id: 'caffe-caruggi',
      name: 'Caffè dei Vicoli',
      kind: 'bar',
      neighbourhood: 'Caruggi',
      real: false,
      characterId: 'roberto-grimaldi',
      imagePrompt: 'Soft pastel sketch on white paper of a tiny café tucked in narrow medieval alley, dark stone walls, warm yellow light spilling onto cobblestones, vintage coffee posters, red awning, intimate and cozy, deep shadows contrasting with golden light',
    },
    {
      id: 'pasticceria-liquorosa',
      name: 'Pasticceria Liquorosa',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'anna-nervi',
      imagePrompt: 'Soft pastel sketch on white paper of an historic pastry shop with glass display cases filled with pandolce genovese, elegant gilt details, pale green and cream interior, delicate sugar work, warm inviting glow, refined and traditional atmosphere',
    },
    {
      id: 'panificio-castelletto',
      name: 'Panificio Sant\'Anna',
      kind: 'bakery',
      neighbourhood: 'Castelletto',
      real: false,
      characterId: 'francesco-parodi',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood bakery with wooden shelves stacked with focaccia genovese, crusty bread loaves, flour-dusted counter, warm ochre and wheat tones, rustic charm, morning sunlight through window',
    },
    {
      id: 'mercato-orientale',
      name: 'Mercato Orientale',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'paolo-doria',
      imagePrompt: 'Soft pastel sketch on white paper of a grand covered market with iron and glass roof, abundant produce stalls, hanging herbs, colorful vegetables, warm terracotta, forest greens, vibrant market energy, dappled light filtering through',
    },
    {
      id: 'mercato-boccadasse',
      name: 'Mercatino del Porto',
      kind: 'market',
      neighbourhood: 'Boccadasse',
      real: false,
      characterId: 'lucia-ferraro',
      imagePrompt: 'Soft pastel sketch on white paper of a small fisherman\'s market by the harbor, fresh catch displayed on ice, striped umbrellas, fishing nets in background, sea blues and silver fish scales, salty maritime atmosphere',
    },
    {
      id: 'bottega-caruggi',
      name: 'Bottega delle Spezie',
      kind: 'market',
      neighbourhood: 'Caruggi',
      real: false,
      characterId: 'teresa-brignole',
      imagePrompt: 'Soft pastel sketch on white paper of a narrow spice and herb shop, bunches of basil hanging, jars of spices lining dark wood shelves, copper scales, green and amber tones, aromatic and mysterious atmosphere',
    },
    {
      id: 'trattoria-rosmarino',
      name: 'Trattoria dal Rosmarino',
      kind: 'trattoria',
      neighbourhood: 'Caruggi',
      real: false,
      characterId: 'giovanni-repetto',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional trattoria with red and white checkered tablecloths, stone archways, hanging copper pots, vintage wine bottles, warm russet and cream colors, homey and welcoming',
    },
    {
      id: 'ristorante-vista',
      name: 'Ristorante Belvedere',
      kind: 'restaurant',
      neighbourhood: 'Castelletto',
      real: false,
      characterId: 'elena-spinola',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant hilltop restaurant with panoramic views, crisp white linens, large windows overlooking the port, soft blues and whites, refined atmosphere, gentle evening light',
    },
    {
      id: 'antica-osteria',
      name: 'Antica Osteria della Foce',
      kind: 'osteria',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'matteo-ghiglione',
      imagePrompt: 'Soft pastel sketch on white paper of a centuries-old osteria with vaulted ceilings, worn wooden tables, maritime artifacts on walls, amber candlelight, deep burgundy and gold tones, atmospheric and historic',
    },
    {
      id: 'focacceria-recco',
      name: 'Focacceria Genovese',
      kind: 'focacceria',
      neighbourhood: 'Caruggi',
      real: false,
      characterId: 'silvia-castagna',
      imagePrompt: 'Soft pastel sketch on white paper of a simple focaccia shop with wood-fired oven visible, golden focaccia with olive oil glistening, minimal white tile, warm bread tones, olive green accents, delicious simplicity',
    },
    {
      id: 'palazzo-ducale',
      name: 'Palazzo Ducale',
      kind: 'landmark',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'chiara-grimaldi',
      imagePrompt: 'Soft pastel sketch on white paper of the grand Doge\'s Palace with Renaissance facade, marble columns, elegant courtyard, soft grays and cream, architectural grandeur, historical majesty, gentle shadows',
    },
    {
      id: 'lanterna',
      name: 'La Lanterna',
      kind: 'landmark',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'andrea-colombo',
      imagePrompt: 'Soft pastel sketch on white paper of the iconic lighthouse tower against coastal sky, striped stone pattern, Mediterranean blues and whites, seabirds in distance, maritime symbol, proud and solitary',
    },
    {
      id: 'san-lorenzo',
      name: 'Cattedrale di San Lorenzo',
      kind: 'church',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'padre-tommaso',
      imagePrompt: 'Soft pastel sketch on white paper of striped black and white marble cathedral facade, Gothic rose window, grand entrance portal, dramatic contrasts softened by pastel treatment, sacred and imposing',
    },
    {
      id: 'santa-maria-castello',
      name: 'Chiesa di Santa Maria di Castello',
      kind: 'church',
      neighbourhood: 'Caruggi',
      real: true,
      characterId: 'suor-margherita',
      imagePrompt: 'Soft pastel sketch on white paper of Romanesque church with cloister garden, ancient stone walls, peaceful courtyard with fountain, soft greens and aged stone colors, serene and contemplative',
    },
    {
      id: 'villetta-dinegro',
      name: 'Villetta Di Negro',
      kind: 'park',
      neighbourhood: 'Castelletto',
      real: true,
      characterId: 'luca-traverso',
      imagePrompt: 'Soft pastel sketch on white paper of terraced gardens cascading down hillside, palm trees, flowering plants, waterfall feature, lush greens and flower pinks, romantic garden atmosphere, city views beyond',
    },
    {
      id: 'piazza-ferrari',
      name: 'Piazza De Ferrari',
      kind: 'piazza',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'beatrice-ravenna',
      imagePrompt: 'Soft pastel sketch on white paper of grand circular plaza with central fountain, elegant surrounding buildings, bronze and water blues, people crossing the square, civic heart of the city, dynamic yet elegant',
    },
    {
      id: 'piazza-boccadasse',
      name: 'Piazzetta di Boccadasse',
      kind: 'piazza',
      neighbourhood: 'Boccadasse',
      real: true,
      characterId: 'diego-vento',
      imagePrompt: 'Soft pastel sketch on white paper of tiny fishing village square with pastel-colored houses, boats on pebble beach, laundry hanging, intimate scale, peach, pink, yellow facades, Mediterranean charm',
    },
    {
      id: 'enoteca-sola',
      name: 'Enoteca Sola',
      kind: 'enoteca',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'alberto-molinari',
      imagePrompt: 'Soft pastel sketch on white paper of sophisticated wine bar with bottle-lined walls, warm wood shelving, intimate lighting, wine glasses catching light, burgundy and amber tones, cultured atmosphere',
    },
    {
      id: 'wine-bar-castelletto',
      name: 'Il Calice',
      kind: 'wine_bar',
      neighbourhood: 'Castelletto',
      real: false,
      characterId: 'valeria-fieschi',
      imagePrompt: 'Soft pastel sketch on white paper of modern wine bar with terrace seating, contemporary design meets traditional touches, sunset views, soft purples and golds, aperitivo hour ambiance',
    },
    {
      id: 'libreria-bozzi',
      name: 'Libreria Bozzi',
      kind: 'bookshop',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'michele-barbieri',
      imagePrompt: 'Soft pastel sketch on white paper of historic bookshop with floor-to-ceiling shelves, rolling ladder, stacked books, reading nook, warm paper and leather tones, intellectual sanctuary, softly lit',
    },
    {
      id: 'farmacia-europa',
      name: 'Farmacia Europa',
      kind: 'pharmacy',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'dottoressa-carla',
      imagePrompt: 'Soft pastel sketch on white paper of traditional pharmacy with green cross sign, wooden drawers, glass bottles, clean white and mint green interior, professional and reassuring atmosphere',
    },
    {
      id: 'stazione-principe',
      name: 'Stazione di Genova Principe',
      kind: 'station',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'stefano-raggi',
      imagePrompt: 'Soft pastel sketch on white paper of grand railway station with art nouveau details, vaulted iron and glass ceiling, platforms stretching back, warm station lighting, sense of arrivals and departures',
    },
    {
      id: 'porto-antico',
      name: 'Porto Antico',
      kind: 'landmark',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'marina-danese',
      imagePrompt: 'Soft pastel sketch on white paper of old harbor with Renzo Piano\'s Bigo crane structure, maritime museum, wooden boats, industrial heritage meets modern renewal, steel blues and sea greens',
    },
    {
      id: 'gelateria-profumo',
      name: 'Gelateria Profumo',
      kind: 'gelateria',
      neighbourhood: 'Boccadasse',
      real: false,
      characterId: 'daniela-moretti',
      imagePrompt: 'Soft pastel sketch on white paper of seaside gelateria with display case of colorful gelato, beach umbrellas visible through window, pastel pinks and mint greens, cool and refreshing atmosphere',
    },
    {
      id: 'salumeria-fontana',
      name: 'Salumeria Fontana',
      kind: 'specialty_food',
      neighbourhood: 'Caruggi',
      real: false,
      characterId: 'ezio-ruffini',
      imagePrompt: 'Soft pastel sketch on white paper of traditional delicatessen with hanging salami, wheels of cheese, jars of pesto, marble counter, rich reds and cream colors, aromatic and abundant',
    },
    {
      id: 'via-garibaldi',
      name: 'Via Garibaldi - Palazzi dei Rolli',
      kind: 'landmark',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'professor-casella',
      imagePrompt: 'Soft pastel sketch on white paper of Renaissance palace-lined street, ornate facades, grand doorways, UNESCO heritage architecture, ochre and rose stone colors, aristocratic elegance',
    },
    {
      id: 'cantina-squarciafico',
      name: 'Cantina Squarciafico',
      kind: 'enoteca',
      neighbourhood: 'Caruggi',
      real: false,
      characterId: 'tommaso-sacco',
      imagePrompt: 'Soft pastel sketch on white paper of ancient wine cellar in medieval alley, stone vaults, barrel seating, candlelit atmosphere, deep wine reds and stone grays, authentic and timeless',
    },
  ],
  characters: [
    {
      id: 'marco-venturi',
      name: 'Marco Venturi',
      age: 42,
      role: 'proprietario',
      placeId: 'caffe-degli-specchi',
      personality: ['eloquent', 'proud', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man in his forties with graying temples, neat mustache, wearing crisp white shirt and vest, minimal watercolor wash in warm sepia tones, confident expression, detailed crosshatching',
    },
    {
      id: 'giulia-costa',
      name: 'Giulia Costa',
      age: 29,
      role: 'barista',
      placeId: 'bar-boccadasse',
      personality: ['cheerful', 'maritime', 'warm'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with sun-lightened hair in a ponytail, bright smile, casual seaside style, minimal watercolor wash in soft blues, friendly eyes, fine line work',
    },
    {
      id: 'roberto-grimaldi',
      name: 'Roberto Grimaldi',
      age: 56,
      role: 'barista',
      placeId: 'caffe-caruggi',
      personality: ['gruff', 'knowledgeable', 'loyal'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stocky older man with weathered face, thick eyebrows, strong features, wearing simple dark sweater, minimal watercolor in gray tones, serious but kind eyes, bold pen strokes',
    },
    {
      id: 'anna-nervi',
      name: 'Anna Nervi',
      age: 38,
      role: 'pasticciera',
      placeId: 'pasticceria-liquorosa',
      personality: ['meticulous', 'artistic', 'refined'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant woman with hair in neat bun, delicate features, wearing white baker\'s coat, minimal watercolor in pale pinks, focused expression, precise linework',
    },
    {
      id: 'francesco-parodi',
      name: 'Francesco Parodi',
      age: 51,
      role: 'fornaio',
      placeId: 'panificio-castelletto',
      personality: ['jovial', 'generous', 'early-riser'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust man with flour-dusted apron, strong arms, warm smile, receding hairline, minimal watercolor in wheat tones, welcoming demeanor, energetic lines',
    },
    {
      id: 'paolo-doria',
      name: 'Paolo Doria',
      age: 63,
      role: 'venditore',
      placeId: 'mercato-orientale',
      personality: ['boisterous', 'shrewd', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of an animated older man with animated expression, weathered hands, flat cap, vest over shirt, minimal watercolor in earthy tones, twinkling eyes, expressive hatching',
    },
    {
      id: 'lucia-ferraro',
      name: 'Lucia Ferraro',
      age: 45,
      role: 'pescatrice',
      placeId: 'mercato-boccadasse',
      personality: ['straightforward', 'humorous', 'hardworking'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy woman with windswept hair, laugh lines, practical clothing, strong hands, minimal watercolor in sea blues, direct gaze, confident strokes',
    },
    {
      id: 'teresa-brignole',
      name: 'Teresa Brignole',
      age: 67,
      role: 'proprietaria',
      placeId: 'bottega-caruggi',
      personality: ['wise', 'mysterious', 'herbalist'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly woman with silver hair, sharp eyes behind glasses, shawl over shoulders, knowing expression, minimal watercolor in sage green, detailed wrinkles, fine crosshatching',
    },
    {
      id: 'giovanni-repetto',
      name: 'Giovanni Repetto',
      age: 58,
      role: 'cuoco',
      placeId: 'trattoria-rosmarino',
      personality: ['passionate', 'perfectionist', 'nostalgic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a heavyset chef with expressive face, chef\'s whites, wooden spoon in hand, minimal watercolor in warm reds, intense eyes, bold pen work',
    },
    {
      id: 'elena-spinola',
      name: 'Elena Spinola',
      age: 41,
      role: 'sommelier',
      placeId: 'ristorante-vista',
      personality: ['sophisticated', 'knowledgeable', 'poised'],
      portraitPrompt: 'Pen and ink portrait on white paper of an refined woman with elegant updo, fine jewelry, professional attire, minimal watercolor in burgundy, composed expression, graceful lines',
    },
    {
      id: 'matteo-ghiglione',
      name: 'Matteo Ghiglione',
      age: 49,
      role: 'oste',
      placeId: 'antica-osteria',
      personality: ['storyteller', 'convivial', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a friendly man with beard, open collar, wine-stained apron, expressive hands, minimal watercolor in amber tones, warm smile, loose sketchy style',
    },
    {
      id: 'silvia-castagna',
      name: 'Silvia Castagna',
      age: 34,
      role: 'fornaia',
      placeId: 'focacceria-recco',
      personality: ['efficient', 'proud', 'focused'],
      portraitPrompt: 'Pen and ink portrait on white paper of a focused woman with hair tied back, flour on cheek, strong forearms, simple clothing, minimal watercolor in golden tones, determined expression, clean lines',
    },
    {
      id: 'chiara-grimaldi',
      name: 'Chiara Grimaldi',
      age: 31,
      role: 'guida turistica',
      placeId: 'palazzo-ducale',
      personality: ['enthusiastic', 'educated', 'articulate'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with intelligent eyes, professional attire, name badge, gesturing hand, minimal watercolor in soft grays, engaging expression, precise linework',
    },
    {
      id: 'andrea-colombo',
      name: 'Andrea Colombo',
      age: 55,
      role: 'guardiano',
      placeId: 'lanterna',
      personality: ['solitary', 'maritime', 'philosophical'],
      portraitPrompt: 'Pen and ink portrait on white paper of a weathered man with salt-and-pepper beard, sailor\'s sweater, far-seeing eyes, minimal watercolor in sea blues, contemplative expression, textured shading',
    },
    {
      id: 'padre-tommaso',
      name: 'Padre Tommaso Ravasco',
      age: 68,
      role: 'sacerdote',
      placeId: 'san-lorenzo',
      personality: ['scholarly', 'gentle', 'devoted'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly priest with kind face, wire-rimmed glasses, clerical collar, hands clasped, minimal watercolor in subtle purples, serene expression, delicate lines',
    },
    {
      id: 'suor-margherita',
      name: 'Suor Margherita Doria',
      age: 72,
      role: 'suora',
      placeId: 'santa-maria-castello',
      personality: ['peaceful', 'nurturing', 'wise'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly nun with gentle smile, habit framing face, peaceful eyes, prayer beads, minimal watercolor in soft blues, tranquil expression, soft hatching',
    },
    {
      id: 'luca-traverso',
      name: 'Luca Traverso',
      age: 44,
      role: 'giardiniere',
      placeId: 'villetta-dinegro',
      personality: ['patient', 'knowledgeable', 'nature-loving'],
      portraitPrompt: 'Pen and ink portrait on white paper of a lean man with sun-weathered face, work shirt, gardening gloves tucked in belt, minimal watercolor in leaf greens, content expression, organic lines',
    },
    {
      id: 'beatrice-ravenna',
      name: 'Beatrice Ravenna',
      age: 26,
      role: 'artista di strada',
      placeId: 'piazza-ferrari',
      personality: ['creative', 'observant', 'free-spirited'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with artistic style, paint-stained fingers, bohemian clothing, sketchbook under arm, minimal watercolor in multiple colors, lively eyes, expressive strokes',
    },
    {
      id: 'diego-vento',
      name: 'Diego Vento',
      age: 71,
      role: 'pescatore',
      placeId: 'piazza-boccadasse',
      personality: ['taciturn', 'traditional', 'weather-wise'],
      portraitPrompt: 'Pen and ink portrait on white paper of an old fisherman with deeply lined face, captain\'s cap, thick sweater, rope-scarred hands, minimal watercolor in faded blues, distant gaze, heavy crosshatching',
    },
    {
      id: 'alberto-molinari',
      name: 'Alberto Molinari',
      age: 47,
      role: 'enotecario',
      placeId: 'enoteca-sola',
      personality: ['sophisticated', 'passionate', 'discerning'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man with salt-and-pepper hair, refined features, holding wine glass up to light, minimal watercolor in wine tones, connoisseur expression, elegant lines',
    },
    {
      id: 'valeria-fieschi',
      name: 'Valeria Fieschi',
      age: 36,
      role: 'proprietaria',
      placeId: 'wine-bar-castelletto',
      personality: ['modern', 'ambitious', 'social'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stylish woman with contemporary haircut, fashionable clothing, confident posture, wine bottle in background, minimal watercolor in sunset tones, dynamic expression, bold lines',
    },
    {
      id: 'michele-barbieri',
      name: 'Michele Barbieri',
      age: 59,
      role: 'libraio',
      placeId: 'libreria-bozzi',
      personality: ['bibliophile', 'intellectual', 'helpful'],
      portraitPrompt: 'Pen and ink portrait on white paper of a scholarly man with reading glasses on chain, cardigan over shirt, book in hand, minimal watercolor in sepia, thoughtful expression, detailed pen strokes',
    },
    {
      id: 'dottoressa-carla',
      name: 'Dott.ssa Carla Olivieri',
      age: 43,
      role: 'farmacista',
      placeId: 'farmacia-europa',
      personality: ['professional', 'caring', 'precise'],
      portraitPrompt: 'Pen and ink portrait on white paper of a professional woman with neat hair, white pharmacist coat, stethoscope around neck, minimal watercolor in clinical greens, reassuring smile, clean linework',
    },
    {
      id: 'stefano-raggi',
      name: 'Stefano Raggi',
      age: 52,
      role: 'capostazione',
      placeId: 'stazione-principe',
      personality: ['punctual', 'authoritative', 'helpful'],
      portraitPrompt: 'Pen and ink portrait on white paper of a uniformed station master with cap, whistle on chain, clipboard, minimal watercolor in railway blues, alert expression, precise hatching',
    },
    {
      id: 'marina-danese',
      name: 'Marina Danese',
      age: 39,
      role: 'guida museo',
      placeId: 'porto-antico',
      personality: ['maritime-expert', 'engaging', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a woman with windblown hair, nautical striped shirt, pointing gesture, minimal watercolor in maritime blues, enthusiastic expression, flowing lines',
    },
    {
      id: 'daniela-moretti',
      name: 'Daniela Moretti',
      age: 28,
      role: 'gelataia',
      placeId: 'gelateria-profumo',
      personality: ['sweet', 'creative', 'cheerful'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with bright smile, colorful apron, ice cream scoop in hand, minimal watercolor in pastel tones, joyful expression, light sketch style',
    },
    {
      id: 'ezio-ruffini',
      name: 'Ezio Ruffini',
      age: 64,
      role: 'salumiere',
      placeId: 'salumeria-fontana',
      personality: ['traditional', 'exacting', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stocky man with handlebar mustache, white apron, knife at belt, minimal watercolor in meat reds, proud expression, bold pen strokes',
    },
    {
      id: 'professor-casella',
      name: 'Prof. Vittorio Casella',
      age: 66,
      role: 'storico',
      placeId: 'via-garibaldi',
      personality: ['erudite', 'passionate', 'distinguished'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly professor with white hair, bow tie, tweed jacket, architectural drawings visible, minimal watercolor in stone grays, animated expression, scholarly detail',
    },
    {
      id: 'tommaso-sacco',
      name: 'Tommaso Sacco',
      age: 37,
      role: 'cantiniere',
      placeId: 'cantina-squarciafico',
      personality: ['passionate', 'knowledgeable', 'convivial'],
      portraitPrompt: 'Pen and ink portrait on white paper of a bearded man with rolled shirtsleeves, wine-stained hands, barrel in background, minimal watercolor in deep reds, animated expression, textured shading',
    },
  ],
  food: [
    'focaccia genovese',
    'pesto alla genovese',
    'trofie al pesto',
    'farinata',
    'pandolce',
    'pansoti con salsa di noci',
    'cappon magro',
    'cima alla genovese',
    'torta pasqualina',
    'buridda',
    'mesciua',
    'acciughe sotto sale',
    'stoccafisso accomodato',
    'sciamadda',
    'tomaxelle',
    'castagnaccio',
  ],
  customs: [
    'aperitivo in piazza at sunset',
    'Sunday passeggiata along the porto',
    'shopping at Mercato Orientale on Saturday morning',
    'taking coffee standing at the bar',
    'debating the best pesto recipe',
    'evening strolls in Boccadasse',
    'discussing Genoa CFC matches',
    'traditional Christmas pandolce preparation',
    'neighborhood festa celebrations',
    'maintaining palazzo courtyards',
  ],
  localTouches: [
    'using "belin" as an all-purpose exclamation',
    'pride in Christopher Columbus heritage',
    'fierce loyalty to neighborhood',
    'discussing which caruggio is best',
    'complaining about the funicular prices',
    'maritime sayings and expressions',
    'reverence for Andrea Doria',
    'debating focaccia thickness',
    'strong opinions on "proper" pesto',
    'using Genovese dialect with friends',
    'claiming superiority over Milan',
    'nostalgic for "old Genova"',
  ],
};
