import { CityPantry } from '@/lib/types';

export const lecce: CityPantry = {
  id: 'lecce',
  name: 'Lecce',
  neighbourhoods: ['Centro Storico', "Piazza Sant'Oronzo", 'Porta Napoli', 'Santa Croce'],
  places: [
    // BARS & CAFÉS (3)
    {
      id: 'caffe-alvino',
      name: 'Caffè Alvino',
      kind: 'bar',
      neighbourhood: "Piazza Sant'Oronzo",
      real: true,
      characterId: 'michele-alvino',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant historic café with ornate baroque details, outdoor tables with wicker chairs on a sunny piazza, warm ochre and cream tones, honey-colored stone, delicate awning, espresso cups on marble counters, textured and inviting, morning light filtering through',
    },
    {
      id: 'bar-della-vittoria',
      name: 'Bar della Vittoria',
      kind: 'bar',
      neighbourhood: 'Porta Napoli',
      real: false,
      characterId: 'rosa-martino',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood corner bar with vintage sign, glass pastry case visible through window, locals gathering outside, warm terracotta and amber tones, worn but charming facade, morning shadows, inviting glow from interior, textured limestone walls',
    },
    {
      id: 'caffe-letterario',
      name: 'Caffè Letterario',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'antonio-greco',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy literary café with bookshelves visible through arched windows, small round tables, soft golden light, weathered shutters in sage green, stacks of newspapers, intimate and artistic atmosphere, warm cream and amber tones, textured stone archway',
    },
    
    // BAKERIES (2)
    {
      id: 'panificio-fiore',
      name: 'Panificio Fiore',
      kind: 'bakery',
      neighbourhood: 'Santa Croce',
      real: false,
      characterId: 'angela-fiore',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional bakery with golden-crusted bread displayed in the window, flour-dusted counter, warm amber light glowing from wood-fired oven, rustic shelves with focaccia and taralli, inviting scent suggested through soft warm tones, textured and homey',
    },
    {
      id: 'pasticceria-natale',
      name: 'Pasticceria Natale',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'donato-natale',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant pasticceria with glass cases filled with pasticciotti and pastries, delicate cream and gold tones, ornate ceiling details, marble counters, soft morning light, trays of almond paste sweets, refined and traditional, warm inviting atmosphere',
    },
    
    // MARKETS (3)
    {
      id: 'mercato-comunale',
      name: 'Mercato Comunale',
      kind: 'market',
      neighbourhood: "Piazza Sant'Oronzo",
      real: false,
      characterId: 'salvatore-leone',
      imagePrompt: 'Soft pastel sketch on white paper of a bustling covered market with vegetable stalls overflowing with vibrant produce, hanging peppers, wooden crates of tomatoes, soft dappled light through awnings, warm earthy tones with pops of red and green, vendors calling out, lively and colorful',
    },
    {
      id: 'mercato-contadino',
      name: 'Mercato Contadino',
      kind: 'market',
      neighbourhood: 'Porta Napoli',
      real: false,
      characterId: 'teresa-maggio',
      imagePrompt: 'Soft pastel sketch on white paper of an outdoor farmers market with rustic wooden stands, local vegetables and olive oil in glass bottles, handwritten signs, weathered stone backdrop, morning sunlight, authentic farm-to-table atmosphere, warm ochre and green tones, textured and earthy',
    },
    {
      id: 'pescheria-del-porto',
      name: 'Pescheria del Porto',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'paolo-marino',
      imagePrompt: 'Soft pastel sketch on white paper of a fresh fish market with ice-covered displays, silvery fish glistening, blue and white tiled walls, weathered wooden counters, cool blue-grey tones mixed with warm stone, maritime character, authentic and bustling, morning catch atmosphere',
    },
    
    // RESTAURANTS (2)
    {
      id: 'alle-due-corti',
      name: 'Alle Due Corti',
      kind: 'restaurant',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'leonardo-rizzo',
      imagePrompt: 'Soft pastel sketch on white paper of an intimate restaurant courtyard with stone arches, candlelit tables with white linens, climbing vines on ancient walls, warm honey-colored stone, romantic evening atmosphere, soft golden light, elegant yet rustic, inviting shadows and warm tones',
    },
    {
      id: 'osteria-degli-spiriti',
      name: 'Osteria degli Spiriti',
      kind: 'restaurant',
      neighbourhood: 'Santa Croce',
      real: true,
      characterId: 'francesca-de-carlo',
      imagePrompt: 'Soft pastel sketch on white paper of a charming osteria with vaulted stone ceiling visible through entrance, rustic wooden tables, wine bottles lining walls, warm amber and terracotta tones, intimate dining atmosphere, soft lamplight, authentic Pugliese character, textured ancient walls',
    },
    
    // SPECIALTY FOOD (2)
    {
      id: 'trattoria-nonna-tetti',
      name: 'Trattoria Nonna Tetti',
      kind: 'trattoria',
      neighbourhood: "Piazza Sant'Oronzo",
      real: false,
      characterId: 'marietta-pellegrino',
      imagePrompt: 'Soft pastel sketch on white paper of a homestyle trattoria with checkered tablecloths, hand-painted ceramic plates on walls, warm family atmosphere, copper pots visible in kitchen, golden afternoon light, red and white accents, inviting and nostalgic, grandmother\'s kitchen feeling',
    },
    {
      id: 'rusticceria-santa-croce',
      name: 'Rusticceria Santa Croce',
      kind: 'rusticceria',
      neighbourhood: 'Santa Croce',
      real: false,
      characterId: 'giuseppe-taurino',
      imagePrompt: 'Soft pastel sketch on white paper of a takeaway shop with golden fried rustico pastries in display, pucce and panzerotti stacked in baskets, casual counter service, warm yellow and amber tones, steam and delicious atmosphere, locals queuing, authentic street food character, inviting warmth',
    },
    
    // MAJOR LANDMARK (1)
    {
      id: 'basilica-santa-croce',
      name: 'Basilica di Santa Croce',
      kind: 'landmark',
      neighbourhood: 'Santa Croce',
      real: true,
      characterId: 'padre-roberto',
      imagePrompt: 'Soft pastel sketch on white paper of the magnificent baroque basilica with elaborate stone carved facade, intricate rose window, dramatic sculptural details, warm honey-colored lecce stone, late afternoon golden light highlighting the ornate carvings, majestic yet inviting, soft shadows, architectural masterpiece',
    },
    
    // CHURCHES/CULTURAL SITES (2)
    {
      id: 'duomo-lecce',
      name: 'Duomo di Lecce',
      kind: 'church',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'suor-clara',
      imagePrompt: 'Soft pastel sketch on white paper of the cathedral in its enclosed piazza, baroque bell tower reaching skyward, ornate facade, warm golden stone glowing in sunlight, quiet spiritual atmosphere, ancient paving stones, soft shadows, peaceful and grand, honey and cream tones',
    },
    {
      id: 'museo-faggiano',
      name: 'Museo Faggiano',
      neighbourhood: 'Centro Storico',
      kind: 'museum',
      real: true,
      characterId: 'lucio-faggiano',
      imagePrompt: 'Soft pastel sketch on white paper of a small museum entrance in an ancient building, archaeological layers visible, stone archways revealing history, warm amber light, mysterious and educational atmosphere, weathered walls showing centuries, intimate cultural space, textured limestone and ancient character',
    },
    
    // PARK/GARDEN (1)
    {
      id: 'villa-comunale',
      name: 'Villa Comunale',
      kind: 'park',
      neighbourhood: 'Porta Napoli',
      real: true,
      characterId: 'enzo-palmieri',
      imagePrompt: 'Soft pastel sketch on white paper of a public garden with palm trees and Mediterranean pines, shaded walking paths, ornate iron benches, dappled sunlight through leaves, soft greens and earth tones, peaceful urban oasis, families strolling, gentle afternoon atmosphere, textured foliage',
    },
    
    // PIAZZAS (2)
    {
      id: 'piazza-santoronzo',
      name: 'Piazza Sant\'Oronzo',
      kind: 'piazza',
      neighbourhood: "Piazza Sant'Oronzo",
      real: true,
      characterId: 'mario-santoro',
      imagePrompt: 'Soft pastel sketch on white paper of the main square with Roman amphitheater ruins, tall column of Sant\'Oronzo, cafés with outdoor seating, people gathering, warm limestone paving, late afternoon golden light, social heart of city, architectural layers, lively yet relaxed atmosphere',
    },
    {
      id: 'piazzetta-falconieri',
      name: 'Piazzetta Falconieri',
      kind: 'piazza',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'giulia-moretti',
      imagePrompt: 'Soft pastel sketch on white paper of a small intimate square with stone benches, baroque palazzo facades, locals chatting, laundry hanging from iron balconies, warm golden hour light, neighborhood gathering spot, authentic daily life, soft ochre and cream tones, textured and charming',
    },
    
    // WINE BARS/APERITIVO (2)
    {
      id: 'enoteca-mamma-elvira',
      name: 'Enoteca Mamma Elvira',
      kind: 'enoteca',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'elvira-convertini',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy wine bar with bottles lining stone walls, intimate candlelit tables, baroque vaulted ceiling, warm amber and burgundy tones, wooden wine crates, evening atmosphere, sophisticated yet welcoming, soft glow, authentic enoteca character',
    },
    {
      id: 'lounge-bar-matteotti',
      name: 'Lounge Bar Matteotti',
      kind: 'bar',
      neighbourhood: "Piazza Sant'Oronzo",
      real: false,
      characterId: 'stefano-bianchi',
      imagePrompt: 'Soft pastel sketch on white paper of a modern aperitivo bar with outdoor seating on elegant piazza, colorful cocktails, aperitivo spreads, contemporary meets historic setting, evening light, stylish and social, warm golden tones, people gathering for pre-dinner drinks, inviting atmosphere',
    },
    
    // BOOKSHOP/CULTURAL (1)
    {
      id: 'libreria-palmieri',
      name: 'Libreria Palmieri',
      kind: 'bookshop',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'anna-palmieri',
      imagePrompt: 'Soft pastel sketch on white paper of a historic bookshop with floor-to-ceiling wooden shelves, stacked books, reading nook with antique chair, warm lamplight, literary atmosphere, dust motes in sunbeam, cream and amber tones, intimate cultural space, inviting for book lovers',
    },
    
    // PRACTICAL (2)
    {
      id: 'farmacia-centrale',
      name: 'Farmacia Centrale',
      kind: 'pharmacy',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'dottoressa-valente',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional pharmacy with green cross sign, antique wooden cabinets with glass jars, marble counter, clean professional atmosphere, soft green and white tones, trusted neighborhood landmark, morning light through historic windows, caring environment',
    },
    {
      id: 'stazione-lecce',
      name: 'Stazione di Lecce',
      kind: 'station',
      neighbourhood: 'Porta Napoli',
      real: true,
      characterId: 'carlo-ferraro',
      imagePrompt: 'Soft pastel sketch on white paper of a regional train station with travelers with luggage, departure boards, arched architecture, functional yet historic character, morning commuters, warm neutral tones, gateway to city, textured platforms, bustling transportation hub atmosphere',
    },
    
    // CITY CHARACTER - LECCE SPECIFIC (3)
    {
      id: 'bottega-cartapesta',
      name: 'Bottega della Cartapesta',
      kind: 'artisan',
      neighbourhood: 'Santa Croce',
      real: false,
      characterId: 'maestro-orlando',
      imagePrompt: 'Soft pastel sketch on white paper of an artisan workshop with papier-mâché figures and saints, works in progress, paints and tools scattered on workbench, warm creative atmosphere, golden afternoon light, traditional craft space, colorful and textured, authentic Lecce art form, inviting chaos',
    },
    {
      id: 'scuola-ceramica',
      name: 'Scuola di Ceramica Salentina',
      kind: 'artisan',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'luisa-de-marco',
      imagePrompt: 'Soft pastel sketch on white paper of a ceramic studio with hand-painted plates and tiles, colorful traditional Salento patterns, potter\'s wheel, shelves of glazed pieces, creative workspace, warm terracotta and blue tones, artistic and authentic, afternoon light on glazed surfaces',
    },
    {
      id: 'anfiteatro-romano',
      name: 'Anfiteatro Romano',
      kind: 'landmark',
      neighbourhood: "Piazza Sant'Oronzo",
      real: true,
      characterId: 'guida-alessandra',
      imagePrompt: 'Soft pastel sketch on white paper of ancient Roman amphitheater ruins partially excavated in city center, weathered stone seats and columns, modern city built around it, layers of history visible, warm limestone in afternoon sun, archaeological wonder, textured ancient stone, atmospheric and timeless',
    },
    
    // ADDITIONAL DAILY LIFE PLACES (4)
    {
      id: 'tabaccheria-moderna',
      name: 'Tabaccheria Moderna',
      kind: 'shop',
      neighbourhood: "Piazza Sant'Oronzo",
      real: false,
      characterId: 'vincenzo-longo',
      imagePrompt: 'Soft pastel sketch on white paper of a corner tobacco shop with newspapers hanging outside, lottery tickets displayed, locals gathering for chat, practical neighborhood spot, warm morning light, blue and white signage, community meeting point, authentic Italian daily life',
    },
    {
      id: 'gelateria-natale',
      name: 'Gelateria Natale',
      kind: 'gelateria',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'simona-bianco',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional gelato shop with colorful tubs of gelato behind glass, pastel-toned walls, vintage gelato cart outside, families with cones, evening passeggiata atmosphere, soft cream and fruit colors, sweet and inviting, warm summer evening light',
    },
    {
      id: 'salumeria-del-corso',
      name: 'Salumeria del Corso',
      kind: 'deli',
      neighbourhood: 'Porta Napoli',
      real: false,
      characterId: 'pino-grassi',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional delicatessen with hanging salami and prosciutto, wheels of cheese, olive oils on shelves, marble counter, rich food atmosphere, warm amber light, authentic provisions shop, terracotta and cream tones, aromatic and inviting',
    },
    {
      id: 'forno-santa-lucia',
      name: 'Forno Santa Lucia',
      kind: 'bakery',
      neighbourhood: "Piazza Sant'Oronzo",
      real: false,
      characterId: 'carmela-russo',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood wood-fired oven bakery with focaccia barese and puccia bread, rustic interior, flour-dusted surfaces, warm glow from oven, locals with shopping bags, morning ritual, golden and cream tones, comforting traditional atmosphere',
    },
  ],
  
  characters: [
    {
      id: 'michele-alvino',
      name: 'Michele Alvino',
      age: 58,
      role: 'proprietario',
      placeId: 'caffe-alvino',
      personality: ['tradizionale', 'orgoglioso', 'accogliente'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man in his late fifties with silver hair, warm smile, wearing crisp white shirt and vest, confident bearing, kind eyes with crow\'s feet, minimal watercolor wash in warm sepia tones, detailed crosshatching, proud proprietor of historic café',
    },
    {
      id: 'rosa-martino',
      name: 'Rosa Martino',
      age: 42,
      role: 'barista',
      placeId: 'bar-della-vittoria',
      personality: ['chiacchierona', 'energica', 'affettuosa'],
      portraitPrompt: 'Pen and ink portrait on white paper of a vivacious woman in her forties with curly dark hair pulled back, bright expressive eyes, warm genuine smile, wearing casual work clothes with apron, animated expression, minimal watercolor wash in warm ochre, detailed pen work, neighborhood favorite',
    },
    {
      id: 'antonio-greco',
      name: 'Antonio Greco',
      age: 35,
      role: 'barista e poeta',
      placeId: 'caffe-letterario',
      personality: ['intellettuale', 'riflessivo', 'gentile'],
      portraitPrompt: 'Pen and ink portrait on white paper of a thoughtful man in his mid-thirties with glasses, slightly tousled hair, sensitive features, wearing casual sweater, book in background, contemplative expression, minimal watercolor wash in cool greys and warm browns, artistic soul, detailed line work',
    },
    {
      id: 'angela-fiore',
      name: 'Angela Fiore',
      age: 51,
      role: 'fornaia',
      placeId: 'panificio-fiore',
      personality: ['laboriosa', 'premurosa', 'schietta'],
      portraitPrompt: 'Pen and ink portrait on white paper of a strong hardworking woman in her fifties with flour-dusted apron, hair in practical bun, capable hands, warm but no-nonsense expression, laugh lines around eyes, minimal watercolor wash in warm wheat tones, detailed hatching, master baker',
    },
    {
      id: 'donato-natale',
      name: 'Donato Natale',
      age: 67,
      role: 'pasticciere',
      placeId: 'pasticceria-natale',
      personality: ['meticoloso', 'tradizionalista', 'saggio'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly master pastry chef with white hair and mustache, dignified bearing, wearing traditional chef whites, experienced gentle eyes, aristocratic features, minimal watercolor wash in cream and gold tones, refined detailed pen work, artisan pride',
    },
    {
      id: 'salvatore-leone',
      name: 'Salvatore Leone',
      age: 54,
      role: 'venditore',
      placeId: 'mercato-comunale',
      personality: ['chiassoso', 'simpatico', 'generoso'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust market vendor in his fifties with weathered face, booming laugh, rolled-up sleeves, hands gesturing expressively, salt-and-pepper hair, joyful eyes, minimal watercolor wash in earthy terracotta, detailed energetic line work, larger than life',
    },
    {
      id: 'teresa-maggio',
      name: 'Teresa Maggio',
      age: 46,
      role: 'contadina',
      placeId: 'mercato-contadino',
      personality: ['genuina', 'orgogliosa', 'paziente'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sun-weathered farmer woman in her forties with kind face, practical head scarf, strong capable features, earth under fingernails, honest direct gaze, minimal watercolor wash in olive green and earth tones, detailed crosshatching, connection to land',
    },
    {
      id: 'paolo-marino',
      name: 'Paolo Marino',
      age: 39,
      role: 'pescivendolo',
      placeId: 'pescheria-del-porto',
      personality: ['diretto', 'scherzoso', 'esperto'],
      portraitPrompt: 'Pen and ink portrait on white paper of a fishmonger in his late thirties with weather-beaten features, quick smile, wearing rubber apron and boots, sleeves rolled up, knowing expression, minimal watercolor wash in cool blue-grey tones, detailed pen work, man of the sea',
    },
    {
      id: 'leonardo-rizzo',
      name: 'Leonardo Rizzo',
      age: 44,
      role: 'chef e proprietario',
      placeId: 'alle-due-corti',
      personality: ['appassionato', 'perfezionista', 'carismatico'],
      portraitPrompt: 'Pen and ink portrait on white paper of a charismatic chef in his forties with intense eyes, confident smile, chef whites, distinguished salt-and-pepper beard, artistic hands, passionate expression, minimal watercolor wash in warm amber, detailed sophisticated line work, culinary artist',
    },
    {
      id: 'francesca-de-carlo',
      name: 'Francesca De Carlo',
      age: 38,
      role: 'chef',
      placeId: 'osteria-degli-spiriti',
      personality: ['creativa', 'determinata', 'cordiale'],
      portraitPrompt: 'Pen and ink portrait on white paper of a talented female chef in her late thirties with pulled-back dark hair, bright intelligent eyes, wearing chef coat, warm welcoming smile, strong features, minimal watercolor wash in terracotta and cream, detailed confident line work, modern traditionalist',
    },
    {
      id: 'marietta-pellegrino',
      name: 'Marietta Pellegrino',
      age: 71,
      role: 'cuoca',
      placeId: 'trattoria-nonna-tetti',
      personality: ['materna', 'testarda', 'affettuosa'],
      portraitPrompt: 'Pen and ink portrait on white paper of a grandmother cook in her seventies with silver hair in bun, warm crinkled eyes, flour on cheek, wearing traditional apron over house dress, loving expression, wooden spoon in hand, minimal watercolor wash in warm rose and cream, detailed tender line work',
    },
    {
      id: 'giuseppe-taurino',
      name: 'Giuseppe Taurino',
      age: 33,
      role: 'friggitore',
      placeId: 'rusticceria-santa-croce',
      personality: ['veloce', 'allegro', 'preciso'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young fry cook in his thirties with quick smile, energetic expression, wearing casual work clothes and cap, confident stance, flour-dusted, happy in his element, minimal watercolor wash in golden yellow, detailed dynamic line work, street food master',
    },
    {
      id: 'padre-roberto',
      name: 'Padre Roberto',
      age: 56,
      role: 'sacerdote',
      placeId: 'basilica-santa-croce',
      personality: ['contemplativo', 'colto', 'disponibile'],
      portraitPrompt: 'Pen and ink portrait on white paper of a priest in his fifties with gentle scholarly features, wire-rim glasses, serene expression, wearing simple clerical collar, wisdom in eyes, minimal watercolor wash in subtle grey and cream, detailed reverent line work, spiritual guide',
    },
    {
      id: 'suor-clara',
      name: 'Suor Clara',
      age: 48,
      role: 'suora',
      placeId: 'duomo-lecce',
      personality: ['serena', 'pratica', 'compassionevole'],
      portraitPrompt: 'Pen and ink portrait on white paper of a nun in her late forties with peaceful face framed by wimple, kind eyes, gentle smile, hands folded, quiet strength in features, minimal watercolor wash in soft grey-blue, detailed delicate line work, devoted caretaker',
    },
    {
      id: 'lucio-faggiano',
      name: 'Lucio Faggiano',
      age: 62,
      role: 'proprietario e guida',
      placeId: 'museo-faggiano',
      personality: ['curioso', 'narratore', 'entusiasta'],
      portraitPrompt: 'Pen and ink portrait on white paper of an enthusiastic museum owner in his sixties with animated features, bright curious eyes, gesturing hands, casual but dignified dress, storyteller expression, minimal watercolor wash in warm earth tones, detailed expressive line work, accidental archaeologist',
    },
    {
      id: 'enzo-palmieri',
      name: 'Enzo Palmieri',
      age: 68,
      role: 'giardiniere',
      placeId: 'villa-comunale',
      personality: ['tranquillo', 'paziente', 'saggio'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly gardener with weathered kind face, sun hat, soil-stained hands, peaceful expression, connection to nature in eyes, wearing practical work clothes, minimal watercolor wash in soft green and brown, detailed gentle line work, keeper of gardens',
    },
    {
      id: 'mario-santoro',
      name: 'Mario Santoro',
      age: 45,
      role: 'musicista di strada',
      placeId: 'piazza-santoronzo',
      personality: ['espressivo', 'bohémien', 'ottimista'],
      portraitPrompt: 'Pen and ink portrait on white paper of a street musician in his forties with expressive face, guitar strap visible, artistic temperament in features, warm eyes, slight beard, casual bohemian style, minimal watercolor wash in warm golden tones, detailed romantic line work, soul of the piazza',
    },
    {
      id: 'giulia-moretti',
      name: 'Giulia Moretti',
      age: 29,
      role: 'artista',
      placeId: 'piazzetta-falconieri',
      personality: ['sognatrice', 'sensibile', 'osservatrice'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young artist in her late twenties with thoughtful eyes, paint-stained fingers, flowing dark hair, sketchbook visible, introspective expression, wearing artistic casual clothes, minimal watercolor wash in soft purple-grey, detailed sensitive line work, creative spirit',
    },
    {
      id: 'elvira-convertini',
      name: 'Elvira Convertini',
      age: 59,
      role: 'proprietaria',
      placeId: 'enoteca-mamma-elvira',
      personality: ['esperta', 'sofisticata', 'calorosa'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant wine bar owner in her late fifties with sophisticated style, knowing smile, holding wine glass, intelligent eyes, tasteful jewelry, confident bearing, minimal watercolor wash in burgundy and cream, detailed refined line work, wine expert',
    },
    {
      id: 'stefano-bianchi',
      name: 'Stefano Bianchi',
      age: 31,
      role: 'barman',
      placeId: 'lounge-bar-matteotti',
      personality: ['moderno', 'socievole', 'professionale'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stylish young bartender in his thirties with neat hair, fashionable beard, mixing cocktail, confident smile, modern style, wearing vest and rolled sleeves, minimal watercolor wash in cool grey and warm amber, detailed contemporary line work, mixologist',
    },
    {
      id: 'anna-palmieri',
      name: 'Anna Palmieri',
      age: 52,
      role: 'libraia',
      placeId: 'libreria-palmieri',
      personality: ['colta', 'appassionata', 'riservata'],
      portraitPrompt: 'Pen and ink portrait on white paper of a cultured bookseller in her fifties with reading glasses on chain, thoughtful expression, book in hand, intelligent features, elegant simple style, surrounded by literary atmosphere, minimal watercolor wash in sepia and cream, detailed scholarly line work, book lover',
    },
    {
      id: 'dottoressa-valente',
      name: 'Dottoressa Valente',
      age: 43,
      role: 'farmacista',
      placeId: 'farmacia-centrale',
      personality: ['professionale', 'premurosa', 'affidabile'],
      portraitPrompt: 'Pen and ink portrait on white paper of a professional pharmacist in her forties with kind competent face, white coat, hair pulled back neatly, caring eyes, trustworthy expression, minimal watercolor wash in soft green and white, detailed precise line work, healthcare provider',
    },
    {
      id: 'carlo-ferraro',
      name: 'Carlo Ferraro',
      age: 55,
      role: 'capostazione',
      placeId: 'stazione-lecce',
      personality: ['puntuale', 'serio', 'rispettoso'],
      portraitPrompt: 'Pen and ink portrait on white paper of a railway station master in his fifties with dignified bearing, uniform cap, serious but kind face, mustache, watch chain visible, responsible expression, minimal watercolor wash in railway blue and grey, detailed authoritative line work, keeper of schedules',
    },
    {
      id: 'maestro-orlando',
      name: 'Maestro Orlando',
      age: 64,
      role: 'artigiano di cartapesta',
      placeId: 'bottega-cartapesta',
      personality: ['creativo', 'paziente', 'tradizionale'],
      portraitPrompt: 'Pen and ink portrait on white paper of a master papier-mâché artisan in his sixties with paint-stained hands, gentle eyes, slight beard, wearing smock, surrounded by his creations, contemplative expression, minimal watercolor wash in warm ochre and blue, detailed artistic line work, keeper of tradition',
    },
    {
      id: 'luisa-de-marco',
      name: 'Luisa De Marco',
      age: 37,
      role: 'ceramista',
      placeId: 'scuola-ceramica',
      personality: ['artistica', 'insegnante', 'innovativa'],
      portraitPrompt: 'Pen and ink portrait on white paper of a ceramic artist in her late thirties with clay-stained hands, bright creative eyes, hair tied back with colorful scarf, wearing pottery apron, passionate expression, minimal watercolor wash in terracotta and azure blue, detailed expressive line work, modern artisan',
    },
    {
      id: 'guida-alessandra',
      name: 'Alessandra Ricci',
      age: 34,
      role: 'guida turistica',
      placeId: 'anfiteatro-romano',
      personality: ['entusiasta', 'preparata', 'comunicativa'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young tour guide in her thirties with animated expression, gesturing hands, intelligent eyes, wearing professional but approachable clothing, warm smile, historical knowledge in bearing, minimal watercolor wash in warm stone tones, detailed engaging line work, storyteller',
    },
    {
      id: 'vincenzo-longo',
      name: 'Vincenzo Longo',
      age: 61,
      role: 'tabaccaio',
      placeId: 'tabaccheria-moderna',
      personality: ['informato', 'pettegolo', 'amichevole'],
      portraitPrompt: 'Pen and ink portrait on white paper of a neighborhood tobacconist in his sixties with knowing smile, reading glasses, newspaper in hand, friendly wrinkled face, vest over shirt, hub of local gossip, minimal watercolor wash in warm brown and blue, detailed character-filled line work, neighborhood oracle',
    },
    {
      id: 'simona-bianco',
      name: 'Simona Bianco',
      age: 28,
      role: 'gelataia',
      placeId: 'gelateria-natale',
      personality: ['allegra', 'dolce', 'solare'],
      portraitPrompt: 'Pen and ink portrait on white paper of a cheerful young gelato maker in her late twenties with bright smile, colorful apron, hair in ponytail, holding gelato scoop, joyful expression, summer in her eyes, minimal watercolor wash in pastel fruit tones, detailed happy line work, bringer of sweetness',
    },
    {
      id: 'pino-grassi',
      name: 'Pino Grassi',
      age: 57,
      role: 'salumiere',
      placeId: 'salumeria-del-corso',
      personality: ['esperto', 'generoso', 'conviviale'],
      portraitPrompt: 'Pen and ink portrait on white paper of a traditional delicatessen owner in his fifties with substantial build, white apron, warm jovial face, mustache, knife in hand, expert in his craft, minimal watercolor wash in rich meat and cheese tones, detailed savory line work, master of provisions',
    },
    {
      id: 'carmela-russo',
      name: 'Carmela Russo',
      age: 49,
      role: 'fornaia',
      placeId: 'forno-santa-lucia',
      personality: ['mattiniera', 'robusta', 'affidabile'],
      portraitPrompt: 'Pen and ink portrait on white paper of a baker woman in her late forties with strong arms, flour in hair, early morning energy in face, practical apron, capable hands, honest hardworking expression, minimal watercolor wash in warm bread tones, detailed sturdy line work, breadmaker of the neighborhood',
    },
  ],
  
  food: [
    'pasticciotto',
    'rustico leccese',
    'puccia',
    'orecchiette',
    'ciceri e tria',
    'riso, patate e cozze',
    'polpo alla pignata',
    'pezzetti di cavallo',
    'fave e cicoria',
    'cotognata',
    'fruttone',
    'caffè in ghiaccio',
    'caffè con latte di mandorla',
    'pittule',
    'taralli',
    'focaccia barese',
    'panzerotto',
    'popizze',
    'purè di fave',
    'burrata',
    'caciocavallo podolico',
    'sagne ncannulate',
    'cupeta',
    'spumone salentino',
  ],
  
  customs: [
    'Il passeggio serale in Via Trinchese',
    'Il caffè in ghiaccio anche d\'inverno',
    'La rosticceria come spuntino mattutino',
    'La visita domenicale al mercato contadino',
    'L\'aperitivo lungo in piazza Sant\'Oronzo',
    'La tradizione della cartapesta per le feste',
    'Il culto di Sant\'Oronzo, patrono della città',
    'Le luminarie elaborate per le feste patronali',
    'La cena in cortile nei mesi estivi',
    'Le conversazioni davanti al portone di casa',
    'La focaccia barese del sabato mattina',
    'Il gelato dopo cena in centro storico',
  ],
  
  localTouches: [
    'Mo te lu spiego - Ora te lo spiego (Now I\'ll explain it to you)',
    'Cu è? - Chi è? (Who is it?)',
    'Aggiu fame - Ho fame (I\'m hungry)',
    'Quant\'è bellu! - Quanto è bello! (How beautiful!)',
    'Salento nel cuore - Salento in the heart',
    'La pietra leccese - The Lecce stone (honey-colored local limestone)',
    'La Firenze del Sud - The Florence of the South',
    'Barocco leccese - Lecce baroque (ornate local architectural style)',
    'Salentinu verace - True person from Salento',
    'Pizzica - Traditional folk dance and music',
    'Ieu sugnu de Lecce - Io sono di Lecce (I\'m from Lecce)',
    'Cristu de lu puzzu - Reference to baroque crucifixes',
  ],
};
