import { CityPantry } from '@/lib/types';

export const lucca: CityPantry = {
  id: 'lucca',
  name: 'Lucca',
  neighbourhoods: ['Centro Storico', 'San Michele', 'San Martino', 'San Frediano'],
  places: [
    // BARS & CAFÉS (9)
    {
      id: 'caffe-di-simo',
      name: 'Caffè Di Simo',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'sergio-di-simo',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant historic café with Art Nouveau interior, marble-topped tables, antique mirrors, ornate chandeliers, warm amber and cream tones, people reading newspapers at the counter, textured walls showing age and character, inviting morning light through tall windows',
    },
    {
      id: 'bar-il-fortino',
      name: 'Bar Il Fortino',
      kind: 'bar',
      neighbourhood: 'San Michele',
      real: false,
      characterId: 'giulia-fortino',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy neighborhood bar with blue-painted wooden shutters, outdoor tables on cobblestones, chalkboard menu, locals chatting at zinc counter, warm ochre and terracotta colors, morning espresso cups lined up, inviting intimate atmosphere',
    },
    {
      id: 'caffe-delle-mura',
      name: 'Caffè delle Mura',
      kind: 'bar',
      neighbourhood: 'San Martino',
      real: false,
      characterId: 'marco-traversi',
      imagePrompt: 'Soft pastel sketch on white paper of a café nestled against the ancient city walls, outdoor terrace with plane trees, stone walls covered in ivy, soft green and gray tones, bicycle propped against wall, morning pastries in glass case, peaceful atmosphere',
    },
    {
      id: 'bar-duomo',
      name: 'Bar Duomo',
      kind: 'bar',
      neighbourhood: 'San Martino',
      real: false,
      characterId: 'anna-benedetti',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional bar with view of cathedral façade, red awning, polished brass espresso machine, locals standing at counter, warm brown and gold tones, morning ritual scene, welcoming and bustling',
    },
    {
      id: 'bar-nannini',
      name: 'Bar Nannini',
      kind: 'bar',
      neighbourhood: 'San Frediano',
      real: false,
      characterId: 'roberto-nannini',
      imagePrompt: 'Soft pastel sketch on white paper of an artisan neighborhood bar with vintage posters, wooden shelving with local products, hand-painted ceramic cups, warm terracotta and sage green colors, students and workers mingling, authentic local atmosphere',
    },
    {
      id: 'caffe-santa-zita',
      name: 'Caffè Santa Zita',
      kind: 'bar',
      neighbourhood: 'San Frediano',
      real: false,
      characterId: 'elena-marchetti',
      imagePrompt: 'Soft pastel sketch on white paper of a charming corner café with flower boxes, pastel pink and cream exterior, round bistro tables, morning light streaming in, neighbors greeting each other, warm welcoming colors, lived-in comfortable feel',
    },
    {
      id: 'bar-anfiteatro',
      name: 'Bar Anfiteatro',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'davide-russo',
      imagePrompt: 'Soft pastel sketch on white paper of a café in the oval piazza, medieval architecture surrounding, terracotta building facades, outdoor seating in curved formation, warm golden and amber tones, tourists and locals mixed, romantic historic setting',
    },
    {
      id: 'caffe-carli',
      name: 'Caffè Carli',
      kind: 'bar',
      neighbourhood: 'San Michele',
      real: false,
      characterId: 'chiara-carli',
      imagePrompt: 'Soft pastel sketch on white paper of a modern-traditional café with exposed brick, contemporary lighting, vintage espresso machine, artful pastry display, soft gray and rose colors, young professionals reading, sophisticated atmosphere',
    },
    {
      id: 'bar-colombini',
      name: 'Bar Colombini',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'francesco-colombini',
      imagePrompt: 'Soft pastel sketch on white paper of a classic Italian bar with green marble counter, silver coffee pots, glass pastry cases, locals in animated conversation, warm cream and green tones, morning newspapers on rack, timeless authentic scene',
    },

    // BAKERIES (6)
    {
      id: 'forno-amedeo-giusti',
      name: 'Forno Amedeo Giusti',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'amedeo-giusti',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional Tuscan bakery with wood-fired oven, golden buccellato breads on display, flour-dusted wooden shelves, warm amber and wheat tones, customers queuing, artisanal rustic atmosphere, morning baking scene',
    },
    {
      id: 'panificio-guidi',
      name: 'Panificio Guidi',
      kind: 'bakery',
      neighbourhood: 'San Michele',
      real: false,
      characterId: 'lucia-guidi',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood bakery with striped awning, baskets of fresh bread, focaccia in window, warm yellow and cream colors, local families shopping, flour handprints on aprons, homey welcoming feel',
    },
    {
      id: 'forno-bernardi',
      name: 'Forno Bernardi',
      kind: 'bakery',
      neighbourhood: 'San Martino',
      real: false,
      characterId: 'paolo-bernardi',
      imagePrompt: 'Soft pastel sketch on white paper of a corner bakery with ceramic tiles, traditional brick oven visible, golden pastries and cakes displayed, warm orange and brown tones, sweet yeasty atmosphere, neighbors chatting outside',
    },
    {
      id: 'panificio-del-corso',
      name: 'Panificio del Corso',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'stefania-mancini',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant bakery on main street, tall windows, artful bread displays, contemporary meets traditional, soft cream and sage tones, wrapped packages with twine, refined presentation',
    },
    {
      id: 'forno-sant-anna',
      name: "Forno Sant'Anna",
      kind: 'bakery',
      neighbourhood: 'San Frediano',
      real: false,
      characterId: 'giovanni-lippi',
      imagePrompt: 'Soft pastel sketch on white paper of a rustic neighborhood bakery with wooden doors, stone floor, mountains of fresh bread, traditional tools on walls, warm wheat and terracotta colors, flour dust in air, authentic craftsman atmosphere',
    },
    {
      id: 'pasticceria-pinelli',
      name: 'Pasticceria Pinelli',
      kind: 'bakery',
      neighbourhood: 'San Michele',
      real: false,
      characterId: 'mariella-pinelli',
      imagePrompt: 'Soft pastel sketch on white paper of a refined pastry shop with glass cases of delicate cakes, buccellato cakes on pedestals, elegant packaging, soft pink and white palette, crystal chandeliers, special occasion atmosphere',
    },

    // MARKETS (3)
    {
      id: 'mercato-del-carmine',
      name: 'Mercato del Carmine',
      kind: 'market',
      neighbourhood: 'San Frediano',
      real: true,
      characterId: 'tommaso-venturi',
      imagePrompt: 'Soft pastel sketch on white paper of a vibrant covered market with striped awnings, colorful produce displays, hanging salumi, vendors calling out, warm reds and greens, bustling morning activity, authentic market atmosphere, baskets overflowing',
    },
    {
      id: 'mercato-ortofrutticolo',
      name: 'Mercato Ortofrutticolo San Michele',
      kind: 'market',
      neighbourhood: 'San Michele',
      real: false,
      characterId: 'alberta-rossi',
      imagePrompt: 'Soft pastel sketch on white paper of an outdoor fruit and vegetable market, wooden crates of seasonal produce, hand-written price signs, vibrant greens and oranges, shoppers with wicker baskets, morning market energy, fresh local abundance',
    },
    {
      id: 'mercato-antiquario',
      name: 'Mercato Antiquario',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'renzo-fontana',
      imagePrompt: 'Soft pastel sketch on white paper of antique market stalls in oval piazza, vintage objects displayed on tables, old books and prints, soft sepia and cream tones, collectors browsing, medieval architecture backdrop, nostalgic atmosphere',
    },

    // RESTAURANTS (2)
    {
      id: 'ristorante-giglio',
      name: 'Ristorante Giglio',
      kind: 'ristorante',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'claudia-stefani',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant traditional restaurant with white tablecloths, vaulted ceilings, wine bottles lining walls, warm candlelight, burgundy and cream colors, formal yet welcoming, classic Tuscan dining atmosphere',
    },
    {
      id: 'ristorante-mecenate',
      name: 'Ristorante Mecenate',
      kind: 'ristorante',
      neighbourhood: 'San Martino',
      real: false,
      characterId: 'lorenzo-bianchi',
      imagePrompt: 'Soft pastel sketch on white paper of a refined restaurant with exposed stone walls, modern lighting, artistic plate presentations, soft gray and gold tones, intimate tables, contemporary Tuscan elegance, sophisticated ambiance',
    },

    // SPECIALTY FOOD (4)
    {
      id: 'trattoria-da-leo',
      name: 'Trattoria da Leo',
      kind: 'trattoria',
      neighbourhood: 'San Frediano',
      real: true,
      characterId: 'leo-buralli',
      imagePrompt: 'Soft pastel sketch on white paper of a bustling family trattoria with paper tablecloths, chalkboard menu, wine carafes on tables, warm yellow walls, crowded with locals, authentic no-frills atmosphere, generous portions being served',
    },
    {
      id: 'osteria-via-fillungo',
      name: 'Osteria Via Fillungo',
      kind: 'osteria',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'simone-pieri',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy osteria with dark wooden beams, ham and garlic hanging from ceiling, checked tablecloths, warm amber lighting, wine bottles in rustic shelving, convivial neighborhood gathering spot',
    },
    {
      id: 'pizzeria-santa-lucia',
      name: 'Pizzeria Santa Lucia',
      kind: 'pizzeria',
      neighbourhood: 'San Michele',
      real: false,
      characterId: 'federico-moretti',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood pizzeria with wood-fired oven visible, chef tossing dough, red and white checkered details, warm orange glow from oven, families dining, casual cheerful atmosphere',
    },
    {
      id: 'gastronomia-angeli',
      name: 'Gastronomia Angeli',
      kind: 'gastronomia',
      neighbourhood: 'San Martino',
      real: false,
      characterId: 'beatrice-angeli',
      imagePrompt: 'Soft pastel sketch on white paper of a gourmet food shop with deli counter, hanging salumi, shelves of olive oils and preserves, cheese display, warm earth tones, prepared foods in cases, artisanal quality products',
    },

    // LANDMARKS & CULTURAL (4)
    {
      id: 'duomo-san-martino',
      name: 'Duomo di San Martino',
      kind: 'chiesa',
      neighbourhood: 'San Martino',
      real: true,
      characterId: 'padre-augusto',
      imagePrompt: 'Soft pastel sketch on white paper of magnificent cathedral with asymmetrical Romanesque façade, green and white marble patterns, ornate carved columns, grand arched entrance, warm golden stone tones, pigeons on steps, majestic presence',
    },
    {
      id: 'basilica-san-frediano',
      name: 'Basilica di San Frediano',
      kind: 'chiesa',
      neighbourhood: 'San Frediano',
      real: true,
      characterId: 'suor-margherita',
      imagePrompt: 'Soft pastel sketch on white paper of ancient basilica with golden mosaic façade showing Christ ascending, Romanesque bell tower, warm gold and white tones, peaceful plaza in front, pilgrims entering, serene spiritual atmosphere',
    },
    {
      id: 'torre-guinigi',
      name: 'Torre Guinigi',
      kind: 'landmark',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'alessio-martinelli',
      imagePrompt: 'Soft pastel sketch on white paper of medieval tower with oak trees growing on top, brick and stone construction, viewing platform visible, warm terracotta and green tones, tourists climbing stairs, unique architectural wonder against sky',
    },
    {
      id: 'orto-botanico',
      name: 'Orto Botanico',
      kind: 'park',
      neighbourhood: 'San Martino',
      real: true,
      characterId: 'isabella-galli',
      imagePrompt: 'Soft pastel sketch on white paper of peaceful botanical garden with winding paths, labeled plant specimens, ancient trees, stone benches, soft greens and earth tones, visitors strolling, quiet contemplative atmosphere, Renaissance walls visible',
    },

    // PIAZZAS (2)
    {
      id: 'piazza-anfiteatro',
      name: 'Piazza Anfiteatro',
      kind: 'piazza',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'matteo-fabbri',
      imagePrompt: 'Soft pastel sketch on white paper of elliptical medieval piazza built on Roman amphitheater, colorful building facades in oval formation, café tables scattered around, warm ochre and terracotta tones, tourists and locals mingling, unique theatrical atmosphere',
    },
    {
      id: 'piazza-san-michele',
      name: 'Piazza San Michele',
      kind: 'piazza',
      neighbourhood: 'San Michele',
      real: true,
      characterId: 'carla-innocenti',
      imagePrompt: 'Soft pastel sketch on white paper of grand central piazza with ornate church façade, people meeting and chatting, market stalls, outdoor café seating, warm golden afternoon light, pigeons, bustling social hub, heart of city life',
    },

    // WINE BARS (2)
    {
      id: 'enoteca-vanni',
      name: 'Enoteca Vanni',
      kind: 'enoteca',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'vanni-ceccarelli',
      imagePrompt: 'Soft pastel sketch on white paper of intimate wine bar with floor-to-ceiling bottles, wooden wine racks, small tasting tables, warm burgundy and gold lighting, sommelier pouring wine, sophisticated cozy atmosphere, wine glasses catching light',
    },
    {
      id: 'wine-bar-delle-mura',
      name: 'Wine Bar delle Mura',
      kind: 'enoteca',
      neighbourhood: 'San Frediano',
      real: false,
      characterId: 'andrea-lombardi',
      imagePrompt: 'Soft pastel sketch on white paper of modern wine bar with brick walls, contemporary shelving, charcuterie boards on counter, soft amber lighting, locals at aperitivo hour, warm intimate gathering spot, Tuscan wine focus',
    },

    // BOOKSHOP (1)
    {
      id: 'libreria-baroni',
      name: 'Libreria Baroni',
      kind: 'libreria',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'silvia-baroni',
      imagePrompt: 'Soft pastel sketch on white paper of charming independent bookshop with wooden shelves to ceiling, reading nook with armchair, stacks of Italian literature, warm amber lighting, literary posters, cat sleeping on counter, intellectual haven atmosphere',
    },

    // PRACTICAL (1)
    {
      id: 'farmacia-massei',
      name: 'Farmacia Massei',
      kind: 'farmacia',
      neighbourhood: 'San Michele',
      real: false,
      characterId: 'dottoressa-massei',
      imagePrompt: 'Soft pastel sketch on white paper of traditional pharmacy with antique wooden cabinets, ceramic medicine jars, green cross sign, white coat hanging, organized shelves, soft green and white colors, trusted neighborhood health spot, professional caring atmosphere',
    },
  ],
  characters: [
    {
      id: 'sergio-di-simo',
      name: 'Sergio Di Simo',
      age: 58,
      role: 'proprietario',
      placeId: 'caffe-di-simo',
      personality: ['refined', 'knowledgeable', 'proud of tradition'],
      portraitPrompt: 'Pen and ink portrait on white paper of distinguished man in his late fifties with silver hair neatly combed, elegant bearing, subtle smile, wearing bow tie and vest, minimal sepia watercolor wash, fine lines showing character, background hint of Art Nouveau curves',
    },
    {
      id: 'giulia-fortino',
      name: 'Giulia Fortino',
      age: 32,
      role: 'barista',
      placeId: 'bar-il-fortino',
      personality: ['friendly', 'energetic', 'knows everyone'],
      portraitPrompt: 'Pen and ink portrait on white paper of cheerful woman in early thirties with short dark hair, bright eyes, warm smile, wearing casual button-down shirt, minimal warm watercolor wash on cheeks, expressive detailed linework, approachable energy',
    },
    {
      id: 'marco-traversi',
      name: 'Marco Traversi',
      age: 45,
      role: 'proprietario',
      placeId: 'caffe-delle-mura',
      personality: ['calm', 'philosophical', 'nature-loving'],
      portraitPrompt: 'Pen and ink portrait on white paper of contemplative man in mid-forties with wavy salt-and-pepper hair, gentle expression, wearing casual sweater, minimal green-gray watercolor wash, peaceful demeanor captured in detailed lines, thoughtful gaze',
    },
    {
      id: 'anna-benedetti',
      name: 'Anna Benedetti',
      age: 50,
      role: 'barista',
      placeId: 'bar-duomo',
      personality: ['efficient', 'warm-hearted', 'devout'],
      portraitPrompt: 'Pen and ink portrait on white paper of kind-faced woman at fifty with hair in neat bun, laugh lines around eyes, wearing simple blouse, minimal warm watercolor wash, competent and caring expression, detailed cross-hatching for depth',
    },
    {
      id: 'roberto-nannini',
      name: 'Roberto Nannini',
      age: 38,
      role: 'barista',
      placeId: 'bar-nannini',
      personality: ['artistic', 'passionate', 'community-minded'],
      portraitPrompt: 'Pen and ink portrait on white paper of creative-looking man in late thirties with tousled dark hair, expressive eyes, slight beard, wearing casual shirt, minimal earth-tone watercolor wash, intense thoughtful expression, energetic line quality',
    },
    {
      id: 'elena-marchetti',
      name: 'Elena Marchetti',
      age: 62,
      role: 'proprietaria',
      placeId: 'caffe-santa-zita',
      personality: ['maternal', 'gossip', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of warm grandmotherly woman in early sixties with graying hair, welcoming smile, wearing floral blouse, minimal rose watercolor wash, gentle wrinkles showing wisdom, motherly warmth in detailed features',
    },
    {
      id: 'davide-russo',
      name: 'Davide Russo',
      age: 29,
      role: 'barista',
      placeId: 'bar-anfiteatro',
      personality: ['ambitious', 'charming', 'social'],
      portraitPrompt: 'Pen and ink portrait on white paper of handsome young man in late twenties with styled dark hair, confident smile, wearing modern casual attire, minimal warm watercolor wash, charismatic expression, clean detailed linework, youthful energy',
    },
    {
      id: 'chiara-carli',
      name: 'Chiara Carli',
      age: 34,
      role: 'proprietaria',
      placeId: 'caffe-carli',
      personality: ['sophisticated', 'perfectionist', 'design-conscious'],
      portraitPrompt: 'Pen and ink portrait on white paper of elegant woman in mid-thirties with sleek bobbed hair, refined features, wearing minimalist jewelry, minimal cool watercolor wash, poised intelligent expression, precise delicate linework',
    },
    {
      id: 'francesco-colombini',
      name: 'Francesco Colombini',
      age: 71,
      role: 'proprietario',
      placeId: 'bar-colombini',
      personality: ['traditional', 'opinionated', 'sharp-witted'],
      portraitPrompt: 'Pen and ink portrait on white paper of elderly gentleman in early seventies with white hair, strong features, wearing classic shirt and suspenders, minimal sepia watercolor wash, wise penetrating gaze, detailed expressive wrinkles, dignified bearing',
    },
    {
      id: 'amedeo-giusti',
      name: 'Amedeo Giusti',
      age: 55,
      role: 'fornaio',
      placeId: 'forno-amedeo-giusti',
      personality: ['meticulous', 'proud', 'third-generation baker'],
      portraitPrompt: 'Pen and ink portrait on white paper of sturdy man in mid-fifties with flour-dusted hair, strong arms, wearing baker apron, minimal wheat-tone watercolor wash, serious craftsman expression, detailed lines showing dedication, flour on cheek',
    },
    {
      id: 'lucia-guidi',
      name: 'Lucia Guidi',
      age: 42,
      role: 'fornaia',
      placeId: 'panificio-guidi',
      personality: ['jovial', 'generous portions', 'storyteller'],
      portraitPrompt: 'Pen and ink portrait on white paper of robust cheerful woman in early forties with curly hair tied back, bright smile, wearing flour-covered apron, minimal warm watercolor wash, laugh lines, welcoming open expression, detailed expressive features',
    },
    {
      id: 'paolo-bernardi',
      name: 'Paolo Bernardi',
      age: 48,
      role: 'fornaio',
      placeId: 'forno-bernardi',
      personality: ['reliable', 'quiet', 'early-riser'],
      portraitPrompt: 'Pen and ink portrait on white paper of solid dependable man in late forties with receding hair, calm face, wearing simple work clothes, minimal earth-tone watercolor wash, steady patient expression, honest hardworking demeanor in detailed lines',
    },
    {
      id: 'stefania-mancini',
      name: 'Stefania Mancini',
      age: 36,
      role: 'fornaia',
      placeId: 'panificio-del-corso',
      personality: ['innovative', 'precise', 'aesthetic-focused'],
      portraitPrompt: 'Pen and ink portrait on white paper of stylish woman in mid-thirties with elegant updo, artistic eye, wearing chef whites, minimal cream watercolor wash, focused creative expression, refined detailed features, modern professional bearing',
    },
    {
      id: 'giovanni-lippi',
      name: 'Giovanni Lippi',
      age: 67,
      role: 'fornaio',
      placeId: 'forno-sant-anna',
      personality: ['traditional', 'gruff but kind', 'neighborhood fixture'],
      portraitPrompt: 'Pen and ink portrait on white paper of weathered elderly baker in late sixties with white mustache, work-worn hands, wearing traditional baker cap, minimal warm watercolor wash, gruff exterior hiding warmth, detailed character lines, flour dust',
    },
    {
      id: 'mariella-pinelli',
      name: 'Mariella Pinelli',
      age: 44,
      role: 'pasticciera',
      placeId: 'pasticceria-pinelli',
      personality: ['artistic', 'delicate touch', 'perfectionist'],
      portraitPrompt: 'Pen and ink portrait on white paper of graceful woman in mid-forties with hair in elegant chignon, gentle smile, wearing pastry chef whites, minimal pink watercolor wash, refined precise features, artistic hands, detailed sensitive linework',
    },
    {
      id: 'tommaso-venturi',
      name: 'Tommaso Venturi',
      age: 53,
      role: 'venditore',
      placeId: 'mercato-del-carmine',
      personality: ['loud', 'jovial', 'generous with samples'],
      portraitPrompt: 'Pen and ink portrait on white paper of robust market vendor in early fifties with weathered face, broad smile, wearing work vest, minimal warm watercolor wash, expressive animated features, welcoming energy, detailed laugh lines',
    },
    {
      id: 'alberta-rossi',
      name: 'Alberta Rossi',
      age: 59,
      role: 'venditrice',
      placeId: 'mercato-ortofrutticolo',
      personality: ['shrewd', 'knows produce', 'no-nonsense'],
      portraitPrompt: 'Pen and ink portrait on white paper of strong-featured woman in late fifties with hair in practical bun, direct gaze, wearing apron, minimal green watercolor wash, competent assured expression, detailed wise features, seasoned professional',
    },
    {
      id: 'renzo-fontana',
      name: 'Renzo Fontana',
      age: 65,
      role: 'antiquario',
      placeId: 'mercato-antiquario',
      personality: ['scholarly', 'storyteller', 'nostalgic'],
      portraitPrompt: 'Pen and ink portrait on white paper of distinguished elderly man in mid-sixties with reading glasses on chain, gray beard, wearing tweed jacket, minimal sepia watercolor wash, intellectual expression, detailed thoughtful features, collector eyes',
    },
    {
      id: 'claudia-stefani',
      name: 'Claudia Stefani',
      age: 41,
      role: 'chef',
      placeId: 'ristorante-giglio',
      personality: ['passionate', 'traditional recipes', 'demanding excellence'],
      portraitPrompt: 'Pen and ink portrait on white paper of intense woman in early forties with dark hair pulled back, focused eyes, wearing chef whites, minimal warm watercolor wash, determined passionate expression, strong detailed features, culinary authority',
    },
    {
      id: 'lorenzo-bianchi',
      name: 'Lorenzo Bianchi',
      age: 39,
      role: 'chef',
      placeId: 'ristorante-mecenate',
      personality: ['creative', 'modern approach', 'ambitious'],
      portraitPrompt: 'Pen and ink portrait on white paper of contemporary chef in late thirties with neat beard, innovative look, wearing modern chef attire, minimal cool watercolor wash, confident creative expression, detailed refined features, artistic vision',
    },
    {
      id: 'leo-buralli',
      name: 'Leo Buralli',
      age: 63,
      role: 'oste',
      placeId: 'trattoria-da-leo',
      personality: ['boisterous', 'generous', 'local character'],
      portraitPrompt: 'Pen and ink portrait on white paper of hearty man in early sixties with full face, wild graying hair, wearing stained apron, minimal red watercolor wash, big personality in expression, detailed animated features, wine-stained smile',
    },
    {
      id: 'simone-pieri',
      name: 'Simone Pieri',
      age: 47,
      role: 'oste',
      placeId: 'osteria-via-fillungo',
      personality: ['convivial', 'wine enthusiast', 'raconteur'],
      portraitPrompt: 'Pen and ink portrait on white paper of friendly man in late forties with warm eyes, slight stubble, wearing casual shirt, minimal burgundy watercolor wash, welcoming storyteller expression, detailed expressive face, genuine hospitality',
    },
    {
      id: 'federico-moretti',
      name: 'Federico Moretti',
      age: 35,
      role: 'pizzaiolo',
      placeId: 'pizzeria-santa-lucia',
      personality: ['skillful', 'quick-handed', 'competitive'],
      portraitPrompt: 'Pen and ink portrait on white paper of athletic man in mid-thirties with strong forearms, focused expression, wearing pizza maker attire, minimal warm watercolor wash, concentrated skilled demeanor, detailed working hands, craftsman pride',
    },
    {
      id: 'beatrice-angeli',
      name: 'Beatrice Angeli',
      age: 52,
      role: 'proprietaria',
      placeId: 'gastronomia-angeli',
      personality: ['knowledgeable', 'quality-obsessed', 'welcoming'],
      portraitPrompt: 'Pen and ink portrait on white paper of elegant woman in early fifties with sophisticated style, knowing smile, wearing elegant casual attire, minimal warm watercolor wash, cultured refined expression, detailed discerning features, food expert',
    },
    {
      id: 'padre-augusto',
      name: 'Padre Augusto',
      age: 68,
      role: 'parroco',
      placeId: 'duomo-san-martino',
      personality: ['scholarly', 'gentle', 'art historian'],
      portraitPrompt: 'Pen and ink portrait on white paper of distinguished elderly priest in late sixties with gray hair, kind eyes behind glasses, wearing clerical collar, minimal purple watercolor wash, serene wise expression, detailed compassionate features, spiritual bearing',
    },
    {
      id: 'suor-margherita',
      name: 'Suor Margherita',
      age: 56,
      role: 'suora',
      placeId: 'basilica-san-frediano',
      personality: ['devoted', 'cheerful', 'community service'],
      portraitPrompt: 'Pen and ink portrait on white paper of serene nun in mid-fifties with gentle face, peaceful smile, wearing traditional habit, minimal blue watercolor wash, spiritual joy in expression, detailed kindly features, devoted service bearing',
    },
    {
      id: 'alessio-martinelli',
      name: 'Alessio Martinelli',
      age: 26,
      role: 'guida turistica',
      placeId: 'torre-guinigi',
      personality: ['enthusiastic', 'history buff', 'athletic'],
      portraitPrompt: 'Pen and ink portrait on white paper of energetic young man in mid-twenties with bright eyes, animated expression, wearing casual tour guide attire, minimal green watercolor wash, passionate educator demeanor, detailed youthful features, storyteller energy',
    },
    {
      id: 'isabella-galli',
      name: 'Isabella Galli',
      age: 61,
      role: 'botanica',
      placeId: 'orto-botanico',
      personality: ['patient', 'scholarly', 'nurturing'],
      portraitPrompt: 'Pen and ink portrait on white paper of intellectual woman in early sixties with silver hair, gentle features, wearing practical garden clothes, minimal green watercolor wash, wise nurturing expression, detailed observant eyes, nature connection',
    },
    {
      id: 'matteo-fabbri',
      name: 'Matteo Fabbri',
      age: 33,
      role: 'musicista di strada',
      placeId: 'piazza-anfiteatro',
      personality: ['artistic', 'free-spirited', 'crowd-pleaser'],
      portraitPrompt: 'Pen and ink portrait on white paper of bohemian young man in early thirties with longer hair, creative style, wearing casual artistic clothing, minimal warm watercolor wash, expressive musical features, detailed passionate eyes, performer energy',
    },
    {
      id: 'carla-innocenti',
      name: 'Carla Innocenti',
      age: 46,
      role: 'fioraia',
      placeId: 'piazza-san-michele',
      personality: ['romantic', 'color-loving', 'observant'],
      portraitPrompt: 'Pen and ink portrait on white paper of graceful woman in mid-forties with flower in hair, warm smile, wearing colorful scarf, minimal floral watercolor wash, artistic romantic expression, detailed gentle features, creative hands',
    },
    {
      id: 'vanni-ceccarelli',
      name: 'Vanni Ceccarelli',
      age: 57,
      role: 'sommelier',
      placeId: 'enoteca-vanni',
      personality: ['expert', 'refined palate', 'educator'],
      portraitPrompt: 'Pen and ink portrait on white paper of distinguished man in late fifties with silver hair, discerning eyes, wearing elegant casual attire, minimal burgundy watercolor wash, knowledgeable sophisticated expression, detailed refined features, wine expert bearing',
    },
    {
      id: 'andrea-lombardi',
      name: 'Andrea Lombardi',
      age: 37,
      role: 'proprietario enoteca',
      placeId: 'wine-bar-delle-mura',
      personality: ['modern', 'social', 'wine passionate'],
      portraitPrompt: 'Pen and ink portrait on white paper of contemporary man in late thirties with trimmed beard, stylish appearance, wearing casual elegant clothing, minimal warm watercolor wash, friendly enthusiast expression, detailed welcoming features, modern sommelier',
    },
    {
      id: 'silvia-baroni',
      name: 'Silvia Baroni',
      age: 43,
      role: 'libraia',
      placeId: 'libreria-baroni',
      personality: ['literary', 'recommender', 'quiet strength'],
      portraitPrompt: 'Pen and ink portrait on white paper of intellectual woman in early forties with reading glasses, thoughtful expression, wearing comfortable sweater, minimal sepia watercolor wash, literary wisdom in eyes, detailed sensitive features, book lover soul',
    },
    {
      id: 'dottoressa-massei',
      name: 'Dott.ssa Massei',
      age: 54,
      role: 'farmacista',
      placeId: 'farmacia-massei',
      personality: ['professional', 'caring', 'trusted advisor'],
      portraitPrompt: 'Pen and ink portrait on white paper of competent woman in mid-fifties with neat professional appearance, kind but authoritative expression, wearing white coat, minimal cool watercolor wash, trusted healer bearing, detailed capable features, medical expertise',
    },
  ],
  food: [
    'buccellato',
    'tordelli lucchesi',
    'zuppa di farro',
    'rovelline',
    'castagnaccio',
    'necci',
    'biadina',
    'matuffi',
    'farro della Garfagnana',
    'olio extravergine di oliva lucchese',
    'prosciutto bazzone',
    'biroldo',
    'cecina',
    'pan co santi',
    'pasimata',
  ],
  customs: [
    'Evening passeggiata along the city walls',
    'Shopping at Mercato del Carmine on Saturday mornings',
    'Sunday concerts in historic churches',
    'Aperitivo hour in Piazza San Michele',
    'Monthly antique market in Piazza Anfiteatro',
    'Cycling on top of the Renaissance walls',
    'Summer music festival Lucca Summer Festival',
    'Comics festival Lucca Comics & Games',
  ],
  localTouches: [
    'Saying "babbo" instead of "papà" for father',
    'The distinctive Tuscan "c" pronounced as "h"',
    'Dropping final vowels in casual speech',
    'Using "la" before female first names (la Lucia)',
    'Expression "essere in gamba" (to be capable)',
    'Calling children "bimbo" or "babino"',
    'Traditional Tuscan "Icché" for "cosa?" (what?)',
    'Using "codesto" for "quello" (that)',
  ],
};
