import { CityPantry } from '@/lib/types';

export const mantova: CityPantry = {
  id: 'mantova',
  name: 'Mantova',
  neighbourhoods: ['Centro Storico', 'Te', 'Cittadella', 'Lunetta'],
  places: [
    // BARS/CAFÉS (9)
    {
      id: 'caffe-modi',
      name: 'Caffè Modi',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'giorgio-bar',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant historic café with marble-topped tables, vintage wood paneling, and brass fixtures. Morning light streams through tall windows overlooking Piazza Erbe. Warm ochre and cream tones, textured strokes suggesting refined Belle Époque atmosphere.',
    },
    {
      id: 'bar-delle-erbe',
      name: 'Bar delle Erbe',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'silvia-barista',
      imagePrompt: 'Soft pastel sketch on white paper of a lively corner bar with outdoor tables under a striped awning. Views of the market square, people watching spot. Golden morning light, terracotta and sage green tones, inviting café atmosphere with textured pastel strokes.',
    },
    {
      id: 'caffe-borsa',
      name: 'Caffè La Borsa',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'franco-proprietario',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional corner café with wooden bar counter, espresso machine gleaming in soft light. Newspapers on wooden racks, locals standing at the bar. Warm browns and creamy whites, textured inviting morning gathering place.',
    },
    {
      id: 'bar-te',
      name: 'Bar Palazzo Te',
      kind: 'bar',
      neighbourhood: 'Te',
      real: false,
      characterId: 'elena-te',
      imagePrompt: 'Soft pastel sketch on white paper of a modern café near the palazzo with minimalist design, outdoor seating under plane trees. Light filtering through leaves, contemporary meets historic. Soft greens and warm grays, welcoming neighborhood bar atmosphere.',
    },
    {
      id: 'bar-sport-cittadella',
      name: 'Bar Sport Cittadella',
      kind: 'bar',
      neighbourhood: 'Cittadella',
      real: false,
      characterId: 'massimo-sport',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood sports bar with TV visible, simple formica counter, local gathering spot. Posters on walls, warm community feel. Earthy tones, textured casual atmosphere of daily rituals.',
    },
    {
      id: 'caffe-virgilio',
      name: 'Caffè Virgilio',
      kind: 'bar',
      neighbourhood: 'Cittadella',
      real: false,
      characterId: 'anna-virgilio',
      imagePrompt: 'Soft pastel sketch on white paper of a corner café with large windows, book exchange shelf, intellectual atmosphere. Morning readers with cappuccinos. Warm amber and cream tones, textured cozy literary café feeling.',
    },
    {
      id: 'bar-matilde',
      name: 'Bar Matilde',
      kind: 'bar',
      neighbourhood: 'Lunetta',
      real: false,
      characterId: 'roberto-matilde',
      imagePrompt: 'Soft pastel sketch on white paper of a family-run neighborhood bar with pastry case, simple tables, local workers stopping in. Residential area morning hub. Warm yellows and browns, inviting everyday community atmosphere.',
    },
    {
      id: 'bar-aldega',
      name: "Bar all'Aldega",
      kind: 'bar',
      neighbourhood: 'Te',
      real: false,
      characterId: 'lucia-aldega',
      imagePrompt: 'Soft pastel sketch on white paper of a cheerful bar near the lakes with windows overlooking water, bicycles parked outside. Morning cyclists stopping for espresso. Aqua blues and warm creams, breezy lakeside atmosphere.',
    },
    {
      id: 'bar-gonzaga',
      name: 'Bar Gonzaga',
      kind: 'bar',
      neighbourhood: 'Lunetta',
      real: false,
      characterId: 'davide-gonzaga',
      imagePrompt: 'Soft pastel sketch on white paper of a modern neighborhood bar with clean lines, excellent pastries, young professionals. Bright and efficient morning service. Fresh whites and warm pastels, contemporary welcoming feel.',
    },

    // BAKERIES (4)
    {
      id: 'panificio-pavesi',
      name: 'Panificio Pavesi',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'pietro-fornaio',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional bakery with wooden shelves filled with golden breads, antico forno visible in back. Flour dust in morning light, warm loaves cooling. Rich golds and creamy whites, textured artisanal bread atmosphere.',
    },
    {
      id: 'pasticceria-caravatti',
      name: 'Pasticceria Caravatti',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'margherita-pasticcera',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant pastry shop with glass cases displaying torta sbrisolona and delicate pastries. Refined historic atmosphere, beautiful presentation. Warm golds and pinks, luxurious sweet shop feeling.',
    },
    {
      id: 'forno-cittadella',
      name: 'Forno della Cittadella',
      kind: 'bakery',
      neighbourhood: 'Cittadella',
      real: false,
      characterId: 'giovanni-pane',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood bakery with simple wooden counter, locals with shopping bags waiting. Daily bread ritual, warm ovens. Rustic browns and creamy tones, textured community bakery atmosphere.',
    },
    {
      id: 'pasticceria-apollo',
      name: 'Pasticceria Apollo',
      kind: 'bakery',
      neighbourhood: 'Te',
      real: false,
      characterId: 'chiara-apollo',
      imagePrompt: 'Soft pastel sketch on white paper of a bright modern pastry shop with creative window displays, contemporary interpretations of local sweets. Stylish cases, morning treat destination. Soft pastels and whites, inviting modern pasticceria.',
    },

    // MARKETS (3)
    {
      id: 'mercato-erbe',
      name: 'Mercato di Piazza delle Erbe',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'stefano-ortolano',
      imagePrompt: 'Soft pastel sketch on white paper of the historic market square with colorful produce stalls, flowers, local vendors under Renaissance arcades. Morning market bustle, fresh vegetables. Vibrant greens, reds, golds, lively textured market atmosphere.',
    },
    {
      id: 'mercato-coperto',
      name: 'Mercato Coperto',
      kind: 'market',
      neighbourhood: 'Cittadella',
      real: false,
      characterId: 'carla-venditrice',
      imagePrompt: 'Soft pastel sketch on white paper of an indoor covered market with meat counters, cheese vendors, local specialties. Iron and glass structure, morning shoppers. Rich textures, earthy tones, authentic market hall feeling.',
    },
    {
      id: 'mercato-agricolo',
      name: "Mercato Agricolo dell'Aldega",
      kind: 'market',
      neighbourhood: 'Lunetta',
      real: false,
      characterId: 'paolo-contadino',
      imagePrompt: 'Soft pastel sketch on white paper of a farmers market near the lakes with farm trucks, seasonal produce, direct from producers. Saturday morning tradition. Fresh greens and earth tones, textured agricultural market atmosphere.',
    },

    // RESTAURANTS (2)
    {
      id: 'ristorante-cigno',
      name: 'Il Cigno dei Martini',
      kind: 'restaurant',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'alberto-chef',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant restaurant interior with vaulted ceilings, white tablecloths, refined Renaissance palazzo setting. Traditional Mantovan dishes. Rich burgundy and cream tones, sophisticated dining atmosphere.',
    },
    {
      id: 'trattoria-martini',
      name: 'Trattoria ai Martini',
      kind: 'restaurant',
      neighbourhood: 'Te',
      real: false,
      characterId: 'maria-cuoca',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy neighborhood trattoria with checkered tablecloths, family photos on walls, handwritten menu board. Home cooking atmosphere. Warm reds and yellows, inviting rustic dining feel.',
    },

    // SPECIALTY FOOD (3)
    {
      id: 'osteria-fragoletta',
      name: "Osteria della Fragoletta",
      kind: 'osteria',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'gianfranco-oste',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional osteria with wooden tables, exposed brick, local wines displayed. Mantovan antipasti and tortelli. Earthy browns and burgundy, textured authentic osteria atmosphere.',
    },
    {
      id: 'salumeria-ducale',
      name: 'Salumeria Ducale',
      kind: 'specialty_food',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'federico-salumiere',
      imagePrompt: 'Soft pastel sketch on white paper of a specialty deli with hanging salami, aged cheeses, local delicacies. Traditional tile and marble counter. Rich textures, warm lighting, artisanal salumeria feeling.',
    },
    {
      id: 'gastronomia-gonzaga',
      name: 'Gastronomia Gonzaga',
      kind: 'specialty_food',
      neighbourhood: 'Cittadella',
      real: false,
      characterId: 'simona-gastronoma',
      imagePrompt: 'Soft pastel sketch on white paper of a prepared foods shop with display cases of fresh pasta, ready dishes, local specialties. Modern neighborhood gastronomia. Fresh whites and appetizing colors, welcoming food shop.',
    },

    // LANDMARKS & CULTURAL (6)
    {
      id: 'palazzo-ducale',
      name: 'Palazzo Ducale',
      kind: 'landmark',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'marcello-guida',
      imagePrompt: 'Soft pastel sketch on white paper of the grand Gonzaga palace facade with towers, Renaissance architecture, elaborate courtyards visible. Majestic presence over the city. Rich ochres and terracotta, textured historic grandeur.',
    },
    {
      id: 'palazzo-te',
      name: 'Palazzo Te',
      kind: 'landmark',
      neighbourhood: 'Te',
      real: true,
      characterId: 'beatrice-storica',
      imagePrompt: 'Soft pastel sketch on white paper of the Mannerist pleasure palace with elegant facade, gardens, frescoed rooms suggested. Renaissance villa atmosphere. Warm pinks and creams, textured palatial beauty.',
    },
    {
      id: 'duomo-mantova',
      name: 'Duomo di Mantova',
      kind: 'church',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'don-giuseppe',
      imagePrompt: 'Soft pastel sketch on white paper of the cathedral with Baroque facade, bell tower, Renaissance interior suggested. Spiritual center of the city. Warm stone colors and gold accents, textured sacred atmosphere.',
    },
    {
      id: 'basilica-andrea',
      name: "Basilica di Sant'Andrea",
      kind: 'church',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'suor-maria',
      imagePrompt: 'Soft pastel sketch on white paper of the grand Renaissance basilica designed by Alberti, impressive dome and classical facade. Architectural masterpiece. Rich warm tones, textured monumental spiritual presence.',
    },
    {
      id: 'parco-te',
      name: 'Parco di Palazzo Te',
      kind: 'park',
      neighbourhood: 'Te',
      real: true,
      characterId: 'andrea-giardiniere',
      imagePrompt: 'Soft pastel sketch on white paper of historic palace gardens with geometric paths, ancient trees, people strolling by the lakes. Green oasis. Fresh greens and soft blues, textured peaceful garden atmosphere.',
    },
    {
      id: 'piazza-sordello',
      name: 'Piazza Sordello',
      kind: 'piazza',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'vincenzo-musicista',
      imagePrompt: 'Soft pastel sketch on white paper of the grand medieval square surrounded by palaces, cathedral, Ducal Palace. Heart of historic Mantova. Rich architectural tones, textured monumental piazza atmosphere.',
    },

    // SOCIAL/EVENING (3)
    {
      id: 'enoteca-cortile',
      name: "Enoteca del Cortile",
      kind: 'enoteca',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'tommaso-sommelier',
      imagePrompt: 'Soft pastel sketch on white paper of a wine bar in a historic courtyard with stone walls, bottles lining shelves, candlelit tables. Evening aperitivo setting. Warm amber lighting, burgundy tones, intimate wine bar atmosphere.',
    },
    {
      id: 'enoteca-lago',
      name: "Enoteca al Lago",
      kind: 'enoteca',
      neighbourhood: 'Te',
      real: false,
      characterId: 'valentina-enotecaia',
      imagePrompt: 'Soft pastel sketch on white paper of a modern wine bar with lake views, contemporary design, local wine selection. Sunset aperitivo spot. Soft evening light, blues and golds, textured sophisticated atmosphere.',
    },
    {
      id: 'libreria-nautilus',
      name: 'Libreria Nautilus',
      kind: 'bookshop',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'claudia-libraia',
      imagePrompt: 'Soft pastel sketch on white paper of an independent bookshop with wooden shelves floor to ceiling, reading nook, literary events. Cultural gathering place. Warm wood tones and soft lighting, inviting bibliophile atmosphere.',
    },

    // PRACTICAL (2)
    {
      id: 'farmacia-gonzaga',
      name: 'Farmacia Gonzaga',
      kind: 'pharmacy',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'dottoressa-ferrari',
      imagePrompt: 'Soft pastel sketch on white paper of a historic pharmacy with wooden cabinets, antique ceramic jars, professional modern service. Traditional meets contemporary. Clean whites and warm wood tones, trusted health atmosphere.',
    },
    {
      id: 'stazione-mantova',
      name: 'Stazione di Mantova',
      kind: 'station',
      neighbourhood: 'Cittadella',
      real: true,
      characterId: 'marco-bigliettaio',
      imagePrompt: 'Soft pastel sketch on white paper of the train station building with Art Nouveau details, platforms, travelers with luggage. Gateway to the city. Soft transportation blues and warm building tones, textured arrival atmosphere.',
    },

    // CITY CHARACTER (3)
    {
      id: 'bottega-virgiliana',
      name: 'Bottega Virgiliana',
      kind: 'shop',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'elisabetta-artigiana',
      imagePrompt: 'Soft pastel sketch on white paper of an artisan shop selling local crafts, Gonzaga-inspired reproductions, Renaissance-style papers. Cultural gift shop. Rich renaissance colors, textured artistic atmosphere.',
    },
    {
      id: 'gelateria-ducale',
      name: 'Gelateria Ducale',
      kind: 'gelateria',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'antonio-gelataio',
      imagePrompt: 'Soft pastel sketch on white paper of an artisanal gelato shop with seasonal flavors, local ingredient focus, sbrisolona gelato specialty. Evening passeggiata stop. Creamy pastels and appetizing tones, inviting sweet atmosphere.',
    },
    {
      id: 'cicli-virgilio',
      name: 'Cicli Virgilio',
      kind: 'shop',
      neighbourhood: 'Cittadella',
      real: false,
      characterId: 'luca-ciclista',
      imagePrompt: 'Soft pastel sketch on white paper of a bicycle shop with new and vintage bikes, repair area, cycling is essential to flat Mantova. Local transportation hub. Metallic blues and warm woods, textured cycling culture atmosphere.',
    },
  ],
  characters: [
    {
      id: 'giorgio-bar',
      name: 'Giorgio Mantovani',
      age: 58,
      role: 'proprietario',
      placeId: 'caffe-modi',
      personality: ['refined', 'knowledgeable', 'dignified'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man in his late fifties with silver hair, elegant posture, wearing a crisp white shirt and vest. Slight smile, knowing eyes. Minimal watercolor wash in warm sepia tones, detailed crosshatching showing refined café owner character.',
    },
    {
      id: 'silvia-barista',
      name: 'Silvia Rossi',
      age: 29,
      role: 'barista',
      placeId: 'bar-delle-erbe',
      personality: ['energetic', 'observant', 'social'],
      portraitPrompt: 'Pen and ink portrait on white paper of a vibrant young woman with expressive eyes, hair pulled back, friendly smile. Observant gaze watching the piazza. Minimal watercolor wash in warm coffee tones, detailed linework capturing spirited barista personality.',
    },
    {
      id: 'franco-proprietario',
      name: 'Franco Bertolini',
      age: 65,
      role: 'proprietario',
      placeId: 'caffe-borsa',
      personality: ['traditional', 'opinionated', 'loyal'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy older man with weathered face, knowing expression, traditional manner. Reading glasses hanging from chain. Minimal watercolor wash in grays and browns, detailed traditional café owner character.',
    },
    {
      id: 'elena-te',
      name: 'Elena Marchetti',
      age: 33,
      role: 'barista',
      placeId: 'bar-te',
      personality: ['modern', 'artistic', 'welcoming'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stylish woman in her thirties with contemporary style, warm smile, creative energy. Confident presence. Minimal watercolor wash in soft greens, detailed linework showing modern barista character.',
    },
    {
      id: 'massimo-sport',
      name: 'Massimo Guidetti',
      age: 52,
      role: 'barista',
      placeId: 'bar-sport-cittadella',
      personality: ['gregarious', 'sports-loving', 'community-minded'],
      portraitPrompt: 'Pen and ink portrait on white paper of a jovial middle-aged man with animated expression, ready laugh, sports enthusiast demeanor. Casual friendly energy. Minimal watercolor wash in warm earth tones, detailed neighborhood character.',
    },
    {
      id: 'anna-virgilio',
      name: 'Anna Virgili',
      age: 41,
      role: 'proprietaria',
      placeId: 'caffe-virgilio',
      personality: ['literary', 'thoughtful', 'cultured'],
      portraitPrompt: 'Pen and ink portrait on white paper of an intellectual woman with gentle eyes, reading glasses, thoughtful expression. Book lover essence. Minimal watercolor wash in soft amber tones, detailed linework capturing cultured café owner.',
    },
    {
      id: 'roberto-matilde',
      name: 'Roberto Donati',
      age: 45,
      role: 'barista',
      placeId: 'bar-matilde',
      personality: ['hardworking', 'family-oriented', 'dependable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a solid working man with kind eyes, steady presence, neighborhood fixture. Reliable demeanor. Minimal watercolor wash in warm browns, detailed character showing community pillar.',
    },
    {
      id: 'lucia-aldega',
      name: 'Lucia Bianchi',
      age: 37,
      role: 'barista',
      placeId: 'bar-aldega',
      personality: ['cheerful', 'outdoor-loving', 'energetic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a bright-eyed woman with sun-touched skin, athletic build, love of nature evident. Active lifestyle. Minimal watercolor wash in aqua tones, detailed linework showing lakeside barista character.',
    },
    {
      id: 'davide-gonzaga',
      name: 'Davide Sartori',
      age: 31,
      role: 'barista',
      placeId: 'bar-gonzaga',
      personality: ['professional', 'efficient', 'quality-focused'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young professional with neat appearance, focused expression, modern sensibility. Precise demeanor. Minimal watercolor wash in clean tones, detailed contemporary barista character.',
    },
    {
      id: 'pietro-fornaio',
      name: 'Pietro Fornari',
      age: 56,
      role: 'fornaio',
      placeId: 'panificio-pavesi',
      personality: ['traditional', 'skilled', 'early-rising'],
      portraitPrompt: 'Pen and ink portrait on white paper of a baker with flour-dusted hair, strong hands, satisfaction of craft in face. Traditional artisan. Minimal watercolor wash in warm wheat tones, detailed linework showing master baker.',
    },
    {
      id: 'margherita-pasticcera',
      name: 'Margherita Caravatti',
      age: 44,
      role: 'pasticcera',
      placeId: 'pasticceria-caravatti',
      personality: ['perfectionist', 'creative', 'elegant'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant pastry chef with refined features, precise manner, artistic sensibility. Craftswoman pride. Minimal watercolor wash in soft rose tones, detailed character showing artistry.',
    },
    {
      id: 'giovanni-pane',
      name: 'Giovanni Prati',
      age: 49,
      role: 'fornaio',
      placeId: 'forno-cittadella',
      personality: ['neighborhood fixture', 'jovial', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy baker with friendly face, flour on apron, community connection evident. Warm presence. Minimal watercolor wash in golden browns, detailed neighborhood baker character.',
    },
    {
      id: 'chiara-apollo',
      name: 'Chiara Moretti',
      age: 35,
      role: 'pasticcera',
      placeId: 'pasticceria-apollo',
      personality: ['innovative', 'ambitious', 'talented'],
      portraitPrompt: 'Pen and ink portrait on white paper of a modern young pastry chef with creative energy, confident smile, contemporary approach. Artistic drive. Minimal watercolor wash in soft pastels, detailed innovative pastry maker.',
    },
    {
      id: 'stefano-ortolano',
      name: 'Stefano Gardoni',
      age: 62,
      role: 'venditore',
      placeId: 'mercato-erbe',
      personality: ['traditional', 'proud', 'weather-wise'],
      portraitPrompt: 'Pen and ink portrait on white paper of a weathered market vendor with knowing eyes, hands that know produce, decades at the market. Traditional seller. Minimal watercolor wash in earth greens, detailed market character.',
    },
    {
      id: 'carla-venditrice',
      name: 'Carla Montanari',
      age: 51,
      role: 'venditrice',
      placeId: 'mercato-coperto',
      personality: ['knowledgeable', 'warm', 'trusted'],
      portraitPrompt: 'Pen and ink portrait on white paper of a confident market woman with welcoming smile, expert in her products, customer relationships. Market wisdom. Minimal watercolor wash in warm tones, detailed vendor character.',
    },
    {
      id: 'paolo-contadino',
      name: 'Paolo Ferrarini',
      age: 58,
      role: 'contadino',
      placeId: 'mercato-agricolo',
      personality: ['earthy', 'direct', 'seasonal'],
      portraitPrompt: 'Pen and ink portrait on white paper of a farmer with sun-weathered face, soil under nails, connection to land evident. Agricultural wisdom. Minimal watercolor wash in earth tones, detailed farmer character.',
    },
    {
      id: 'alberto-chef',
      name: 'Alberto Cignaroli',
      age: 55,
      role: 'chef',
      placeId: 'ristorante-cigno',
      personality: ['refined', 'traditional', 'exacting'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished chef with serious expression, classical training evident, culinary pride. Master of tradition. Minimal watercolor wash in burgundy tones, detailed fine dining chef.',
    },
    {
      id: 'maria-cuoca',
      name: 'Maria Zanardi',
      age: 59,
      role: 'cuoca',
      placeId: 'trattoria-martini',
      personality: ['maternal', 'passionate', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warm cook with flour on hands, generations of recipes in memory, feeding people joy. Nonna energy. Minimal watercolor wash in warm reds, detailed traditional cook character.',
    },
    {
      id: 'gianfranco-oste',
      name: 'Gianfranco Volta',
      age: 67,
      role: 'oste',
      placeId: 'osteria-fragoletta',
      personality: ['storytelling', 'convivial', 'wine-loving'],
      portraitPrompt: 'Pen and ink portrait on white paper of an old-school osteria owner with expressive face, glass in hand, stories for everyone. Traditional hospitality. Minimal watercolor wash in wine tones, detailed host character.',
    },
    {
      id: 'federico-salumiere',
      name: 'Federico Boselli',
      age: 47,
      role: 'salumiere',
      placeId: 'salumeria-ducale',
      personality: ['artisanal', 'knowledgeable', 'selective'],
      portraitPrompt: 'Pen and ink portrait on white paper of a specialty food merchant with discerning eye, expert knowledge, pride in products. Artisan trader. Minimal watercolor wash in rich tones, detailed salumiere character.',
    },
    {
      id: 'simona-gastronoma',
      name: 'Simona Leoni',
      age: 39,
      role: 'proprietaria',
      placeId: 'gastronomia-gonzaga',
      personality: ['efficient', 'quality-focused', 'modern'],
      portraitPrompt: 'Pen and ink portrait on white paper of a professional food shop owner with organized manner, contemporary approach, excellent taste. Modern gastronoma. Minimal watercolor wash in fresh tones, detailed shop owner.',
    },
    {
      id: 'marcello-guida',
      name: 'Marcello Andreoli',
      age: 43,
      role: 'guida turistica',
      placeId: 'palazzo-ducale',
      personality: ['erudite', 'passionate', 'eloquent'],
      portraitPrompt: 'Pen and ink portrait on white paper of a knowledgeable guide with animated expression, love of history evident, storytelling gift. Renaissance scholar energy. Minimal watercolor wash in heritage tones, detailed guide character.',
    },
    {
      id: 'beatrice-storica',
      name: "Beatrice dell'Arte",
      age: 36,
      role: 'storica dell\'arte',
      placeId: 'palazzo-te',
      personality: ['scholarly', 'enthusiastic', 'detail-oriented'],
      portraitPrompt: 'Pen and ink portrait on white paper of an art historian with intelligent eyes, Renaissance passion, interpretive skill. Academic grace. Minimal watercolor wash in soft pinks, detailed scholar character.',
    },
    {
      id: 'don-giuseppe',
      name: 'Don Giuseppe Mazzini',
      age: 68,
      role: 'parroco',
      placeId: 'duomo-mantova',
      personality: ['serene', 'wise', 'community-caring'],
      portraitPrompt: 'Pen and ink portrait on white paper of a gentle priest with kind eyes, decades of service, spiritual presence. Pastoral wisdom. Minimal watercolor wash in soft grays, detailed parish priest character.',
    },
    {
      id: 'suor-maria',
      name: 'Suor Maria Benedetta',
      age: 54,
      role: 'suora',
      placeId: 'basilica-andrea',
      personality: ['devoted', 'gentle', 'helpful'],
      portraitPrompt: 'Pen and ink portrait on white paper of a serene nun with peaceful expression, life of service, quiet strength. Spiritual dedication. Minimal watercolor wash in soft tones, detailed religious character.',
    },
    {
      id: 'andrea-giardiniere',
      name: 'Andrea Giardini',
      age: 50,
      role: 'giardiniere',
      placeId: 'parco-te',
      personality: ['patient', 'nature-loving', 'seasonal'],
      portraitPrompt: 'Pen and ink portrait on white paper of a gardener with earth-touched hands, connection to plants, outdoor life written in face. Green thumb. Minimal watercolor wash in garden greens, detailed gardener character.',
    },
    {
      id: 'vincenzo-musicista',
      name: 'Vincenzo Monteverdi',
      age: 71,
      role: 'musicista',
      placeId: 'piazza-sordello',
      personality: ['artistic', 'nostalgic', 'romantic'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly street musician with violin case, musical soul, living history. Artistic spirit. Minimal watercolor wash in rich tones, detailed musician character.',
    },
    {
      id: 'tommaso-sommelier',
      name: 'Tommaso Rubini',
      age: 42,
      role: 'sommelier',
      placeId: 'enoteca-cortile',
      personality: ['refined', 'passionate', 'educational'],
      portraitPrompt: 'Pen and ink portrait on white paper of a knowledgeable sommelier with wine glass, refined palate, teaching joy. Wine expertise. Minimal watercolor wash in burgundy, detailed wine professional character.',
    },
    {
      id: 'valentina-enotecaia',
      name: 'Valentina Pellegrini',
      age: 34,
      role: 'proprietaria',
      placeId: 'enoteca-lago',
      personality: ['sophisticated', 'social', 'modern'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stylish wine bar owner with contemporary elegance, wine knowledge, aperitivo mastery. Modern enoteca spirit. Minimal watercolor wash in evening golds, detailed character.',
    },
    {
      id: 'claudia-libraia',
      name: 'Claudia Tassoni',
      age: 38,
      role: 'libraia',
      placeId: 'libreria-nautilus',
      personality: ['literary', 'recommending', 'cultural'],
      portraitPrompt: 'Pen and ink portrait on white paper of a bookshop owner with intelligent eyes, book in hand, reader connection. Literary soul. Minimal watercolor wash in warm book tones, detailed bookseller character.',
    },
    {
      id: 'dottoressa-ferrari',
      name: 'Dott.ssa Laura Ferrari',
      age: 46,
      role: 'farmacista',
      placeId: 'farmacia-gonzaga',
      personality: ['professional', 'caring', 'trusted'],
      portraitPrompt: 'Pen and ink portrait on white paper of a pharmacist with competent manner, white coat, community health guardian. Medical professionalism. Minimal watercolor wash in clean whites, detailed pharmacist character.',
    },
    {
      id: 'marco-bigliettaio',
      name: 'Marco Scalvini',
      age: 52,
      role: 'bigliettaio',
      placeId: 'stazione-mantova',
      personality: ['helpful', 'patient', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a station worker with uniform, decades of travelers helped, connection point. Transportation wisdom. Minimal watercolor wash in railway blues, detailed station character.',
    },
    {
      id: 'elisabetta-artigiana',
      name: 'Elisabetta Gonzaga',
      age: 44,
      role: 'artigiana',
      placeId: 'bottega-virgiliana',
      personality: ['creative', 'heritage-proud', 'skilled'],
      portraitPrompt: 'Pen and ink portrait on white paper of an artisan with creative eyes, skilled hands, Renaissance inspiration. Craft dedication. Minimal watercolor wash in renaissance colors, detailed artisan character.',
    },
    {
      id: 'antonio-gelataio',
      name: 'Antonio Cremona',
      age: 40,
      role: 'gelataio',
      placeId: 'gelateria-ducale',
      personality: ['innovative', 'seasonal', 'perfectionist'],
      portraitPrompt: 'Pen and ink portrait on white paper of a gelato maker with creative spirit, taste-testing expression, artisan pride. Frozen art master. Minimal watercolor wash in creamy tones, detailed gelataio character.',
    },
    {
      id: 'luca-ciclista',
      name: 'Luca Pedali',
      age: 36,
      role: 'meccanico',
      placeId: 'cicli-virgilio',
      personality: ['enthusiastic', 'technical', 'cycling-passionate'],
      portraitPrompt: 'Pen and ink portrait on white paper of a bike mechanic with grease-touched hands, cycling enthusiasm, technical knowledge. Two-wheeled devotion. Minimal watercolor wash in metallic blues, detailed cyclist character.',
    },
  ],
  food: [
    'tortelli di zucca',
    'risotto alla pilota',
    'luccio in salsa',
    'stracotto d\'asino',
    'torta sbrisolona',
    'anolini in brodo',
    'cotechino',
    'mostarda mantovana',
    'salame mantovano',
    'grana padano',
    'pesce di lago',
    'agnoli',
    'torta delle rose',
    'capunsei',
    'chisöl',
  ],
  customs: [
    'Passeggiata around the three lakes on Sunday',
    'Aperitivo in Piazza delle Erbe',
    'Shopping at the Thursday market',
    'Cycling everywhere in the flat city',
    'Teatro Bibiena concerts',
    'Festa di San Luigi Gonzaga',
    'Visiting Palazzo Ducale multiple times',
    'Lake fish on Friday',
    'Sbrisolona with coffee',
    'Evening stroll in Piazza Sordello',
  ],
  localTouches: [
    'Calling Mantova "the sleeping beauty"',
    '"Uffa" as common exclamation',
    'Pride in Virgil being from here',
    'Gonzaga family references everywhere',
    'Talk of the three lakes (Superiore, Mezzo, Inferiore)',
    'Renaissance festival atmosphere',
    '"Mangiare come i Gonzaga"',
    'Bicycle is essential transportation',
    'Lake mist creates atmosphere',
    '"Bella cità" said with deep local pride',
  ],
};
