import { CityPantry } from '@/lib/types';

export const matera: CityPantry = {
  id: 'matera',
  name: 'Matera',
  neighbourhoods: ['Sassi Barisano', 'Sassi Caveoso', 'Civita', 'Piano'],
  places: [
    // BARS/CAFÉS (3)
    {
      id: 'caffe-schiuma',
      name: 'Caffè Schiuma',
      kind: 'bar',
      neighbourhood: 'Sassi Barisano',
      real: false,
      characterId: 'antonio-russo',
      imagePrompt: 'Soft pastel sketch on white paper of a cave bar carved into ancient tufa stone, warm golden morning light filtering through arched entrance, small round tables outside overlooking the ravine, espresso machine gleaming inside the stone interior, textured limestone walls, inviting atmosphere, loose watercolor washes',
    },
    {
      id: 'bar-vitantonio',
      name: 'Bar Vitantonio',
      kind: 'bar',
      neighbourhood: 'Piano',
      real: false,
      characterId: 'lucia-dimatteo',
      imagePrompt: 'Soft pastel sketch on white paper of a modern corner bar with large windows, morning sunlight streaming in, chrome espresso machine, glass pastry case with cornetti, locals reading newspapers at counter, warm ochre and cream tones, welcoming neighborhood feel, textured sketch style',
    },
    {
      id: 'caffe-degli-archi',
      name: 'Caffè degli Archi',
      kind: 'bar',
      neighbourhood: 'Civita',
      real: false,
      characterId: 'michele-lorusso',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant café under stone archways, tables set with white linens, view of cathedral in background, morning aperitivo setup, vintage coffee roaster visible, warm amber and rose tones, atmospheric perspective, inviting historic charm',
    },
    // BAKERIES (2)
    {
      id: 'panificio-del-sasso',
      name: 'Panificio del Sasso',
      kind: 'bakery',
      neighbourhood: 'Sassi Caveoso',
      real: false,
      characterId: 'rosa-palmieri',
      imagePrompt: 'Soft pastel sketch on white paper of a cave bakery with wood-fired oven carved into rock, golden loaves of pane di Matera cooling on wooden racks, flour dust catching morning light, rustic stone interior, warm bread browns and golden yellows, cozy and aromatic atmosphere',
    },
    {
      id: 'forno-antico',
      name: 'Forno Antico San Giuseppe',
      kind: 'bakery',
      neighbourhood: 'Piano',
      real: false,
      characterId: 'giuseppe-bruno',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional bakery storefront, window display filled with focaccia barese and taralli, vintage tile floor, wooden shelves lined with bread, warm morning glow, customers waiting, earthy terracotta and wheat tones, welcoming family atmosphere',
    },
    // MARKETS (3)
    {
      id: 'mercato-piccianello',
      name: 'Mercato di Piccianello',
      kind: 'market',
      neighbourhood: 'Piano',
      real: true,
      characterId: 'carmela-gentile',
      imagePrompt: 'Soft pastel sketch on white paper of a bustling covered market, vegetable stalls overflowing with peperoni cruschi, tomatoes, and wild greens, vendors calling out, colorful awnings, crates of seasonal produce, vibrant reds and greens, lively morning energy, textured watercolor style',
    },
    {
      id: 'bottega-sassi',
      name: 'Bottega dei Sassi',
      kind: 'market',
      neighbourhood: 'Sassi Barisano',
      real: false,
      characterId: 'pietro-volpe',
      imagePrompt: 'Soft pastel sketch on white paper of a small cave shop selling local products, shelves with olive oil, wine, preserved vegetables, hanging peperoni cruschi, stone walls, soft interior lighting, warm amber and olive green tones, intimate rustic charm',
    },
    {
      id: 'mercato-contadino',
      name: 'Mercato Contadino',
      kind: 'market',
      neighbourhood: 'Civita',
      real: false,
      characterId: 'anna-lagrotta',
      imagePrompt: 'Soft pastel sketch on white paper of a farmers market in historic piazza, tables with fresh cheeses, honey, vegetables, elderly farmers with weathered hands, morning shadows, cathedral visible behind, earthy browns and greens, authentic local atmosphere',
    },
    // RESTAURANTS (2)
    {
      id: 'ristorante-francesca',
      name: 'Ristorante Francesca',
      kind: 'ristorante',
      neighbourhood: 'Civita',
      real: true,
      characterId: 'francesca-clemente',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant cave restaurant, vaulted stone ceilings, white tablecloths, candles flickering, view through arched windows to ravine, wine bottles lining walls, sophisticated warm lighting, romantic amber tones, refined atmosphere',
    },
    {
      id: 'ristorante-soul',
      name: 'Soul Kitchen',
      kind: 'ristorante',
      neighbourhood: 'Sassi Barisano',
      real: false,
      characterId: 'marco-dibari',
      imagePrompt: 'Soft pastel sketch on white paper of a contemporary restaurant in restored cave, modern lighting against ancient stone, open kitchen visible, artistic plating, blend of old and new, warm spotlights, sophisticated grey and gold tones, innovative atmosphere',
    },
    // SPECIALTY FOOD (2)
    {
      id: 'trattoria-lucana',
      name: 'Trattoria Lucana',
      kind: 'trattoria',
      neighbourhood: 'Sassi Caveoso',
      real: false,
      characterId: 'donato-santoro',
      imagePrompt: 'Soft pastel sketch on white paper of a rustic cave trattoria, wooden tables with checkered cloths, hanging cured meats, handwritten menu on blackboard, pots of orecchiette cooking, family photos on stone walls, warm reds and browns, homey welcoming feel',
    },
    {
      id: 'osteria-purgatorio',
      name: "Osteria del Purgatorio",
      kind: 'osteria',
      neighbourhood: 'Civita',
      real: false,
      characterId: 'isabella-greco',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy osteria with low vaulted ceilings, wine barrels as tables, copper pots hanging, locals sharing plates, candlelit ambiance, deep wine reds and golden tones, convivial intimate atmosphere',
    },
    // MAJOR LANDMARK (1)
    {
      id: 'sassi-belvedere',
      name: 'Belvedere dei Sassi',
      kind: 'landmark',
      neighbourhood: 'Civita',
      real: true,
      characterId: 'giovanni-montemurro',
      imagePrompt: 'Soft pastel sketch on white paper of a panoramic viewpoint overlooking the ancient Sassi cave dwellings cascading down the ravine, golden afternoon light, Murgia plateau across canyon, dramatic perspective, warm ochres and dusty roses, breathtaking atmospheric depth',
    },
    // CHURCHES/CULTURAL (2)
    {
      id: 'cattedrale',
      name: 'Cattedrale di Matera',
      kind: 'church',
      neighbourhood: 'Civita',
      real: true,
      characterId: 'padre-leonardo',
      imagePrompt: 'Soft pastel sketch on white paper of a Romanesque cathedral with rose window, honey-colored stone facade, bell tower rising against blue sky, pigeons on steps, morning light warming ancient stone, soft yellows and blues, majestic yet intimate',
    },
    {
      id: 'casa-grotta',
      name: 'Casa Grotta di Vico Solitario',
      kind: 'museum',
      neighbourhood: 'Sassi Caveoso',
      real: true,
      characterId: 'teresa-morelli',
      imagePrompt: 'Soft pastel sketch on white paper of a restored cave dwelling museum, period furniture and tools, carved stone rooms, small windows, historical atmosphere, muted earth tones, educational displays, authentic glimpse into past life',
    },
    // PARK (1)
    {
      id: 'parco-murgia',
      name: 'Parco della Murgia Materana',
      kind: 'park',
      neighbourhood: 'Civita',
      real: true,
      characterId: 'saverio-gattini',
      imagePrompt: 'Soft pastel sketch on white paper of a wild Mediterranean landscape, rocky plateau with ancient rupestrian churches, hiking trails through scrubland, panoramic views of Sassi across ravine, wild herbs and flowers, sage greens and dusty golds, rugged natural beauty',
    },
    // PIAZZAS (2)
    {
      id: 'piazza-vittorio',
      name: 'Piazza Vittorio Veneto',
      kind: 'piazza',
      neighbourhood: 'Piano',
      real: true,
      characterId: 'elena-laterza',
      imagePrompt: 'Soft pastel sketch on white paper of a grand main square, elegant buildings with balconies, cafés with outdoor seating, fountain in center, people strolling at passeggiata hour, warm evening light, vibrant social energy, honey and rose tones',
    },
    {
      id: 'piazza-duomo',
      name: 'Piazza del Duomo',
      kind: 'piazza',
      neighbourhood: 'Civita',
      real: true,
      characterId: 'alberto-rizzi',
      imagePrompt: 'Soft pastel sketch on white paper of a historic cathedral square, stone paving, view to ravine beyond, locals chatting in small groups, cathedral facade dominating, afternoon shadows, peaceful sacred atmosphere, warm limestone tones',
    },
    // WINE BARS/APERITIVO (2)
    {
      id: 'enoteca-lucania',
      name: 'Enoteca I Vini di Lucania',
      kind: 'enoteca',
      neighbourhood: 'Sassi Barisano',
      real: false,
      characterId: 'vincenzo-pace',
      imagePrompt: 'Soft pastel sketch on white paper of a sophisticated wine cave, bottles lining ancient stone walls, wooden tasting bar, wine glasses catching candlelight, cheese and salumi boards, deep burgundy and amber tones, refined relaxed atmosphere',
    },
    {
      id: 'alle-fornaci',
      name: 'Alle Fornaci',
      kind: 'wine_bar',
      neighbourhood: 'Piano',
      real: true,
      characterId: 'claudia-mastrangelo',
      imagePrompt: 'Soft pastel sketch on white paper of a chic aperitivo bar, modern interior with exposed stone, craft cocktails being mixed, plates of local appetizers, young crowd socializing, evening golden hour light, contemporary burgundy and gold accents, stylish ambiance',
    },
    // BOOKSHOP (1)
    {
      id: 'libreria-matera',
      name: 'Libreria Matera',
      kind: 'bookshop',
      neighbourhood: 'Piano',
      real: false,
      characterId: 'beatrice-loperfido',
      imagePrompt: 'Soft pastel sketch on white paper of an independent bookshop, floor-to-ceiling shelves, reading nook with armchair, local history section prominent, soft lamp lighting, books about Sassi and Basilicata, warm book browns and cream tones, intellectual cozy atmosphere',
    },
    // PHARMACY (1)
    {
      id: 'farmacia-centrale',
      name: 'Farmacia Centrale',
      kind: 'pharmacy',
      neighbourhood: 'Piano',
      real: false,
      characterId: 'dottoressa-mancini',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional Italian pharmacy, green cross sign, wooden cabinets with remedies, white-coated pharmacist, herbal preparations, clean organized shelves, clinical whites and pharmacy greens, professional trusted atmosphere',
    },
    // TRANSPORTATION (1)
    {
      id: 'stazione-fal',
      name: 'Stazione FAL Matera Centrale',
      kind: 'station',
      neighbourhood: 'Piano',
      real: true,
      characterId: 'roberto-nardella',
      imagePrompt: 'Soft pastel sketch on white paper of a regional train station, platform with waiting passengers, timetable boards, ticket office, connection to Bari, functional architecture, travelers with luggage, transit blues and greys, gateway atmosphere',
    },
    // CITY CHARACTER - Cave Hotel (unique to Matera)
    {
      id: 'hotel-sassi',
      name: 'Hotel Le Grotte della Civita',
      kind: 'hotel',
      neighbourhood: 'Sassi Caveoso',
      real: true,
      characterId: 'simone-lasorella',
      imagePrompt: 'Soft pastel sketch on white paper of a luxury cave hotel, rooms carved into ancient stone, designer furnishings against rough walls, infinity pool overlooking ravine, sophisticated lighting, blend of ancient and modern, warm luxurious tones, unique exclusive feel',
    },
    // CITY CHARACTER - Rupestrian Church (unique to Matera)
    {
      id: 'san-pietro-caveoso',
      name: 'Chiesa di San Pietro Caveoso',
      kind: 'church',
      neighbourhood: 'Sassi Caveoso',
      real: true,
      characterId: 'suor-margherita',
      imagePrompt: 'Soft pastel sketch on white paper of a baroque church built into rock face, ornate facade against stone cliff, bell tower, stone steps leading down, afternoon light illuminating facade, spiritual presence, warm stone whites and golds, dramatic setting',
    },
    // CITY CHARACTER - Artisan Workshop
    {
      id: 'bottega-artigiana',
      name: 'Bottega del Cucù',
      kind: 'artisan_shop',
      neighbourhood: 'Sassi Barisano',
      real: false,
      characterId: 'maurizio-stigliano',
      imagePrompt: 'Soft pastel sketch on white paper of an artisan workshop in cave, craftsman making traditional clay cucù whistles and ceramics, shelves of handmade pieces, tools and clay, creative workspace, earthy terracotta and clay tones, authentic craft atmosphere',
    },
    // Additional specialty food
    {
      id: 'salumeria-peperoni',
      name: 'Salumeria dei Peperoni',
      kind: 'deli',
      neighbourhood: 'Sassi Barisano',
      real: false,
      characterId: 'caterina-gallo',
      imagePrompt: 'Soft pastel sketch on white paper of a specialty deli, hanging bunches of peperoni cruschi, wheels of pecorino, cured lucanica sausages, jars of preserved vegetables, marble counter, rich food colors, aromatic traditional atmosphere',
    },
    // Gelateria
    {
      id: 'gelateria-artigiana',
      name: 'Gelateria I Vizi degli Angeli',
      kind: 'gelateria',
      neighbourhood: 'Piano',
      real: false,
      characterId: 'filippo-fortunato',
      imagePrompt: 'Soft pastel sketch on white paper of an artisan gelato shop, display case with creative flavors, customers choosing cones, bright interior, gelato in natural colors, evening light, cool pastels and cream tones, sweet inviting atmosphere',
    },
    // Ceramics shop (Matera traditional craft)
    {
      id: 'ceramiche-sassi',
      name: 'Ceramiche dei Sassi',
      kind: 'ceramics_shop',
      neighbourhood: 'Civita',
      real: false,
      characterId: 'daniela-tataranni',
      imagePrompt: 'Soft pastel sketch on white paper of a ceramics shop in stone building, window display of hand-painted pottery with Matera motifs, traditional patterns, artisan pieces on shelves, warm kiln in back, earthy glazed colors, artistic traditional feel',
    },
  ],
  characters: [
    {
      id: 'antonio-russo',
      name: 'Antonio Russo',
      age: 52,
      role: 'proprietario',
      placeId: 'caffe-schiuma',
      personality: ['warm', 'philosophical', 'proud of Matera heritage'],
      portraitPrompt: 'Pen and ink portrait on white paper of a middle-aged Italian man with salt-and-pepper hair, kind wrinkles around eyes, slight smile, wearing casual button-up shirt, minimal sepia watercolor wash on face, white background, detailed cross-hatching, warm character',
    },
    {
      id: 'lucia-dimatteo',
      name: 'Lucia Di Matteo',
      age: 28,
      role: 'barista',
      placeId: 'bar-vitantonio',
      personality: ['energetic', 'chatty', 'knows everyone'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young Italian woman with dark hair in ponytail, bright smile, expressive eyes, apron over casual clothes, minimal warm watercolor wash, white background, confident friendly expression, fine pen work',
    },
    {
      id: 'michele-lorusso',
      name: 'Michele Lorusso',
      age: 45,
      role: 'barista',
      placeId: 'caffe-degli-archi',
      personality: ['refined', 'attentive', 'coffee perfectionist'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished Italian man with groomed beard, observant eyes, crisp white shirt, subtle amber watercolor wash, white background, precise lines, professional demeanor',
    },
    {
      id: 'rosa-palmieri',
      name: 'Rosa Palmieri',
      age: 61,
      role: 'fornaia',
      placeId: 'panificio-del-sasso',
      personality: ['nurturing', 'traditional', 'early riser'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly Italian woman with hair in bun, flour-dusted apron, warm smile lines, strong hands, minimal wheat-tone watercolor wash, white background, maternal gentle expression, detailed rendering',
    },
    {
      id: 'giuseppe-bruno',
      name: 'Giuseppe Bruno',
      age: 38,
      role: 'fornaio',
      placeId: 'forno-antico',
      personality: ['jovial', 'hardworking', 'storyteller'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy Italian man with thick dark hair, cheerful expression, baker\'s whites, flour on cheek, minimal warm watercolor wash, white background, friendly open face, expressive pen strokes',
    },
    {
      id: 'carmela-gentile',
      name: 'Carmela Gentile',
      age: 55,
      role: 'venditrice',
      placeId: 'mercato-piccianello',
      personality: ['loud', 'generous', 'negotiator'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust Italian woman with curly hair, animated expression, colorful scarf, market apron, minimal earthy watercolor wash, white background, lively character, bold pen lines',
    },
    {
      id: 'pietro-volpe',
      name: 'Pietro Volpe',
      age: 67,
      role: 'negoziante',
      placeId: 'bottega-sassi',
      personality: ['knowledgeable', 'patient', 'guardian of traditions'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly Italian man with weathered face, wise eyes, cap, vest over shirt, minimal olive-tone watercolor wash, white background, dignified peaceful expression, careful detail work',
    },
    {
      id: 'anna-lagrotta',
      name: 'Anna La Grotta',
      age: 49,
      role: 'contadina',
      placeId: 'mercato-contadino',
      personality: ['earthy', 'honest', 'connected to land'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sun-weathered Italian woman with strong features, headscarf, work-worn hands, minimal earth-tone watercolor wash, white background, authentic rural character, textured pen work',
    },
    {
      id: 'francesca-clemente',
      name: 'Francesca Clemente',
      age: 43,
      role: 'chef proprietaria',
      placeId: 'ristorante-francesca',
      personality: ['elegant', 'precise', 'passionate about cuisine'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sophisticated Italian woman with styled short hair, chef\'s whites, refined features, minimal watercolor wash, white background, confident artistic expression, clean pen lines',
    },
    {
      id: 'marco-dibari',
      name: 'Marco Di Bari',
      age: 34,
      role: 'chef',
      placeId: 'ristorante-soul',
      personality: ['innovative', 'ambitious', 'perfectionist'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young Italian chef with intense gaze, modern chef jacket, trimmed beard, minimal cool watercolor wash, white background, creative determined expression, sharp pen detail',
    },
    {
      id: 'donato-santoro',
      name: 'Donato Santoro',
      age: 58,
      role: 'proprietario',
      placeId: 'trattoria-lucana',
      personality: ['hospitable', 'humorous', 'family-oriented'],
      portraitPrompt: 'Pen and ink portrait on white paper of a portly Italian man with mustache, laughing eyes, casual shirt, apron, minimal warm watercolor wash, white background, jolly welcoming expression, loose confident pen strokes',
    },
    {
      id: 'isabella-greco',
      name: 'Isabella Greco',
      age: 31,
      role: 'proprietaria',
      placeId: 'osteria-purgatorio',
      personality: ['warm', 'social', 'wine enthusiast'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young Italian woman with wavy dark hair, bright eyes, casual elegant style, minimal wine-red watercolor wash, white background, inviting smile, graceful pen lines',
    },
    {
      id: 'giovanni-montemurro',
      name: 'Giovanni Montemurro',
      age: 71,
      role: 'guida turistica',
      placeId: 'sassi-belvedere',
      personality: ['wise', 'eloquent', 'local historian'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly Italian man with white hair, gentle smile, cardigan, walking stick, minimal sepia watercolor wash, white background, scholarly kind expression, detailed portraiture',
    },
    {
      id: 'padre-leonardo',
      name: 'Padre Leonardo',
      age: 56,
      role: 'parroco',
      placeId: 'cattedrale',
      personality: ['serene', 'thoughtful', 'community leader'],
      portraitPrompt: 'Pen and ink portrait on white paper of a priest with receding hair, compassionate eyes, clerical collar, minimal watercolor wash, white background, peaceful dignified expression, reverent pen work',
    },
    {
      id: 'teresa-morelli',
      name: 'Teresa Morelli',
      age: 47,
      role: 'guida museale',
      placeId: 'casa-grotta',
      personality: ['educational', 'detail-oriented', 'preservationist'],
      portraitPrompt: 'Pen and ink portrait on white paper of a middle-aged Italian woman with glasses, professional attire, museum badge, minimal watercolor wash, white background, intelligent engaged expression, precise pen detail',
    },
    {
      id: 'saverio-gattini',
      name: 'Saverio Gattini',
      age: 39,
      role: 'guardiaparco',
      placeId: 'parco-murgia',
      personality: ['outdoorsy', 'protective', 'nature educator'],
      portraitPrompt: 'Pen and ink portrait on white paper of a fit Italian man with sun-weathered face, ranger uniform, binoculars around neck, minimal green watercolor wash, white background, alert friendly expression, naturalistic pen strokes',
    },
    {
      id: 'elena-laterza',
      name: 'Elena Laterza',
      age: 26,
      role: 'studente e musicista',
      placeId: 'piazza-vittorio',
      personality: ['artistic', 'social', 'free-spirited'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young Italian woman with long hair, bohemian style, guitar case strap visible, minimal watercolor wash, white background, creative dreamy expression, flowing pen lines',
    },
    {
      id: 'alberto-rizzi',
      name: 'Alberto Rizzi',
      age: 64,
      role: 'pensionato',
      placeId: 'piazza-duomo',
      personality: ['contemplative', 'friendly', 'daily routine'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly Italian man with cap, sport coat, newspaper tucked under arm, minimal watercolor wash, white background, contented peaceful expression, gentle pen work',
    },
    {
      id: 'vincenzo-pace',
      name: 'Vincenzo Pace',
      age: 41,
      role: 'sommelier',
      placeId: 'enoteca-lucania',
      personality: ['knowledgeable', 'passionate', 'discerning'],
      portraitPrompt: 'Pen and ink portrait on white paper of an Italian man with refined features, holding wine glass, vest and tie, minimal burgundy watercolor wash, white background, sophisticated appreciative expression, elegant pen lines',
    },
    {
      id: 'claudia-mastrangelo',
      name: 'Claudia Mastrangelo',
      age: 29,
      role: 'bartender',
      placeId: 'alle-fornaci',
      personality: ['stylish', 'mixologist', 'trendy'],
      portraitPrompt: 'Pen and ink portrait on white paper of a fashionable young Italian woman with modern hairstyle, cocktail shaker, stylish bar attire, minimal cool watercolor wash, white background, confident creative expression, contemporary pen work',
    },
    {
      id: 'beatrice-loperfido',
      name: 'Beatrice Loperfido',
      age: 36,
      role: 'libraia',
      placeId: 'libreria-matera',
      personality: ['literary', 'recommends books', 'thoughtful'],
      portraitPrompt: 'Pen and ink portrait on white paper of an Italian woman with glasses, cardigan, book in hand, intelligent eyes, minimal watercolor wash, white background, bookish warm expression, detailed pen rendering',
    },
    {
      id: 'dottoressa-mancini',
      name: 'Dott.ssa Elena Mancini',
      age: 44,
      role: 'farmacista',
      placeId: 'farmacia-centrale',
      personality: ['professional', 'caring', 'trusted advisor'],
      portraitPrompt: 'Pen and ink portrait on white paper of an Italian woman in white pharmacist coat, professional demeanor, kind smile, minimal watercolor wash, white background, competent reassuring expression, clean medical pen detail',
    },
    {
      id: 'roberto-nardella',
      name: 'Roberto Nardella',
      age: 51,
      role: 'capostazione',
      placeId: 'stazione-fal',
      personality: ['punctual', 'helpful', 'knows all schedules'],
      portraitPrompt: 'Pen and ink portrait on white paper of an Italian man in railway uniform, cap, whistle, clipboard, minimal blue watercolor wash, white background, reliable efficient expression, structured pen work',
    },
    {
      id: 'simone-lasorella',
      name: 'Simone Lasorella',
      age: 37,
      role: 'direttore',
      placeId: 'hotel-sassi',
      personality: ['sophisticated', 'multilingual', 'hospitality expert'],
      portraitPrompt: 'Pen and ink portrait on white paper of a polished Italian man in elegant suit, welcoming gesture, refined features, minimal watercolor wash, white background, professional warm expression, executive pen detail',
    },
    {
      id: 'suor-margherita',
      name: 'Suor Margherita',
      age: 69,
      role: 'suora',
      placeId: 'san-pietro-caveoso',
      personality: ['devout', 'gentle', 'community helper'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly nun with habit, serene face, rosary beads, minimal watercolor wash, white background, peaceful spiritual expression, reverent detailed pen work',
    },
    {
      id: 'maurizio-stigliano',
      name: 'Maurizio Stigliano',
      age: 53,
      role: 'artigiano',
      placeId: 'bottega-artigiana',
      personality: ['creative', 'patient', 'master craftsman'],
      portraitPrompt: 'Pen and ink portrait on white paper of an Italian artisan with work apron, clay on hands, focused eyes, minimal terracotta watercolor wash, white background, concentrated artistic expression, textured pen strokes',
    },
    {
      id: 'caterina-gallo',
      name: 'Caterina Gallo',
      age: 42,
      role: 'salumiera',
      placeId: 'salumeria-peperoni',
      personality: ['proud', 'expert', 'loves to sample'],
      portraitPrompt: 'Pen and ink portrait on white paper of an Italian woman with apron, holding salami, warm smile, minimal rich food-tone watercolor wash, white background, enthusiastic friendly expression, appetizing pen detail',
    },
    {
      id: 'filippo-fortunato',
      name: 'Filippo Fortunato',
      age: 32,
      role: 'gelataio',
      placeId: 'gelateria-artigiana',
      personality: ['cheerful', 'perfectionist', 'flavor innovator'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young Italian man with gelato scoop, white uniform, happy expression, minimal cool pastel watercolor wash, white background, joyful creative character, sweet pen work',
    },
    {
      id: 'daniela-tataranni',
      name: 'Daniela Tataranni',
      age: 40,
      role: 'ceramista',
      placeId: 'ceramiche-sassi',
      personality: ['artistic', 'traditional techniques', 'passionate'],
      portraitPrompt: 'Pen and ink portrait on white paper of an Italian woman with paint-stained smock, holding ceramic piece, creative eyes, minimal glazed watercolor wash, white background, artistic focused expression, crafted pen detail',
    },
  ],
  food: [
    'pane di Matera IGP',
    'peperoni cruschi',
    'crapiata',
    'orecchiette con cime di rapa',
    'cialledda',
    'lucanica',
    'pecorino di Filiano',
    'caciocavallo podolico',
    'strazzate',
    'taralli',
    'pane cotto',
    'agnello alla lucana',
    'baccalà alla materana',
    'cavatelli',
    'pezzente',
    'soppressata lucana',
    'calzone materano',
  ],
  customs: [
    'Festa della Bruna (July 2nd) - major religious festival',
    'Sagre celebrating local products throughout summer',
    'Passeggiata in Piazza Vittorio Veneto',
    'Sunday family lunches lasting hours',
    'Coffee standing at the bar, quick and strong',
    'Aperitivo hour with local wines',
    'Preservation of cave dwelling traditions',
    'UNESCO World Heritage Site pride',
    'Film location tourism (from Passion of the Christ, Bond)',
  ],
  localTouches: [
    'Materani are called "materani" with pride',
    '"U sasse" - dialect for the Sassi',
    'Reference to life before 1950s evacuation',
    'Cave dwelling (grotto/casa grotta) terminology',
    'Gravina - the ravine',
    'Regional Basilicata pride vs national identity',
    'Connection to ancient past and prehistory',
    'Tufo - the local limestone',
    'References to film productions',
    'Matera as European Capital of Culture 2019',
  ],
};
