import { CityPantry } from '@/lib/types';

export const milano: CityPantry = {
  id: 'milano',
  name: 'Milano',
  neighbourhoods: ['Navigli', 'Brera', 'Porta Romana', 'Isola'],
  places: [
    // BARS/CAFÉS (9 places - 2-3 per neighborhood)
    {
      id: 'pasticceria-marchesi',
      name: 'Pasticceria Marchesi',
      kind: 'bar',
      neighbourhood: 'Brera',
      real: true,
      characterId: 'giulia-marchesi',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant historic Milanese pasticceria with mint green facade, gold lettering, vintage display cases filled with pastel-colored pastries, marble counters, Art Nouveau details, warm morning light streaming through tall windows, textured, inviting atmosphere',
    },
    {
      id: 'bar-rita',
      name: 'Bar Rita',
      kind: 'bar',
      neighbourhood: 'Navigli',
      real: false,
      characterId: 'roberto-costa',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy corner bar along the canal, outdoor tables with red umbrellas, vintage espresso machine visible through the window, flower boxes, weathered ochre walls, morning sunlight reflecting off the water, warm inviting colors',
    },
    {
      id: 'caffe-napoli',
      name: 'Caffè Napoli',
      kind: 'bar',
      neighbourhood: 'Porta Romana',
      real: false,
      characterId: 'vincenzo-romano',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional Milanese caffè with deep red awning, zinc counter, shelves of liquor bottles, locals reading Corriere della Sera, vintage posters, warm amber lighting, textured walls',
    },
    {
      id: 'bar-quadronno',
      name: 'Bar Quadronno',
      kind: 'bar',
      neighbourhood: 'Isola',
      real: false,
      characterId: 'chiara-fontana',
      imagePrompt: 'Soft pastel sketch on white paper of a modern-meets-traditional bar with exposed brick, industrial elements, wooden tables, plants hanging from ceiling, specialty coffee equipment, young creative atmosphere, soft natural light',
    },
    {
      id: 'pasticceria-sant-ambrogio',
      name: 'Pasticceria Sant\'Ambrogio',
      kind: 'bar',
      neighbourhood: 'Brera',
      real: false,
      characterId: 'marco-bellini',
      imagePrompt: 'Soft pastel sketch on white paper of an upscale pasticceria with pristine white interior, glass display cases of panettone and colomba, elegant chandelier, customers in fashionable attire, soft pink and gold accents, luxurious inviting atmosphere',
    },
    {
      id: 'bar-della-darsena',
      name: 'Bar della Darsena',
      kind: 'bar',
      neighbourhood: 'Navigli',
      real: false,
      characterId: 'elena-grassi',
      imagePrompt: 'Soft pastel sketch on white paper of a waterfront bar with outdoor seating, green and white striped awning, view of canal boats, bicycles parked outside, morning aperitivo setup, warm golden hour light on water',
    },
    {
      id: 'caffe-design',
      name: 'Caffè Design',
      kind: 'bar',
      neighbourhood: 'Porta Romana',
      real: false,
      characterId: 'alessandro-gatti',
      imagePrompt: 'Soft pastel sketch on white paper of a sleek design-forward café with minimalist white furniture, design magazines on shelves, large windows, modern art on walls, clean lines, soft grey and white palette with pops of color',
    },
    {
      id: 'bar-isola',
      name: 'Bar Isola',
      kind: 'bar',
      neighbourhood: 'Isola',
      real: false,
      characterId: 'francesca-moretti',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood bar with vintage blue tile facade, locals chatting at counter, vintage Campari signs, worn wooden floors, community bulletin board, warm familiar atmosphere',
    },
    {
      id: 'pasticceria-cucchi',
      name: 'Pasticceria Cucchi',
      kind: 'bar',
      neighbourhood: 'Porta Romana',
      real: false,
      characterId: 'sofia-cucchi',
      imagePrompt: 'Soft pastel sketch on white paper of a belle époque pasticceria with ornate mirrors, velvet seating, crystal chandeliers, elaborate pastry displays, gilded details, soft pink and cream tones, elegant timeless atmosphere',
    },

    // BAKERIES (4 places)
    {
      id: 'panificio-davide-longoni',
      name: 'Panificio Davide Longoni',
      kind: 'bakery',
      neighbourhood: 'Isola',
      real: true,
      characterId: 'davide-longoni',
      imagePrompt: 'Soft pastel sketch on white paper of an artisanal bakery with wooden shelves stacked with sourdough loaves, flour-dusted surfaces, stone oven visible in back, burlap sacks of grain, rustic warm atmosphere, golden wheat tones',
    },
    {
      id: 'forno-navigli',
      name: 'Forno dei Navigli',
      kind: 'bakery',
      neighbourhood: 'Navigli',
      real: false,
      characterId: 'giuseppe-mancini',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional neighborhood bakery with terracotta tile floor, wooden bread baskets, handwritten price signs, focaccia in the window, warm oven glow, flour in the air',
    },
    {
      id: 'panetteria-brera',
      name: 'Panetteria Brera',
      kind: 'bakery',
      neighbourhood: 'Brera',
      real: false,
      characterId: 'laura-conti',
      imagePrompt: 'Soft pastel sketch on white paper of an upscale artisan bakery with white marble counters, organic flour labels, beautifully arranged michette bread, fresh flowers, soft morning light, refined rustic aesthetic',
    },
    {
      id: 'forno-sant-eustorgio',
      name: 'Forno Sant\'Eustorgio',
      kind: 'bakery',
      neighbourhood: 'Porta Romana',
      real: false,
      characterId: 'andrea-colombo',
      imagePrompt: 'Soft pastel sketch on white paper of a family-run bakery with vintage ovens, generations of bread-making tools on display, golden-brown loaves cooling on racks, grandmother\'s recipes framed on wall, warm nostalgic atmosphere',
    },

    // MARKETS (3 places)
    {
      id: 'mercato-di-porta-romana',
      name: 'Mercato di Porta Romana',
      kind: 'market',
      neighbourhood: 'Porta Romana',
      real: false,
      characterId: 'mario-esposito',
      imagePrompt: 'Soft pastel sketch on white paper of a vibrant outdoor market with colorful produce stalls, striped awnings, crates of fresh vegetables, hanging salamis, bustling shoppers, morning light, lively atmosphere with soft greens and reds',
    },
    {
      id: 'mercato-comunale-isola',
      name: 'Mercato Comunale dell\'Isola',
      kind: 'market',
      neighbourhood: 'Isola',
      real: false,
      characterId: 'rosa-ferrari',
      imagePrompt: 'Soft pastel sketch on white paper of a covered market hall with vendor stalls, hanging lights, fresh fish on ice, cheese wheels, flowers, local shoppers with carts, warm community feeling, soft yellows and blues',
    },
    {
      id: 'mercatino-navigli',
      name: 'Mercatino dei Navigli',
      kind: 'market',
      neighbourhood: 'Navigli',
      real: false,
      characterId: 'carlo-brambilla',
      imagePrompt: 'Soft pastel sketch on white paper of a canalside market with antique stalls, vintage finds, produce vendors, artists selling crafts, bicycles, waterway in background, bohemian atmosphere, warm earthy tones',
    },

    // RESTAURANTS (4 places)
    {
      id: 'trattoria-masuelli',
      name: 'Trattoria Masuelli San Marco',
      kind: 'trattoria',
      neighbourhood: 'Porta Romana',
      real: true,
      characterId: 'anna-masuelli',
      imagePrompt: 'Soft pastel sketch on white paper of a classic Milanese trattoria with white tablecloths, wood-paneled walls, vintage photographs, wine bottles on shelves, warm intimate lighting, traditional elegant atmosphere',
    },
    {
      id: 'ristorante-brera',
      name: 'Ristorante da Giacomo',
      kind: 'ristorante',
      neighbourhood: 'Brera',
      real: false,
      characterId: 'giacomo-villa',
      imagePrompt: 'Soft pastel sketch on white paper of an upscale restaurant with art deco details, crisp white napkins, fresh flowers on tables, marble accents, sophisticated diners, soft candlelight, refined atmosphere',
    },
    {
      id: 'osteria-navigli',
      name: 'Osteria del Binari',
      kind: 'osteria',
      neighbourhood: 'Navigli',
      real: false,
      characterId: 'paolo-russo',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy osteria with brick vaulted ceilings, wooden tables, wine casks, candlelight, aperitivo spread at bar, locals chatting, warm convivial atmosphere, rustic charm',
    },
    {
      id: 'trattoria-isola',
      name: 'Trattoria dell\'Isola',
      kind: 'trattoria',
      neighbourhood: 'Isola',
      real: false,
      characterId: 'beatrice-galli',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood trattoria with checked tablecloths, family photos on walls, pasta drying, chalkboard menu, grandmother cooking in visible kitchen, homey warm atmosphere',
    },

    // SPECIALTY FOOD (3 places)
    {
      id: 'peck',
      name: 'Peck',
      kind: 'gastronomia',
      neighbourhood: 'Brera',
      real: true,
      characterId: 'lorenzo-peck',
      imagePrompt: 'Soft pastel sketch on white paper of a legendary Milanese delicatessen with glass cases of prepared foods, hanging prosciutto, cheese counter, wine cellar entrance, elegant shoppers, luxurious gourmet atmosphere, rich warm tones',
    },
    {
      id: 'pizzeria-spontini',
      name: 'Pizzeria Spontini',
      kind: 'pizzeria',
      neighbourhood: 'Porta Romana',
      real: true,
      characterId: 'luca-spontini',
      imagePrompt: 'Soft pastel sketch on white paper of a bustling pizzeria with high thick pizza slices in display, standing customers eating, vintage signs, marble counters, quick service atmosphere, warm reds and golds',
    },
    {
      id: 'gelateria-navigli',
      name: 'Gelateria della Conca',
      kind: 'gelateria',
      neighbourhood: 'Navigli',
      real: false,
      characterId: 'valentina-renzi',
      imagePrompt: 'Soft pastel sketch on white paper of an artisanal gelato shop with colorful gelato display, handwritten flavor signs, customers with cones by canal, pastel pink and mint green decor, sweet inviting atmosphere',
    },

    // CULTURAL/LANDMARKS (7 places)
    {
      id: 'duomo-milano',
      name: 'Duomo di Milano',
      kind: 'landmark',
      neighbourhood: 'Brera',
      real: true,
      characterId: 'padre-stefano',
      imagePrompt: 'Soft pastel sketch on white paper of the magnificent Gothic cathedral with intricate spires reaching skyward, white marble facade, people in the piazza, pigeons, warm afternoon light, majestic atmospheric perspective',
    },
    {
      id: 'pinacoteca-brera',
      name: 'Pinacoteca di Brera',
      kind: 'museum',
      neighbourhood: 'Brera',
      real: true,
      characterId: 'dottoressa-martini',
      imagePrompt: 'Soft pastel sketch on white paper of a grand palazzo courtyard with Renaissance architecture, bronze statue in center, students sketching, visitors entering museum, soft afternoon light, cultured atmosphere',
    },
    {
      id: 'basilica-sant-eustorgio',
      name: 'Basilica di Sant\'Eustorgio',
      kind: 'church',
      neighbourhood: 'Porta Romana',
      real: true,
      characterId: 'suor-teresa',
      imagePrompt: 'Soft pastel sketch on white paper of a Romanesque basilica with brick bell tower, ancient stone walls, peaceful courtyard, cypress trees, soft golden light, serene spiritual atmosphere',
    },
    {
      id: 'parco-sempione',
      name: 'Parco Sempione',
      kind: 'park',
      neighbourhood: 'Brera',
      real: true,
      characterId: 'matteo-verdi',
      imagePrompt: 'Soft pastel sketch on white paper of a sprawling urban park with tree-lined paths, joggers, families picnicking, Castello Sforzesco towers in background, fountain, soft green and gold light filtering through leaves',
    },
    {
      id: 'piazza-santo-stefano',
      name: 'Piazza Santo Stefano',
      kind: 'piazza',
      neighbourhood: 'Navigli',
      real: false,
      characterId: 'giovanna-sartori',
      imagePrompt: 'Soft pastel sketch on white paper of a charming neighborhood square with outdoor cafés, cobblestones, church facade, people meeting, bicycles, market flowers, warm community gathering place',
    },
    {
      id: 'piazza-xxv-aprile',
      name: 'Piazza XXV Aprile',
      kind: 'piazza',
      neighbourhood: 'Isola',
      real: true,
      characterId: 'fabio-cattaneo',
      imagePrompt: 'Soft pastel sketch on white paper of a lively urban square with modern trams passing, aperitivo bars with outdoor seating, young people socializing, trees, contemporary atmosphere meeting historic Milan',
    },
    {
      id: 'biblioteca-isola',
      name: 'Biblioteca di Isola',
      kind: 'library',
      neighbourhood: 'Isola',
      real: false,
      characterId: 'isabella-rizzi',
      imagePrompt: 'Soft pastel sketch on white paper of a modern neighborhood library with floor-to-ceiling windows, reading areas, children\'s section, community events space, natural light, welcoming cultural hub atmosphere',
    },

    // SOCIAL/EVENING (3 places)
    {
      id: 'enoteca-brera',
      name: 'Enoteca Brera',
      kind: 'enoteca',
      neighbourhood: 'Brera',
      real: false,
      characterId: 'massimo-riva',
      imagePrompt: 'Soft pastel sketch on white paper of a sophisticated wine bar with bottles floor to ceiling, small tables, cheese and salumi boards, candlelight, intimate conversations, warm amber and burgundy tones',
    },
    {
      id: 'mag-cafe',
      name: 'Mag Cafè',
      kind: 'bar',
      neighbourhood: 'Navigli',
      real: false,
      characterId: 'silvia-neri',
      imagePrompt: 'Soft pastel sketch on white paper of a bohemian aperitivo spot with vintage furniture, bookshelves, canalside seating, cocktails, young creatives, string lights, relaxed artistic evening atmosphere',
    },
    {
      id: 'libreria-brera',
      name: 'Libreria dell\'Arte',
      kind: 'bookshop',
      neighbourhood: 'Brera',
      real: false,
      characterId: 'tommaso-berti',
      imagePrompt: 'Soft pastel sketch on white paper of an intimate art bookshop with wooden shelves, art catalogs, reading nook, gallery posters, soft lighting, customers browsing, cultured contemplative atmosphere',
    },

    // PRACTICAL (2 places)
    {
      id: 'farmacia-centrale',
      name: 'Farmacia Centrale',
      kind: 'pharmacy',
      neighbourhood: 'Porta Romana',
      real: false,
      characterId: 'dottore-lombardi',
      imagePrompt: 'Soft pastel sketch on white paper of a historic Milanese pharmacy with vintage wooden cabinets, glass bottles, white coat service, Art Nouveau details, green cross sign, professional caring atmosphere',
    },
    {
      id: 'stazione-porta-garibaldi',
      name: 'Stazione Porta Garibaldi',
      kind: 'station',
      neighbourhood: 'Isola',
      real: true,
      characterId: 'michele-franco',
      imagePrompt: 'Soft pastel sketch on white paper of a modern train station with glass and steel architecture, commuters with coffee, departure boards, morning rush, urban energy, clean contemporary lines',
    },

    // CITY CHARACTER (2 places)
    {
      id: 'galleria-vittorio-emanuele',
      name: 'Galleria Vittorio Emanuele II',
      kind: 'landmark',
      neighbourhood: 'Brera',
      real: true,
      characterId: 'emanuele-rossini',
      imagePrompt: 'Soft pastel sketch on white paper of the magnificent glass-vaulted shopping arcade with ornate iron and glass roof, mosaic floor, elegant boutiques, cafés, people walking through, soft light filtering through glass ceiling, grand Milanese elegance',
    },
    {
      id: 'atelier-moda',
      name: 'Atelier Moda Milano',
      kind: 'shop',
      neighbourhood: 'Brera',
      real: false,
      characterId: 'federica-bianchi',
      imagePrompt: 'Soft pastel sketch on white paper of a fashion atelier with dress forms, fabric swatches, sketches on walls, large windows with natural light, sewing machines, mannequins in designer pieces, creative sophisticated atmosphere',
    },
  ],
  characters: [
    {
      id: 'giulia-marchesi',
      name: 'Giulia Marchesi',
      age: 42,
      role: 'pasticciera',
      placeId: 'pasticceria-marchesi',
      personality: ['meticulous', 'elegant', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sophisticated woman in her 40s with hair in an elegant chignon, wearing a pristine white chef\'s jacket, subtle makeup, knowing smile, minimal watercolor wash in mint green and gold tones, detailed linework, refined professional presence',
    },
    {
      id: 'roberto-costa',
      name: 'Roberto Costa',
      age: 55,
      role: 'barista',
      placeId: 'bar-rita',
      personality: ['friendly', 'talkative', 'local character'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warm middle-aged man with salt-and-pepper hair, laugh lines, wearing casual button-down shirt, friendly open expression, minimal watercolor wash in warm ochre and red tones, detailed expressive features',
    },
    {
      id: 'vincenzo-romano',
      name: 'Vincenzo Romano',
      age: 68,
      role: 'proprietor',
      placeId: 'caffe-napoli',
      personality: ['old-school', 'opinionated', 'loyal'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly gentleman with distinguished gray hair, strong features, reading glasses on chain, vest and tie, serious but kind expression, minimal watercolor wash in deep burgundy and amber tones, traditional dignified presence',
    },
    {
      id: 'chiara-fontana',
      name: 'Chiara Fontana',
      age: 28,
      role: 'barista',
      placeId: 'bar-quadronno',
      personality: ['creative', 'passionate', 'modern'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with modern short haircut, tattoo visible on forearm, wearing denim apron, bright intelligent eyes, confident smile, minimal watercolor wash in soft grey and green tones, contemporary artistic energy',
    },
    {
      id: 'marco-bellini',
      name: 'Marco Bellini',
      age: 35,
      role: 'pasticciere',
      placeId: 'pasticceria-sant-ambrogio',
      personality: ['ambitious', 'perfectionist', 'charming'],
      portraitPrompt: 'Pen and ink portrait on white paper of a handsome man in mid-30s with styled dark hair, well-groomed beard, wearing chef\'s whites, intense focused expression, minimal watercolor wash in pink and gold tones, polished professional appearance',
    },
    {
      id: 'elena-grassi',
      name: 'Elena Grassi',
      age: 31,
      role: 'proprietor',
      placeId: 'bar-della-darsena',
      personality: ['energetic', 'social', 'organized'],
      portraitPrompt: 'Pen and ink portrait on white paper of a lively woman in her 30s with wavy hair pulled back, bright eyes, warm smile, wearing casual stylish clothes, minimal watercolor wash in green and yellow tones, approachable welcoming energy',
    },
    {
      id: 'alessandro-gatti',
      name: 'Alessandro Gatti',
      age: 26,
      role: 'barista',
      placeId: 'caffe-design',
      personality: ['minimalist', 'precise', 'design-focused'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with angular features, clean-shaven, modern glasses, black t-shirt, thoughtful expression, minimal watercolor wash in grey and white tones, contemporary aesthetic sensibility',
    },
    {
      id: 'francesca-moretti',
      name: 'Francesca Moretti',
      age: 49,
      role: 'barista',
      placeId: 'bar-isola',
      personality: ['maternal', 'gossipy', 'warm-hearted'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust woman in her late 40s with curly hair, kind round face, flour-dusted apron, knowing smile, minimal watercolor wash in warm blue and cream tones, neighborhood mother figure',
    },
    {
      id: 'sofia-cucchi',
      name: 'Sofia Cucchi',
      age: 38,
      role: 'manager',
      placeId: 'pasticceria-cucchi',
      personality: ['refined', 'knowledgeable', 'gracious'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant woman in her late 30s with classic updo, pearl earrings, sophisticated dress, poised expression, minimal watercolor wash in soft pink and cream tones, timeless Milanese elegance',
    },
    {
      id: 'davide-longoni',
      name: 'Davide Longoni',
      age: 45,
      role: 'baker',
      placeId: 'panificio-davide-longoni',
      personality: ['artisan', 'passionate', 'principled'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy man in mid-40s with flour in hair, strong hands, wearing simple baker\'s shirt, intense eyes, genuine smile, minimal watercolor wash in wheat and golden tones, craftsman\'s dedication',
    },
    {
      id: 'giuseppe-mancini',
      name: 'Giuseppe Mancini',
      age: 60,
      role: 'baker',
      placeId: 'forno-navigli',
      personality: ['traditional', 'generous', 'early-riser'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stocky man in his 60s with weathered hands, simple white baker\'s clothing, warm grandfatherly smile, minimal watercolor wash in terracotta and cream tones, lifetime of bread-making in his eyes',
    },
    {
      id: 'laura-conti',
      name: 'Laura Conti',
      age: 33,
      role: 'baker',
      placeId: 'panetteria-brera',
      personality: ['innovative', 'health-conscious', 'artistic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a woman in her early 30s with natural beauty, flour-dusted apron, loose hair, gentle confident expression, minimal watercolor wash in soft wheat and white tones, modern artisan spirit',
    },
    {
      id: 'andrea-colombo',
      name: 'Andrea Colombo',
      age: 52,
      role: 'baker',
      placeId: 'forno-sant-eustorgio',
      personality: ['family-oriented', 'nostalgic', 'reliable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a solid man in his 50s with thinning hair, wearing traditional baker\'s attire, kind eyes, content smile, minimal watercolor wash in golden brown tones, multi-generational wisdom',
    },
    {
      id: 'mario-esposito',
      name: 'Mario Esposito',
      age: 58,
      role: 'vendor',
      placeId: 'mercato-di-porta-romana',
      personality: ['boisterous', 'humorous', 'savvy'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust man in late 50s with weather-beaten face, cap, calling out to customers, big grin, minimal watercolor wash in green and red produce tones, market vendor vitality',
    },
    {
      id: 'rosa-ferrari',
      name: 'Rosa Ferrari',
      age: 47,
      role: 'vendor',
      placeId: 'mercato-comunale-isola',
      personality: ['sharp-witted', 'honest', 'hardworking'],
      portraitPrompt: 'Pen and ink portrait on white paper of a strong-featured woman in her late 40s with hair tied back, practical clothes, direct gaze, knowing smile, minimal watercolor wash in market colors, no-nonsense competence',
    },
    {
      id: 'carlo-brambilla',
      name: 'Carlo Brambilla',
      age: 63,
      role: 'vendor',
      placeId: 'mercatino-navigli',
      personality: ['eccentric', 'storyteller', 'collector'],
      portraitPrompt: 'Pen and ink portrait on white paper of a weathered man in his 60s with wild gray hair, vintage vest, interesting rings, twinkling eyes, minimal watercolor wash in earthy antique tones, bohemian character',
    },
    {
      id: 'anna-masuelli',
      name: 'Anna Masuelli',
      age: 56,
      role: 'owner',
      placeId: 'trattoria-masuelli',
      personality: ['authoritative', 'exacting', 'protective'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished woman in her 50s with elegant updo, classic dress, commanding presence, warm but firm expression, minimal watercolor wash in traditional burgundy tones, old Milan matriarch',
    },
    {
      id: 'giacomo-villa',
      name: 'Giacomo Villa',
      age: 44,
      role: 'chef',
      placeId: 'ristorante-brera',
      personality: ['sophisticated', 'demanding', 'talented'],
      portraitPrompt: 'Pen and ink portrait on white paper of a handsome man in mid-40s with greying temples, chef\'s whites, intense eyes, slight smile, minimal watercolor wash in marble white and grey tones, culinary authority',
    },
    {
      id: 'paolo-russo',
      name: 'Paolo Russo',
      age: 39,
      role: 'owner',
      placeId: 'osteria-navigli',
      personality: ['convivial', 'wine-loving', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a jovial man in late 30s with beard, casual shirt, glass of wine in hand gesture, big laugh, minimal watercolor wash in wine red and warm tones, host personality',
    },
    {
      id: 'beatrice-galli',
      name: 'Beatrice Galli',
      age: 71,
      role: 'cook',
      placeId: 'trattoria-isola',
      personality: ['nonno-like', 'loving', 'wise'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly woman with white hair, apron, wooden spoon, gentle grandmother face, twinkling eyes, minimal watercolor wash in warm kitchen tones, nonna energy and love',
    },
    {
      id: 'lorenzo-peck',
      name: 'Lorenzo Peck',
      age: 51,
      role: 'department manager',
      placeId: 'peck',
      personality: ['refined', 'knowledgeable', 'discerning'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man in his 50s with impeccable grooming, suit and tie, refined features, expert expression, minimal watercolor wash in rich gourmet tones, culinary connoisseur',
    },
    {
      id: 'luca-spontini',
      name: 'Luca Spontini',
      age: 29,
      role: 'pizzaiolo',
      placeId: 'pizzeria-spontini',
      personality: ['fast-paced', 'skilled', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man in late 20s with muscular arms, flour on face, white t-shirt, confident grin, minimal watercolor wash in pizza red and gold tones, quick efficient energy',
    },
    {
      id: 'valentina-renzi',
      name: 'Valentina Renzi',
      age: 24,
      role: 'gelataia',
      placeId: 'gelateria-navigli',
      personality: ['sweet', 'cheerful', 'artistic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman in mid-20s with bright smile, colorful apron, gelato scoop in hand gesture, playful expression, minimal watercolor wash in pastel gelato tones, youthful joy',
    },
    {
      id: 'padre-stefano',
      name: 'Padre Stefano',
      age: 67,
      role: 'priest',
      placeId: 'duomo-milano',
      personality: ['scholarly', 'patient', 'inspiring'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly priest with gentle face, clerical collar, wise eyes, serene expression, minimal watercolor wash in cathedral stone tones, spiritual gravitas',
    },
    {
      id: 'dottoressa-martini',
      name: 'Dottoressa Martini',
      age: 43,
      role: 'curator',
      placeId: 'pinacoteca-brera',
      personality: ['intellectual', 'passionate', 'articulate'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sophisticated woman in her 40s with stylish glasses, elegant professional attire, art catalog in hand, intelligent gaze, minimal watercolor wash in gallery tones, cultured authority',
    },
    {
      id: 'suor-teresa',
      name: 'Suor Teresa',
      age: 54,
      role: 'nun',
      placeId: 'basilica-sant-eustorgio',
      personality: ['peaceful', 'welcoming', 'devoted'],
      portraitPrompt: 'Pen and ink portrait on white paper of a kind-faced nun in her 50s with habit, gentle smile, prayer book, serene expression, minimal watercolor wash in soft religious tones, quiet strength',
    },
    {
      id: 'matteo-verdi',
      name: 'Matteo Verdi',
      age: 36,
      role: 'gardener',
      placeId: 'parco-sempione',
      personality: ['nature-loving', 'quiet', 'observant'],
      portraitPrompt: 'Pen and ink portrait on white paper of a lean man in mid-30s with sun-weathered skin, work clothes, pruning shears, peaceful expression, minimal watercolor wash in green garden tones, outdoor vitality',
    },
    {
      id: 'giovanna-sartori',
      name: 'Giovanna Sartori',
      age: 41,
      role: 'florist',
      placeId: 'piazza-santo-stefano',
      personality: ['romantic', 'chatty', 'colorful'],
      portraitPrompt: 'Pen and ink portrait on white paper of a vibrant woman in her 40s with flowers in hair, bright scarf, arranging bouquet gesture, warm smile, minimal watercolor wash in flower market colors, artistic spirit',
    },
    {
      id: 'fabio-cattaneo',
      name: 'Fabio Cattaneo',
      age: 32,
      role: 'street musician',
      placeId: 'piazza-xxv-aprile',
      personality: ['artistic', 'free-spirited', 'talented'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man in early 30s with slightly disheveled hair, casual artistic clothes, guitar strap visible, soulful eyes, minimal watercolor wash in urban tones, creative independence',
    },
    {
      id: 'isabella-rizzi',
      name: 'Isabella Rizzi',
      age: 37,
      role: 'librarian',
      placeId: 'biblioteca-isola',
      personality: ['helpful', 'bookish', 'community-minded'],
      portraitPrompt: 'Pen and ink portrait on white paper of a woman in late 30s with glasses, cardigan, book in hand, intelligent kind expression, minimal watercolor wash in library tones, quiet competence',
    },
    {
      id: 'massimo-riva',
      name: 'Massimo Riva',
      age: 48,
      role: 'sommelier',
      placeId: 'enoteca-brera',
      personality: ['sophisticated', 'knowledgeable', 'conversational'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man in late 40s with salt-pepper hair, holding wine glass, expert expression, minimal watercolor wash in wine burgundy and amber tones, oenophile authority',
    },
    {
      id: 'silvia-neri',
      name: 'Silvia Neri',
      age: 27,
      role: 'bartender',
      placeId: 'mag-cafe',
      personality: ['hip', 'creative', 'social'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stylish young woman in late 20s with alternative fashion, mixing cocktail gesture, confident smile, minimal watercolor wash in aperitivo orange tones, young Milan energy',
    },
    {
      id: 'tommaso-berti',
      name: 'Tommaso Berti',
      age: 53,
      role: 'bookseller',
      placeId: 'libreria-brera',
      personality: ['intellectual', 'thoughtful', 'recommending'],
      portraitPrompt: 'Pen and ink portrait on white paper of a scholarly man in his 50s with reading glasses, sweater vest, book in hand, contemplative expression, minimal watercolor wash in bookshop tones, literary knowledge',
    },
    {
      id: 'dottore-lombardi',
      name: 'Dottore Lombardi',
      age: 59,
      role: 'pharmacist',
      placeId: 'farmacia-centrale',
      personality: ['professional', 'caring', 'precise'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man in late 50s with white coat, glasses, reassuring expression, minimal watercolor wash in pharmacy green and white tones, medical trust',
    },
    {
      id: 'michele-franco',
      name: 'Michele Franco',
      age: 34,
      role: 'station worker',
      placeId: 'stazione-porta-garibaldi',
      personality: ['efficient', 'helpful', 'urban'],
      portraitPrompt: 'Pen and ink portrait on white paper of a man in mid-30s with transit uniform, radio, helpful gesture, professional smile, minimal watercolor wash in railway tones, city infrastructure',
    },
    {
      id: 'emanuele-rossini',
      name: 'Emanuele Rossini',
      age: 46,
      role: 'gallery guide',
      placeId: 'galleria-vittorio-emanuele',
      personality: ['proud', 'historical', 'eloquent'],
      portraitPrompt: 'Pen and ink portrait on white paper of a well-dressed man in mid-40s with elegant attire, explaining gesture, passionate expression, minimal watercolor wash in Galleria gold and glass tones, Milanese pride',
    },
    {
      id: 'federica-bianchi',
      name: 'Federica Bianchi',
      age: 40,
      role: 'fashion designer',
      placeId: 'atelier-moda',
      personality: ['stylish', 'perfectionist', 'visionary'],
      portraitPrompt: 'Pen and ink portrait on white paper of a chic woman in her 40s with fashionable attire, measuring tape around neck, fabric swatch in hand, creative intensity, minimal watercolor wash in fashion tones, Milan style authority',
    },
  ],
  food: [
    'risotto alla milanese',
    'cotoletta alla milanese',
    'ossobuco',
    'panettone',
    'michetta',
    'cassoeula',
    'mondeghili',
    'tortelli di zucca',
    'brasato',
    'pizzoccheri',
    'polenta',
    'gorgonzola',
    'taleggio',
    'salame milano',
    'mostarda',
    'amaretti',
    'colomba pasquale',
    'barbajada',
  ],
  customs: [
    'aperitivo hour starting at 6pm',
    'always cappuccino only in the morning',
    'standing at the bar for quick espresso',
    'fashion week twice a year',
    'navigli evening strolls',
    'Sunday aperitivo ritual',
    'quick lunch breaks',
    'Salone del Mobile in April',
    'opera season at La Scala',
    'business-focused mindset',
    'Milanese reserve and privacy',
    'panettone at Christmas',
  ],
  localTouches: [
    'Ciao bello/bella',
    'Va là!',
    'Andiamo a fare l\'aperitivo?',
    'Che bello!',
    'Sciur (Milanese dialect for signore)',
    'Sciura (Milanese dialect for signora)',
    'Ué (hey)',
    'Lazer (Milanese for work)',
    'Tranquillo/a',
    'Dai!',
    'Ma va là',
    'Bella lì',
  ],
};
