import { CityPantry } from '@/lib/types';

export const napoli: CityPantry = {
  id: 'napoli',
  name: 'Napoli',
  neighbourhoods: ['Centro Storico', 'Vomero', 'Chiaia', 'Spaccanapoli'],
  places: [
    // BARS/CAFÉS (9)
    {
      id: 'bar-nilo',
      name: 'Bar Nilo',
      kind: 'bar',
      neighbourhood: 'Spaccanapoli',
      real: true,
      characterId: 'carmine-russo',
      imagePrompt: 'Soft pastel sketch on white paper of a tiny traditional Neapolitan bar with blue-tiled walls, a chrome espresso machine gleaming on the counter, and a small shrine to Maradona visible on the wall. Warm ochre and azure tones, morning light streaming through the doorway, textured and inviting.',
    },
    {
      id: 'caffe-gambrinus',
      name: 'Caffè Gambrinus',
      kind: 'bar',
      neighbourhood: 'Chiaia',
      real: true,
      characterId: 'sofia-esposito',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant belle époque café with ornate gilded mirrors, marble-topped tables, and velvet chairs. Rich burgundy and gold tones, crystal chandeliers catching afternoon light, atmospheric and refined.',
    },
    {
      id: 'bar-mexico',
      name: 'Bar Mexico',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'gennaro-de-luca',
      imagePrompt: 'Soft pastel sketch on white paper of a bustling corner bar with customers standing at the counter, pastries displayed in glass cases, and a vintage espresso machine. Warm cream and coffee brown tones, energetic morning atmosphere, inviting textures.',
    },
    {
      id: 'caffe-del-professore',
      name: 'Caffè del Professore',
      kind: 'bar',
      neighbourhood: 'Spaccanapoli',
      real: true,
      characterId: 'mimmo-verde',
      imagePrompt: 'Soft pastel sketch on white paper of a narrow café with walls covered in vintage coffee advertisements and black-and-white photos of old Napoli. Deep espresso brown and cream tones, steamy atmospheric quality, cozy and historic.',
    },
    {
      id: 'bar-vomero-alto',
      name: 'Bar Vomero Alto',
      kind: 'bar',
      neighbourhood: 'Vomero',
      real: false,
      characterId: 'lucia-romano',
      imagePrompt: 'Soft pastel sketch on white paper of a modern neighborhood bar with large windows overlooking the bay, clean lines, and a sleek espresso setup. Soft blue and white tones, airy hilltop light, fresh and contemporary.',
    },
    {
      id: 'bar-epoca',
      name: "Bar dell'Epoca",
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'antonio-casale',
      imagePrompt: 'Soft pastel sketch on white paper of a vintage-style bar with art deco details, geometric floor tiles in black and white, and copper fixtures. Warm amber and sage green tones, nostalgic morning atmosphere.',
    },
    {
      id: 'caffe-toledo',
      name: 'Caffè Toledo',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'rosa-marino',
      imagePrompt: 'Soft pastel sketch on white paper of a busy café on a main shopping street with outdoor seating, red awning, and people watching the world go by. Vibrant coral and terracotta tones, lively street energy.',
    },
    {
      id: 'bar-chiaia-sera',
      name: 'Bar Chiaia Sera',
      kind: 'bar',
      neighbourhood: 'Chiaia',
      real: false,
      characterId: 'francesco-sorrentino',
      imagePrompt: 'Soft pastel sketch on white paper of a chic aperitivo bar with low lighting, leather stools, and shelves of colorful bottles. Deep amber and ruby tones, early evening warmth, sophisticated and inviting.',
    },
    {
      id: 'bar-piedigrotta',
      name: 'Bar Piedigrotta',
      kind: 'bar',
      neighbourhood: 'Chiaia',
      real: false,
      characterId: 'elena-vitale',
      imagePrompt: 'Soft pastel sketch on white paper of a seaside bar with blue shutters, white walls, and a view of Mergellina port. Azure and white tones, salty sea light, breezy and coastal.',
    },

    // BAKERIES (4)
    {
      id: 'pasticceria-poppella',
      name: 'Pasticceria Poppella',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'ciro-poppella',
      imagePrompt: 'Soft pastel sketch on white paper of a beloved pasticceria with glass cases full of fiocchi di neve and sfogliatelle, white-tiled walls, and customers queuing at the counter. Sweet cream and golden tones, sugary morning light, warm and tempting.',
    },
    {
      id: 'forno-attanasio',
      name: 'Antico Forno Attanasio',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'maria-attanasio',
      imagePrompt: 'Soft pastel sketch on white paper of a historic bakery with a wood-fired oven visible in the back, golden sfogliatelle and code di aragosta piled high. Rich butterscotch and amber tones, flour-dusted warmth, aromatic and traditional.',
    },
    {
      id: 'pasticceria-capparelli',
      name: 'Pasticceria Capparelli',
      kind: 'bakery',
      neighbourhood: 'Vomero',
      real: true,
      characterId: 'giuseppe-capparelli',
      imagePrompt: 'Soft pastel sketch on white paper of an upscale pasticceria with elegant display cases of babà, pastiera, and decorative cakes. Soft pink and gold tones, refined lighting, delicate and sophisticated.',
    },
    {
      id: 'panificio-vico',
      name: 'Panificio del Vico',
      neighbourhood: 'Spaccanapoli',
      kind: 'bakery',
      real: false,
      characterId: 'anna-greco',
      imagePrompt: 'Soft pastel sketch on white paper of a small neighborhood bread bakery with rustic loaves, taralli, and fresh focaccia in woven baskets. Warm wheat and terracotta tones, yeasty morning atmosphere, humble and authentic.',
    },

    // MARKETS (3)
    {
      id: 'mercato-pignasecca',
      name: 'Mercato della Pignasecca',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'salvatore-di-maio',
      imagePrompt: 'Soft pastel sketch on white paper of a vibrant street market with colorful produce stalls, hanging salumi, and vendors calling out. Bright tomato red, green, and yellow tones, bustling energy, lively and authentic.',
    },
    {
      id: 'mercato-antignano',
      name: 'Mercato di Antignano',
      kind: 'market',
      neighbourhood: 'Vomero',
      real: true,
      characterId: 'raffaele-bruno',
      imagePrompt: 'Soft pastel sketch on white paper of a covered neighborhood market with fish stalls, vegetable vendors, and local shoppers with bags. Cool silver and green tones, morning market light, fresh and communal.',
    },
    {
      id: 'mercato-porta-nolana',
      name: 'Mercato di Porta Nolana',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'teresa-gargiulo',
      imagePrompt: 'Soft pastel sketch on white paper of a sprawling fish and produce market near the port with octopus, clams, and lemons piled high. Briny blue-grey and citrus yellow tones, chaotic morning energy, raw and vital.',
    },

    // PIZZERIAS (3)
    {
      id: 'pizzeria-sorbillo',
      name: 'Pizzeria Gino Sorbillo',
      kind: 'pizzeria',
      neighbourhood: 'Spaccanapoli',
      real: true,
      characterId: 'gino-sorbillo',
      imagePrompt: 'Soft pastel sketch on white paper of a famous pizzeria with a wood-fired oven blazing, pizza makers tossing dough, and customers lined up outside. Warm flame orange and charcoal tones, smoky heat, legendary and bustling.',
    },
    {
      id: 'pizzeria-michele',
      name: "L'Antica Pizzeria da Michele",
      kind: 'pizzeria',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'paolo-condurro',
      imagePrompt: 'Soft pastel sketch on white paper of an iconic minimalist pizzeria with marble tables, simple décor, and perfect margherita pizzas being served. Classic red, white and green tones, no-frills authenticity, timeless and pure.',
    },
    {
      id: 'pizzeria-starita',
      name: 'Pizzeria Starita',
      kind: 'pizzeria',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'antonio-starita',
      imagePrompt: 'Soft pastel sketch on white paper of a historic pizzeria with vintage photos on the walls, a tiled oven, and the famous pizza fritta being prepared. Golden fried tones and deep red, nostalgic warmth, traditional and proud.',
    },

    // RESTAURANTS (2)
    {
      id: 'trattoria-nennella',
      name: 'Trattoria Nennella',
      kind: 'trattoria',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'nennella-russo',
      imagePrompt: 'Soft pastel sketch on white paper of a chaotic family-style trattoria with communal tables, hanging garlic and peppers, and steaming plates of pasta. Rustic red and warm wood tones, boisterous energy, authentic and homey.',
    },
    {
      id: 'ristorante-palazzo-petrucci',
      name: 'Palazzo Petrucci',
      kind: 'ristorante',
      neighbourhood: 'Chiaia',
      real: true,
      characterId: 'luca-petrucci',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant restaurant with high ceilings, modern artwork, and views of Piazza San Domenico Maggiore. Sophisticated grey and ivory tones, refined lighting, upscale and contemporary.',
    },

    // SPECIALTY FOOD (2)
    {
      id: 'salumeria-upnea',
      name: 'Salumeria Upnea',
      kind: 'salumeria',
      neighbourhood: 'Chiaia',
      real: true,
      characterId: 'vincenzo-ricci',
      imagePrompt: 'Soft pastel sketch on white paper of a gourmet deli with hanging prosciutto, wheels of cheese, and bottles of wine lining the shelves. Rich burgundy and aged gold tones, aromatic and curated, artisanal and refined.',
    },
    {
      id: 'friggitoria-vico',
      name: 'Friggitoria del Vico',
      kind: 'friggitoria',
      neighbourhood: 'Spaccanapoli',
      real: false,
      characterId: 'peppe-conte',
      imagePrompt: 'Soft pastel sketch on white paper of a tiny street-food shop with golden fried foods in display cases—arancini, frittatine, and zeppole. Crispy golden and oil-shimmer tones, sizzling atmosphere, street-food authenticity.',
    },

    // LANDMARKS & CULTURAL (5)
    {
      id: 'duomo-napoli',
      name: 'Duomo di Napoli',
      kind: 'church',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'padre-domenico',
      imagePrompt: 'Soft pastel sketch on white paper of a grand cathedral with baroque façade, ornate interior visible through open doors, and the Chapel of San Gennaro. Rich ecclesiastical gold and deep blue tones, sacred light, majestic and devotional.',
    },
    {
      id: 'castel-ovo',
      name: "Castel dell'Ovo",
      kind: 'landmark',
      neighbourhood: 'Chiaia',
      real: true,
      characterId: 'marco-ferri',
      imagePrompt: 'Soft pastel sketch on white paper of an ancient seaside castle on a promontory with waves lapping below and the bay stretching beyond. Stone grey and Mediterranean blue tones, historic grandeur, atmospheric and romantic.',
    },
    {
      id: 'villa-floridiana',
      name: 'Villa Floridiana',
      kind: 'park',
      neighbourhood: 'Vomero',
      real: true,
      characterId: 'giulia-martino',
      imagePrompt: 'Soft pastel sketch on white paper of a neoclassical villa surrounded by lush gardens, palm trees, and panoramic views of the bay. Fresh green and sky blue tones, peaceful afternoon light, elegant and serene.',
    },
    {
      id: 'piazza-bellini',
      name: 'Piazza Bellini',
      kind: 'piazza',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'davide-amato',
      imagePrompt: 'Soft pastel sketch on white paper of a lively square with ancient Greek walls exposed, outdoor café tables, and young people gathering. Warm evening amber and stone grey tones, bohemian energy, cultural and social.',
    },
    {
      id: 'certosa-san-martino',
      name: 'Certosa di San Martino',
      kind: 'church',
      neighbourhood: 'Vomero',
      real: true,
      characterId: 'suor-caterina',
      imagePrompt: 'Soft pastel sketch on white paper of a hilltop monastery with baroque cloisters, majolica tiles, and sweeping views over the city. Pure white and cobalt blue tones, contemplative light, peaceful and breathtaking.',
    },

    // WINE BARS & APERITIVO (2)
    {
      id: 'enoteca-belledonne',
      name: 'Enoteca Belledonne',
      kind: 'enoteca',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'michele-improta',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy wine bar with bottles lining brick walls, small tables with cheese boards, and warm candlelight. Deep wine red and amber tones, intimate evening glow, sophisticated and welcoming.',
    },
    {
      id: 'cammarota-spritz',
      name: 'Cammarota Spritz',
      kind: 'bar',
      neighbourhood: 'Chiaia',
      real: true,
      characterId: 'claudia-cammarota',
      imagePrompt: 'Soft pastel sketch on white paper of a trendy aperitivo spot with orange Aperol spritzes on the bar, stylish crowd, and waterfront terrace. Bright orange and sunset pink tones, golden hour light, chic and social.',
    },

    // BOOKSHOP (1)
    {
      id: 'libreria-dante-descartes',
      name: 'Libreria Dante & Descartes',
      kind: 'bookshop',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'beatrice-longo',
      imagePrompt: 'Soft pastel sketch on white paper of an intimate bookshop with floor-to-ceiling shelves, philosophy and literature sections, and a reading corner. Warm sepia and leather-bound tones, quiet scholarly light, intellectual and cozy.',
    },

    // PHARMACY (1)
    {
      id: 'farmacia-centrale',
      name: 'Farmacia Centrale',
      kind: 'pharmacy',
      neighbourhood: 'Vomero',
      real: false,
      characterId: 'dottoressa-capasso',
      imagePrompt: 'Soft pastel sketch on white paper of a modern pharmacy with white shelves, green cross sign, and a helpful pharmacist at the counter. Clean white and medical green tones, professional lighting, practical and reassuring.',
    },

    // TRANSPORTATION HUB (1)
    {
      id: 'stazione-centrale',
      name: 'Stazione Napoli Centrale',
      kind: 'station',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'roberto-albano',
      imagePrompt: 'Soft pastel sketch on white paper of a grand railway station with vaulted ceilings, departure boards, and travelers with luggage moving through. Industrial grey and travel-worn tones, transient energy, bustling gateway.',
    },

    // UNIQUE NAPLES CHARACTER (3)
    {
      id: 'spaccanapoli-street',
      name: 'Via Spaccanapoli',
      kind: 'street',
      neighbourhood: 'Spaccanapoli',
      real: true,
      characterId: 'nonna-assunta',
      imagePrompt: 'Soft pastel sketch on white paper of the famous narrow street that splits the ancient city, lined with shops, churches, and laundry hanging overhead. Ochre and terracotta building tones, dramatic perspective, quintessentially Neapolitan.',
    },
    {
      id: 'gay-odin',
      name: 'Gay-Odin',
      kind: 'chocolatier',
      neighbourhood: 'Chiaia',
      real: true,
      characterId: 'mario-magliulo',
      imagePrompt: 'Soft pastel sketch on white paper of a historic chocolate shop with art nouveau details, displays of Vesuvio-shaped chocolates and dark chocolate bars. Rich cocoa brown and elegant gold tones, decadent lighting, luxurious and traditional.',
    },
    {
      id: 'presepi-san-gregorio',
      name: 'Via San Gregorio Armeno',
      kind: 'artisan-street',
      neighbourhood: 'Spaccanapoli',
      real: true,
      characterId: 'maestro-ferrigno',
      imagePrompt: 'Soft pastel sketch on white paper of a magical street filled with workshops making presepi (nativity scenes), with miniature figures, lights, and craftsmen at work. Warm Christmas tones year-round, enchanting detail, artisanal wonder.',
    },
  ],
  characters: [
    {
      id: 'carmine-russo',
      name: 'Carmine Russo',
      age: 58,
      role: 'barista',
      placeId: 'bar-nilo',
      personality: ['devout Maradona fan', 'quick-witted', 'philosophical'],
      portraitPrompt: 'Pen and ink portrait on white paper of a middle-aged Neapolitan man with expressive eyes, salt-and-pepper hair, and a slight smile. Minimal watercolor wash in warm browns for his skin and a hint of blue for his work shirt. Detailed linework showing laugh lines and character.',
    },
    {
      id: 'sofia-esposito',
      name: 'Sofia Esposito',
      age: 32,
      role: 'waitress',
      placeId: 'caffe-gambrinus',
      personality: ['elegant', 'attentive', 'proud of tradition'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sophisticated young woman with pulled-back dark hair, defined features, and professional demeanor. Minimal watercolor wash in burgundy for her lips and soft beige for her uniform. Refined and graceful linework.',
    },
    {
      id: 'gennaro-de-luca',
      name: 'Gennaro De Luca',
      age: 45,
      role: 'barista',
      placeId: 'bar-mexico',
      personality: ['energetic', 'talkative', 'knows everyone'],
      portraitPrompt: 'Pen and ink portrait on white paper of an animated middle-aged man with a broad smile, receding hairline, and expressive hands. Minimal watercolor wash in warm coffee tones. Dynamic linework suggesting constant motion.',
    },
    {
      id: 'mimmo-verde',
      name: 'Mimmo Verde',
      age: 67,
      role: 'owner',
      placeId: 'caffe-del-professore',
      personality: ['scholarly', 'perfectionist', 'reserved'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly gentleman with round glasses, neat grey hair, and thoughtful expression. Minimal watercolor wash in sepia tones. Precise, careful linework suggesting quiet dignity.',
    },
    {
      id: 'lucia-romano',
      name: 'Lucia Romano',
      age: 29,
      role: 'barista',
      placeId: 'bar-vomero-alto',
      personality: ['modern', 'friendly', 'ambitious'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with contemporary style, bright eyes, and confident smile. Minimal watercolor wash in cool blues and warm peach for skin tone. Clean, modern linework.',
    },
    {
      id: 'antonio-casale',
      name: 'Antonio Casale',
      age: 52,
      role: 'barista',
      placeId: 'bar-epoca',
      personality: ['nostalgic', 'storyteller', 'meticulous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man with slicked-back hair, strong jaw, and vintage style. Minimal watercolor wash in amber and grey tones. Art deco-influenced linework.',
    },
    {
      id: 'rosa-marino',
      name: 'Rosa Marino',
      age: 41,
      role: 'owner',
      placeId: 'caffe-toledo',
      personality: ['observant', 'warm', 'business-savvy'],
      portraitPrompt: 'Pen and ink portrait on white paper of a confident woman with wavy hair, kind eyes, and practical expression. Minimal watercolor wash in coral and brown tones. Strong, capable linework.',
    },
    {
      id: 'francesco-sorrentino',
      name: 'Francesco Sorrentino',
      age: 35,
      role: 'bartender',
      placeId: 'bar-chiaia-sera',
      personality: ['sophisticated', 'charming', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a handsome man with styled dark hair, well-groomed beard, and confident gaze. Minimal watercolor wash in deep amber for his vest. Elegant, refined linework.',
    },
    {
      id: 'elena-vitale',
      name: 'Elena Vitale',
      age: 27,
      role: 'barista',
      placeId: 'bar-piedigrotta',
      personality: ['breezy', 'optimistic', 'loves the sea'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with sun-lightened hair, freckles, and bright smile. Minimal watercolor wash in azure blue and warm sand tones. Light, flowing linework.',
    },
    {
      id: 'ciro-poppella',
      name: 'Ciro Poppella',
      age: 44,
      role: 'pastry chef',
      placeId: 'pasticceria-poppella',
      personality: ['proud', 'perfectionist', 'family-oriented'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy man with flour-dusted apron, strong hands, and determined expression. Minimal watercolor wash in white and cream tones. Honest, hardworking linework.',
    },
    {
      id: 'maria-attanasio',
      name: 'Maria Attanasio',
      age: 39,
      role: 'baker',
      placeId: 'forno-attanasio',
      personality: ['traditional', 'generous', 'early riser'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust woman with hair tied back, warm smile, and capable hands. Minimal watercolor wash in golden wheat tones. Solid, nurturing linework.',
    },
    {
      id: 'giuseppe-capparelli',
      name: 'Giuseppe Capparelli',
      age: 55,
      role: 'pastry master',
      placeId: 'pasticceria-capparelli',
      personality: ['refined', 'artistic', 'exacting'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant older man with grey temples, artist hands, and focused expression. Minimal watercolor wash in soft pink and gold. Delicate, precise linework.',
    },
    {
      id: 'anna-greco',
      name: 'Anna Greco',
      age: 48,
      role: 'baker',
      placeId: 'panificio-vico',
      personality: ['motherly', 'chatty', 'knows the neighborhood'],
      portraitPrompt: 'Pen and ink portrait on white paper of a round-faced woman with kind eyes, hair in a bun, and flour on her cheek. Minimal watercolor wash in warm terracotta. Soft, comforting linework.',
    },
    {
      id: 'salvatore-di-maio',
      name: 'Salvatore Di Maio',
      age: 61,
      role: 'produce vendor',
      placeId: 'mercato-pignasecca',
      personality: ['loud', 'theatrical', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a weathered man with expressive face, work-worn hands, and booming presence. Minimal watercolor wash in earthy vegetable greens and browns. Bold, energetic linework.',
    },
    {
      id: 'raffaele-bruno',
      name: 'Raffaele Bruno',
      age: 53,
      role: 'fish vendor',
      placeId: 'mercato-antignano',
      personality: ['straightforward', 'fair', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stocky man with honest face, rolled-up sleeves, and direct gaze. Minimal watercolor wash in silver-grey and blue tones. Strong, dependable linework.',
    },
    {
      id: 'teresa-gargiulo',
      name: 'Teresa Gargiulo',
      age: 57,
      role: 'market vendor',
      placeId: 'mercato-porta-nolana',
      personality: ['tough', 'shrewd', 'protective'],
      portraitPrompt: 'Pen and ink portrait on white paper of a formidable woman with sharp eyes, strong build, and no-nonsense expression. Minimal watercolor wash in stormy blue-grey. Powerful, assertive linework.',
    },
    {
      id: 'gino-sorbillo',
      name: 'Gino Sorbillo',
      age: 49,
      role: 'pizzaiolo',
      placeId: 'pizzeria-sorbillo',
      personality: ['passionate', 'charismatic', 'ambassador of pizza'],
      portraitPrompt: 'Pen and ink portrait on white paper of a vibrant man with intense eyes, animated expression, and flour on his face. Minimal watercolor wash in warm flame orange. Dynamic, passionate linework.',
    },
    {
      id: 'paolo-condurro',
      name: 'Paolo Condurro',
      age: 42,
      role: 'pizzaiolo',
      placeId: 'pizzeria-michele',
      personality: ['purist', 'focused', 'minimalist'],
      portraitPrompt: 'Pen and ink portrait on white paper of a serious man with clear eyes, short hair, and concentrated expression. Minimal watercolor wash in classic red and white. Clean, essential linework.',
    },
    {
      id: 'antonio-starita',
      name: 'Antonio Starita',
      age: 68,
      role: 'master pizzaiolo',
      placeId: 'pizzeria-starita',
      personality: ['legendary', 'innovative', 'teacher'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished elderly man with wise eyes, white hair, and masterful hands. Minimal watercolor wash in golden fried tones. Masterful, confident linework.',
    },
    {
      id: 'nennella-russo',
      name: 'Nennella Russo',
      age: 73,
      role: 'owner',
      placeId: 'trattoria-nennella',
      personality: ['fiery', 'matriarchal', 'unforgettable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a spirited elderly woman with sharp eyes, expressive mouth, and commanding presence. Minimal watercolor wash in rustic red. Bold, characterful linework.',
    },
    {
      id: 'luca-petrucci',
      name: 'Luca Petrucci',
      age: 41,
      role: 'chef',
      placeId: 'ristorante-palazzo-petrucci',
      personality: ['innovative', 'precise', 'respectful of tradition'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined chef with intense gaze, clean chef whites, and artistic sensibility. Minimal watercolor wash in sophisticated grey. Contemporary, elegant linework.',
    },
    {
      id: 'vincenzo-ricci',
      name: 'Vincenzo Ricci',
      age: 56,
      role: 'salumiere',
      placeId: 'salumeria-upnea',
      personality: ['connoisseur', 'patient', 'educator'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man with silver beard, apron, and knowledgeable expression. Minimal watercolor wash in burgundy and aged gold. Refined, artisanal linework.',
    },
    {
      id: 'peppe-conte',
      name: 'Peppe Conte',
      age: 34,
      role: 'friggitore',
      placeId: 'friggitoria-vico',
      personality: ['jovial', 'fast-moving', 'street-smart'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with quick smile, oil-stained apron, and energetic demeanor. Minimal watercolor wash in golden fried tones. Quick, lively linework.',
    },
    {
      id: 'padre-domenico',
      name: 'Padre Domenico',
      age: 64,
      role: 'priest',
      placeId: 'duomo-napoli',
      personality: ['devout', 'scholarly', 'compassionate'],
      portraitPrompt: 'Pen and ink portrait on white paper of a gentle elderly priest with kind eyes, clerical collar, and peaceful expression. Minimal watercolor wash in ecclesiastical gold and blue. Serene, devotional linework.',
    },
    {
      id: 'marco-ferri',
      name: 'Marco Ferri',
      age: 38,
      role: 'tour guide',
      placeId: 'castel-ovo',
      personality: ['knowledgeable', 'enthusiastic', 'storyteller'],
      portraitPrompt: 'Pen and ink portrait on white paper of an animated man with gesturing hands, bright eyes, and engaging smile. Minimal watercolor wash in stone grey and sea blue. Expressive, engaging linework.',
    },
    {
      id: 'giulia-martino',
      name: 'Giulia Martino',
      age: 31,
      role: 'gardener',
      placeId: 'villa-floridiana',
      personality: ['peaceful', 'nature-loving', 'patient'],
      portraitPrompt: 'Pen and ink portrait on white paper of a serene young woman with natural beauty, garden gloves, and content expression. Minimal watercolor wash in fresh green tones. Gentle, flowing linework.',
    },
    {
      id: 'davide-amato',
      name: 'Davide Amato',
      age: 26,
      role: 'street musician',
      placeId: 'piazza-bellini',
      personality: ['artistic', 'bohemian', 'idealistic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with tousled hair, guitar strap visible, and dreamy expression. Minimal watercolor wash in warm amber evening tones. Romantic, artistic linework.',
    },
    {
      id: 'suor-caterina',
      name: 'Suor Caterina',
      age: 47,
      role: 'nun',
      placeId: 'certosa-san-martino',
      personality: ['contemplative', 'wise', 'welcoming'],
      portraitPrompt: 'Pen and ink portrait on white paper of a serene nun with habit, peaceful eyes, and gentle smile. Minimal watercolor wash in pure white and soft blue. Tranquil, spiritual linework.',
    },
    {
      id: 'michele-improta',
      name: 'Michele Improta',
      age: 43,
      role: 'sommelier',
      placeId: 'enoteca-belledonne',
      personality: ['passionate', 'knowledgeable', 'welcoming'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warm man with wine-stained fingers, intelligent eyes, and inviting smile. Minimal watercolor wash in deep wine red. Sophisticated, hospitable linework.',
    },
    {
      id: 'claudia-cammarota',
      name: 'Claudia Cammarota',
      age: 33,
      role: 'owner',
      placeId: 'cammarota-spritz',
      personality: ['trendy', 'social', 'entrepreneurial'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stylish woman with fashionable hair, bright lipstick, and confident smile. Minimal watercolor wash in orange Aperol and sunset pink. Chic, modern linework.',
    },
    {
      id: 'beatrice-longo',
      name: 'Beatrice Longo',
      age: 37,
      role: 'bookseller',
      placeId: 'libreria-dante-descartes',
      personality: ['intellectual', 'introverted', 'passionate about literature'],
      portraitPrompt: 'Pen and ink portrait on white paper of a thoughtful woman with glasses, book in hand, and quiet intelligence. Minimal watercolor wash in sepia and leather tones. Detailed, literary linework.',
    },
    {
      id: 'dottoressa-capasso',
      name: 'Dott.ssa Capasso',
      age: 44,
      role: 'pharmacist',
      placeId: 'farmacia-centrale',
      personality: ['helpful', 'professional', 'trustworthy'],
      portraitPrompt: 'Pen and ink portrait on white paper of a competent woman in white coat, neat hair, and reassuring expression. Minimal watercolor wash in medical green and white. Clean, professional linework.',
    },
    {
      id: 'roberto-albano',
      name: 'Roberto Albano',
      age: 50,
      role: 'station master',
      placeId: 'stazione-centrale',
      personality: ['organized', 'helpful', 'seen-it-all'],
      portraitPrompt: 'Pen and ink portrait on white paper of a uniformed man with authoritative but kind face, cap, and efficient demeanor. Minimal watercolor wash in railway grey and navy. Solid, dependable linework.',
    },
    {
      id: 'nonna-assunta',
      name: 'Nonna Assunta',
      age: 81,
      role: 'resident',
      placeId: 'spaccanapoli-street',
      personality: ['gossip', 'watchful', 'heart of the neighborhood'],
      portraitPrompt: 'Pen and ink portrait on white paper of a tiny elderly woman with sharp eyes, headscarf, and knowing smile. Minimal watercolor wash in faded ochre and terracotta. Character-filled, timeless linework.',
    },
    {
      id: 'mario-magliulo',
      name: 'Mario Magliulo',
      age: 59,
      role: 'chocolatier',
      placeId: 'gay-odin',
      personality: ['precise', 'proud', 'traditional craftsman'],
      portraitPrompt: 'Pen and ink portrait on white paper of a dignified man with chocolate-stained apron, meticulous expression, and artisan hands. Minimal watercolor wash in rich cocoa brown. Careful, masterful linework.',
    },
    {
      id: 'maestro-ferrigno',
      name: 'Maestro Ferrigno',
      age: 70,
      role: 'presepe artisan',
      placeId: 'presepi-san-gregorio',
      personality: ['masterful', 'patient', 'keeper of tradition'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly master craftsman with magnifying glasses, wise eyes, and delicate hands holding tiny figures. Minimal watercolor wash in warm Christmas tones. Intricate, reverent linework.',
    },
  ],
  food: [
    'pizza napoletana',
    'sfogliatella',
    'babà',
    'pastiera',
    'pasta e fagioli',
    'ragù napoletano',
    'parmigiana di melanzane',
    'friarielli',
    'pizza fritta',
    'spaghetti alle vongole',
    'impepata di cozze',
    'polpo alla luciana',
    'zeppole di San Giuseppe',
    'struffoli',
    'roccocò',
    'taralli',
    'mozzarella di bufala',
    'provolone del Monaco',
    'caprese',
    'frittatina di pasta',
    'arancini',
    'casatiello',
    'tortano',
    'pasta e patate',
    'genovese',
    "o' per e o' muss",
    'cuoppo fritto',
    'limoncello',
    'caffè sospeso',
  ],
  customs: [
    'Drinking espresso standing at the bar counter',
    'The tradition of caffè sospeso (suspended coffee for those in need)',
    'Sunday pranzo with the entire extended family',
    'Celebrating San Gennaro and the miracle of the blood',
    'Making presepi (nativity scenes) year-round on Via San Gregorio Armeno',
    'Taking the passeggiata along Via Chiaia in the evening',
    'Keeping balcony shrines to San Gennaro or the Madonna',
    'Lowering baskets from windows to receive deliveries',
    'Loud, animated conversations in the street',
    'Neighbors calling to each other from windows',
    'Beach days at Bagno Elena in summer',
    'Saturday shopping at the neighborhood market',
    'Vespa rides through impossible traffic',
    'Celebrating with sfogliatelle on special occasions',
    'Making pilgrimage to Madonna dell\'Arco',
  ],
  localTouches: [
    'Uè!',
    'Jammo!',
    'Che vvuò?',
    'Statt accuort',
    'O\'mare',
    'Guaglione/guagliona',
    'Mammeta',
    'Madonna!',
    'Vabb\'è',
    'Aiò',
    'Nu poc\'e pazienza',
    'Aggio capito',
    'Stai fresco',
    'Embè?',
    'Comme staje?',
  ],
};
