import { CityPantry } from '@/lib/types';

export const orvieto: CityPantry = {
  id: 'orvieto',
  name: 'Orvieto',
  neighbourhoods: ['Centro Storico', 'Duomo', 'Quartiere Medievale', 'Porta Maggiore'],
  places: [
    // BARS/CAFÉS (9 across neighborhoods)
    {
      id: 'caffe-montanucci',
      name: 'Caffè Montanucci',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'paolo-montanucci',
      imagePrompt: 'Soft pastel sketch on white paper of a historic Italian café with a long marble counter, vintage espresso machine gleaming in copper tones, rows of pastries under glass domes, warm amber and cream colors, morning light streaming through tall windows, textured walls with faded elegance, inviting and nostalgic atmosphere',
    },
    {
      id: 'bar-duomo',
      name: 'Bar Duomo',
      kind: 'bar',
      neighbourhood: 'Duomo',
      real: true,
      characterId: 'giulia-ferretti',
      imagePrompt: 'Soft pastel sketch on white paper of a corner café with outdoor tables facing a cathedral, white umbrellas, terracotta façade, chalkboard menu, warm ochre and sage green tones, dappled sunlight, tourists and locals mingling, welcoming morning energy, textured cobblestones',
    },
    {
      id: 'caffe-sant-angelo',
      name: "Caffè Sant'Angelo",
      kind: 'bar',
      neighbourhood: 'Quartiere Medievale',
      real: false,
      characterId: 'marco-bianchi',
      imagePrompt: 'Soft pastel sketch on white paper of a small neighborhood bar tucked under medieval stone arches, simple wooden counter, bottles of amaro on shelves, locals reading newspapers, warm sienna and burnt umber colors, intimate and traditional, morning ritual atmosphere, textured ancient walls',
    },
    {
      id: 'bar-centrale',
      name: 'Bar Centrale',
      kind: 'bar',
      neighbourhood: 'Porta Maggiore',
      real: false,
      characterId: 'alessia-romani',
      imagePrompt: 'Soft pastel sketch on white paper of a lively neighborhood bar with chrome accents, colorful aperitivo spread on the counter, Campari posters on walls, warm golden and red tones, locals chatting animatedly, inviting social atmosphere, textured plaster walls with character',
    },
    {
      id: 'caffe-della-piazza',
      name: 'Caffè della Piazza',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'roberto-tosi',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant café overlooking a main square, art deco details, polished brass fixtures, outdoor seating with wicker chairs, warm cream and gold tones, sophisticated morning crowd, inviting and refined, textured stonework',
    },
    {
      id: 'bar-del-corso',
      name: 'Bar del Corso',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'anna-grossi',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional bar along the main street, display of cornetti and pastries, vintage Lavazza sign, locals standing at counter, warm amber and coffee brown tones, authentic daily routine atmosphere, textured and welcoming',
    },
    {
      id: 'caffe-cavour',
      name: 'Caffè Cavour',
      kind: 'bar',
      neighbourhood: 'Duomo',
      real: false,
      characterId: 'stefano-marini',
      imagePrompt: 'Soft pastel sketch on white paper of a refined café with velvet banquettes, ornate mirror behind the bar, artistic coffee presentations, warm burgundy and cream tones, morning elegance, locals in conversation, inviting sophisticated atmosphere, textured details',
    },
    {
      id: 'bar-della-rupe',
      name: 'Bar della Rupe',
      kind: 'bar',
      neighbourhood: 'Quartiere Medievale',
      real: false,
      characterId: 'lorenzo-sabbatini',
      imagePrompt: 'Soft pastel sketch on white paper of a bar with panoramic views over the cliff edge, outdoor terrace with iron railings, morning light over the valley, warm terracotta and sky blue tones, breathtaking vista, inviting viewpoint atmosphere, textured stone walls',
    },
    {
      id: 'bar-sant-antonio',
      name: "Bar Sant'Antonio",
      kind: 'bar',
      neighbourhood: 'Porta Maggiore',
      real: false,
      characterId: 'francesca-mieli',
      imagePrompt: 'Soft pastel sketch on white paper of a family-run neighborhood bar, homemade cakes under glass, photos of regulars on walls, simple wooden furniture, warm honey and cream tones, genuine local atmosphere, morning gathering place, textured and authentic',
    },
    
    // BAKERIES (6 across neighborhoods)
    {
      id: 'pasticceria-adriano',
      name: 'Pasticceria Adriano',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'adriano-conti',
      imagePrompt: 'Soft pastel sketch on white paper of an artisan pastry shop with elegant display cases, tiered stands of delicate pastries, golden sfogliatelle and maritozzi, warm buttery yellow and pink tones, sweet aromas visually suggested, refined and tempting, textured details',
    },
    {
      id: 'forno-del-duomo',
      name: 'Forno del Duomo',
      kind: 'bakery',
      neighbourhood: 'Duomo',
      real: false,
      characterId: 'elena-puccini',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional bakery with wood-fired oven visible, fresh bread on wooden shelves, flour dust in the air, warm golden and wheat tones, rustic and aromatic, morning bread ritual, textured oven bricks and worn counter',
    },
    {
      id: 'panificio-moderna',
      name: 'Panificio Moderna',
      kind: 'bakery',
      neighbourhood: 'Quartiere Medievale',
      real: false,
      characterId: 'simone-neri',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood bread shop in medieval stone building, baskets of pane di Orvieto, simple wooden shelves, warm ochre and cream tones, honest and traditional, daily bread atmosphere, textured ancient doorway',
    },
    {
      id: 'pasticceria-montanari',
      name: 'Pasticceria Montanari',
      kind: 'bakery',
      neighbourhood: 'Porta Maggiore',
      real: false,
      characterId: 'carla-montanari',
      imagePrompt: 'Soft pastel sketch on white paper of a corner pastry shop with vintage tiles, trays of biscotti and torta al testo, glass jars of cookies, warm caramel and cream tones, nostalgic family bakery, inviting morning stop, textured tile work',
    },
    {
      id: 'forno-san-giovenale',
      name: 'Forno San Giovenale',
      kind: 'bakery',
      neighbourhood: 'Quartiere Medievale',
      real: false,
      characterId: 'giovanni-perugini',
      imagePrompt: 'Soft pastel sketch on white paper of an ancient bakery with vaulted tufa stone ceiling, traditional Umbrian breads, pane casereccio stacked high, warm earth and wheat tones, timeless baking tradition, aromatic and welcoming, textured stone architecture',
    },
    {
      id: 'dolci-tentazioni',
      name: 'Dolci Tentazioni',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'valentina-rossi',
      imagePrompt: 'Soft pastel sketch on white paper of a modern pastry boutique with minimalist display, artistic cakes and tarts, chocolate creations, warm rose gold and ivory tones, elegant contemporary design, tempting showcase, textured marble counter',
    },
    
    // MARKETS (3)
    {
      id: 'mercato-coperto',
      name: 'Mercato Coperto',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'mario-benedetti',
      imagePrompt: 'Soft pastel sketch on white paper of a covered market hall with iron and glass roof, stalls of fresh produce, hanging salumi, cheese wheels, warm amber light filtering through, vibrant vegetable colors, bustling morning market atmosphere, textured market architecture',
    },
    {
      id: 'mercato-contadino',
      name: 'Mercato Contadino',
      kind: 'market',
      neighbourhood: 'Porta Maggiore',
      real: false,
      characterId: 'teresa-campagnoli',
      imagePrompt: 'Soft pastel sketch on white paper of an open-air farmers market in a piazza, white tents with local produce, crates of seasonal vegetables, artisan cheeses, warm morning sunlight, earthy greens and ochres, authentic farm-to-market atmosphere, textured cobblestones',
    },
    {
      id: 'bottega-sapori-umbri',
      name: 'Bottega Sapori Umbri',
      kind: 'market',
      neighbourhood: 'Duomo',
      real: false,
      characterId: 'federico-lunardi',
      imagePrompt: 'Soft pastel sketch on white paper of a specialty food shop with walls lined with local products, truffle oil, Orvieto Classico wines, ceramic jars of lentils, hanging prosciutto, warm rustic tones, treasure trove of Umbrian flavors, textured wooden shelves',
    },
    
    // RESTAURANTS (2)
    {
      id: 'ristorante-la-grotta',
      name: 'Ristorante La Grotta',
      kind: 'ristorante',
      neighbourhood: 'Duomo',
      real: false,
      characterId: 'alberto-santini',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant restaurant carved into tufa caves, vaulted stone ceilings, white tablecloths, candlelight, warm golden and stone gray tones, romantic subterranean atmosphere, refined dining, textured ancient rock walls',
    },
    {
      id: 'ristorante-zeppelin',
      name: 'Ristorante Zeppelin',
      kind: 'ristorante',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'claudia-tiberi',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional restaurant with exposed wooden beams, copper pots on walls, checkered tablecloths, warm rustic atmosphere, Umbrian dishes being served, warm amber and terracotta tones, welcoming trattoria feeling, textured stone and wood',
    },
    
    // SPECIALTY FOOD (3)
    {
      id: 'trattoria-del-orso',
      name: "Trattoria dell'Orso",
      kind: 'trattoria',
      neighbourhood: 'Quartiere Medievale',
      real: false,
      characterId: 'bruno-matteini',
      imagePrompt: 'Soft pastel sketch on white paper of a rustic trattoria with paper tablecloths, famiglia recipes on chalkboard, wine bottles lining walls, warm burgundy and cream tones, homestyle cooking atmosphere, locals dining, textured and cozy',
    },
    {
      id: 'osteria-la-madia',
      name: 'Osteria La Madia',
      kind: 'osteria',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'luca-salvatori',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy osteria with barrel tables, hanging garlic braids, open kitchen with pots simmering, warm orange and wood tones, convivial traditional atmosphere, regional specialties visible, textured rustic details',
    },
    {
      id: 'pizzeria-charlie',
      name: 'Pizzeria Charlie',
      kind: 'pizzeria',
      neighbourhood: 'Porta Maggiore',
      real: true,
      characterId: 'carlo-fabrizi',
      imagePrompt: 'Soft pastel sketch on white paper of a casual pizzeria with wood-fired oven blazing, pizzaiolo tossing dough, red and white checkered details, warm flame orange and cream tones, informal lively atmosphere, families dining, textured brick oven',
    },
    
    // CULTURAL/LANDMARK (5)
    {
      id: 'duomo-orvieto',
      name: 'Duomo di Orvieto',
      kind: 'landmark',
      neighbourhood: 'Duomo',
      real: true,
      characterId: 'don-michele-volpi',
      imagePrompt: 'Soft pastel sketch on white paper of the magnificent Gothic cathedral façade with golden mosaics, intricate rose window, striped marble columns, warm gold and cream tones with hints of blue mosaic, awe-inspiring grandeur, textured ornate details, sunlight catching gold',
    },
    {
      id: 'pozzo-san-patrizio',
      name: 'Pozzo di San Patrizio',
      kind: 'landmark',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'matteo-galeotti',
      imagePrompt: 'Soft pastel sketch on white paper of the famous well with double helix staircases spiraling down, natural light filtering into depths, Renaissance engineering marvel, warm stone gray and moss green tones, mysterious atmospheric depths, textured ancient stonework',
    },
    {
      id: 'chiesa-san-giovenale',
      name: 'Chiesa di San Giovenale',
      neighbourhood: 'Quartiere Medievale',
      kind: 'church',
      real: true,
      characterId: 'suor-beatrice',
      imagePrompt: 'Soft pastel sketch on white paper of a Romanesque church with simple stone bell tower, weathered façade, medieval frescoes hinted inside doorway, warm amber and stone tones, ancient spiritual atmosphere, quiet contemplation, textured worn stones',
    },
    {
      id: 'giardini-pubblici',
      name: 'Giardini Pubblici',
      kind: 'park',
      neighbourhood: 'Porta Maggiore',
      real: false,
      characterId: 'gino-marziani',
      imagePrompt: 'Soft pastel sketch on white paper of public gardens on cliff edge with panoramic valley views, pine trees, benches, children playing, warm green and sky blue tones, peaceful afternoon atmosphere, textured foliage and distant landscape',
    },
    {
      id: 'piazza-del-popolo',
      name: 'Piazza del Popolo',
      kind: 'piazza',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'lucia-moretti',
      imagePrompt: 'Soft pastel sketch on white paper of the main square with Palazzo del Popolo tower, outdoor café tables, people strolling, warm golden afternoon light, ochre and cream building tones, social heart of city, textured medieval architecture',
    },
    
    // SOCIAL/EVENING (3)
    {
      id: 'enoteca-al-pozzo',
      name: 'Enoteca Al Pozzo',
      kind: 'enoteca',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'davide-piccioni',
      imagePrompt: 'Soft pastel sketch on white paper of a wine bar with floor-to-ceiling bottles, oak barrels, wine glasses catching light, warm ruby and amber tones, intimate evening atmosphere, cheese and salumi boards, textured brick vaulting',
    },
    {
      id: 'libreria-del-duomo',
      name: 'Libreria del Duomo',
      kind: 'bookshop',
      neighbourhood: 'Duomo',
      real: false,
      characterId: 'elisa-bruni',
      imagePrompt: 'Soft pastel sketch on white paper of an independent bookshop with floor-to-ceiling shelves, reading nook by window, stacks of Italian literature, warm sepia and cream tones, quiet intellectual atmosphere, afternoon reading light, textured old wood',
    },
    {
      id: 'vineria-del-corso',
      name: 'Vineria del Corso',
      kind: 'enoteca',
      neighbourhood: 'Quartiere Medievale',
      real: false,
      characterId: 'tommaso-fiorentini',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy wine bar in medieval cellar, stone arches, candlelit tables, local Orvieto wines displayed, warm amber and burgundy tones, romantic evening atmosphere, textured tufa stone walls',
    },
    
    // PRACTICAL (2)
    {
      id: 'farmacia-centrale',
      name: 'Farmacia Centrale',
      kind: 'pharmacy',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'dottoressa-martini',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional pharmacy with wooden cabinets, glass bottles of herbs, antique scales, vintage ceramic jars, warm green and cream tones, trusted neighborhood health stop, textured old-world charm',
    },
    {
      id: 'funicolare',
      name: 'Funicolare di Orvieto',
      kind: 'transport',
      neighbourhood: 'Porta Maggiore',
      real: true,
      characterId: 'giuseppe-roscini',
      imagePrompt: 'Soft pastel sketch on white paper of the funicular station with cable car ascending cliff, modern and historic elements, views over countryside, warm steel blue and cream tones, engineering marvel, connection to city above, textured rock face',
    },
    
    // CITY CHARACTER (3)
    {
      id: 'bottega-michelangeli',
      name: 'Bottega Michelangeli',
      kind: 'shop',
      neighbourhood: 'Duomo',
      real: true,
      characterId: 'pietro-michelangeli',
      imagePrompt: 'Soft pastel sketch on white paper of an artisan ceramics workshop with hand-painted majolica pottery, colorful Orvieto designs, potter at wheel, warm terracotta and cobalt blue tones, artistic tradition alive, textured clay and glazes',
    },
    {
      id: 'cantina-foresi',
      name: 'Cantina Foresi',
      kind: 'cantina',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'maurizio-foresi',
      imagePrompt: 'Soft pastel sketch on white paper of a historic wine cellar carved in tufa caves, barrels aging, bottles of Orvieto Classico, tasting counter, warm gold and stone tones, centuries of winemaking tradition, textured volcanic rock walls',
    },
    {
      id: 'teatro-mancinelli',
      name: 'Teatro Luigi Mancinelli',
      kind: 'theater',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'irene-vitali',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant 19th-century theater interior with red velvet seats, ornate balconies, crystal chandeliers, warm crimson and gold tones, cultural heart of city, evening performance atmosphere, textured baroque details',
    },
  ],
  
  characters: [
    {
      id: 'paolo-montanucci',
      name: 'Paolo Montanucci',
      age: 58,
      role: 'barista',
      placeId: 'caffe-montanucci',
      personality: ['traditional', 'knowledgeable', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man in his late fifties with silver hair, mustache, wearing a white shirt and black vest, confident knowing expression, minimal sepia watercolor wash, skilled hands suggesting decades of coffee craft, detailed facial lines showing character',
    },
    {
      id: 'giulia-ferretti',
      name: 'Giulia Ferretti',
      age: 29,
      role: 'barista',
      placeId: 'bar-duomo',
      personality: ['friendly', 'energetic', 'multilingual'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with short dark hair, bright smile, modern barista apron, welcoming expression, minimal warm watercolor wash, confident and open demeanor, detailed expressive eyes',
    },
    {
      id: 'marco-bianchi',
      name: 'Marco Bianchi',
      age: 67,
      role: 'proprietor',
      placeId: 'caffe-sant-angelo',
      personality: ['gruff', 'loyal', 'observant'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly man with weathered face, deep-set eyes, thick eyebrows, wearing a cardigan, serious but kind expression, minimal gray watercolor wash, hands folded, detailed wrinkles telling stories',
    },
    {
      id: 'alessia-romani',
      name: 'Alessia Romani',
      age: 35,
      role: 'barista',
      placeId: 'bar-centrale',
      personality: ['chatty', 'warm', 'gossip'],
      portraitPrompt: 'Pen and ink portrait on white paper of a vivacious woman with curly hair pulled back, expressive face mid-laugh, colorful scarf, animated gestures suggested, minimal coral watercolor wash, warm personality radiating, detailed smile lines',
    },
    {
      id: 'roberto-tosi',
      name: 'Roberto Tosi',
      age: 42,
      role: 'owner',
      placeId: 'caffe-della-piazza',
      personality: ['sophisticated', 'cultured', 'perfectionist'],
      portraitPrompt: 'Pen and ink portrait on white paper of a well-groomed man in his forties with styled hair, pressed shirt, refined features, discerning expression, minimal cool watercolor wash, attention to detail evident, detailed precise lines',
    },
    {
      id: 'anna-grossi',
      name: 'Anna Grossi',
      age: 51,
      role: 'barista',
      placeId: 'bar-del-corso',
      personality: ['efficient', 'no-nonsense', 'reliable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy woman with hair in practical bun, strong features, capable hands, direct gaze, minimal warm watercolor wash, dependable presence, detailed character in face',
    },
    {
      id: 'stefano-marini',
      name: 'Stefano Marini',
      age: 33,
      role: 'barista',
      placeId: 'caffe-cavour',
      personality: ['artistic', 'passionate', 'meticulous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with artistic bearing, thoughtful expression, gentle eyes, casual elegance, minimal indigo watercolor wash, creative spirit visible, detailed sensitive features',
    },
    {
      id: 'lorenzo-sabbatini',
      name: 'Lorenzo Sabbatini',
      age: 44,
      role: 'owner',
      placeId: 'bar-della-rupe',
      personality: ['contemplative', 'philosophical', 'welcoming'],
      portraitPrompt: 'Pen and ink portrait on white paper of a bearded man with kind eyes, relaxed posture, weathered outdoor skin, peaceful expression, minimal earth-tone watercolor wash, connection to landscape, detailed textured beard',
    },
    {
      id: 'francesca-mieli',
      name: 'Francesca Mieli',
      age: 38,
      role: 'owner',
      placeId: 'bar-sant-antonio',
      personality: ['maternal', 'generous', 'community-minded'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warm-faced woman with soft features, caring smile, flour on apron, nurturing presence, minimal rose watercolor wash, hands busy with care, detailed gentle expression',
    },
    {
      id: 'adriano-conti',
      name: 'Adriano Conti',
      age: 55,
      role: 'pastry chef',
      placeId: 'pasticceria-adriano',
      personality: ['precise', 'artistic', 'demanding'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished pastry chef with serious expression, chef whites, focused intense eyes, minimal vanilla watercolor wash, artistic temperament visible, detailed precise features showing concentration',
    },
    {
      id: 'elena-puccini',
      name: 'Elena Puccini',
      age: 47,
      role: 'baker',
      placeId: 'forno-del-duomo',
      personality: ['strong', 'traditional', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust woman with flour in hair, rolled-up sleeves, strong forearms, honest face, minimal wheat-tone watercolor wash, generations of baking in her bearing, detailed work-worn hands',
    },
    {
      id: 'simone-neri',
      name: 'Simone Neri',
      age: 31,
      role: 'baker',
      placeId: 'panificio-moderna',
      personality: ['dedicated', 'humble', 'early-riser'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with tired but satisfied eyes, simple work clothes, flour-dusted, genuine smile, minimal warm watercolor wash, honest labor evident, detailed hands shaping dough',
    },
    {
      id: 'carla-montanari',
      name: 'Carla Montanari',
      age: 63,
      role: 'pastry maker',
      placeId: 'pasticceria-montanari',
      personality: ['nostalgic', 'sweet', 'grandmotherly'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly woman with soft wrinkles, wire-rimmed glasses, hair in neat bun, gentle smile, minimal lavender watercolor wash, recipes in her memory, detailed loving expression',
    },
    {
      id: 'giovanni-perugini',
      name: 'Giovanni Perugini',
      age: 59,
      role: 'master baker',
      placeId: 'forno-san-giovenale',
      personality: ['traditional', 'gruff', 'skilled'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stocky man with powerful build, gray stubble, serious expression, flour everywhere, minimal ochre watercolor wash, ancient techniques in his hands, detailed weathered face',
    },
    {
      id: 'valentina-rossi',
      name: 'Valentina Rossi',
      age: 27,
      role: 'pastry chef',
      placeId: 'dolci-tentazioni',
      personality: ['innovative', 'perfectionist', 'Instagram-savvy'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stylish young woman with modern chef attire, creative expression, confident smile, minimal rose-gold watercolor wash, contemporary artisan spirit, detailed expressive features',
    },
    {
      id: 'mario-benedetti',
      name: 'Mario Benedetti',
      age: 71,
      role: 'produce vendor',
      placeId: 'mercato-coperto',
      personality: ['boisterous', 'humorous', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a jovial elderly man with ruddy cheeks, cap, loud laugh, suspenders, minimal green watercolor wash, lifetime at the market, detailed character-filled face',
    },
    {
      id: 'teresa-campagnoli',
      name: 'Teresa Campagnoli',
      age: 54,
      role: 'farmer',
      placeId: 'mercato-contadino',
      personality: ['earthy', 'honest', 'hardworking'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sun-weathered woman with strong hands, headscarf, direct gaze, soil under nails, minimal earth-tone watercolor wash, connection to land, detailed work-hardened features',
    },
    {
      id: 'federico-lunardi',
      name: 'Federico Lunardi',
      age: 45,
      role: 'shop owner',
      placeId: 'bottega-sapori-umbri',
      personality: ['knowledgeable', 'passionate', 'educator'],
      portraitPrompt: 'Pen and ink portrait on white paper of a enthusiastic man gesturing while explaining, intelligent eyes, casual elegance, minimal wine-red watercolor wash, love of regional products evident, detailed animated expression',
    },
    {
      id: 'alberto-santini',
      name: 'Alberto Santini',
      age: 52,
      role: 'chef',
      placeId: 'ristorante-la-grotta',
      personality: ['refined', 'creative', 'ambitious'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished chef with chef whites, salt-and-pepper hair, intense creative gaze, minimal gray watercolor wash, culinary mastery suggested, detailed refined features',
    },
    {
      id: 'claudia-tiberi',
      name: 'Claudia Tiberi',
      age: 39,
      role: 'restaurant owner',
      placeId: 'ristorante-zeppelin',
      personality: ['welcoming', 'organized', 'family-oriented'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warm woman with pulled-back hair, elegant but practical dress, gracious smile, minimal amber watercolor wash, hospitality in her bearing, detailed kind expression',
    },
    {
      id: 'bruno-matteini',
      name: 'Bruno Matteini',
      age: 68,
      role: 'chef-owner',
      placeId: 'trattoria-del-orso',
      personality: ['gruff', 'authentic', 'uncompromising'],
      portraitPrompt: 'Pen and ink portrait on white paper of a burly man with stained apron, stubborn jaw, serious eyes, traditional bearing, minimal burgundy watercolor wash, old recipes in his soul, detailed rugged face',
    },
    {
      id: 'luca-salvatori',
      name: 'Luca Salvatori',
      age: 41,
      role: 'chef',
      placeId: 'osteria-la-madia',
      personality: ['jovial', 'storyteller', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a friendly man with open expression, cooking stains on shirt, warm smile, minimal orange watercolor wash, convivial spirit, detailed laugh lines and expressive face',
    },
    {
      id: 'carlo-fabrizi',
      name: 'Carlo Fabrizi',
      age: 36,
      role: 'pizzaiolo',
      placeId: 'pizzeria-charlie',
      personality: ['energetic', 'skilled', 'entertaining'],
      portraitPrompt: 'Pen and ink portrait on white paper of a muscular man with flour on forearms, confident grin, bandana, pizza peel suggested, minimal red watercolor wash, showmanship and skill, detailed strong features',
    },
    {
      id: 'don-michele-volpi',
      name: 'Don Michele Volpi',
      age: 64,
      role: 'priest',
      placeId: 'duomo-orvieto',
      personality: ['learned', 'gentle', 'art-lover'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished priest with kind eyes, clerical collar, intellectual bearing, peaceful expression, minimal gold watercolor wash, spiritual depth, detailed contemplative face',
    },
    {
      id: 'matteo-galeotti',
      name: 'Matteo Galeotti',
      age: 28,
      role: 'tour guide',
      placeId: 'pozzo-san-patrizio',
      personality: ['enthusiastic', 'knowledgeable', 'dramatic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with expressive gestures, bright eyes, casual professional attire, engaging smile, minimal stone-gray watercolor wash, passion for history, detailed animated features',
    },
    {
      id: 'suor-beatrice',
      name: 'Suor Beatrice',
      age: 72,
      role: 'nun',
      placeId: 'chiesa-san-giovenale',
      personality: ['serene', 'wise', 'devoted'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly nun with habit, peaceful aged face, deep spiritual eyes, gentle smile, minimal pale blue watercolor wash, lifetime of prayer, detailed tranquil expression',
    },
    {
      id: 'gino-marziani',
      name: 'Gino Marziani',
      age: 76,
      role: 'gardener',
      placeId: 'giardini-pubblici',
      personality: ['patient', 'observant', 'gentle'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly man with sun hat, weathered kind face, soil on hands, peaceful demeanor, minimal green watercolor wash, decades tending gardens, detailed wise gentle features',
    },
    {
      id: 'lucia-moretti',
      name: 'Lucia Moretti',
      age: 43,
      role: 'street artist',
      placeId: 'piazza-del-popolo',
      personality: ['bohemian', 'observant', 'social'],
      portraitPrompt: 'Pen and ink portrait on white paper of an artistic woman with flowing scarf, paint on fingers, observant eyes, creative spirit, minimal ochre watercolor wash, sketching the piazza, detailed expressive artistic features',
    },
    {
      id: 'davide-piccioni',
      name: 'Davide Piccioni',
      age: 37,
      role: 'sommelier',
      placeId: 'enoteca-al-pozzo',
      personality: ['sophisticated', 'passionate', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined man with wine glass, discerning expression, sommelier attire, minimal ruby watercolor wash, wine expertise evident, detailed contemplative tasting expression',
    },
    {
      id: 'elisa-bruni',
      name: 'Elisa Bruni',
      age: 32,
      role: 'bookseller',
      placeId: 'libreria-del-duomo',
      personality: ['literary', 'introverted', 'recommender'],
      portraitPrompt: 'Pen and ink portrait on white paper of a thoughtful woman with glasses, book in hand, intelligent eyes, casual cardigan, minimal sepia watercolor wash, love of literature, detailed gentle intellectual features',
    },
    {
      id: 'tommaso-fiorentini',
      name: 'Tommaso Fiorentini',
      age: 49,
      role: 'wine bar owner',
      placeId: 'vineria-del-corso',
      personality: ['romantic', 'poetic', 'wine-expert'],
      portraitPrompt: 'Pen and ink portrait on white paper of a man with salt-and-pepper beard, soulful eyes, wine-stained apron, contemplative expression, minimal burgundy watercolor wash, passion for wine, detailed thoughtful face',
    },
    {
      id: 'dottoressa-martini',
      name: 'Dottoressa Martini',
      age: 56,
      role: 'pharmacist',
      placeId: 'farmacia-centrale',
      personality: ['professional', 'caring', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a professional woman with white coat, confident caring expression, reading glasses on chain, minimal green watercolor wash, trusted health advisor, detailed reassuring features',
    },
    {
      id: 'giuseppe-roscini',
      name: 'Giuseppe Roscini',
      age: 61,
      role: 'funicular operator',
      placeId: 'funicolare',
      personality: ['reliable', 'punctual', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a uniformed man with cap, mustache, precise bearing, decades of service, minimal steel-blue watercolor wash, connection between worlds, detailed dignified face',
    },
    {
      id: 'pietro-michelangeli',
      name: 'Pietro Michelangeli',
      age: 58,
      role: 'master ceramist',
      placeId: 'bottega-michelangeli',
      personality: ['artistic', 'traditional', 'meticulous'],
      portraitPrompt: 'Pen and ink portrait on white paper of an artisan with clay on hands, focused intense expression, artist smock, minimal cobalt watercolor wash, centuries of tradition, detailed skilled craftsman features',
    },
    {
      id: 'maurizio-foresi',
      name: 'Maurizio Foresi',
      age: 53,
      role: 'winemaker',
      placeId: 'cantina-foresi',
      personality: ['traditional', 'proud', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man with wine-stained hands, vintner apron, knowing smile, minimal gold watercolor wash, generations of winemaking, detailed confident features',
    },
    {
      id: 'irene-vitali',
      name: 'Irene Vitali',
      age: 34,
      role: 'theater director',
      placeId: 'teatro-mancinelli',
      personality: ['dramatic', 'passionate', 'visionary'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant woman with expressive gestures, artistic bearing, intense creative eyes, minimal crimson watercolor wash, theatrical spirit, detailed passionate animated features',
    },
  ],
  
  food: [
    'umbrichelli al tartufo',
    'palomba alla ghiotta',
    'coniglio in porchetta',
    'torta al testo',
    'cinghiale in umido',
    'lenticchie di Castelluccio',
    'salumi umbri',
    'pecorino stagionato',
    'bruschetta al tartufo nero',
    'pane casereccio',
    'pappardelle al cinghiale',
    'strangozzi',
    'biscotto di Orvieto',
    'acquacotta',
    'fagioli con le cotiche',
    'porchetta',
    'piccione arrosto',
  ],
  
  customs: [
    'the passeggiata along Corso Cavour at sunset',
    'attending Mass at the Duomo on feast days',
    'truffle hunting in autumn in nearby woods',
    'wine tasting in the tufa caves',
    'celebrating Corpus Domini with the cathedral procession',
    'taking the funicolare up from the train station',
    'shopping at Thursday morning market',
    'aperitivo in the piazza before dinner',
    'Sunday lunch lasting hours with family',
    'visiting the Pozzo di San Patrizio for good luck',
    'buying fresh bread twice daily',
    'the evening stroll to see the illuminated Duomo',
  ],
  
  localTouches: [
    'beh! - well!, expression of surprise',
    'aho - hey, attention-getter',
    'magari - if only, I wish',
    'allora - so, well then',
    'dai - come on',
    'piano piano - slowly, carefully',
    'un goccetto - a little drop (of wine)',
    'fare una scampagnata - to take a countryside outing',
    'sotto la rupe - below the cliff (life below Orvieto)',
    'su in città - up in the city (on the cliff)',
    'al fresco - in the cool (caves)',
    'fà bello/brutto - the weather is nice/bad',
  ],
};
