import { CityPantry } from '@/lib/types';

export const palermo: CityPantry = {
  id: 'palermo',
  name: 'Palermo',
  neighbourhoods: ['Kalsa', 'Vucciria', 'Ballarò', 'Politeama'],
  places: [
    // BARS/CAFÉS (9 total - 3 per major neighborhood + extras)
    {
      id: 'bar-alba',
      name: 'Bar Alba',
      kind: 'bar',
      neighbourhood: 'Vucciria',
      real: true,
      characterId: 'salvatore-russo',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional Sicilian bar with marble counter, vintage espresso machine gleaming in morning light, brioche filled pastry case, locals standing at counter, warm peachy walls, textured brushstrokes, inviting atmosphere',
    },
    {
      id: 'caffe-del-kassaro',
      name: 'Caffè del Kassaro',
      kind: 'bar',
      neighbourhood: 'Kalsa',
      real: false,
      characterId: 'angela-lombardo',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant café with small round tables on cobblestones, Art Nouveau details, potted jasmine plants, view of baroque buildings, morning sunlight, soft yellows and creams, warm and welcoming',
    },
    {
      id: 'bar-touring',
      name: 'Bar Touring',
      kind: 'bar',
      neighbourhood: 'Politeama',
      real: true,
      characterId: 'roberto-di-maggio',
      imagePrompt: 'Soft pastel sketch on white paper of a bustling modern bar near the theater, glossy counter with granite prosecco, glass pastry displays, businesspeople getting morning coffee, soft grays and golds, energetic yet refined',
    },
    {
      id: 'antico-caffe-spinnato',
      name: 'Antico Caffè Spinnato',
      kind: 'bar',
      neighbourhood: 'Politeama',
      real: true,
      characterId: 'francesca-vitale',
      imagePrompt: 'Soft pastel sketch on white paper of a historic café with Belle Époque interior, mirrored walls, chandelier, elegant pastry counter filled with cassata and cannoli, ladies having coffee, soft pinks and ivory, luxurious atmosphere',
    },
    {
      id: 'bar-garibaldi',
      name: 'Bar Garibaldi',
      kind: 'bar',
      neighbourhood: 'Ballarò',
      real: false,
      characterId: 'pino-caruso',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood bar with worn tiles, locals playing cards at small tables, espresso cups clinking, street life visible through open door, earthy terracottas and faded blues, authentic and lived-in',
    },
    {
      id: 'caffe-mazzara',
      name: 'Caffè Mazzara',
      kind: 'bar',
      neighbourhood: 'Vucciria',
      real: false,
      characterId: 'lucia-messina',
      imagePrompt: 'Soft pastel sketch on white paper of a corner café with outdoor seating, colorful umbrellas, granita display case, vintage Campari posters, morning market-goers stopping by, vibrant oranges and turquoise, lively atmosphere',
    },
    {
      id: 'bar-marocco',
      name: 'Bar Marocco',
      kind: 'bar',
      neighbourhood: 'Kalsa',
      real: false,
      characterId: 'giuseppe-arena',
      imagePrompt: 'Soft pastel sketch on white paper of a simple bar with checkered floor, Formica counter, locals reading Giornale di Sicilia, pastries under glass dome, morning routine atmosphere, soft whites and café au lait tones, comforting',
    },
    {
      id: 'pasticceria-cappello',
      name: 'Pasticceria Cappello',
      kind: 'bar',
      neighbourhood: 'Politeama',
      real: true,
      characterId: 'martina-greco',
      imagePrompt: 'Soft pastel sketch on white paper of an upscale pasticceria with minimalist design, geometric pastry displays, artistic cakes in glass cases, espresso bar, modern yet warm with soft grays and rose gold accents, sophisticated',
    },

    // BAKERIES (4 total)
    {
      id: 'panificio-morello',
      name: 'Panificio Morello',
      kind: 'bakery',
      neighbourhood: 'Ballarò',
      real: false,
      characterId: 'calogero-morello',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional bakery with wood-fired oven visible in back, shelves of pane cunzato and sesame-crusted loaves, flour-dusted surfaces, warm golden light, wheaty yellows and browns, rustic charm',
    },
    {
      id: 'antico-forno-graziano',
      name: 'Antico Forno Graziano',
      kind: 'bakery',
      neighbourhood: 'Vucciria',
      real: false,
      characterId: 'rosa-graziano',
      imagePrompt: 'Soft pastel sketch on white paper of a historic bakery with vaulted stone ceiling, trays of sfincione cooling, people queuing, centuries-old atmosphere, warm terracotta and cream tones, aromatic and inviting',
    },
    {
      id: 'panificio-san-francesco',
      name: 'Panificio San Francesco',
      kind: 'bakery',
      neighbourhood: 'Kalsa',
      real: false,
      characterId: 'tommaso-rizzo',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood bakery with open windows, fresh bread cooling on racks, locals with shopping bags, sunlight streaming in, golden and ivory tones, daily life atmosphere',
    },
    {
      id: 'forno-santa-chiara',
      name: 'Forno Santa Chiara',
      kind: 'bakery',
      neighbourhood: 'Politeama',
      real: false,
      characterId: 'daniela-costa',
      imagePrompt: 'Soft pastel sketch on white paper of a modern bakery with glass frontage, artisanal loaves displayed like art, sleek interior, morning customers, soft whites and warm browns, contemporary yet traditional',
    },

    // MARKETS (3 total)
    {
      id: 'mercato-ballaro',
      name: 'Mercato di Ballarò',
      kind: 'market',
      neighbourhood: 'Ballarò',
      real: true,
      characterId: 'vito-abbate',
      imagePrompt: 'Soft pastel sketch on white paper of a vibrant street market with colorful produce stalls, hanging swordfish, vendors calling out, awnings creating striped shadows, vegetables in crates, bursts of red tomatoes and green fennel, energetic chaos',
    },
    {
      id: 'mercato-vucciria',
      name: 'Mercato della Vucciria',
      kind: 'market',
      neighbourhood: 'Vucciria',
      real: true,
      characterId: 'concetta-barone',
      imagePrompt: 'Soft pastel sketch on white paper of a historic covered market with vendors shouting prices, fresh fish on ice, citrus pyramids, hanging meats, crowds of shoppers, rich reds and oranges, Mediterranean abundance',
    },
    {
      id: 'mercato-del-capo',
      name: 'Mercato del Capo',
      kind: 'market',
      neighbourhood: 'Kalsa',
      real: true,
      characterId: 'antonio-ferrara',
      imagePrompt: 'Soft pastel sketch on white paper of a lively neighborhood market with fabric awnings, cheese and olive stalls, produce vendors, housewives with shopping carts, laundry hanging overhead, warm yellows and greens, authentic street life',
    },

    // RESTAURANTS (2 total)
    {
      id: 'trattoria-ai-cascinari',
      name: 'Trattoria ai Cascinari',
      kind: 'trattoria',
      neighbourhood: 'Ballarò',
      real: true,
      characterId: 'carmela-todaro',
      imagePrompt: 'Soft pastel sketch on white paper of a family trattoria with checkered tablecloths, walls covered in old photos, kitchen visible through beaded curtain, pasta dishes being served, warm amber lighting, intimate and homey',
    },
    {
      id: 'osteria-ballarò',
      name: 'Osteria Ballarò',
      kind: 'osteria',
      neighbourhood: 'Vucciria',
      real: false,
      characterId: 'filippo-basile',
      imagePrompt: 'Soft pastel sketch on white paper of a rustic osteria with wooden tables, wine bottles lining walls, open kitchen with sizzling pans, locals dining, soft golden candlelight, terracotta and burgundy tones, convivial atmosphere',
    },

    // SPECIALTY FOOD (3 total)
    {
      id: 'antica-focacceria-san-francesco',
      name: 'Antica Focacceria San Francesco',
      kind: 'focacceria',
      neighbourhood: 'Kalsa',
      real: true,
      characterId: 'giovanna-orlando',
      imagePrompt: 'Soft pastel sketch on white paper of a historic focacceria with marble tables, tourists and locals mixing, pani ca meusa counter, vintage tile floors, traditional atmosphere, soft greens and creams, iconic Palermo spot',
    },
    {
      id: 'friggitoria-chiluzzo',
      name: 'Friggitoria Chiluzzo',
      kind: 'friggitoria',
      neighbourhood: 'Ballarò',
      real: false,
      characterId: 'santo-lo-verde',
      imagePrompt: 'Soft pastel sketch on white paper of a street food spot with deep fryers, arancine and panelle displayed, people eating standing up, steam rising, casual atmosphere, golden fried tones and warm lighting, authentic street food',
    },
    {
      id: 'ke-palle',
      name: 'Ke Palle',
      kind: 'arancina-shop',
      neighbourhood: 'Politeama',
      real: true,
      characterId: 'marco-gentile',
      imagePrompt: 'Soft pastel sketch on white paper of a modern arancina shop with creative flavors displayed, young crowd, contemporary interior, traditional meets trendy, bright whites and saffron yellows, hip atmosphere',
    },

    // CULTURAL/LANDMARKS (6 total)
    {
      id: 'teatro-massimo',
      name: 'Teatro Massimo',
      kind: 'landmark',
      neighbourhood: 'Politeama',
      real: true,
      characterId: 'elena-bianchi',
      imagePrompt: 'Soft pastel sketch on white paper of the grand neoclassical opera house with columned facade, monumental steps, evening light, tourists taking photos, pigeons in piazza, soft golds and stone grays, majestic presence',
    },
    {
      id: 'chiesa-della-martorana',
      name: 'Chiesa della Martorana',
      kind: 'church',
      neighbourhood: 'Kalsa',
      real: true,
      characterId: 'padre-leonardo',
      imagePrompt: 'Soft pastel sketch on white paper of a Byzantine church with Arab-Norman architecture, golden mosaics visible through door, bell tower, tourists and faithful entering, soft golds and azure blues, spiritual atmosphere',
    },
    {
      id: 'cattedrale-di-palermo',
      name: 'Cattedrale di Palermo',
      kind: 'church',
      neighbourhood: 'Kalsa',
      real: true,
      characterId: 'suor-teresa',
      imagePrompt: 'Soft pastel sketch on white paper of the majestic cathedral with Norman-Gothic architecture, multiple domes, tourists and pilgrims, palm trees nearby, warm stone colors and Mediterranean light, architectural layering',
    },
    {
      id: 'giardino-garibaldi',
      name: 'Giardino Garibaldi',
      kind: 'park',
      neighbourhood: 'Kalsa',
      real: true,
      characterId: 'nunzio-palmeri',
      imagePrompt: 'Soft pastel sketch on white paper of a public garden with enormous ficus trees, elderly people on benches, children playing, dappled shade, iron fence, soft greens and sandy paths, peaceful urban oasis',
    },
    {
      id: 'piazza-pretoria',
      name: 'Piazza Pretoria',
      kind: 'piazza',
      neighbourhood: 'Kalsa',
      real: true,
      characterId: 'grazia-salamone',
      imagePrompt: 'Soft pastel sketch on white paper of a baroque square with ornate fountain of nude statues, surrounding palaces, people gathering, evening passeggiata, soft pinks and marble whites, theatrical beauty',
    },
    {
      id: 'quattro-canti',
      name: 'Quattro Canti',
      neighbourhood: 'Vucciria',
      kind: 'piazza',
      real: true,
      characterId: 'alberto-marino',
      imagePrompt: 'Soft pastel sketch on white paper of the baroque intersection with four ornate corner buildings, fountains and statues, traffic and pedestrians crossing, dramatic architecture, warm stone tones and shadows, heart of the city',
    },

    // SOCIAL/EVENING (3 total)
    {
      id: 'enoteca-picone',
      name: 'Enoteca Picone',
      kind: 'enoteca',
      neighbourhood: 'Politeama',
      real: true,
      characterId: 'alessio-picone',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant wine bar with floor-to-ceiling bottles, wooden shelving, small tables with wine glasses, soft lighting, wine-tasting atmosphere, burgundy and oak tones, sophisticated',
    },
    {
      id: 'libreria-del-mare',
      name: 'Libreria del Mare',
      kind: 'bookshop',
      neighbourhood: 'Kalsa',
      real: false,
      characterId: 'beatrice-amato',
      imagePrompt: 'Soft pastel sketch on white paper of an independent bookshop with wooden shelves, armchair reading nook, Sicilian literature section, maritime themed, soft lamplight, warm browns and navy blues, intimate cultural space',
    },
    {
      id: 'corleone-wine-bar',
      name: 'Bar del Sole',
      kind: 'aperitivo-bar',
      neighbourhood: 'Vucciria',
      real: false,
      characterId: 'davide-bruno',
      imagePrompt: 'Soft pastel sketch on white paper of a trendy aperitivo bar with outdoor seating, spritz glasses, small plates of food, young crowd socializing, evening golden hour, warm oranges and soft lighting, social energy',
    },

    // PRACTICAL (2 total)
    {
      id: 'farmacia-centrale',
      name: 'Farmacia Centrale',
      kind: 'pharmacy',
      neighbourhood: 'Politeama',
      real: false,
      characterId: 'dottoressa-silvia',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional pharmacy with green cross sign, wooden cabinets with remedies, professional counter, neighborhood helpers, clean whites and medicinal greens, trustworthy atmosphere',
    },
    {
      id: 'stazione-centrale',
      name: 'Stazione Centrale',
      kind: 'train-station',
      neighbourhood: 'Politeama',
      real: true,
      characterId: 'michele-sorrentino',
      imagePrompt: 'Soft pastel sketch on white paper of a grand railway station with vaulted ceilings, travelers with luggage, departure boards, ticket windows, pigeons, soft grays and transportation blues, gateway atmosphere',
    },

    // CITY CHARACTER (3 unique Palermo spots)
    {
      id: 'cappella-palatina',
      name: 'Cappella Palatina',
      kind: 'chapel',
      neighbourhood: 'Kalsa',
      real: true,
      characterId: 'dottor-giuseppe-randazzo',
      imagePrompt: 'Soft pastel sketch on white paper of a jewel-like chapel interior with golden Byzantine mosaics, Arab-Norman details, filtered light through small windows, visitors in awe, rich golds and lapis blues, sacred artistry',
    },
    {
      id: 'catacombe-dei-cappuccini',
      name: 'Catacombe dei Cappuccini',
      kind: 'catacombs',
      neighbourhood: 'Politeama',
      real: true,
      characterId: 'fra-massimo',
      imagePrompt: 'Soft pastel sketch on white paper of the entrance to underground corridors, stone archway, solemn visitors, cypress trees outside, mysterious atmosphere, soft grays and earth tones, memento mori presence',
    },
    {
      id: 'palazzo-abatellis',
      name: 'Palazzo Abatellis',
      kind: 'museum',
      neighbourhood: 'Kalsa',
      real: true,
      characterId: 'claudia-ferrante',
      imagePrompt: 'Soft pastel sketch on white paper of a Gothic-Catalan palace housing art museum, courtyard with arches, medieval paintings visible through windows, art students sketching, soft stone colors and gallery whites, cultural treasure',
    },
  ],
  characters: [
    {
      id: 'salvatore-russo',
      name: 'Salvatore Russo',
      age: 52,
      role: 'barista',
      placeId: 'bar-alba',
      personality: ['traditional', 'gruff-but-kind', 'opinionated'],
      portraitPrompt: 'Pen and ink portrait on white paper of a middle-aged Sicilian man with salt-and-pepper hair, strong features, slight stubble, wearing white shirt and black vest, knowing expression, minimal watercolor wash in warm sepias, detailed cross-hatching',
    },
    {
      id: 'angela-lombardo',
      name: 'Angela Lombardo',
      age: 38,
      role: 'owner',
      placeId: 'caffe-del-kassaro',
      personality: ['elegant', 'cultured', 'welcoming'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant Sicilian woman with dark hair pulled back, pearl earrings, refined features, warm smile, minimal watercolor wash in soft rose tones, graceful line work',
    },
    {
      id: 'roberto-di-maggio',
      name: 'Roberto Di Maggio',
      age: 29,
      role: 'barista',
      placeId: 'bar-touring',
      personality: ['efficient', 'ambitious', 'modern'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young Sicilian man with styled hair, clean-shaven, sharp eyes, contemporary style, minimal watercolor wash in cool grays, precise ink work',
    },
    {
      id: 'francesca-vitale',
      name: 'Francesca Vitale',
      age: 45,
      role: 'manager',
      placeId: 'antico-caffe-spinnato',
      personality: ['refined', 'detail-oriented', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sophisticated Sicilian woman with styled hair, subtle makeup, professional demeanor, elegant scarf, minimal watercolor wash in soft pinks, detailed rendering',
    },
    {
      id: 'pino-caruso',
      name: 'Pino Caruso',
      age: 67,
      role: 'owner',
      placeId: 'bar-garibaldi',
      personality: ['storyteller', 'humorous', 'neighborhood-fixture'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly Sicilian man with weathered face, deep laugh lines, flat cap, twinkle in eye, minimal watercolor wash in warm earth tones, expressive ink strokes',
    },
    {
      id: 'lucia-messina',
      name: 'Lucia Messina',
      age: 33,
      role: 'barista',
      placeId: 'caffe-mazzara',
      personality: ['chatty', 'generous', 'energetic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a vibrant Sicilian woman with curly dark hair, animated expression, bright eyes, casual style, minimal watercolor wash in sunny yellows, lively line work',
    },
    {
      id: 'giuseppe-arena',
      name: 'Giuseppe Arena',
      age: 58,
      role: 'barista',
      placeId: 'bar-marocco',
      personality: ['quiet', 'observant', 'reliable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a reserved middle-aged Sicilian man with mustache, kind eyes, simple clothing, contemplative expression, minimal watercolor wash in muted tones, gentle shading',
    },
    {
      id: 'martina-greco',
      name: 'Martina Greco',
      age: 27,
      role: 'pastry-chef',
      placeId: 'pasticceria-cappello',
      personality: ['creative', 'perfectionist', 'passionate'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young Sicilian woman with hair in neat bun, focused expression, chef whites, artistic sensibility, minimal watercolor wash in pastel tones, refined details',
    },
    {
      id: 'calogero-morello',
      name: 'Calogero Morello',
      age: 61,
      role: 'master-baker',
      placeId: 'panificio-morello',
      personality: ['skilled', 'patient', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy Sicilian man with flour-dusted hair, strong hands, warm smile, baker apron, minimal watercolor wash in wheaty golds, textured cross-hatching',
    },
    {
      id: 'rosa-graziano',
      name: 'Rosa Graziano',
      age: 55,
      role: 'baker',
      placeId: 'antico-forno-graziano',
      personality: ['matriarchal', 'no-nonsense', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust Sicilian woman with hair covered, strong features, capable expression, flour on apron, minimal watercolor wash in warm terracottas, bold ink work',
    },
    {
      id: 'tommaso-rizzo',
      name: 'Tommaso Rizzo',
      age: 42,
      role: 'baker',
      placeId: 'panificio-san-francesco',
      personality: ['friendly', 'hardworking', 'community-minded'],
      portraitPrompt: 'Pen and ink portrait on white paper of a friendly Sicilian man with dark hair, easy smile, working clothes, open expression, minimal watercolor wash in golden tones, warm line work',
    },
    {
      id: 'daniela-costa',
      name: 'Daniela Costa',
      age: 36,
      role: 'owner',
      placeId: 'forno-santa-chiara',
      personality: ['innovative', 'business-savvy', 'quality-focused'],
      portraitPrompt: 'Pen and ink portrait on white paper of a modern Sicilian woman with professional style, intelligent eyes, contemporary appearance, confident posture, minimal watercolor wash in clean tones, precise rendering',
    },
    {
      id: 'vito-abbate',
      name: 'Vito Abbate',
      age: 48,
      role: 'produce-vendor',
      placeId: 'mercato-ballaro',
      personality: ['loud', 'charismatic', 'shrewd'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust Sicilian market vendor with animated expression, calling out prices, sun-weathered skin, work clothes, minimal watercolor wash in vibrant tones, energetic strokes',
    },
    {
      id: 'concetta-barone',
      name: 'Concetta Barone',
      age: 63,
      role: 'fish-vendor',
      placeId: 'mercato-vucciria',
      personality: ['tough', 'knowledgeable', 'respected'],
      portraitPrompt: 'Pen and ink portrait on white paper of a strong Sicilian woman with head scarf, weathered hands, sharp eyes, market apron, minimal watercolor wash in sea blues, decisive ink work',
    },
    {
      id: 'antonio-ferrara',
      name: 'Antonio Ferrara',
      age: 51,
      role: 'cheese-vendor',
      placeId: 'mercato-del-capo',
      personality: ['knowledgeable', 'proud', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a dignified Sicilian man with neat appearance, expert expression, holding cheese wheel, minimal watercolor wash in creamy tones, detailed rendering',
    },
    {
      id: 'carmela-todaro',
      name: 'Carmela Todaro',
      age: 59,
      role: 'owner-cook',
      placeId: 'trattoria-ai-cascinari',
      personality: ['motherly', 'passionate-about-food', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warm Sicilian woman with apron, wooden spoon in hand, caring expression, traditional style, minimal watercolor wash in warm kitchen tones, loving details',
    },
    {
      id: 'filippo-basile',
      name: 'Filippo Basile',
      age: 44,
      role: 'owner-chef',
      placeId: 'osteria-ballarò',
      personality: ['passionate', 'gregarious', 'wine-loving'],
      portraitPrompt: 'Pen and ink portrait on white paper of an enthusiastic Sicilian chef with five o\'clock shadow, chef coat, wine glass in hand, jovial expression, minimal watercolor wash in burgundy tones, expressive lines',
    },
    {
      id: 'giovanna-orlando',
      name: 'Giovanna Orlando',
      age: 37,
      role: 'server',
      placeId: 'antica-focacceria-san-francesco',
      personality: ['efficient', 'proud-of-tradition', 'helpful'],
      portraitPrompt: 'Pen and ink portrait on white paper of a professional Sicilian woman with hair back, crisp uniform, knowledgeable expression, traditional bearing, minimal watercolor wash in classic tones, clean lines',
    },
    {
      id: 'santo-lo-verde',
      name: 'Santo Lo Verde',
      age: 34,
      role: 'fry-cook',
      placeId: 'friggitoria-chiluzzo',
      personality: ['fast-talking', 'humorous', 'street-smart'],
      portraitPrompt: 'Pen and ink portrait on white paper of a lively Sicilian man with bandana, quick smile, working the fryer, energetic presence, minimal watercolor wash in golden fried tones, dynamic strokes',
    },
    {
      id: 'marco-gentile',
      name: 'Marco Gentile',
      age: 26,
      role: 'owner',
      placeId: 'ke-palle',
      personality: ['entrepreneurial', 'creative', 'trend-conscious'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young Sicilian entrepreneur with modern style, hipster beard, confident expression, contemporary clothing, minimal watercolor wash in bright tones, fresh line work',
    },
    {
      id: 'elena-bianchi',
      name: 'Elena Bianchi',
      age: 41,
      role: 'tour-guide',
      placeId: 'teatro-massimo',
      personality: ['knowledgeable', 'theatrical', 'passionate-about-culture'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant Sicilian woman with expressive hands, cultured appearance, speaking gestures, professional attire, minimal watercolor wash in operatic golds, dramatic rendering',
    },
    {
      id: 'padre-leonardo',
      name: 'Padre Leonardo',
      age: 68,
      role: 'priest',
      placeId: 'chiesa-della-martorana',
      personality: ['scholarly', 'gentle', 'multilingual'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly priest with kind eyes, clerical collar, serene expression, scholarly demeanor, minimal watercolor wash in Byzantine golds, reverent detail',
    },
    {
      id: 'suor-teresa',
      name: 'Suor Teresa',
      age: 72,
      role: 'nun',
      placeId: 'cattedrale-di-palermo',
      personality: ['devout', 'welcoming', 'keeper-of-history'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly nun in habit, peaceful expression, weathered hands holding rosary, gentle smile, minimal watercolor wash in soft grays, spiritual quality',
    },
    {
      id: 'nunzio-palmeri',
      name: 'Nunzio Palmeri',
      age: 76,
      role: 'gardener',
      placeId: 'giardino-garibaldi',
      personality: ['patient', 'loves-trees', 'philosophical'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly gardener with weathered face, flat cap, pruning shears, surrounded by nature, minimal watercolor wash in garden greens, gentle strokes',
    },
    {
      id: 'grazia-salamone',
      name: 'Grazia Salamone',
      age: 31,
      role: 'street-artist',
      placeId: 'piazza-pretoria',
      personality: ['artistic', 'observant', 'romantic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young Sicilian artist with sketchbook, bohemian style, creative expression, paint on fingers, minimal watercolor wash in artistic tones, expressive lines',
    },
    {
      id: 'alberto-marino',
      name: 'Alberto Marino',
      age: 54,
      role: 'photographer',
      placeId: 'quattro-canti',
      personality: ['patient', 'artistic', 'storyteller'],
      portraitPrompt: 'Pen and ink portrait on white paper of a photographer with camera around neck, observant eyes, casual professional style, capturing moments, minimal watercolor wash in photo gray tones, detailed work',
    },
    {
      id: 'alessio-picone',
      name: 'Alessio Picone',
      age: 39,
      role: 'sommelier',
      placeId: 'enoteca-picone',
      personality: ['knowledgeable', 'passionate', 'discerning'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined Sicilian sommelier with wine in hand, sophisticated appearance, expert expression, professional attire, minimal watercolor wash in wine tones, elegant lines',
    },
    {
      id: 'beatrice-amato',
      name: 'Beatrice Amato',
      age: 47,
      role: 'bookseller',
      placeId: 'libreria-del-mare',
      personality: ['literary', 'thoughtful', 'recommendative'],
      portraitPrompt: 'Pen and ink portrait on white paper of an intellectual Sicilian woman with reading glasses, book in hand, warm smile, surrounded by literature, minimal watercolor wash in book tones, thoughtful detail',
    },
    {
      id: 'davide-bruno',
      name: 'Davide Bruno',
      age: 32,
      role: 'bartender',
      placeId: 'corleone-wine-bar',
      personality: ['social', 'mixologist', 'night-owl'],
      portraitPrompt: 'Pen and ink portrait on white paper of a trendy Sicilian bartender with styled hair, mixing drink, friendly smile, casual-hip style, minimal watercolor wash in aperitivo orange, contemporary strokes',
    },
    {
      id: 'dottoressa-silvia',
      name: 'Dottoressa Silvia Campisi',
      age: 49,
      role: 'pharmacist',
      placeId: 'farmacia-centrale',
      personality: ['professional', 'caring', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a professional pharmacist with white coat, reassuring expression, competent demeanor, medical setting, minimal watercolor wash in clinical whites, precise rendering',
    },
    {
      id: 'michele-sorrentino',
      name: 'Michele Sorrentino',
      age: 43,
      role: 'station-master',
      placeId: 'stazione-centrale',
      personality: ['helpful', 'multilingual', 'organized'],
      portraitPrompt: 'Pen and ink portrait on white paper of a railway official in uniform, helpful expression, cap and badge, professional bearing, minimal watercolor wash in railway blues, structured lines',
    },
    {
      id: 'dottor-giuseppe-randazzo',
      name: 'Dottor Giuseppe Randazzo',
      age: 56,
      role: 'art-historian',
      placeId: 'cappella-palatina',
      personality: ['scholarly', 'passionate-about-history', 'detailed'],
      portraitPrompt: 'Pen and ink portrait on white paper of an art historian with glasses, gesturing to architecture, professorial appearance, enthusiastic expression, minimal watercolor wash in golden tones, academic detail',
    },
    {
      id: 'fra-massimo',
      name: 'Fra Massimo',
      age: 53,
      role: 'capuchin-monk',
      placeId: 'catacombe-dei-cappuccini',
      personality: ['solemn', 'philosophical', 'humble'],
      portraitPrompt: 'Pen and ink portrait on white paper of a Capuchin monk in brown habit, contemplative expression, serene demeanor, spiritual presence, minimal watercolor wash in earth tones, reverent strokes',
    },
    {
      id: 'claudia-ferrante',
      name: 'Claudia Ferrante',
      age: 35,
      role: 'museum-curator',
      placeId: 'palazzo-abatellis',
      personality: ['knowledgeable', 'preservation-focused', 'educational'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young curator with elegant style, intelligent eyes, professional attire, surrounded by art, minimal watercolor wash in gallery tones, refined details',
    },
  ],
  food: [
    'arancina',
    'panelle',
    'sfincione',
    'pane ca meusa',
    'pasta con le sarde',
    'caponata',
    'cannoli',
    'cassata siciliana',
    'brioche col gelato',
    'granita',
    'pasta alla Norma',
    'involtini di pesce spada',
    'cous cous di pesce',
    'pane cunzato',
    'stigghiola',
  ],
  customs: [
    'Loud market haggling and vendor calls',
    'Taking evening passeggiata in piazzas',
    'Standing at bar for morning coffee',
    'Multi-generational family meals',
    'Shopping daily at neighborhood markets',
    'Aperitivo culture before dinner',
    'Religious processions and festivals',
    'Street food eaten while walking',
    'Sunday family gatherings',
    'Coffee rituals throughout day',
  ],
  localTouches: [
    'Abbagnato - "Don\'t worry about it"',
    'Minchia - Common expletive (very casual)',
    'Schifiu - "Disgusting" in Sicilian',
    'Picciotto/a - Young person',
    'Amuninni - "Let\'s go"',
    'Futtitinni - "Forget about it"',
    'Taliare - "To look" in Sicilian',
    'Bedda matri - "Good heavens!"',
    'Cu è? - "Who is it?"',
    'Trasi - "Come in"',
  ],
};
