import { CityPantry } from '@/lib/types';

export const siena: CityPantry = {
  id: 'siena',
  name: 'Siena',
  neighbourhoods: ['Piazza del Campo', 'Terzo di Città', 'Terzo di San Martino', 'Terzo di Camollia'],
  places: [
    {
      id: 'caffe-fiorella',
      name: 'Caffè Fiorella',
      kind: 'bar',
      neighbourhood: 'Piazza del Campo',
      real: false,
      characterId: 'marco-fiorella',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional Italian café with small marble-topped tables along the edge of Piazza del Campo, rust-red awning, vintage espresso machine visible through the window, warm ochre and terracotta tones, morning light, textured and inviting.',
    },
    {
      id: 'bar-il-palio',
      name: 'Bar Il Palio',
      kind: 'bar',
      neighbourhood: 'Terzo di San Martino',
      real: false,
      characterId: 'giulia-neri',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy corner bar with Palio flags and contrada banners on brick walls, polished wooden counter, pastries under glass dome, warm amber and cream colors, inviting morning atmosphere, textured brushwork.',
    },
    {
      id: 'caffe-nannini',
      name: 'Caffè Nannini',
      kind: 'bar',
      neighbourhood: 'Terzo di Città',
      real: true,
      characterId: 'alessandro-nannini',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant historic café with Art Nouveau details, display cases filled with pastries and chocolates, black and white checkered floor, warm golden lighting, sienna and cream tones, sophisticated and inviting atmosphere.',
    },
    {
      id: 'pasticceria-bini',
      name: 'Pasticceria Bini',
      kind: 'bakery',
      neighbourhood: 'Terzo di Camollia',
      real: true,
      characterId: 'lucia-bini',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional pasticceria with glass cases displaying ricciarelli and panforte, vintage tile floor, warm peachy-pink walls, morning sunlight streaming through windows, powdered sugar dusting the air, inviting and sweet.',
    },
    {
      id: 'forno-dei-galli',
      name: 'Forno dei Galli',
      kind: 'bakery',
      neighbourhood: 'Terzo di San Martino',
      real: false,
      characterId: 'roberto-galli',
      imagePrompt: 'Soft pastel sketch on white paper of a rustic neighborhood bakery with wood-fired oven visible in back, shelves of fresh pane toscano, warm golden light, flour-dusted surfaces, earthy terracotta and wheat tones, textured and aromatic atmosphere.',
    },
    {
      id: 'mercato-della-terra',
      name: 'Mercato della Terra',
      kind: 'market',
      neighbourhood: 'Piazza del Campo',
      real: false,
      characterId: 'paolo-rossi',
      imagePrompt: 'Soft pastel sketch on white paper of an open-air farmers market with white canvas stalls, crates of seasonal vegetables and fruit, bunches of fresh herbs, warm morning light, earth tones and vibrant greens, bustling and organic atmosphere.',
    },
    {
      id: 'mercato-coperto',
      name: 'La Lizza Market',
      kind: 'market',
      neighbourhood: 'Terzo di Camollia',
      real: true,
      characterId: 'anna-mercanti',
      imagePrompt: 'Soft pastel sketch on white paper of a covered market hall with vendor stalls selling cheeses, salamis, fresh produce, overhead industrial lights, colorful array of goods, warm and cool tones mixed, lively and authentic marketplace feel.',
    },
    {
      id: 'bottega-del-gusto',
      name: 'Bottega del Gusto',
      kind: 'market',
      neighbourhood: 'Terzo di Città',
      real: false,
      characterId: 'simone-guidi',
      imagePrompt: 'Soft pastel sketch on white paper of a specialty food shop with hanging prosciutto, wheels of pecorino cheese, bottles of local wine and olive oil, wooden shelves, warm amber lighting, rich burgundy and gold tones, intimate and traditional.',
    },
    {
      id: 'osteria-le-logge',
      name: 'Osteria Le Logge',
      kind: 'osteria',
      neighbourhood: 'Terzo di Città',
      real: true,
      characterId: 'chiara-castellani',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant osteria interior with vaulted brick ceilings, white tablecloths, wine bottles lining stone walls, soft candlelight, warm sienna and cream colors, sophisticated yet welcoming atmosphere.',
    },
    {
      id: 'trattoria-papei',
      name: 'Trattoria Papei',
      kind: 'trattoria',
      neighbourhood: 'Piazza del Campo',
      real: true,
      characterId: 'franco-papei',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional trattoria with outdoor seating near the Campo, red-checked tablecloths, rustic wooden chairs, vine-covered pergola, warm afternoon light, terracotta and green tones, casual and authentic.',
    },
    {
      id: 'ristorante-mugolone',
      name: 'Ristorante Mugolone',
      kind: 'ristorante',
      neighbourhood: 'Terzo di San Martino',
      real: true,
      characterId: 'vittorio-brunelli',
      imagePrompt: 'Soft pastel sketch on white paper of a refined restaurant dining room with exposed brick arches, intimate table settings, soft lamp lighting, tuscan landscape paintings on walls, warm ochre and burgundy tones, elegant and romantic.',
    },
    {
      id: 'pizzeria-del-campo',
      name: 'Pizzeria Il Carroccio',
      kind: 'pizzeria',
      neighbourhood: 'Terzo di Camollia',
      real: false,
      characterId: 'davide-marino',
      imagePrompt: 'Soft pastel sketch on white paper of a lively pizzeria with wood-burning oven glowing orange, pizza peels hanging on walls, simple wooden tables, flour in the air, warm golden and red tones, energetic and welcoming.',
    },
    {
      id: 'duomo-siena',
      name: 'Cattedrale di Siena',
      kind: 'church',
      neighbourhood: 'Terzo di Città',
      real: true,
      characterId: 'padre-giuseppe',
      imagePrompt: 'Soft pastel sketch on white paper of the magnificent striped marble cathedral facade, black and white geometric patterns, intricate Gothic details, bronze doors, warm afternoon light on stone, majestic and sacred atmosphere, textured brushwork.',
    },
    {
      id: 'basilica-san-domenico',
      name: 'Basilica di San Domenico',
      kind: 'church',
      neighbourhood: 'Terzo di Camollia',
      real: true,
      characterId: 'sister-maria',
      imagePrompt: 'Soft pastel sketch on white paper of a grand brick basilica with simple facade, tall bell tower, cypress trees nearby, warm terracotta tones against blue sky, peaceful and contemplative atmosphere, soft textures.',
    },
    {
      id: 'piazza-del-campo',
      name: 'Piazza del Campo',
      kind: 'piazza',
      neighbourhood: 'Piazza del Campo',
      real: true,
      characterId: 'leonardo-conti',
      imagePrompt: 'Soft pastel sketch on white paper of the famous shell-shaped piazza sloping downward, Palazzo Pubblico and Torre del Mangia rising above, warm brick paving, people scattered across the campo, golden afternoon light, iconic and breathtaking.',
    },
    {
      id: 'piazza-salimbeni',
      name: 'Piazza Salimbeni',
      kind: 'piazza',
      neighbourhood: 'Terzo di Camollia',
      real: true,
      characterId: 'beatrice-salvi',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant Renaissance square surrounded by historic palazzi, central statue, benches under trees, warm stone facades, quiet and refined atmosphere, soft peachy and grey tones.',
    },
    {
      id: 'torre-del-mangia',
      name: 'Torre del Mangia',
      kind: 'landmark',
      neighbourhood: 'Piazza del Campo',
      real: true,
      characterId: 'matteo-torre',
      imagePrompt: 'Soft pastel sketch on white paper of the soaring medieval bell tower rising above terracotta rooftops, white stone crown at top, dramatic perspective from below, warm sienna and cream tones, majestic and timeless.',
    },
    {
      id: 'orto-de-pecci',
      name: "Orto de' Pecci",
      kind: 'park',
      neighbourhood: 'Terzo di San Martino',
      real: true,
      characterId: 'carla-nesti',
      imagePrompt: 'Soft pastel sketch on white paper of a terraced Renaissance garden with geometric beds, medicinal herbs, stone pathways, views over Tuscan countryside, dappled shade, soft greens and earth tones, peaceful and historic.',
    },
    {
      id: 'enoteca-italiana',
      name: 'Enoteca Italiana',
      kind: 'enoteca',
      neighbourhood: 'Terzo di Camollia',
      real: true,
      characterId: 'stefano-vini',
      imagePrompt: 'Soft pastel sketch on white paper of a vaulted brick wine cellar with endless bottles lining walls, wooden tasting bar, soft amber lighting, deep burgundy and gold tones, sophisticated and atmospheric.',
    },
    {
      id: 'enoteca-san-domenico',
      name: 'Enoteca San Domenico',
      kind: 'enoteca',
      neighbourhood: 'Terzo di Camollia',
      real: false,
      characterId: 'michele-vanni',
      imagePrompt: 'Soft pastel sketch on white paper of an intimate wine bar with small wooden tables, chalkboard listing wines, exposed stone walls, warm candlelight, rich reds and warm browns, cozy and inviting.',
    },
    {
      id: 'libreria-senese',
      name: 'Libreria Senese',
      kind: 'bookshop',
      neighbourhood: 'Terzo di Città',
      real: true,
      characterId: 'elisabetta-libri',
      imagePrompt: 'Soft pastel sketch on white paper of a charming bookshop with floor-to-ceiling wooden shelves, stacks of Italian literature, reading nook by window, warm lamp lighting, cream and forest green tones, intellectual and intimate.',
    },
    {
      id: 'bottega-del-palio',
      name: 'Bottega del Palio',
      kind: 'shop',
      neighbourhood: 'Piazza del Campo',
      real: false,
      characterId: 'giovanni-bacci',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional shop selling Palio silk scarves, contrada flags, ceramic horses, hand-painted banners, vibrant colors against white walls, festive and authentic atmosphere.',
    },
    {
      id: 'farmacia-centrale',
      name: 'Farmacia Centrale',
      kind: 'pharmacy',
      neighbourhood: 'Terzo di Città',
      real: false,
      characterId: 'dottoressa-ricci',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional pharmacy with antique wooden cabinets, ceramic apothecary jars, modern counter, soft green cross sign glowing, clean whites and medicinal greens, professional and trustworthy.',
    },
    {
      id: 'consorzio-agrario',
      name: 'Consorzio Agrario',
      kind: 'shop',
      neighbourhood: 'Terzo di San Martino',
      real: true,
      characterId: 'alberto-fattori',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional agricultural cooperative store with local wines, olive oils, honey, dried goods in bulk bins, rustic wooden shelves, warm earthy tones, authentic and regional.',
    },
    {
      id: 'antica-drogheria-manganelli',
      name: 'Antica Drogheria Manganelli',
      kind: 'specialty-food',
      neighbourhood: 'Terzo di Città',
      real: true,
      characterId: 'claudia-manganelli',
      imagePrompt: 'Soft pastel sketch on white paper of a historic drogheria with vintage wooden drawers, glass jars of spices and sweets, ricciarelli and panforte displayed, copper scales, warm amber lighting, nostalgic and precious.',
    },
    {
      id: 'gelateria-brivido',
      name: 'Gelateria Brivido',
      kind: 'gelateria',
      neighbourhood: 'Terzo di San Martino',
      real: true,
      characterId: 'andrea-brivido',
      imagePrompt: 'Soft pastel sketch on white paper of a modern gelateria with gleaming display cases of colorful gelato, chrome scoops, clean white and pastel interiors, bright and cheerful atmosphere, creamy pinks and mint greens.',
    },
    {
      id: 'fortezza-medicea',
      name: 'Fortezza Medicea',
      kind: 'landmark',
      neighbourhood: 'Terzo di Camollia',
      real: true,
      characterId: 'lorenzo-forti',
      imagePrompt: 'Soft pastel sketch on white paper of massive Renaissance fortress walls with bastions, green lawn inside courtyard, cypress trees, warm brick and stone textures, commanding presence against blue sky, historic and powerful.',
    },
    {
      id: 'caffe-del-corso',
      name: 'Caffè del Corso',
      kind: 'bar',
      neighbourhood: 'Terzo di San Martino',
      real: false,
      characterId: 'fabio-rosso',
      imagePrompt: 'Soft pastel sketch on white paper of a bustling corner café along the main shopping street, Art Deco details, outdoor seating with umbrellas, morning bustle, warm ochre and cream tones, lively and social.',
    },
    {
      id: 'alimentari-morbidi',
      name: 'Alimentari Morbidi',
      kind: 'specialty-food',
      neighbourhood: 'Terzo di Camollia',
      real: true,
      characterId: 'teresa-morbidi',
      imagePrompt: 'Soft pastel sketch on white paper of a historic food shop with hanging salamis, shelves of pasta and preserves, wheels of pecorino, wooden counter worn smooth by time, warm golden light, traditional and beloved.',
    },
  ],
  characters: [
    {
      id: 'marco-fiorella',
      name: 'Marco Fiorella',
      age: 42,
      role: 'proprietario',
      placeId: 'caffe-fiorella',
      personality: ['passionate', 'welcoming', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a middle-aged Italian man with warm smile, salt-and-pepper hair swept back, laugh lines around eyes, wearing crisp white shirt, minimal watercolor wash in warm sepia tones, detailed crosshatching, personal and genuine.',
    },
    {
      id: 'giulia-neri',
      name: 'Giulia Neri',
      age: 28,
      role: 'barista',
      placeId: 'bar-il-palio',
      personality: ['energetic', 'chatty', 'loyal-to-her-contrada'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with bright eyes, dark hair in ponytail, friendly smile, wearing black apron, minimal watercolor wash in soft peachy tones, confident expression, detailed linework.',
    },
    {
      id: 'alessandro-nannini',
      name: 'Alessandro Nannini',
      age: 55,
      role: 'maestro caffettiere',
      placeId: 'caffe-nannini',
      personality: ['perfectionist', 'traditional', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished older man with silver hair, sharp features, focused gaze, bow tie, minimal watercolor wash in cool grey tones, precise detailed features, professional and refined.',
    },
    {
      id: 'lucia-bini',
      name: 'Lucia Bini',
      age: 38,
      role: 'pasticciera',
      placeId: 'pasticceria-bini',
      personality: ['meticulous', 'sweet', 'artistic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a woman with flour-dusted apron, gentle smile, hair in neat bun, delicate hands, minimal watercolor wash in soft powdery pinks, warm and nurturing expression, fine detailed linework.',
    },
    {
      id: 'roberto-galli',
      name: 'Roberto Galli',
      age: 61,
      role: 'fornaio',
      placeId: 'forno-dei-galli',
      personality: ['gruff-but-kind', 'early-riser', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy older man with strong forearms, weathered face, knowing smile, flour in graying hair, minimal watercolor wash in warm wheat tones, honest and hardworking expression.',
    },
    {
      id: 'paolo-rossi',
      name: 'Paolo Rossi',
      age: 47,
      role: 'venditore',
      placeId: 'mercato-della-terra',
      personality: ['jovial', 'generous', 'storyteller'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust man with sun-weathered skin, broad smile, wearing work vest, hands gesture expressively, minimal watercolor wash in earthy terracotta, animated and warm expression.',
    },
    {
      id: 'anna-mercanti',
      name: 'Anna Mercanti',
      age: 52,
      role: 'venditrice di formaggi',
      placeId: 'mercato-coperto',
      personality: ['practical', 'no-nonsense', 'fair'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy woman with sharp eyes, sensible apron, hair in practical braid, confident posture, minimal watercolor wash in cream tones, direct and trustworthy expression.',
    },
    {
      id: 'simone-guidi',
      name: 'Simone Guidi',
      age: 44,
      role: 'proprietario',
      placeId: 'bottega-del-gusto',
      personality: ['passionate-about-food', 'educator', 'particular'],
      portraitPrompt: 'Pen and ink portrait on white paper of a slim man with expressive hands, intense eyes, salt-and-pepper beard, wearing apron over dress shirt, minimal watercolor wash in rich burgundy, knowledgeable and enthusiastic.',
    },
    {
      id: 'chiara-castellani',
      name: 'Chiara Castellani',
      age: 35,
      role: 'chef',
      placeId: 'osteria-le-logge',
      personality: ['creative', 'precise', 'ambitious'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant woman with sharp features, hair tied back, chef whites, determined expression, minimal watercolor wash in soft sienna, confident and talented demeanor.',
    },
    {
      id: 'franco-papei',
      name: 'Franco Papei',
      age: 68,
      role: 'proprietario',
      placeId: 'trattoria-papei',
      personality: ['wise', 'humorous', 'grandfatherly'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly man with kind wrinkles, twinkling eyes, white hair, comfortable old cardigan, minimal watercolor wash in warm ochre, welcoming and beloved expression.',
    },
    {
      id: 'vittorio-brunelli',
      name: 'Vittorio Brunelli',
      age: 41,
      role: 'sommelier',
      placeId: 'ristorante-mugolone',
      personality: ['sophisticated', 'attentive', 'cultivated'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined man with neat beard, intelligent eyes, elegant posture, wine key on chain, minimal watercolor wash in burgundy tones, polished and professional.',
    },
    {
      id: 'davide-marino',
      name: 'Davide Marino',
      age: 29,
      role: 'pizzaiolo',
      placeId: 'pizzeria-del-campo',
      personality: ['energetic', 'friendly', 'skillful'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with muscular forearms, bright smile, bandana around head, flour-dusted shirt, minimal watercolor wash in warm golden tones, enthusiastic and approachable.',
    },
    {
      id: 'padre-giuseppe',
      name: 'Padre Giuseppe',
      age: 71,
      role: 'sacerdote',
      placeId: 'duomo-siena',
      personality: ['serene', 'learned', 'gentle'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly priest with peaceful expression, wire-rimmed glasses, clerical collar, wise eyes, minimal watercolor wash in soft grey-blue, spiritual and compassionate.',
    },
    {
      id: 'sister-maria',
      name: 'Suor Maria Caterina',
      age: 58,
      role: 'suora',
      placeId: 'basilica-san-domenico',
      personality: ['devoted', 'nurturing', 'quiet'],
      portraitPrompt: 'Pen and ink portrait on white paper of a nun with gentle face, simple habit, kind eyes, serene expression, minimal watercolor wash in soft cream and grey, peaceful and devoted demeanor.',
    },
    {
      id: 'leonardo-conti',
      name: 'Leonardo Conti',
      age: 33,
      role: 'guida turistica',
      placeId: 'piazza-del-campo',
      personality: ['articulate', 'proud-senese', 'engaging'],
      portraitPrompt: 'Pen and ink portrait on white paper of a handsome young man with animated expression, gesturing hands, casual but neat clothing, bright eyes, minimal watercolor wash in warm terracotta, passionate and articulate.',
    },
    {
      id: 'beatrice-salvi',
      name: 'Beatrice Salvi',
      age: 26,
      role: 'studentessa',
      placeId: 'piazza-salimbeni',
      personality: ['studious', 'thoughtful', 'romantic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with book under arm, thoughtful gaze, flowing hair, simple scarf, minimal watercolor wash in soft lavender, intellectual and dreamy expression.',
    },
    {
      id: 'matteo-torre',
      name: 'Matteo Torre',
      age: 45,
      role: 'custode',
      placeId: 'torre-del-mangia',
      personality: ['fit', 'informative', 'patient'],
      portraitPrompt: 'Pen and ink portrait on white paper of a lean athletic man with weathered face from sun, knowing smile, casual uniform, minimal watercolor wash in warm stone colors, steady and reliable expression.',
    },
    {
      id: 'carla-nesti',
      name: 'Carla Nesti',
      age: 64,
      role: 'giardiniera',
      placeId: 'orto-de-pecci',
      personality: ['knowledgeable', 'patient', 'green-thumbed'],
      portraitPrompt: 'Pen and ink portrait on white paper of an older woman with sun hat, gentle smile, gardening gloves tucked in pocket, earth under nails, minimal watercolor wash in soft green tones, nurturing and wise.',
    },
    {
      id: 'stefano-vini',
      name: 'Stefano Vini',
      age: 50,
      role: 'sommelier',
      placeId: 'enoteca-italiana',
      personality: ['expert', 'discerning', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man with subtle smile, holding wine glass to light, refined features, minimal watercolor wash in deep burgundy, knowledgeable and sophisticated.',
    },
    {
      id: 'michele-vanni',
      name: 'Michele Vanni',
      age: 39,
      role: 'proprietario',
      placeId: 'enoteca-san-domenico',
      personality: ['warm', 'conversational', 'wine-enthusiast'],
      portraitPrompt: 'Pen and ink portrait on white paper of a friendly man with expressive face, slight stubble, open collar shirt, wine stain on apron, minimal watercolor wash in warm amber, welcoming and passionate.',
    },
    {
      id: 'elisabetta-libri',
      name: 'Elisabetta Libri',
      age: 43,
      role: 'libraia',
      placeId: 'libreria-senese',
      personality: ['literary', 'helpful', 'cultured'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant woman with reading glasses on chain, intelligent eyes, simple sweater, book in hand, minimal watercolor wash in soft sage green, thoughtful and refined.',
    },
    {
      id: 'giovanni-bacci',
      name: 'Giovanni Bacci',
      age: 56,
      role: 'artigiano',
      placeId: 'bottega-del-palio',
      personality: ['traditional', 'proud', 'meticulous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a craftsman with skillful hands, concentrated expression, wearing contrada scarf, graying hair, minimal watercolor wash in silk banner colors, dedicated and authentic.',
    },
    {
      id: 'dottoressa-ricci',
      name: 'Dottoressa Ricci',
      age: 48,
      role: 'farmacista',
      placeId: 'farmacia-centrale',
      personality: ['professional', 'caring', 'precise'],
      portraitPrompt: 'Pen and ink portrait on white paper of a professional woman with neat hair, white coat, gentle but competent expression, minimal watercolor wash in clean whites and soft blue, trustworthy and knowledgeable.',
    },
    {
      id: 'alberto-fattori',
      name: 'Alberto Fattori',
      age: 59,
      role: 'commesso',
      placeId: 'consorzio-agrario',
      personality: ['knowledgeable', 'local', 'helpful'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy man with weathered hands, practical work clothes, warm smile, minimal watercolor wash in earth tones, honest and dependable expression.',
    },
    {
      id: 'claudia-manganelli',
      name: 'Claudia Manganelli',
      age: 36,
      role: 'proprietaria',
      placeId: 'antica-drogheria-manganelli',
      personality: ['tradition-keeper', 'gracious', 'particular'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant woman with vintage apron, careful hands, warm but professional smile, minimal watercolor wash in antique gold tones, refined and proud.',
    },
    {
      id: 'andrea-brivido',
      name: 'Andrea Brivido',
      age: 31,
      role: 'gelatiere',
      placeId: 'gelateria-brivido',
      personality: ['creative', 'cheerful', 'innovative'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with bright smile, modern style, holding gelato scoop, playful expression, minimal watercolor wash in pastel colors, energetic and friendly.',
    },
    {
      id: 'lorenzo-forti',
      name: 'Lorenzo Forti',
      age: 37,
      role: 'custode',
      placeId: 'fortezza-medicea',
      personality: ['history-buff', 'serious', 'informative'],
      portraitPrompt: 'Pen and ink portrait on white paper of a serious man with strong features, neat uniform, attentive eyes, minimal watercolor wash in stone grey tones, authoritative and knowledgeable.',
    },
    {
      id: 'fabio-rosso',
      name: 'Fabio Rosso',
      age: 25,
      role: 'barista',
      placeId: 'caffe-del-corso',
      personality: ['social', 'quick', 'ambitious'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with stylish hair, quick smile, modern casual style, energetic posture, minimal watercolor wash in warm coffee tones, dynamic and friendly.',
    },
    {
      id: 'teresa-morbidi',
      name: 'Teresa Morbidi',
      age: 67,
      role: 'proprietaria',
      placeId: 'alimentari-morbidi',
      personality: ['grandmotherly', 'traditional', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly woman with kind face, traditional apron, gentle hands, warm smile, minimal watercolor wash in soft cream tones, beloved and nurturing expression.',
    },
  ],
  food: [
    'pici cacio e pepe',
    'pici all\'aglione',
    'pappardelle al cinghiale',
    'ribollita',
    'panzanella',
    'bistecca alla fiorentina',
    'panforte',
    'ricciarelli',
    'cantucci',
    'cavallucci',
    'copate',
    'crostini di fegatini',
    'salumi toscani',
    'pecorino senese',
    'pane toscano',
    'fagioli all\'uccelletto',
    'acquacotta',
    'tortelli maremmani',
    'cinghiale in umido',
    'scottiglia',
  ],
  customs: [
    'Il Palio di Siena - the historic horse race twice yearly in the Campo',
    'Contrada loyalty - deep identity with your neighborhood contrada',
    'Passeggiata along Via di Città in the evening',
    'Aperitivo before dinner, often in Piazza del Campo',
    'Blessing of the horses before the Palio',
    'Cena della prova - victory dinners in the contrade',
    'Shopping at the Wednesday market at La Lizza',
    'Sunday lunch lasting hours with multiple courses',
    'Celebrating Santa Caterina, patron saint of Siena',
    'Taking morning coffee standing at the bar',
  ],
  localTouches: [
    'Calling Siena "la più bella" - the most beautiful',
    'Using "Oca" or "Drago" with pride when mentioning your contrada',
    'Saying "Evviva!" during Palio celebrations',
    'Referring to Florence as rivals with knowing smiles',
    'Using "bischero" playfully as gentle teasing',
    'Saying "Ehi, bello!" as casual greeting',
    'Pronouncing "la" with hard "c" - "hoca hola" (Tuscan gorgia)',
    'Using "babbo" instead of "papà" for father',
    'Saying "un po\'" frequently - a little bit',
    'Referring to the Campo simply as "il Campo"',
  ],
};
