import { CityPantry } from '@/lib/types';

export const siracusa: CityPantry = {
  id: 'siracusa',
  name: 'Siracusa',
  neighbourhoods: ['Ortigia', 'Neapolis', 'Acradina', 'Tyche'],
  places: [
    // DAILY ROUTINE - BARS/CAFÉS (3)
    {
      id: 'bar-dolce-vita',
      name: 'Bar Dolce Vita',
      kind: 'bar',
      neighbourhood: 'Ortigia',
      real: false,
      characterId: 'salvatore-bar',
      imagePrompt: 'Soft pastel sketch on white paper of a charming corner bar with turquoise shutters and marble counter visible through open doors, outdoor tables with wicker chairs, morning sunlight casting warm shadows, potted jasmine by entrance, Sicilian ceramic tiles accent, warm ochres and sea blues, textured and inviting',
    },
    {
      id: 'caffe-archimede',
      name: 'Caffè Archimede',
      kind: 'bar',
      neighbourhood: 'Neapolis',
      real: false,
      characterId: 'rosa-caffe',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant café with Art Nouveau details, gleaming brass espresso machine behind curved counter, vintage mirrors reflecting morning light, display case of cornetti and iris, geometric floor tiles, warm amber and cream tones, inviting atmosphere',
    },
    {
      id: 'bar-apollo',
      name: 'Bar Apollo',
      kind: 'bar',
      neighbourhood: 'Acradina',
      real: false,
      characterId: 'giuseppe-apollo',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood bar with simple wooden counter, shelves lined with colorful liqueur bottles, locals reading newspapers at small tables, vintage espresso cups, morning light through lace curtains, terracotta and sage green tones, warm and familiar',
    },
    // BAKERIES (2)
    {
      id: 'panificio-regina',
      name: 'Panificio Regina',
      kind: 'bakery',
      neighbourhood: 'Ortigia',
      real: false,
      characterId: 'angela-panificio',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional bakery with wooden shelves laden with golden bread loaves, trays of sfincione and scaccia, wood-fired oven glowing in background, flour dust in air catching light, rustic baskets, warm golden and wheat tones, aromatic and inviting',
    },
    {
      id: 'pasticceria-santa-lucia',
      name: 'Pasticceria Santa Lucia',
      kind: 'bakery',
      neighbourhood: 'Tyche',
      real: false,
      characterId: 'carmelo-pasticceria',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant pastry shop with glass cases displaying cassata siciliana and cannoli, delicate almond pastries, decorative baroque mirrors, vintage scales, white marble surfaces, pistachio green and cream colors, refined and sweet-scented',
    },
    // MARKETS (3)
    {
      id: 'mercato-ortigia',
      name: 'Mercato di Ortigia',
      kind: 'market',
      neighbourhood: 'Ortigia',
      real: true,
      characterId: 'pietro-mercato',
      imagePrompt: 'Soft pastel sketch on white paper of a vibrant outdoor market with colorful produce stalls, pyramids of blood oranges and lemons, fresh fish on ice, striped awnings, vendors calling out, ancient stone buildings in background, brilliant oranges, greens, and blues, lively and bustling',
    },
    {
      id: 'mercato-acradina',
      name: 'Mercato di Acradina',
      kind: 'market',
      neighbourhood: 'Acradina',
      real: false,
      characterId: 'francesca-verdura',
      imagePrompt: 'Soft pastel sketch on white paper of a covered market hall with vendors selling seasonal vegetables, bunches of wild fennel, ripe tomatoes, fresh ricotta in baskets, hanging herbs, dappled light through market roof, earthy greens and reds, authentic and aromatic',
    },
    {
      id: 'pescheria-mare',
      name: 'Pescheria Il Mare Nostro',
      kind: 'market',
      neighbourhood: 'Ortigia',
      real: false,
      characterId: 'tonino-pesce',
      imagePrompt: 'Soft pastel sketch on white paper of a fish market stall with fresh catch displayed on ice, silvery anchovies, red prawns, swordfish steaks, marble counter wet with seawater, fishing nets decorating walls, cool blues and silvers, fresh and maritime',
    },
    // RESTAURANTS (2)
    {
      id: 'ristorante-dioniso',
      name: 'Ristorante Dioniso',
      kind: 'ristorante',
      neighbourhood: 'Neapolis',
      real: false,
      characterId: 'lorenzo-dioniso',
      imagePrompt: 'Soft pastel sketch on white paper of an upscale restaurant with white tablecloths, view of ancient Greek theater through arched windows, wine bottles in wooden racks, elegant table settings, soft candlelight, warm terra cotta and ivory tones, refined and historic',
    },
    {
      id: 'ristorante-luna',
      name: 'Ristorante La Luna sul Mare',
      kind: 'ristorante',
      neighbourhood: 'Ortigia',
      real: false,
      characterId: 'isabella-luna',
      imagePrompt: 'Soft pastel sketch on white paper of a romantic seaside restaurant with terrace overlooking harbor, fishing boats bobbing in water, string lights, tables set with local ceramics, sea breeze moving curtains, deep blues and moonlight whites, enchanting and coastal',
    },
    // SPECIALTY FOOD (2)
    {
      id: 'trattoria-aretusa',
      name: 'Trattoria Aretusa',
      kind: 'trattoria',
      neighbourhood: 'Ortigia',
      real: false,
      characterId: 'maria-trattoria',
      imagePrompt: 'Soft pastel sketch on white paper of a family-run trattoria with checkered tablecloths, copper pots on walls, handwritten menu board, pasta drying on racks, warm kitchen visible through doorway, red wine bottles, rustic reds and golds, homey and welcoming',
    },
    {
      id: 'osteria-siciliana',
      name: 'Osteria Siciliana',
      kind: 'osteria',
      neighbourhood: 'Tyche',
      real: false,
      characterId: 'vincenzo-osteria',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy osteria with wooden beams, hanging garlic and peppers, local wine in carafes, simple wooden tables, antipasti displayed on counter, traditional terracotta dishes, warm amber and burgundy tones, authentic and rustic',
    },
    // CULTURAL/LANDMARK (4)
    {
      id: 'duomo-siracusa',
      name: 'Duomo di Siracusa',
      kind: 'church',
      neighbourhood: 'Ortigia',
      real: true,
      characterId: 'padre-antonio',
      imagePrompt: 'Soft pastel sketch on white paper of magnificent baroque cathedral facade with ancient Greek columns incorporated, grand staircase, ornate statues, golden light on cream stone, pigeons in plaza, dramatic shadows, ivory and warm gold tones, majestic and timeless',
    },
    {
      id: 'fonte-aretusa',
      name: 'Fonte Aretusa',
      kind: 'landmark',
      neighbourhood: 'Ortigia',
      real: true,
      characterId: 'elena-guide',
      imagePrompt: 'Soft pastel sketch on white paper of mythical freshwater spring by the sea, papyrus plants growing in clear water, stone balustrade, ducks swimming, ancient walls, sea sparkling beyond, lush greens and azure blues, magical and serene',
    },
    {
      id: 'parco-archeologico',
      name: 'Parco Archeologico della Neapolis',
      kind: 'park',
      neighbourhood: 'Neapolis',
      real: true,
      characterId: 'marco-archeologo',
      imagePrompt: 'Soft pastel sketch on white paper of ancient Greek theater carved into hillside, limestone seats descending toward stage, wildflowers growing between stones, Mediterranean pines, brilliant blue sky, scattered tourists, stone grays and spring greens, ancient and peaceful',
    },
    {
      id: 'piazza-archimede',
      name: 'Piazza Archimede',
      kind: 'piazza',
      neighbourhood: 'Ortigia',
      real: true,
      characterId: 'alberto-piazza',
      imagePrompt: 'Soft pastel sketch on white paper of elegant baroque square with central fountain of Artemis, cafes with outdoor seating, historic palazzos with ornate balconies, people strolling, pigeons, dappled shade from palms, warm ochre and sky blue, vibrant and social',
    },
    // ADDITIONAL CHURCH
    {
      id: 'santuario-madonna',
      name: 'Santuario della Madonna delle Lacrime',
      kind: 'church',
      neighbourhood: 'Acradina',
      real: true,
      characterId: 'suor-gabriella',
      imagePrompt: 'Soft pastel sketch on white paper of striking modern conical sanctuary with soaring concrete tower, pilgrims at entrance, contemporary architecture against ancient city backdrop, peaceful gardens, soft grays and whites, contemplative and modern',
    },
    // WINE BARS/APERITIVO (2)
    {
      id: 'enoteca-bacco',
      name: 'Enoteca Bacco',
      kind: 'enoteca',
      neighbourhood: 'Ortigia',
      real: false,
      characterId: 'stefano-vino',
      imagePrompt: 'Soft pastel sketch on white paper of intimate wine bar with exposed stone walls, wooden wine racks floor to ceiling, small marble bar, wine barrels as tables, candlelight, glasses catching light, deep burgundy and amber tones, sophisticated and cozy',
    },
    {
      id: 'wine-bar-etna',
      name: 'Wine Bar Etna',
      kind: 'wine bar',
      neighbourhood: 'Neapolis',
      real: false,
      characterId: 'claudia-sommelier',
      imagePrompt: 'Soft pastel sketch on white paper of modern wine bar with sleek counter, shelves of Sicilian wines, small plates of local cheeses and olives, soft lighting, contemporary art on walls, wine glasses arranged artfully, plum and gold accents, refined and welcoming',
    },
    // BOOKSHOP/CULTURAL (1)
    {
      id: 'libreria-papiro',
      name: 'Libreria Il Papiro',
      kind: 'bookshop',
      neighbourhood: 'Ortigia',
      real: false,
      characterId: 'beatrice-libri',
      imagePrompt: 'Soft pastel sketch on white paper of charming bookshop with floor-to-ceiling shelves, stacks of Sicilian literature, antique reading chair by window, vintage maps on walls, ladder to reach high shelves, warm lamp light, sepia and sage tones, literary and intimate',
    },
    // PRACTICAL (2)
    {
      id: 'farmacia-apollo',
      name: 'Farmacia Apollo',
      kind: 'pharmacy',
      neighbourhood: 'Acradina',
      real: false,
      characterId: 'dottore-ricci',
      imagePrompt: 'Soft pastel sketch on white paper of traditional pharmacy with wooden cabinets, ceramic apothecary jars, green cross sign, prescription counter, herbal remedies displayed, professional but warm atmosphere, mint green and white tones, clean and trustworthy',
    },
    {
      id: 'stazione-siracusa',
      name: 'Stazione di Siracusa',
      kind: 'station',
      neighbourhood: 'Tyche',
      real: true,
      characterId: 'roberto-stazione',
      imagePrompt: 'Soft pastel sketch on white paper of modest railway station with platforms, travelers with luggage, ticket windows, arrivals and departures board, palm trees outside, trains waiting, utilitarian but Mediterranean character, dusty rose and cream, transitional and busy',
    },
    // CITY CHARACTER - SICILIAN SPECIFIC (3)
    {
      id: 'antica-giudecca',
      name: 'Antica Giudecca',
      kind: 'cultural site',
      neighbourhood: 'Ortigia',
      real: false,
      characterId: 'davide-storia',
      imagePrompt: 'Soft pastel sketch on white paper of ancient Jewish quarter with narrow medieval streets, stone archways, glimpses of courtyards, weathered doorways, hanging laundry, potted geraniums, warm honey stone, shadows and light, historic and atmospheric',
    },
    {
      id: 'laboratorio-papiro',
      name: 'Laboratorio del Papiro',
      kind: 'workshop',
      neighbourhood: 'Ortigia',
      real: false,
      characterId: 'arturo-papiro',
      imagePrompt: 'Soft pastel sketch on white paper of artisan workshop with papyrus plants drying, ancient paper-making tools, finished papyrus scrolls with painted scenes, workbench with natural materials, demonstration area, earthy greens and parchment tones, traditional and crafted',
    },
    {
      id: 'gelateria-nettuno',
      name: 'Gelateria Nettuno',
      kind: 'gelateria',
      neighbourhood: 'Ortigia',
      real: false,
      characterId: 'lucia-gelato',
      imagePrompt: 'Soft pastel sketch on white paper of artisanal gelato shop with display cases of vibrant flavors, pistachio and almond from local nuts, citrus sorbets, customers with cones, seaside location, tiled counter, pastel colors of gelato, cool aquas and pistachios, refreshing and sweet',
    },
    {
      id: 'bottega-ceramica',
      name: 'Bottega della Ceramica Siciliana',
      kind: 'shop',
      neighbourhood: 'Ortigia',
      real: false,
      characterId: 'giulia-ceramica',
      imagePrompt: 'Soft pastel sketch on white paper of ceramic workshop with colorful hand-painted plates, traditional Sicilian patterns, vases with lemons and baroque designs, potter\'s wheel, shelves of finished pieces, bright yellows and blues, artisanal and colorful',
    },
    // ADDITIONAL PLACES TO REACH 28
    {
      id: 'pescheria-antica',
      name: 'Antica Pescheria',
      kind: 'restaurant',
      neighbourhood: 'Ortigia',
      real: false,
      characterId: 'salvatore-pesce',
      imagePrompt: 'Soft pastel sketch on white paper of seafood restaurant with nautical decor, fresh catch displayed on ice at entrance, simple tables with sea views, fishing nets and anchors on walls, crisp white and ocean blue, maritime and fresh',
    },
    {
      id: 'bar-minerva',
      name: 'Bar Minerva',
      kind: 'bar',
      neighbourhood: 'Tyche',
      real: false,
      characterId: 'filippo-minerva',
      imagePrompt: 'Soft pastel sketch on white paper of neighborhood bar with locals playing cards, espresso machine hissing, pastries under glass dome, lottery tickets and newspapers, small TV in corner, worn but loved atmosphere, warm browns and yellows, community and daily life',
    },
    {
      id: 'orto-botanico',
      name: 'Giardino Pubblico',
      kind: 'garden',
      neighbourhood: 'Acradina',
      real: false,
      characterId: 'gino-giardiniere',
      imagePrompt: 'Soft pastel sketch on white paper of public garden with palm trees and Mediterranean plants, stone benches, elderly men playing chess, mothers with children, gravel paths, flowering bougainvillea, dappled shade, soft pinks and greens, peaceful and communal',
    },
    {
      id: 'macelleria-tradizionale',
      name: 'Macelleria Greco',
      kind: 'butcher',
      neighbourhood: 'Acradina',
      real: false,
      characterId: 'antonio-macellaio',
      imagePrompt: 'Soft pastel sketch on white paper of traditional butcher shop with hanging salamis, display case of fresh meats, marble counter, sawdust on floor, handwritten price signs, professional knives, red and white tones, traditional and professional',
    },
  ],
  characters: [
    {
      id: 'salvatore-bar',
      name: 'Salvatore Greco',
      age: 52,
      role: 'proprietario',
      placeId: 'bar-dolce-vita',
      personality: ['jovial', 'talkative', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stout middle-aged Sicilian man with salt-and-pepper hair, warm smile lines around eyes, wearing crisp white shirt, minimal watercolor wash of warm skin tones and dark hair, Mediterranean features, expressive and welcoming, white background',
    },
    {
      id: 'rosa-caffe',
      name: 'Rosa Battaglia',
      age: 38,
      role: 'barista',
      placeId: 'caffe-archimede',
      personality: ['efficient', 'observant', 'witty'],
      portraitPrompt: 'Pen and ink portrait on white paper of a slender woman with dark hair pulled back in neat bun, intelligent eyes, delicate gold earrings, minimal watercolor wash of olive skin and deep brown eyes, elegant bone structure, knowing smile, white background',
    },
    {
      id: 'giuseppe-apollo',
      name: 'Giuseppe Marino',
      age: 67,
      role: 'barista',
      placeId: 'bar-apollo',
      personality: ['philosophical', 'patient', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly man with deeply lined face, white mustache, kind eyes behind reading glasses, minimal watercolor wash of weathered skin and silver hair, dignified expression, wise and gentle, white background',
    },
    {
      id: 'angela-panificio',
      name: 'Angela Fontana',
      age: 45,
      role: 'fornaia',
      placeId: 'panificio-regina',
      personality: ['nurturing', 'proud', 'early-riser'],
      portraitPrompt: 'Pen and ink portrait on white paper of a round-faced woman with flour-dusted apron, strong arms, hair in practical braid, minimal watercolor wash of rosy cheeks and warm brown eyes, maternal smile, capable hands, white background',
    },
    {
      id: 'carmelo-pasticceria',
      name: 'Carmelo Russo',
      age: 41,
      role: 'pasticciere',
      placeId: 'pasticceria-santa-lucia',
      personality: ['perfectionist', 'artistic', 'meticulous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined man with carefully trimmed beard, focused expression, chef\'s whites, minimal watercolor wash of light olive skin and dark eyes, artistic fingers, concentrated and precise, white background',
    },
    {
      id: 'pietro-mercato',
      name: 'Pietro D\'Amico',
      age: 58,
      role: 'venditore',
      placeId: 'mercato-ortigia',
      personality: ['boisterous', 'honest', 'humorous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust man with weathered face, loud voice suggested in expression, work cap, open collar, minimal watercolor wash of sun-bronzed skin, laugh lines, energetic and charismatic, white background',
    },
    {
      id: 'francesca-verdura',
      name: 'Francesca Vitale',
      age: 35,
      role: 'venditrice',
      placeId: 'mercato-acradina',
      personality: ['knowledgeable', 'friendly', 'local'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with practical ponytail, bright eyes, ready smile, work apron, minimal watercolor wash of fresh complexion and dark hair, energetic and approachable, white background',
    },
    {
      id: 'tonino-pesce',
      name: 'Tonino Sciacca',
      age: 49,
      role: 'pescivendolo',
      placeId: 'pescheria-mare',
      personality: ['straightforward', 'expert', 'maritime'],
      portraitPrompt: 'Pen and ink portrait on white paper of a lean man with weathered fisherman face, intense gaze, rubber boots suggested, minimal watercolor wash of sea-weathered skin, knowing eyes, strong and authentic, white background',
    },
    {
      id: 'lorenzo-dioniso',
      name: 'Lorenzo Greco',
      age: 44,
      role: 'chef',
      placeId: 'ristorante-dioniso',
      personality: ['passionate', 'traditional', 'demanding'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man with graying temples, intense dark eyes, chef\'s jacket, minimal watercolor wash of Mediterranean complexion, determined expression, culinary artist, white background',
    },
    {
      id: 'isabella-luna',
      name: 'Isabella Caruso',
      age: 36,
      role: 'proprietaria',
      placeId: 'ristorante-luna',
      personality: ['elegant', 'attentive', 'gracious'],
      portraitPrompt: 'Pen and ink portrait on white paper of a beautiful woman with sophisticated updo, pearl earrings, graceful neck, minimal watercolor wash of luminous skin and hazel eyes, refined smile, poised and welcoming, white background',
    },
    {
      id: 'maria-trattoria',
      name: 'Maria Lombardo',
      age: 61,
      role: 'cuoca',
      placeId: 'trattoria-aretusa',
      personality: ['motherly', 'no-nonsense', 'skilled'],
      portraitPrompt: 'Pen and ink portrait on white paper of a matronly woman with strong features, hair in traditional bun, gold cross necklace, minimal watercolor wash of warm skin and dark eyes, loving but firm expression, white background',
    },
    {
      id: 'vincenzo-osteria',
      name: 'Vincenzo Catalano',
      age: 55,
      role: 'oste',
      placeId: 'osteria-siciliana',
      personality: ['storyteller', 'welcoming', 'wine-lover'],
      portraitPrompt: 'Pen and ink portrait on white paper of a jovial man with generous belly, merry eyes, vest over shirt, minimal watercolor wash of ruddy cheeks and graying hair, glass of wine suggested, convivial and warm, white background',
    },
    {
      id: 'padre-antonio',
      name: 'Padre Antonio Serra',
      age: 68,
      role: 'sacerdote',
      placeId: 'duomo-siracusa',
      personality: ['scholarly', 'gentle', 'historical'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly priest with kind lined face, wire-rimmed glasses, clerical collar, minimal watercolor wash of pale skin and white hair, benevolent expression, learned and peaceful, white background',
    },
    {
      id: 'elena-guide',
      name: 'Elena Ragusa',
      age: 29,
      role: 'guida turistica',
      placeId: 'fonte-aretusa',
      personality: ['enthusiastic', 'educated', 'multilingual'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with animated expression, modern glasses, professional scarf, minimal watercolor wash of bright eyes and natural beauty, intelligent and engaging, white background',
    },
    {
      id: 'marco-archeologo',
      name: 'Marco Alberti',
      age: 53,
      role: 'archeologo',
      placeId: 'parco-archeologico',
      personality: ['passionate', 'academic', 'patient'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished scholar with sun hat suggested, weathered face from outdoor work, thoughtful expression, minimal watercolor wash of tanned skin and gray-streaked hair, dedicated and knowledgeable, white background',
    },
    {
      id: 'alberto-piazza',
      name: 'Alberto Messina',
      age: 72,
      role: 'pensionato',
      placeId: 'piazza-archimede',
      personality: ['sociable', 'opinionated', 'local fixture'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly gentleman with dignified bearing, newspaper under arm suggested, flat cap, minimal watercolor wash of weathered face and white hair, knowing smile, community elder, white background',
    },
    {
      id: 'suor-gabriella',
      name: 'Suor Gabriella',
      age: 43,
      role: 'suora',
      placeId: 'santuario-madonna',
      personality: ['serene', 'compassionate', 'modern'],
      portraitPrompt: 'Pen and ink portrait on white paper of a nun with gentle face, simple habit, peaceful eyes, minimal watercolor wash of soft features and kind expression, spiritual grace, contemporary devotion, white background',
    },
    {
      id: 'stefano-vino',
      name: 'Stefano Nicolosi',
      age: 39,
      role: 'enotecario',
      placeId: 'enoteca-bacco',
      personality: ['sophisticated', 'knowledgeable', 'discerning'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined man with neat beard, wine-stained apron over button-down, minimal watercolor wash of intelligent eyes and cultured expression, wine glass suggested, connoisseur, white background',
    },
    {
      id: 'claudia-sommelier',
      name: 'Claudia Romano',
      age: 33,
      role: 'sommelier',
      placeId: 'wine-bar-etna',
      personality: ['professional', 'adventurous', 'precise'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stylish woman with confident expression, sommelier pin on collar, minimal watercolor wash of striking features and dark hair, wine expertise in eyes, modern and knowledgeable, white background',
    },
    {
      id: 'beatrice-libri',
      name: 'Beatrice Moretti',
      age: 47,
      role: 'libraia',
      placeId: 'libreria-papiro',
      personality: ['literary', 'thoughtful', 'recommends well'],
      portraitPrompt: 'Pen and ink portrait on white paper of an intellectual woman with reading glasses on chain, gentle smile, book in hand suggested, minimal watercolor wash of kind eyes and graying hair, literary soul, welcoming, white background',
    },
    {
      id: 'dottore-ricci',
      name: 'Dott. Francesco Ricci',
      age: 56,
      role: 'farmacista',
      placeId: 'farmacia-apollo',
      personality: ['trustworthy', 'precise', 'caring'],
      portraitPrompt: 'Pen and ink portrait on white paper of a professional man with white pharmacist coat, wire glasses, reassuring expression, minimal watercolor wash of distinguished features, medical precision, dependable and kind, white background',
    },
    {
      id: 'roberto-stazione',
      name: 'Roberto Bianchi',
      age: 50,
      role: 'capostazione',
      placeId: 'stazione-siracusa',
      personality: ['punctual', 'helpful', 'efficient'],
      portraitPrompt: 'Pen and ink portrait on white paper of a uniformed station worker with official cap, whistle suggested, organized expression, minimal watercolor wash of professional bearing, dependable face, railway authority, white background',
    },
    {
      id: 'davide-storia',
      name: 'Davide Levi',
      age: 64,
      role: 'storico',
      placeId: 'antica-giudecca',
      personality: ['scholarly', 'preservationist', 'storyteller'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished historian with thoughtful eyes, slight stoop from study, minimal watercolor wash of intellectual face and gray beard, ancient knowledge, passionate keeper of memory, white background',
    },
    {
      id: 'arturo-papiro',
      name: 'Arturo Pappalardo',
      age: 58,
      role: 'artigiano',
      placeId: 'laboratorio-papiro',
      personality: ['traditional', 'skilled', 'patient teacher'],
      portraitPrompt: 'Pen and ink portrait on white paper of a craftsman with work-worn hands, concentration in eyes, artisan apron, minimal watercolor wash of weathered face, ancient craft in expression, dedicated and masterful, white background',
    },
    {
      id: 'lucia-gelato',
      name: 'Lucia Bellini',
      age: 27,
      role: 'gelataia',
      placeId: 'gelateria-nettuno',
      personality: ['cheerful', 'creative', 'sunny'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with bright smile, colorful apron, hair in playful style, minimal watercolor wash of fresh face and happy eyes, gelato scoop suggested, joyful and sweet, white background',
    },
    {
      id: 'giulia-ceramica',
      name: 'Giulia Terrana',
      age: 42,
      role: 'ceramista',
      placeId: 'bottega-ceramica',
      personality: ['artistic', 'traditional', 'colorful'],
      portraitPrompt: 'Pen and ink portrait on white paper of an artist with paint-stained fingers, creative eyes, colorful scarf, minimal watercolor wash of expressive face and paint smudges, Sicilian patterns suggested, vibrant and skilled, white background',
    },
    {
      id: 'salvatore-pesce',
      name: 'Salvatore Costa',
      age: 46,
      role: 'chef',
      placeId: 'pescheria-antica',
      personality: ['seafood expert', 'straightforward', 'quality-focused'],
      portraitPrompt: 'Pen and ink portrait on white paper of a chef with maritime background, strong features, white chef jacket, minimal watercolor wash of sea-loving eyes and capable hands, fresh fish expertise, authentic and direct, white background',
    },
    {
      id: 'filippo-minerva',
      name: 'Filippo Salerno',
      age: 63,
      role: 'barista',
      placeId: 'bar-minerva',
      personality: ['neighborhood fixture', 'card player', 'gossipy'],
      portraitPrompt: 'Pen and ink portrait on white paper of a local character with expressive face, vest and shirtsleeves, cards suggested, minimal watercolor wash of animated features, community hub personality, talkative and familiar, white background',
    },
    {
      id: 'gino-giardiniere',
      name: 'Gino Palmieri',
      age: 59,
      role: 'giardiniere',
      placeId: 'orto-botanico',
      personality: ['nature-loving', 'quiet', 'observant'],
      portraitPrompt: 'Pen and ink portrait on white paper of a gardener with sun-weathered face, work clothes, pruning shears suggested, minimal watercolor wash of earth-toned skin and peaceful eyes, plants are his language, gentle and wise, white background',
    },
    {
      id: 'antonio-macellaio',
      name: 'Antonio Greco',
      age: 51,
      role: 'macellaio',
      placeId: 'macelleria-tradizionale',
      personality: ['professional', 'third-generation', 'quality-obsessed'],
      portraitPrompt: 'Pen and ink portrait on white paper of a butcher with strong hands, white apron, traditional mustache, minimal watercolor wash of honest face and expert eyes, knife skills suggested, proud craftsman, trustworthy, white background',
    },
  ],
  food: [
    'arancini',
    'pasta alla Norma',
    'sarde a beccafico',
    'caponata',
    'cannoli',
    'cassata siciliana',
    'pasta con le sarde',
    'pesce spada',
    'panelle',
    'sfincione',
    'scaccia',
    'granita con brioche',
    'pistacchio di Bronte',
    'ricotta fresca',
    'gambero rosso di Mazara',
    'tonno rosso',
    'arance rosse',
    'limoni di Siracusa',
    'mandorle',
    'capperi',
    'olive',
    'pomodori pachino',
    'finocchietto selvatico',
    'bottarga',
  ],
  customs: [
    'La passeggiata lungo il lungomare di Ortigia',
    'Il mercato mattutino per il pesce fresco',
    'La granita con brioche per colazione d\'estate',
    'Le celebrazioni di Santa Lucia a dicembre',
    'Il teatro greco in estate',
    'L\'aperitivo in Piazza Duomo',
    'La raccolta del papiro alla Fonte Aretusa',
    'Le processioni religiose per le vie di Ortigia',
    'Il caffè al Bar dopo pranzo',
    'La domenica in famiglia con il pranzo lungo',
  ],
  localTouches: [
    'Minchia! - common Sicilian exclamation',
    'Picciriddu/Picciridda - boy/girl in Sicilian',
    'Bedda matri - "beautiful mother" (Madonna)',
    'Arriminati - "let\'s go" or "move it"',
    'U mari - the sea (in dialect)',
    'Semu - we are (Sicilian)',
    'Accussì - like this, this way',
    'Travagghiu - work (Sicilian)',
    'Bon appetitu - buon appetito in Sicilian',
    'Ciào beddu/bedda - hello beautiful (m/f)',
    'Chi bellizza! - what beauty!',
    'Manciàri - to eat (Sicilian verb)',
  ],
};
