import { CityPantry } from '@/lib/types';

export const taormina: CityPantry = {
  id: 'taormina',
  name: 'Taormina',
  neighbourhoods: ['Centro Storico', 'Corso Umberto', 'Teatro Greco', 'Castelmola'],
  places: [
    // BARS/CAFÉS (9)
    {
      id: 'bar-turrisi',
      name: 'Bar Turrisi',
      kind: 'bar',
      neighbourhood: 'Castelmola',
      real: true,
      characterId: 'paolo-turrisi',
      imagePrompt: 'Soft pastel sketch on white paper, warm terracotta and cream tones, charming Sicilian bar terrace with ceramic decorations and almond wine bottles, climbing bougainvillea in magenta, distant view of Mount Etna, Mediterranean light, textured, inviting atmosphere',
    },
    {
      id: 'caffe-wunderbar',
      name: 'Caffè Wunderbar',
      kind: 'bar',
      neighbourhood: 'Corso Umberto',
      real: true,
      characterId: 'giuliana-rosi',
      imagePrompt: 'Soft pastel sketch on white paper, elegant café with historic charm, vintage interior in warm beiges and gold, outdoor tables on the corso with striped awning, morning light filtering through, coffee cups and cornetti displayed, textured, sophisticated ambiance',
    },
    {
      id: 'bar-san-giorgio',
      name: 'Bar San Giorgio',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'salvatore-greco',
      imagePrompt: 'Soft pastel sketch on white paper, traditional Sicilian bar with marble counter, warm amber and cream colors, vintage espresso machine gleaming, shelves of liqueurs and granita flavors, morning sunlight through arched doorway, textured, authentic local feel',
    },
    {
      id: 'bar-morgana',
      name: 'Bar Morgana',
      kind: 'bar',
      neighbourhood: 'Teatro Greco',
      real: false,
      characterId: 'alessia-morgana',
      imagePrompt: 'Soft pastel sketch on white paper, modern bar with ancient stone walls visible, soft grays and rose tones, granita machine with vibrant fruit colors, view of the Greek theater through window, morning light, textured, blend of old and new',
    },
    {
      id: 'bar-panoramico',
      name: 'Bar Panoramico',
      kind: 'bar',
      neighbourhood: 'Castelmola',
      real: false,
      characterId: 'vincenzo-costa',
      imagePrompt: 'Soft pastel sketch on white paper, mountaintop bar with breathtaking views, warm ochre and sky blue tones, outdoor terrace with colorful cushions, almond blossoms in spring, Mediterranean panorama, textured, airy and elevated atmosphere',
    },
    {
      id: 'caffe-duomo',
      name: 'Caffè del Duomo',
      kind: 'bar',
      neighbourhood: 'Corso Umberto',
      real: false,
      characterId: 'rosa-battaglia',
      imagePrompt: 'Soft pastel sketch on white paper, café facing cathedral square, warm honey and white tones, elegant outdoor seating with wrought iron chairs, cathedral steps in background, aperitivo setup with Aperol spritz, golden hour light, textured, romantic setting',
    },
    {
      id: 'bar-etna',
      name: 'Bar Etna',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'marco-ferrara',
      imagePrompt: 'Soft pastel sketch on white paper, local neighborhood bar, earthy terracotta and deep blue tones, locals reading newspapers, pastries under glass dome, vintage Campari posters, morning ritual atmosphere, textured, community gathering spot',
    },
    {
      id: 'bar-timoleone',
      name: 'Bar Timoleone',
      kind: 'bar',
      neighbourhood: 'Teatro Greco',
      real: false,
      characterId: 'giancarlo-russo',
      imagePrompt: 'Soft pastel sketch on white paper, artistic bar near ancient theater, warm sienna and sage green tones, vintage photographs of old Taormina, espresso cups lined up, gelato display, cultural atmosphere, textured, historic charm',
    },
    {
      id: 'bar-belvedere',
      name: 'Bar Belvedere',
      kind: 'bar',
      neighbourhood: 'Corso Umberto',
      real: false,
      characterId: 'francesca-marino',
      imagePrompt: 'Soft pastel sketch on white paper, elegant bar with terrace overlooking sea, soft peach and turquoise tones, morning brioche spread, fresh orange juice, flowering plants, coastal breeze atmosphere, textured, uplifting and fresh',
    },

    // BAKERIES (4)
    {
      id: 'pasticceria-etna',
      name: 'Pasticceria Etna',
      kind: 'bakery',
      neighbourhood: 'Corso Umberto',
      real: true,
      characterId: 'antonio-messina',
      imagePrompt: 'Soft pastel sketch on white paper, traditional Sicilian pastry shop, warm golden and cream tones, display cases filled with cannoli and cassata, colorful marzipan fruits, almond pastries, sweet aroma suggested by warm colors, textured, irresistible sweetness',
    },
    {
      id: 'panificio-san-pancrazio',
      name: 'Panificio San Pancrazio',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'carmela-rizzo',
      imagePrompt: 'Soft pastel sketch on white paper, artisan bread bakery, rustic wheat and terracotta tones, wooden shelves with pane siciliano, sesame seed bread, wood-fired oven glow, flour dust in morning light, textured, warm and aromatic',
    },
    {
      id: 'dolceria-naxos',
      name: 'Dolceria Naxos',
      kind: 'bakery',
      neighbourhood: 'Teatro Greco',
      real: false,
      characterId: 'giuseppe-greco',
      imagePrompt: 'Soft pastel sketch on white paper, sweet shop specializing in almond treats, soft cream and pistachio green tones, displays of granita, arancini, sfogliatelle, traditional ceramic tiles, textured, Sicilian abundance',
    },
    {
      id: 'forno-castelmola',
      name: 'Forno di Castelmola',
      kind: 'bakery',
      neighbourhood: 'Castelmola',
      real: false,
      characterId: 'maria-costa',
      imagePrompt: 'Soft pastel sketch on white paper, mountain village bakery, warm amber and honey tones, rustic stone interior, fresh bread cooling on racks, local cookies with almonds, cozy village atmosphere, textured, homey and traditional',
    },

    // MARKETS (3)
    {
      id: 'mercato-giardini',
      name: 'Mercato di Giardini Naxos',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'filippo-verde',
      imagePrompt: 'Soft pastel sketch on white paper, vibrant Sicilian market, rich greens and reds of produce, citrus pyramids, tomatoes, eggplants, fresh fish on ice, vendor stalls with striped awnings, bustling morning energy, textured, sensory abundance',
    },
    {
      id: 'mercato-corso',
      name: 'Mercatino del Corso',
      kind: 'market',
      neighbourhood: 'Corso Umberto',
      real: false,
      characterId: 'concetta-luciano',
      imagePrompt: 'Soft pastel sketch on white paper, small daily market, warm earth tones, local vegetables and herbs, wild fennel, capers, sun-dried tomatoes, handwoven baskets, intimate neighborhood scale, textured, authentic local shopping',
    },
    {
      id: 'pescheria-sirena',
      name: 'Pescheria La Sirena',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'angelo-marina',
      imagePrompt: 'Soft pastel sketch on white paper, fresh fish market, cool silver and blue tones, swordfish, red prawns, sardines on ice, marble counters, Mediterranean catch displayed artfully, morning market bustle, textured, fresh sea atmosphere',
    },

    // RESTAURANTS (4)
    {
      id: 'ristorante-baronessa',
      name: 'Ristorante La Baronessa',
      kind: 'ristorante',
      neighbourhood: 'Corso Umberto',
      real: false,
      characterId: 'stefano-barone',
      imagePrompt: 'Soft pastel sketch on white paper, elegant restaurant terrace, warm rose and cream tones, white tablecloths, lemon trees in terra cotta pots, view of coastline, candlelit tables, romantic fine dining atmosphere, textured, sophisticated Sicily',
    },
    {
      id: 'trattoria-nonna',
      name: 'Trattoria da Nonna Carla',
      kind: 'trattoria',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'carla-messina',
      imagePrompt: 'Soft pastel sketch on white paper, family-run trattoria, warm ochre and tomato red tones, checkered tablecloths, hanging garlic and peppers, handwritten menu on chalkboard, homey Sicilian cooking atmosphere, textured, welcoming comfort',
    },
    {
      id: 'osteria-antica',
      name: 'Osteria Antica Taormina',
      kind: 'osteria',
      neighbourhood: 'Teatro Greco',
      real: false,
      characterId: 'domenico-greco',
      imagePrompt: 'Soft pastel sketch on white paper, historic osteria in ancient stone building, warm amber and burgundy tones, wine barrels, exposed beams, local salumi hanging, candles in wine bottles, rustic elegance, textured, timeless tradition',
    },
    {
      id: 'ristorante-bellavista',
      name: 'Ristorante Bellavista',
      kind: 'ristorante',
      neighbourhood: 'Castelmola',
      real: false,
      characterId: 'emilia-valentino',
      imagePrompt: 'Soft pastel sketch on white paper, restaurant with panoramic terrace, soft blue and white tones, pergola with grapevines, stunning Etna views, seafood platters, sunset dining atmosphere, textured, breathtaking setting',
    },

    // SPECIALTY FOOD (3)
    {
      id: 'pizzeria-nettuno',
      name: 'Pizzeria Nettuno',
      kind: 'pizzeria',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'luca-forno',
      imagePrompt: 'Soft pastel sketch on white paper, traditional pizzeria, warm red and wheat tones, wood-fired oven blazing, pizza being stretched, fresh mozzarella and basil, casual dining tables, delicious informal atmosphere, textured, pizza perfection',
    },
    {
      id: 'gelateria-paradiso',
      name: 'Gelateria Il Paradiso',
      kind: 'gelateria',
      neighbourhood: 'Corso Umberto',
      real: false,
      characterId: 'isabella-dolce',
      imagePrompt: 'Soft pastel sketch on white paper, artisanal gelato shop, vibrant pistachio green and lemon yellow tones, display case with colorful gelato, fresh fruit garnishes, marble counter, summer evening atmosphere, textured, sweet indulgence',
    },
    {
      id: 'salumeria-sicilia',
      name: 'Salumeria Sicilia',
      kind: 'salumeria',
      neighbourhood: 'Corso Umberto',
      real: false,
      characterId: 'roberto-salvo',
      imagePrompt: 'Soft pastel sketch on white paper, traditional delicatessen, rich burgundy and cream tones, hanging salumi and prosciutto, wheels of pecorino, olive oil bottles, capers and preserves, aromatic abundance, textured, gourmet Sicily',
    },

    // CULTURAL/LANDMARKS (5)
    {
      id: 'teatro-greco',
      name: 'Teatro Antico di Taormina',
      kind: 'landmark',
      neighbourhood: 'Teatro Greco',
      real: true,
      characterId: 'dario-storia',
      imagePrompt: 'Soft pastel sketch on white paper, ancient Greek theater ruins, warm stone beige and sky blue tones, dramatic columns against Mount Etna backdrop, Mediterranean vista, archaeological majesty, afternoon light, textured, timeless grandeur',
    },
    {
      id: 'duomo-taormina',
      name: 'Duomo di Taormina',
      kind: 'church',
      neighbourhood: 'Corso Umberto',
      real: true,
      characterId: 'padre-benedetto',
      imagePrompt: 'Soft pastel sketch on white paper, medieval cathedral, warm cream and rose stone tones, fortress-like facade, baroque interior glimpse, quiet piazza in front, sacred peaceful atmosphere, textured, spiritual heritage',
    },
    {
      id: 'villa-comunale',
      name: 'Villa Comunale',
      kind: 'park',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'elena-giardini',
      imagePrompt: 'Soft pastel sketch on white paper, public gardens with exotic plants, lush green and floral tones, palm trees, Mediterranean flowers, stone paths, panoramic sea views, peaceful benches, textured, botanical paradise',
    },
    {
      id: 'piazza-ix-aprile',
      name: 'Piazza IX Aprile',
      kind: 'piazza',
      neighbourhood: 'Corso Umberto',
      real: true,
      characterId: 'massimo-piazza',
      imagePrompt: 'Soft pastel sketch on white paper, iconic town square with bell tower, warm terracotta and white tones, checkered pavement, café tables, stunning bay views, clock tower, social gathering space, textured, heart of Taormina',
    },
    {
      id: 'chiesa-varò',
      name: 'Chiesa della Madonna della Rocca',
      kind: 'church',
      neighbourhood: 'Castelmola',
      real: true,
      characterId: 'suor-agata',
      imagePrompt: 'Soft pastel sketch on white paper, church built into mountainside, warm stone and sky tones, rustic steps leading up, dramatic clifftop location, small sacred interior, pilgrimage atmosphere, textured, devotional beauty',
    },

    // WINE BARS/APERITIVO (2)
    {
      id: 'enoteca-nero',
      name: 'Enoteca Nero d\'Avola',
      kind: 'enoteca',
      neighbourhood: 'Corso Umberto',
      real: false,
      characterId: 'riccardo-vino',
      imagePrompt: 'Soft pastel sketch on white paper, sophisticated wine bar, deep burgundy and warm wood tones, shelves of Sicilian wines, wine barrels, tasting glasses, cheese and antipasti boards, evening atmosphere, textured, elegant wine culture',
    },
    {
      id: 'wine-bar-dioniso',
      name: 'Wine Bar Dioniso',
      kind: 'wine bar',
      neighbourhood: 'Teatro Greco',
      real: false,
      characterId: 'valentina-somma',
      imagePrompt: 'Soft pastel sketch on white paper, intimate wine bar near ancient ruins, warm amber and grape purple tones, outdoor seating, aperitivo spread, Etna wines featured, sunset hour, textured, cultural aperitivo experience',
    },

    // BOOKSHOP (1)
    {
      id: 'libreria-taormina',
      name: 'Libreria Taormina Antiquaria',
      kind: 'bookshop',
      neighbourhood: 'Corso Umberto',
      real: false,
      characterId: 'claudio-libri',
      imagePrompt: 'Soft pastel sketch on white paper, antique bookshop, warm sepia and cream tones, floor-to-ceiling shelves, rare books on Sicily, reading nook, literary atmosphere, afternoon light through window, textured, intellectual haven',
    },

    // PRACTICAL (2)
    {
      id: 'farmacia-centrale',
      name: 'Farmacia Centrale',
      kind: 'pharmacy',
      neighbourhood: 'Corso Umberto',
      real: false,
      characterId: 'dottoressa-laura',
      imagePrompt: 'Soft pastel sketch on white paper, traditional Italian pharmacy, clean white and green cross tones, wooden cabinets with remedies, professional counter, herbal preparations, trusted community resource, textured, healthcare tradition',
    },
    {
      id: 'funivia-taormina',
      name: 'Funivia Taormina-Mazzarò',
      kind: 'cable car',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'pietro-cabina',
      imagePrompt: 'Soft pastel sketch on white paper, cable car station, bright red and white tones, cars suspended over dramatic coastline, beach below, mountain above, transit connection, textured, scenic transportation',
    },

    // CITY CHARACTER (2)
    {
      id: 'ceramiche-siciliane',
      name: 'Ceramiche Siciliane d\'Arte',
      kind: 'ceramics shop',
      neighbourhood: 'Corso Umberto',
      real: false,
      characterId: 'andrea-ceramista',
      imagePrompt: 'Soft pastel sketch on white paper, ceramic art workshop and shop, vibrant blue, yellow, and green Sicilian patterns, hand-painted plates and vases, teste di moro, traditional motifs, artisan workspace, textured, colorful craftsmanship',
    },
    {
      id: 'terrazza-panoramica',
      name: 'Terrazza dei Poeti',
      kind: 'viewpoint',
      neighbourhood: 'Teatro Greco',
      real: false,
      characterId: 'federico-poeta',
      imagePrompt: 'Soft pastel sketch on white paper, scenic terrace overlook, soft lavender and azure tones, sweeping coastal panorama, Mount Etna in distance, romantic spot, poetic atmosphere, golden hour light, textured, inspirational vista',
    },
  ],
  characters: [
    {
      id: 'paolo-turrisi',
      name: 'Paolo Turrisi',
      age: 58,
      role: 'proprietario',
      placeId: 'bar-turrisi',
      personality: ['storyteller', 'proud', 'hospitable'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, Sicilian man in his late 50s, salt-and-pepper hair, warm smile with laugh lines, holding glass of almond wine, detailed cross-hatching, warm amber wash, welcoming expression, white background',
    },
    {
      id: 'giuliana-rosi',
      name: 'Giuliana Rosi',
      age: 42,
      role: 'barista',
      placeId: 'caffe-wunderbar',
      personality: ['elegant', 'observant', 'cultured'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, sophisticated Sicilian woman in her 40s, dark hair in elegant updo, pearl earrings, preparing espresso, fine line work, soft rose and cream wash, refined expression, white background',
    },
    {
      id: 'salvatore-greco',
      name: 'Salvatore Greco',
      age: 67,
      role: 'barista',
      placeId: 'bar-san-giorgio',
      personality: ['traditional', 'gruff but kind', 'local historian'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, elderly Sicilian barista, weathered face, thick gray mustache, white apron, detailed wrinkles showing character, sepia wash, knowing eyes, white background',
    },
    {
      id: 'alessia-morgana',
      name: 'Alessia Morgana',
      age: 29,
      role: 'barista',
      placeId: 'bar-morgana',
      personality: ['artistic', 'modern', 'passionate about granita'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, young Sicilian woman, long dark wavy hair, bright eyes, making granita, expressive line work, cool blue and lemon wash, creative energy, white background',
    },
    {
      id: 'vincenzo-costa',
      name: 'Vincenzo Costa',
      age: 55,
      role: 'proprietario',
      placeId: 'bar-panoramico',
      personality: ['philosophical', 'weathered', 'mountain lover'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, middle-aged Sicilian man, wind-touched skin, contemplative expression, looking toward mountains, detailed pen strokes, earth tone wash, serene presence, white background',
    },
    {
      id: 'rosa-battaglia',
      name: 'Rosa Battaglia',
      age: 38,
      role: 'cameriera',
      placeId: 'caffe-duomo',
      personality: ['gracious', 'romantic', 'devotional'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, Sicilian woman in late 30s, kind face, hair pulled back, serving aperitivo, gentle line work, warm peach wash, caring expression, white background',
    },
    {
      id: 'marco-ferrara',
      name: 'Marco Ferrara',
      age: 44,
      role: 'barista',
      placeId: 'bar-etna',
      personality: ['jovial', 'gossipy', 'neighborhood fixture'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, stocky Sicilian man in his 40s, friendly round face, animated expression, gesturing while talking, energetic line work, terracotta wash, convivial personality, white background',
    },
    {
      id: 'giancarlo-russo',
      name: 'Giancarlo Russo',
      age: 51,
      role: 'proprietario',
      placeId: 'bar-timoleone',
      personality: ['intellectual', 'theater lover', 'contemplative'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, distinguished Sicilian man, graying temples, reading glasses, holding espresso cup, refined pen work, sepia and sage wash, thoughtful gaze, white background',
    },
    {
      id: 'francesca-marino',
      name: 'Francesca Marino',
      age: 33,
      role: 'barista',
      placeId: 'bar-belvedere',
      personality: ['cheerful', 'health-conscious', 'sunrise enthusiast'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, young Sicilian woman, bright smile, fresh appearance, preparing fresh juice, clean line work, peachy morning light wash, optimistic energy, white background',
    },
    {
      id: 'antonio-messina',
      name: 'Antonio Messina',
      age: 62,
      role: 'pasticciere',
      placeId: 'pasticceria-etna',
      personality: ['perfectionist', 'sweet-tempered', 'master craftsman'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, master pastry chef, white chef hat, flour on hands, holding cannolo, detailed cross-hatching, golden cream wash, proud artisan, white background',
    },
    {
      id: 'carmela-rizzo',
      name: 'Carmela Rizzo',
      age: 56,
      role: 'fornaia',
      placeId: 'panificio-san-pancrazio',
      personality: ['nurturing', 'early riser', 'strong'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, sturdy Sicilian baker woman, hair in bun under scarf, strong arms, holding fresh bread, bold line work, wheat tone wash, maternal strength, white background',
    },
    {
      id: 'giuseppe-greco',
      name: 'Giuseppe Greco',
      age: 48,
      role: 'pasticciere',
      placeId: 'dolceria-naxos',
      personality: ['generous', 'traditional', 'family-focused'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, Sicilian pastry maker, warm face, white apron, arranging marzipan fruits, careful detail work, pistachio green wash, welcoming smile, white background',
    },
    {
      id: 'maria-costa',
      name: 'Maria Costa',
      age: 71,
      role: 'fornaia',
      placeId: 'forno-castelmola',
      personality: ['wise', 'village matriarch', 'keeper of recipes'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, elderly Sicilian baker, deeply lined face, traditional dress, hands dusted with flour, loving detail, warm amber wash, ancestral wisdom, white background',
    },
    {
      id: 'filippo-verde',
      name: 'Filippo Verde',
      age: 45,
      role: 'venditore',
      placeId: 'mercato-giardini',
      personality: ['boisterous', 'generous with samples', 'produce expert'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, market vendor, animated expression, holding citrus fruit, calling to customers, energetic pen strokes, vibrant green and orange wash, lively character, white background',
    },
    {
      id: 'concetta-luciano',
      name: 'Concetta Luciano',
      age: 59,
      role: 'venditrice',
      placeId: 'mercato-corso',
      personality: ['shrewd', 'fair', 'herbalist knowledge'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, market woman, sharp eyes, traditional headscarf, bunch of wild herbs in hand, precise line work, herb green wash, knowing expression, white background',
    },
    {
      id: 'angelo-marina',
      name: 'Angelo Marina',
      age: 52,
      role: 'pescivendolo',
      placeId: 'pescheria-sirena',
      personality: ['salty humor', 'fisherman heritage', 'weather predictor'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, fishmonger with weathered face, rubber apron, holding fresh swordfish, textured line work showing sea life, cool blue wash, maritime character, white background',
    },
    {
      id: 'stefano-barone',
      name: 'Stefano Barone',
      age: 41,
      role: 'chef',
      placeId: 'ristorante-baronessa',
      personality: ['refined', 'ambitious', 'Michelin-dreaming'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, elegant chef in whites, carefully plating dish, focused expression, fine detailed work, subtle rose wash, culinary artistry, white background',
    },
    {
      id: 'carla-messina',
      name: 'Carla Messina',
      age: 68,
      role: 'cuoca',
      placeId: 'trattoria-nonna',
      personality: ['motherly', 'no-nonsense', 'recipe guardian'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, grandmother chef, apron over traditional dress, wooden spoon in hand, warm wrinkled face, loving detail, tomato red wash, nurturing presence, white background',
    },
    {
      id: 'domenico-greco',
      name: 'Domenico Greco',
      age: 57,
      role: 'oste',
      placeId: 'osteria-antica',
      personality: ['storytelling', 'wine knowledgeable', 'history buff'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, osteria keeper, salt-and-pepper beard, holding wine bottle, tales in his eyes, rich cross-hatching, burgundy wash, convivial host, white background',
    },
    {
      id: 'emilia-valentino',
      name: 'Emilia Valentino',
      age: 39,
      role: 'chef',
      placeId: 'ristorante-bellavista',
      personality: ['ambitious', 'sunset-obsessed', 'seafood specialist'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, female chef with determined look, chef whites, presenting seafood dish, confident line work, soft blue wash, professional pride, white background',
    },
    {
      id: 'luca-forno',
      name: 'Luca Forno',
      age: 35,
      role: 'pizzaiolo',
      placeId: 'pizzeria-nettuno',
      personality: ['energetic', 'theatrical', 'dough perfectionist'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, young pizzaiolo tossing dough, muscular forearms, flour in air, dynamic motion lines, warm wheat wash, joyful mastery, white background',
    },
    {
      id: 'isabella-dolce',
      name: 'Isabella Dolce',
      age: 27,
      role: 'gelataia',
      placeId: 'gelateria-paradiso',
      personality: ['creative', 'flavor experimenter', 'Instagram savvy'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, young gelato maker, bright eyes, scooping pistachio gelato, cheerful expression, playful line work, colorful gelato wash, sweet enthusiasm, white background',
    },
    {
      id: 'roberto-salvo',
      name: 'Roberto Salvo',
      age: 64,
      role: 'salumiere',
      placeId: 'salumeria-sicilia',
      personality: ['exacting', 'proud Sicilian', 'salumi poet'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, dignified delicatessen owner, slicing prosciutto with precision, serious concentration, detailed technique, burgundy wash, artisan dedication, white background',
    },
    {
      id: 'dario-storia',
      name: 'Dario Storia',
      age: 53,
      role: 'guida turistica',
      placeId: 'teatro-greco',
      personality: ['eloquent', 'theatrical', 'classicist'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, tour guide gesturing dramatically, passionate expression, ancient columns behind, expressive line work, stone beige wash, bringing history alive, white background',
    },
    {
      id: 'padre-benedetto',
      name: 'Padre Benedetto',
      age: 66,
      role: 'sacerdote',
      placeId: 'duomo-taormina',
      personality: ['gentle', 'multilingual', 'art historian'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, elderly priest in cassock, kind weathered face, hands in prayer gesture, soft detailed work, subtle rose wash, peaceful devotion, white background',
    },
    {
      id: 'elena-giardini',
      name: 'Elena Giardini',
      age: 46,
      role: 'giardiniera',
      placeId: 'villa-comunale',
      personality: ['botanical expert', 'patient', 'English garden lover'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, gardener with sun hat, gentle smile, holding pruning shears, surrounded by botanical sketches, green leaf wash, peaceful dedication, white background',
    },
    {
      id: 'massimo-piazza',
      name: 'Massimo Piazza',
      age: 43,
      role: 'musicista di strada',
      placeId: 'piazza-ix-aprile',
      personality: ['romantic', 'observant', 'mandolin virtuoso'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, street musician with mandolin, expressive face mid-song, musician hands detailed, warm terracotta wash, artistic soul, white background',
    },
    {
      id: 'suor-agata',
      name: 'Suor Agata',
      age: 72,
      role: 'suora',
      placeId: 'chiesa-varò',
      personality: ['serene', 'pilgrimage guide', 'contemplative'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, elderly nun in habit, peaceful lined face, hands holding rosary, spiritual presence, soft gray-blue wash, devotional calm, white background',
    },
    {
      id: 'riccardo-vino',
      name: 'Riccardo Vino',
      age: 37,
      role: 'sommelier',
      placeId: 'enoteca-nero',
      personality: ['sophisticated', 'wine educator', 'Etna wine evangelist'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, sommelier examining wine glass, refined features, wine stains on apron, expert concentration, deep red wash, oenological passion, white background',
    },
    {
      id: 'valentina-somma',
      name: 'Valentina Somma',
      age: 31,
      role: 'sommelier',
      placeId: 'wine-bar-dioniso',
      personality: ['knowledgeable', 'aperitivo enthusiast', 'volcanic terroir expert'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, female sommelier pouring wine at sunset, elegant profile, wine bottle in hand, graceful line work, purple-amber wash, sophisticated warmth, white background',
    },
    {
      id: 'claudio-libri',
      name: 'Claudio Libri',
      age: 61,
      role: 'libraio',
      placeId: 'libreria-taormina',
      personality: ['scholarly', 'bibliophile', 'multilingual'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, bookseller with reading glasses on chain, holding rare volume, surrounded by books, detailed crosshatching, sepia wash, literary knowledge, white background',
    },
    {
      id: 'dottoressa-laura',
      name: 'Dottoressa Laura Salerno',
      age: 49,
      role: 'farmacista',
      placeId: 'farmacia-centrale',
      personality: ['professional', 'trusted advisor', 'herbal medicine advocate'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, pharmacist in white coat, competent expression, preparing prescription, clean precise lines, mint green wash, healthcare professional, white background',
    },
    {
      id: 'pietro-cabina',
      name: 'Pietro Cabina',
      age: 54,
      role: 'operatore funivia',
      placeId: 'funivia-taormina',
      personality: ['patient', 'height-loving', 'reassuring'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, cable car operator in uniform, calm steady presence, control panel visible, reliable expression, sky blue wash, mountain professional, white background',
    },
    {
      id: 'andrea-ceramista',
      name: 'Andrea Ceramista',
      age: 44,
      role: 'artigiano',
      placeId: 'ceramiche-siciliane',
      personality: ['artistic', 'traditional patterns master', 'patient teacher'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, ceramic artist painting traditional design, focused concentration, paint-stained hands, detailed brush work, vibrant Sicilian color wash, creative dedication, white background',
    },
    {
      id: 'federico-poeta',
      name: 'Federico Poeta',
      age: 36,
      role: 'poeta locale',
      placeId: 'terrazza-panoramica',
      personality: ['dreamer', 'romantic', 'sunset worshipper'],
      portraitPrompt: 'Pen and ink portrait on white paper with minimal watercolor wash, young poet with notebook, wind-swept hair, gazing at vista, thoughtful eyes, flowing line work, lavender-gold wash, artistic soul, white background',
    },
  ],
  food: [
    'arancini',
    'cannoli',
    'cassata siciliana',
    'pasta alla Norma',
    'caponata',
    'pasta con le sarde',
    'pesce spada',
    'involtini di pesce spada',
    'granita al limone',
    'granita di mandorla',
    'brioche col tuppo',
    'pane cunzato',
    'panelle',
    'sfincione',
    'marzapane',
    'frutta martorana',
    'pistacchio di Bronte',
    'capperi',
    'pomodori secchi',
    'melanzane',
    'ricotta salata',
    'vino dell\'Etna',
    'vino Nero d\'Avola',
    'limoncello',
    'amaro Averna',
  ],
  customs: [
    'La passeggiata along Corso Umberto in the evening',
    'Drinking vino alla mandorla (almond wine) in Castelmola',
    'Granita con brioche for breakfast in summer',
    'Attending performances at Teatro Greco',
    'Watching sunset from Piazza IX Aprile',
    'Shopping for ceramics with traditional Sicilian motifs',
    'Taking the funivia down to Isola Bella beach',
    'Aperitivo hour with views of Mount Etna',
    'Festival of San Pancrazio (patron saint) celebrations',
    'Easter processions through medieval streets',
  ],
  localTouches: [
    'Saying "Trizza!" (Sicilian for "cheers!")',
    'Referring to Mount Etna as "Idda" (she/her)',
    'Using "Picciotto/Picciotta" for young man/woman',
    'Greeting with "Bedda Matri!" (beautiful mother - expression of surprise)',
    'Calling a friend "Cumpà" or "Cummà"',
    'Saying "Minchia!" as an exclamation',
    'Using "Tutto apposto?" (Everything okay?) as greeting',
    'Describing something beautiful as "Bedda/Beddu"',
  ],
};
