import { CityPantry } from '@/lib/types';

export const torino: CityPantry = {
  id: 'torino',
  name: 'Torino',
  neighbourhoods: ['Centro', 'Quadrilatero Romano', 'San Salvario', 'Crocetta'],
  places: [
    // BARS/CAFÉS (3)
    {
      id: 'caffe-san-carlo',
      name: 'Caffè San Carlo',
      kind: 'bar',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'michele-barista',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant historic Torinese café with ornate chandeliers, gilded mirrors, and marble-topped tables. Rich golds, deep reds, and warm creams. Atmospheric light filtering through tall windows onto the classic bar counter. Textured, inviting, nostalgic.',
    },
    {
      id: 'bicerin-dal-1763',
      name: 'Al Bicerin',
      kind: 'bar',
      neighbourhood: 'Quadrilatero Romano',
      real: true,
      characterId: 'franca-proprietaria',
      imagePrompt: 'Soft pastel sketch on white paper of a tiny traditional café with dark wood paneling, antique coffee equipment, and small marble tables. Warm browns, ivory, and chocolate tones. Intimate, cozy atmosphere with vintage character. Soft morning light, textured walls, inviting.',
    },
    {
      id: 'caffe-mulassano',
      name: 'Caffè Mulassano',
      kind: 'bar',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'roberto-cameriere',
      imagePrompt: 'Soft pastel sketch on white paper of an Art Nouveau café with stained glass, polished wood bar, and Belle Époque details. Emerald greens, amber, and cream colors. Elegant Torinese atmosphere with display of tramezzini. Warm, textured, historic charm.',
    },
    
    // BAKERIES (2)
    {
      id: 'panetteria-borgo-antico',
      name: 'Panetteria Borgo Antico',
      kind: 'bakery',
      neighbourhood: 'Quadrilatero Romano',
      real: false,
      characterId: 'giuseppe-fornaio',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional bakery with wooden shelves filled with grissini torinesi, focaccia, and fresh bread. Golden yellows, wheat tones, warm ochre. Flour-dusted counter, brick oven visible in background. Inviting, warm, artisanal feel.',
    },
    {
      id: 'pasticceria-stratta',
      name: 'Pasticceria Stratta',
      kind: 'bakery',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'claudia-pasticciera',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant historic pastry shop with glass display cases of giandujotti, cakes, and pralines. Soft pinks, chocolate browns, gold accents. Refined Torinese elegance, vintage charm. Warm lighting, textured, luxurious yet inviting.',
    },
    
    // MARKETS (3)
    {
      id: 'mercato-porta-palazzo',
      name: 'Mercato di Porta Palazzo',
      kind: 'market',
      neighbourhood: 'Quadrilatero Romano',
      real: true,
      characterId: 'anna-fruttivendola',
      imagePrompt: 'Soft pastel sketch on white paper of a bustling outdoor market with colorful produce stalls, awnings, and vendors. Vibrant vegetable greens, tomato reds, sunny yellows. Lively European market atmosphere, cobblestones, morning light. Textured, energetic, inviting.',
    },
    {
      id: 'mercato-crocetta',
      name: 'Mercato Crocetta',
      kind: 'market',
      neighbourhood: 'Crocetta',
      real: true,
      characterId: 'paolo-venditore',
      imagePrompt: 'Soft pastel sketch on white paper of a covered neighborhood market hall with stalls of cheese, meat, and fresh produce. Warm terracotta, cream, and forest green tones. Local market atmosphere, friendly vendors, natural light from skylights. Inviting, community feel.',
    },
    {
      id: 'eataly-torino',
      name: 'Eataly Lingotto',
      kind: 'market',
      neighbourhood: 'San Salvario',
      real: true,
      characterId: 'davide-commesso',
      imagePrompt: 'Soft pastel sketch on white paper of a modern gourmet food market with sections for pasta, wine, cheese, and produce. Warm earth tones, deep reds, Italian flag colors. Contemporary yet traditional Italian food temple. Bright, textured, abundant.',
    },
    
    // RESTAURANTS (2)
    {
      id: 'ristorante-del-cambio',
      name: 'Ristorante Del Cambio',
      kind: 'ristorante',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'stefano-maitre',
      imagePrompt: 'Soft pastel sketch on white paper of an opulent historical restaurant with frescoed ceilings, crystal chandeliers, and white tablecloths. Rich burgundy, gold, ivory tones. Regal Torinese elegance, Savoy-era grandeur. Warm candlelight, textured, refined.',
    },
    {
      id: 'ristorante-consorzio',
      name: 'Ristorante Consorzio',
      kind: 'ristorante',
      neighbourhood: 'San Salvario',
      real: true,
      characterId: 'giulia-chef',
      imagePrompt: 'Soft pastel sketch on white paper of a contemporary Piemontese restaurant with exposed brick, modern lighting, and rustic wooden tables. Warm grays, brick red, natural wood tones. Modern yet traditional, open kitchen visible. Inviting, warm, sophisticated.',
    },
    
    // SPECIALTY FOOD (2)
    {
      id: 'trattoria-valenza',
      name: 'Trattoria Valenza',
      kind: 'trattoria',
      neighbourhood: 'Quadrilatero Romano',
      real: false,
      characterId: 'mario-oste',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy neighborhood trattoria with checkered tablecloths, wine bottles lining walls, and handwritten menu boards. Warm reds, cream, burgundy. Homey Piemontese atmosphere, intimate dining. Soft lighting, textured, welcoming.',
    },
    {
      id: 'osteria-antiche-sere',
      name: 'Osteria Antiche Sere',
      kind: 'osteria',
      neighbourhood: 'San Salvario',
      real: true,
      characterId: 'bruno-cuoco',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional osteria with vaulted brick ceilings, wooden tables, and rustic charm. Terracotta, warm yellows, deep wine reds. Authentic Piemontese tavern atmosphere. Candlelit, textured stone walls, inviting.',
    },
    
    // MAJOR LANDMARK (1)
    {
      id: 'mole-antonelliana',
      name: 'Mole Antonelliana',
      kind: 'landmark',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'elena-guida',
      imagePrompt: 'Soft pastel sketch on white paper of the iconic towering Mole Antonelliana with its distinctive spire against a soft sky. Slate grays, sky blues, warm stone tones. Majestic vertical perspective, surrounding Turin rooftops. Atmospheric, textured, monumental yet gentle.',
    },
    
    // CHURCHES/CULTURAL SITES (2)
    {
      id: 'duomo-torino',
      name: 'Duomo di Torino',
      kind: 'church',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'padre-luca',
      imagePrompt: 'Soft pastel sketch on white paper of a Renaissance cathedral with white marble façade, bell tower, and the Chapel of the Holy Shroud. Ivory white, soft grays, warm stone. Sacred, peaceful atmosphere, architectural details. Soft light, textured, reverent.',
    },
    {
      id: 'palazzo-reale',
      name: 'Palazzo Reale',
      kind: 'museum',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'isabella-curatrice',
      imagePrompt: 'Soft pastel sketch on white paper of a grand Baroque royal palace with ornate gates, formal gardens, and elegant façade. Regal golds, cream, soft greens from gardens. Savoy dynasty grandeur, majestic. Warm afternoon light, textured, palatial.',
    },
    
    // PARK (1)
    {
      id: 'parco-valentino',
      name: 'Parco del Valentino',
      kind: 'park',
      neighbourhood: 'San Salvario',
      real: true,
      characterId: 'giacomo-giardiniere',
      imagePrompt: 'Soft pastel sketch on white paper of a romantic riverside park with tree-lined paths, the Po River, and Castello del Valentino in background. Fresh greens, sky blues, soft earth tones. Peaceful, romantic atmosphere, dappled sunlight. Textured, inviting, serene.',
    },
    
    // PIAZZAS (2)
    {
      id: 'piazza-castello',
      name: 'Piazza Castello',
      kind: 'piazza',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'luca-musicista',
      imagePrompt: 'Soft pastel sketch on white paper of a grand baroque square with arcaded buildings, Palazzo Madama centerpiece, and people strolling. Warm ochre, soft grays, sky blue. Majestic Torinese urban space, elegant proportions. Atmospheric light, textured, vibrant.',
    },
    {
      id: 'piazza-vittorio-veneto',
      name: 'Piazza Vittorio Veneto',
      kind: 'piazza',
      neighbourhood: 'San Salvario',
      real: true,
      characterId: 'martina-artista',
      imagePrompt: 'Soft pastel sketch on white paper of one of Europe\'s largest squares with arcaded porticos, descending toward the Po River, and Monte dei Cappuccini beyond. Golden yellows, river blues, warm stone. Grand perspective, open sky. Textured, expansive, social.',
    },
    
    // WINE BARS/APERITIVO (2)
    {
      id: 'enoteca-bacco',
      name: 'Enoteca Bacco e Venere',
      kind: 'enoteca',
      neighbourhood: 'Quadrilatero Romano',
      real: false,
      characterId: 'simone-sommelier',
      imagePrompt: 'Soft pastel sketch on white paper of a sophisticated wine bar with floor-to-ceiling wine racks, cozy wooden tables, and warm lighting. Deep burgundy, forest green, warm amber. Intimate Piemontese wine culture atmosphere. Candlelit, textured, refined.',
    },
    {
      id: 'aperitivo-cult',
      name: 'Aperitivo & Cult',
      kind: 'wine bar',
      neighbourhood: 'San Salvario',
      real: false,
      characterId: 'valeria-bartender',
      imagePrompt: 'Soft pastel sketch on white paper of a trendy aperitivo bar with vintage furniture, Vermouth bottles displayed, and plates of aperitivo spread. Soft oranges, vintage teal, warm cream. Social Turin evening ritual atmosphere. Warm light, textured, lively.',
    },
    
    // BOOKSHOP (1)
    {
      id: 'libreria-luxemburg',
      name: 'Libreria Luxemburg',
      kind: 'bookshop',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'teresa-libraio',
      imagePrompt: 'Soft pastel sketch on white paper of an independent bookshop with wooden shelves packed with books, reading nooks, and literary posters. Warm browns, cream, sage green. Intellectual, cozy atmosphere, literary culture. Soft natural light, textured, intimate.',
    },
    
    // PHARMACY (1)
    {
      id: 'farmacia-centrale',
      name: 'Farmacia Centrale',
      kind: 'pharmacy',
      neighbourhood: 'Crocetta',
      real: false,
      characterId: 'dottoressa-carla',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional Italian pharmacy with dark wood cabinets, white coat service, and vintage apothecary jars. Clean whites, medical greens, warm wood tones. Professional, historic charm. Bright, textured, trustworthy.',
    },
    
    // TRANSPORTATION HUB (1)
    {
      id: 'porta-nuova',
      name: 'Stazione di Porta Nuova',
      kind: 'train station',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'federico-bigliettaio',
      imagePrompt: 'Soft pastel sketch on white paper of a grand 19th-century railway station with vaulted glass ceiling, departure boards, and travelers. Steel grays, warm yellows from lighting, sky blue through glass. Bustling transit hub atmosphere. Dynamic light, textured, movement.',
    },
    
    // CITY CHARACTER - Chocolate/Gianduja (1)
    {
      id: 'guido-gobino',
      name: 'Guido Gobino',
      kind: 'chocolate shop',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'marco-cioccolataio',
      imagePrompt: 'Soft pastel sketch on white paper of an artisan chocolate atelier with glass displays of giandujotti, cremino, and gourmet pralines. Rich chocolate browns, gold foil, cream. Luxurious Torinese chocolate tradition. Warm light, textured, tempting.',
    },
    
    // CITY CHARACTER - Vermouth (1)
    {
      id: 'casa-del-vermouth',
      name: 'Casa del Vermouth',
      kind: 'specialty shop',
      neighbourhood: 'Quadrilatero Romano',
      real: false,
      characterId: 'antonio-esperto',
      imagePrompt: 'Soft pastel sketch on white paper of a vermouth specialty shop with vintage bottles, botanical illustrations, and tasting counter. Deep amber, herbal greens, vintage label colors. Turin vermouth heritage atmosphere. Warm, textured, aromatic.',
    },
    
    // CITY CHARACTER - Automotive Museum (1)
    {
      id: 'museo-automobile',
      name: 'Museo dell\'Automobile',
      kind: 'museum',
      neighbourhood: 'San Salvario',
      real: true,
      characterId: 'lorenzo-curatore',
      imagePrompt: 'Soft pastel sketch on white paper of a modern automotive museum with vintage Fiat cars, sleek displays, and industrial architecture. Chrome silvers, racing reds, deep blacks. Turin\'s automotive heritage, modern design. Bright, textured, dynamic.',
    },
    
    // Additional places to reach 25-30
    {
      id: 'gelateria-pepino',
      name: 'Gelateria Pepino',
      kind: 'gelateria',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'sofia-gelataia',
      imagePrompt: 'Soft pastel sketch on white paper of a historic gelateria with vintage decor, display cases of gelato, and the famous pinguino (chocolate-covered gelato bar). Pastel gelato colors, cream, chocolate. Sweet Torinese tradition, nostalgic. Soft light, textured, delightful.',
    },
    {
      id: 'mercato-centrale-torino',
      name: 'Mercato Centrale Torino',
      kind: 'food hall',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'alessandro-venditore',
      imagePrompt: 'Soft pastel sketch on white paper of a restored food hall inside Porta Palazzo station with artisan food stalls, communal tables, and industrial-chic design. Warm woods, exposed brick, fresh produce colors. Modern food culture meets tradition. Bright, textured, communal.',
    },
    {
      id: 'caffe-fiorio',
      name: 'Caffè Fiorio',
      kind: 'bar',
      neighbourhood: 'Centro',
      real: true,
      characterId: 'benedetta-barista',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant 18th-century café with crystal chandeliers, velvet seating, and mirrors. Royal blues, golds, cream. Historic meeting place of Risorgimento figures. Refined, textured, storied atmosphere.',
    },
    {
      id: 'balon-flea-market',
      name: 'Mercato del Balon',
      kind: 'market',
      neighbourhood: 'Quadrilatero Romano',
      real: true,
      characterId: 'riccardo-antiquario',
      imagePrompt: 'Soft pastel sketch on white paper of a lively flea market with antiques, vintage items, and curious objects spread on tables and cobblestones. Eclectic colors, warm browns, vintage patina. Treasure-hunting atmosphere, bohemian. Dappled light, textured, chaotic charm.',
    },
    {
      id: 'osteria-rabezzana',
      name: 'Osteria Rabezzana',
      kind: 'osteria',
      neighbourhood: 'Crocetta',
      real: false,
      characterId: 'matteo-proprietario',
      imagePrompt: 'Soft pastel sketch on white paper of a family-run neighborhood osteria with regional wine bottles, hand-written daily menus, and paper tablecloths. Warm ochre, wine red, rustic wood. Homey Piemontese cooking atmosphere. Intimate lighting, textured, authentic.',
    },
  ],
  characters: [
    {
      id: 'michele-barista',
      name: 'Michele Ferrero',
      age: 42,
      role: 'barista',
      placeId: 'caffe-san-carlo',
      personality: ['professional', 'proud', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished Italian barista in his forties with salt-and-pepper hair, wearing a crisp white shirt and black bow tie. Confident expression, hint of a smile. Minimal warm sepia wash on face. Detailed crosshatching, classic composition.',
    },
    {
      id: 'franca-proprietaria',
      name: 'Franca Cavallo',
      age: 68,
      role: 'proprietaria',
      placeId: 'bicerin-dal-1763',
      personality: ['warm', 'knowledgeable', 'guardian of tradition'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant elderly Italian woman with white hair in a bun, wearing a traditional apron over refined clothing. Kind eyes, wise expression. Minimal amber watercolor wash. Detailed linework, dignified presence.',
    },
    {
      id: 'roberto-cameriere',
      name: 'Roberto Allemandi',
      age: 35,
      role: 'cameriere',
      placeId: 'caffe-mulassano',
      personality: ['efficient', 'charming', 'well-dressed'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stylish waiter in his thirties with slicked-back dark hair, wearing a formal vest and tie. Attentive expression, professional demeanor. Minimal cool gray wash. Clean lines, elegant composition.',
    },
    {
      id: 'giuseppe-fornaio',
      name: 'Giuseppe Rosso',
      age: 51,
      role: 'fornaio',
      placeId: 'panetteria-borgo-antico',
      personality: ['hardworking', 'jovial', 'flour-dusted'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust baker in his fifties with strong arms, wearing a flour-dusted apron and traditional baker hat. Warm smile, honest face. Minimal wheat-tone watercolor wash. Bold strokes, working-class dignity.',
    },
    {
      id: 'claudia-pasticciera',
      name: 'Claudia Stratta',
      age: 29,
      role: 'pasticciera',
      placeId: 'pasticceria-stratta',
      personality: ['artistic', 'perfectionist', 'sweet'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young pastry chef with hair pulled back, wearing a pristine white chef coat. Focused expression, gentle features. Minimal pink watercolor wash on cheeks. Delicate lines, refined presence.',
    },
    {
      id: 'anna-fruttivendola',
      name: 'Anna Bianchi',
      age: 45,
      role: 'fruttivendola',
      placeId: 'mercato-porta-palazzo',
      personality: ['loud', 'friendly', 'no-nonsense'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust market vendor woman in her forties with curly hair, wearing a practical apron. Broad smile, expressive face. Minimal warm terracotta wash. Energetic lines, vital personality.',
    },
    {
      id: 'paolo-venditore',
      name: 'Paolo Marchetti',
      age: 58,
      role: 'cheese vendor',
      placeId: 'mercato-crocetta',
      personality: ['expert', 'generous with samples', 'storyteller'],
      portraitPrompt: 'Pen and ink portrait on white paper of a friendly cheese vendor in his late fifties with a mustache, wearing an apron. Knowledgeable eyes, welcoming expression. Minimal cream watercolor wash. Detailed facial features, approachable.',
    },
    {
      id: 'davide-commesso',
      name: 'Davide Olivetti',
      age: 26,
      role: 'commesso',
      placeId: 'eataly-torino',
      personality: ['enthusiastic', 'foodie', 'helpful'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young shop assistant with modern glasses and neat beard, wearing Eataly branded apron. Eager expression, knowledgeable look. Minimal green watercolor accent. Clean contemporary lines.',
    },
    {
      id: 'stefano-maitre',
      name: 'Stefano Del Cambio',
      age: 52,
      role: 'maître',
      placeId: 'ristorante-del-cambio',
      personality: ['elegant', 'formal', 'impeccable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished maître d\' in his fifties with silver temples, wearing an elegant suit. Refined posture, discerning expression. Minimal burgundy watercolor accent. Sophisticated linework, aristocratic bearing.',
    },
    {
      id: 'giulia-chef',
      name: 'Giulia Bergamasco',
      age: 38,
      role: 'chef',
      placeId: 'ristorante-consorzio',
      personality: ['innovative', 'passionate', 'regional pride'],
      portraitPrompt: 'Pen and ink portrait on white paper of a confident female chef in her late thirties with hair in a bandana, wearing chef whites. Determined expression, creative energy. Minimal warm ochre wash. Strong lines, contemporary presence.',
    },
    {
      id: 'mario-oste',
      name: 'Mario Gastaldi',
      age: 62,
      role: 'oste',
      placeId: 'trattoria-valenza',
      personality: ['paternal', 'welcoming', 'wine-loving'],
      portraitPrompt: 'Pen and ink portrait on white paper of a portly innkeeper in his sixties with a broad face, wearing a checkered shirt. Warm laugh lines, hospitable expression. Minimal wine-red watercolor wash. Generous strokes, convivial character.',
    },
    {
      id: 'bruno-cuoco',
      name: 'Bruno Malvezzi',
      age: 47,
      role: 'cuoco',
      placeId: 'osteria-antiche-sere',
      personality: ['traditional', 'gruff but kind', 'talented'],
      portraitPrompt: 'Pen and ink portrait on white paper of a serious cook in his forties with strong features, wearing a cooking apron and bandana. Concentrated expression, capable hands. Minimal earth-tone wash. Bold strokes, working authenticity.',
    },
    {
      id: 'elena-guida',
      name: 'Elena Agnelli',
      age: 31,
      role: 'tour guide',
      placeId: 'mole-antonelliana',
      personality: ['knowledgeable', 'animated', 'city-proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of an articulate young woman with expressive eyes, wearing professional but stylish clothing with a museum badge. Engaging expression, intelligent gaze. Minimal blue watercolor accent. Detailed, articulate lines.',
    },
    {
      id: 'padre-luca',
      name: 'Padre Luca Molinari',
      age: 55,
      role: 'priest',
      placeId: 'duomo-torino',
      personality: ['serene', 'scholarly', 'welcoming'],
      portraitPrompt: 'Pen and ink portrait on white paper of a gentle priest in his fifties with glasses and graying hair, wearing clerical collar. Peaceful expression, kind eyes. Minimal pale gray wash. Contemplative lines, spiritual presence.',
    },
    {
      id: 'isabella-curatrice',
      name: 'Isabella Savoia',
      age: 44,
      role: 'curator',
      placeId: 'palazzo-reale',
      personality: ['sophisticated', 'historian', 'detail-oriented'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant museum curator in her forties with upswept hair, wearing refined clothing and pearl earrings. Intelligent expression, cultured bearing. Minimal gold watercolor accent. Refined lines, academic grace.',
    },
    {
      id: 'giacomo-giardiniere',
      name: 'Giacomo Valentino',
      age: 59,
      role: 'gardener',
      placeId: 'parco-valentino',
      personality: ['patient', 'nature-loving', 'philosophical'],
      portraitPrompt: 'Pen and ink portrait on white paper of a weathered gardener in his late fifties with sun-worn face, wearing work clothes and cap. Peaceful expression, knowing eyes. Minimal green watercolor wash. Organic lines, earthy character.',
    },
    {
      id: 'luca-musicista',
      name: 'Luca Monferrato',
      age: 33,
      role: 'street musician',
      placeId: 'piazza-castello',
      personality: ['artistic', 'romantic', 'free-spirited'],
      portraitPrompt: 'Pen and ink portrait on white paper of a bohemian musician in his thirties with tousled hair and expressive face, wearing a scarf. Dreamy expression, creative soul. Minimal amber watercolor wash. Flowing lines, artistic temperament.',
    },
    {
      id: 'martina-artista',
      name: 'Martina Fenoglio',
      age: 27,
      role: 'street artist',
      placeId: 'piazza-vittorio-veneto',
      personality: ['creative', 'independent', 'observant'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young artist with paint-stained fingers and creative style, wearing casual layers. Observant eyes, artistic expression. Minimal colorful watercolor splashes. Loose lines, creative energy.',
    },
    {
      id: 'simone-sommelier',
      name: 'Simone Barolo',
      age: 41,
      role: 'sommelier',
      placeId: 'enoteca-bacco',
      personality: ['expert', 'enthusiastic', 'regional pride'],
      portraitPrompt: 'Pen and ink portrait on white paper of a knowledgeable sommelier in his forties with refined features, wearing sommelier medallion. Passionate expression, discerning look. Minimal burgundy watercolor wash. Sophisticated lines, oenophile character.',
    },
    {
      id: 'valeria-bartender',
      name: 'Valeria Morra',
      age: 29,
      role: 'bartender',
      placeId: 'aperitivo-cult',
      personality: ['social', 'trendy', 'mixology-skilled'],
      portraitPrompt: 'Pen and ink portrait on white paper of a stylish young bartender with modern haircut, wearing fashionable attire and bar apron. Friendly smile, confident presence. Minimal orange watercolor accent. Contemporary lines, urban energy.',
    },
    {
      id: 'teresa-libraio',
      name: 'Teresa Pavese',
      age: 48,
      role: 'bookseller',
      placeId: 'libreria-luxemburg',
      personality: ['literary', 'thoughtful', 'recommends perfectly'],
      portraitPrompt: 'Pen and ink portrait on white paper of an intellectual bookseller in her forties with reading glasses on a chain, surrounded by literary atmosphere. Thoughtful expression, book-lover\'s eyes. Minimal sepia wash. Detailed, bibliophile character.',
    },
    {
      id: 'dottoressa-carla',
      name: 'Dott.ssa Carla Boero',
      age: 56,
      role: 'pharmacist',
      placeId: 'farmacia-centrale',
      personality: ['professional', 'caring', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a competent pharmacist in her fifties wearing a white coat and glasses. Caring expression, professional demeanor. Minimal clinical green wash. Precise lines, medical authority.',
    },
    {
      id: 'federico-bigliettaio',
      name: 'Federico Costa',
      age: 39,
      role: 'ticket agent',
      placeId: 'porta-nuova',
      personality: ['efficient', 'multilingual', 'helpful'],
      portraitPrompt: 'Pen and ink portrait on white paper of a railway employee in his late thirties wearing uniform and cap. Alert expression, service-oriented. Minimal blue railway wash. Clean lines, professional presence.',
    },
    {
      id: 'marco-cioccolataio',
      name: 'Marco Gobino',
      age: 36,
      role: 'chocolatier',
      placeId: 'guido-gobino',
      personality: ['artisan', 'perfectionist', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a master chocolatier in his thirties with intense focus, wearing chef whites. Precise expression, artisan pride. Minimal chocolate-brown watercolor wash. Detailed lines, craftsman character.',
    },
    {
      id: 'antonio-esperto',
      name: 'Antonio Carpano',
      age: 64,
      role: 'vermouth expert',
      placeId: 'casa-del-vermouth',
      personality: ['traditional', 'storyteller', 'botanical knowledge'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished vermouth expert in his sixties with a sophisticated manner, wearing vintage-style vest. Knowledgeable eyes, refined taste. Minimal amber vermouth wash. Classic lines, heritage keeper.',
    },
    {
      id: 'lorenzo-curatore',
      name: 'Lorenzo Bertone',
      age: 43,
      role: 'automotive curator',
      placeId: 'museo-automobile',
      personality: ['passionate', 'technical', 'nostalgic'],
      portraitPrompt: 'Pen and ink portrait on white paper of an automotive enthusiast curator in his forties with precise gestures, wearing modern professional attire. Enthusiastic expression, technical mind. Minimal chrome-gray wash. Sharp lines, automotive passion.',
    },
    {
      id: 'sofia-gelataia',
      name: 'Sofia Pepino',
      age: 24,
      role: 'gelataia',
      placeId: 'gelateria-pepino',
      personality: ['cheerful', 'sweet', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a bright young gelato maker with a sunny smile, wearing vintage-style uniform and cap. Cheerful expression, welcoming energy. Minimal pastel watercolor wash. Light lines, joyful presence.',
    },
    {
      id: 'alessandro-venditore',
      name: 'Alessandro Gallo',
      age: 32,
      role: 'food vendor',
      placeId: 'mercato-centrale-torino',
      personality: ['artisan', 'modern', 'quality-focused'],
      portraitPrompt: 'Pen and ink portrait on white paper of a contemporary food artisan in his early thirties with a trimmed beard, wearing modern work apron. Proud expression, quality conscious. Minimal warm earth wash. Clean contemporary lines.',
    },
    {
      id: 'benedetta-barista',
      name: 'Benedetta Fiorio',
      age: 37,
      role: 'barista',
      placeId: 'caffe-fiorio',
      personality: ['elegant', 'historic knowledge', 'refined'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant barista in her late thirties with classic style, wearing formal café attire. Gracious expression, cultured manner. Minimal royal blue wash. Refined lines, historic pride.',
    },
    {
      id: 'riccardo-antiquario',
      name: 'Riccardo Balon',
      age: 61,
      role: 'antique dealer',
      placeId: 'balon-flea-market',
      personality: ['eccentric', 'treasure hunter', 'storyteller'],
      portraitPrompt: 'Pen and ink portrait on white paper of a colorful antique dealer in his sixties with weathered face and quirky style, wearing layers and vintage accessories. Mischievous eyes, character-filled face. Minimal vintage sepia wash. Expressive lines, bohemian spirit.',
    },
    {
      id: 'matteo-proprietario',
      name: 'Matteo Rabezzana',
      age: 50,
      role: 'owner',
      placeId: 'osteria-rabezzana',
      personality: ['family-oriented', 'generous', 'traditional cook'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warm family restaurant owner in his fifties with genuine smile, wearing casual shirt and apron. Welcoming expression, honest face. Minimal warm ochre wash. Solid lines, familial warmth.',
    },
  ],
  food: [
    'agnolotti del plin',
    'vitello tonnato',
    'bagna cauda',
    'brasato al Barolo',
    'finanziera',
    'fritto misto alla piemontese',
    'bollito misto',
    'tajarin',
    'gnocchi al castelmagno',
    'insalata russa',
    'acciughe al verde',
    'bicerin (drink)',
    'giandujotti',
    'cremino',
    'torrone',
    'baci di dama',
    'grissini torinesi',
    'focaccia',
    'tomini',
    'robiola di Roccaverano',
    'salame di Turgia',
    'marron glacé',
    'zabaione',
    'bunet',
  ],
  customs: [
    'Taking the ritual bicerin (coffee, chocolate, and cream drink)',
    'Aperitivo hour with vermouth di Torino and abundant buffet',
    'Sunday stroll along the Po River and Parco del Valentino',
    'Merenda sinoira (traditional Piedmontese afternoon snack meal)',
    'Chocolate hunting in historic pasticcerie',
    'Shopping under the elegant arcades (portici)',
    'Sunday morning at Balon flea market',
    'Coffee standing at the bar, never sitting',
    'The passeggiata in Piazza Vittorio Veneto at sunset',
  ],
  localTouches: [
    'Madama (referring to Palazzo Madama)',
    'Ël Tòro (the bull - local dialect for Torino)',
    'Fëtta (slice, used for bread or cake in Piedmontese)',
    'Bogia nen! (Don\'t move! - common Torinese expression)',
    'Marenda (snack in Piedmontese)',
    'Bagna (sauce, as in bagna cauda)',
    'Bunet (typical Torinese chocolate pudding)',
    'Gianduiotto/Gianduja (hazelnut-chocolate)',
  ],
};
