import { CityPantry } from '@/lib/types';

export const venezia: CityPantry = {
  id: 'venezia',
  name: 'Venezia',
  neighbourhoods: ['Cannaregio', 'Castello', 'Dorsoduro', 'San Marco'],
  places: [
    // DAILY ROUTINE - Bars/Cafés (9)
    {
      id: 'bar-al-timon',
      name: 'Al Timon',
      kind: 'bar',
      neighbourhood: 'Cannaregio',
      real: true,
      characterId: 'marco-timon',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy canalside bar with outdoor seating, warm amber and terracotta tones, wooden tables along the fondamenta, wine bottles visible through windows, morning light reflecting off canal water, textured and inviting atmosphere',
    },
    {
      id: 'caffe-florian',
      name: 'Caffè Florian',
      kind: 'bar',
      neighbourhood: 'San Marco',
      real: true,
      characterId: 'antonio-florian',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant historic café with arched porticos, cream and gold tones, small round tables with white tablecloths, ornate interior glimpses, pigeons in the piazza, warm morning light, sophisticated and timeless',
    },
    {
      id: 'bar-ai-do-leoni',
      name: 'Bar ai Do Leoni',
      kind: 'bar',
      neighbourhood: 'Castello',
      real: false,
      characterId: 'giulia-leoni',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood bar with two lion statues flanking the entrance, warm ochre and rose tones, locals standing at counter with espresso, morning newspapers, nautical touches, welcoming and authentic',
    },
    {
      id: 'caffe-rosso',
      name: 'Caffè Rosso',
      kind: 'bar',
      neighbourhood: 'Dorsoduro',
      real: true,
      characterId: 'stefano-rosso',
      imagePrompt: 'Soft pastel sketch on white paper of a lively campo café with red awning, warm brick and burgundy tones, students and locals mingling, outdoor tables in square, morning bustle, energetic and bohemian atmosphere',
    },
    {
      id: 'bar-alla-toletta',
      name: 'Bar alla Toletta',
      kind: 'bar',
      neighbourhood: 'Dorsoduro',
      real: false,
      characterId: 'elena-toletta',
      imagePrompt: 'Soft pastel sketch on white paper of a corner bar near a small bridge, soft blue-grey and cream tones, barista visible through window, morning pastries displayed, quiet canal view, intimate and charming',
    },
    {
      id: 'caffe-del-doge',
      name: 'Caffè del Doge',
      kind: 'bar',
      neighbourhood: 'San Marco',
      real: true,
      characterId: 'roberto-doge',
      imagePrompt: 'Soft pastel sketch on white paper of an artisan coffee roastery café, warm brown and copper tones, coffee sacks and roasting equipment visible, aromatic atmosphere, wooden counters, rich and inviting',
    },
    {
      id: 'bar-ai-ormesini',
      name: 'Bar ai Ormesini',
      kind: 'bar',
      neighbourhood: 'Cannaregio',
      real: false,
      characterId: 'chiara-ormesini',
      imagePrompt: 'Soft pastel sketch on white paper of a local workers bar on a wide fondamenta, pale yellow and white tones, morning crowd at counter, tramezzini sandwiches displayed, boats passing by, working-class warmth',
    },
    {
      id: 'bar-da-gino',
      name: 'Bar da Gino',
      kind: 'bar',
      neighbourhood: 'Castello',
      real: false,
      characterId: 'gino-battaglia',
      imagePrompt: 'Soft pastel sketch on white paper of a tiny neighborhood bar tucked in a narrow calle, warm terracotta and olive tones, old espresso machine gleaming, local fishermen gathering, weathered charm and authenticity',
    },
    {
      id: 'torrefazione-cannaregio',
      name: 'Torrefazione Cannaregio',
      kind: 'bar',
      neighbourhood: 'Cannaregio',
      real: false,
      characterId: 'luciana-caffe',
      imagePrompt: 'Soft pastel sketch on white paper of a coffee roasting shop with café counter, deep brown and cream tones, burlap sacks of beans, vintage roaster visible, aromatic morning scene, artisanal and specialized',
    },

    // DAILY ROUTINE - Bakeries (4)
    {
      id: 'panificio-volpe',
      name: 'Panificio Volpe',
      kind: 'bakery',
      neighbourhood: 'Cannaregio',
      real: false,
      characterId: 'angela-volpe',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional bakery with wooden shelves, warm golden and wheat tones, fresh bread loaves displayed, flour dust in morning light, oven glow from back, wholesome and fragrant',
    },
    {
      id: 'pasticceria-dal-mas',
      name: 'Pasticceria Dal Mas',
      kind: 'bakery',
      neighbourhood: 'Dorsoduro',
      real: false,
      characterId: 'tommaso-dalmas',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant pastry shop with glass cases, soft pink and cream tones, delicate Venetian cookies displayed, fritole and galani pastries, refined morning sweetness',
    },
    {
      id: 'panificio-san-marco',
      name: 'Panificio San Marco',
      kind: 'bakery',
      neighbourhood: 'San Marco',
      real: false,
      characterId: 'francesca-pane',
      imagePrompt: 'Soft pastel sketch on white paper of a busy bakery near tourist routes, warm amber and gold tones, focaccia and traditional breads, locals and visitors mixing, aromatic morning atmosphere',
    },
    {
      id: 'pasticceria-rizzardini',
      name: 'Pasticceria Rizzardini',
      kind: 'bakery',
      neighbourhood: 'Castello',
      real: false,
      characterId: 'paolo-rizzardini',
      imagePrompt: 'Soft pastel sketch on white paper of a historic pastry shop with vintage signage, soft cream and chocolate tones, traditional Venetian sweets, brass fixtures, timeless morning ritual',
    },

    // FOOD & SHOPPING - Markets (3)
    {
      id: 'mercato-rialto',
      name: 'Mercato di Rialto',
      kind: 'market',
      neighbourhood: 'San Marco',
      real: true,
      characterId: 'sergio-rialto',
      imagePrompt: 'Soft pastel sketch on white paper of the famous Rialto fish and produce market, vibrant seafood blues and vegetable greens, market stalls under white canopies, Grand Canal beyond, lively morning commerce, iconic Venetian scene',
    },
    {
      id: 'mercato-cannaregio',
      name: 'Mercato di Cannaregio',
      kind: 'market',
      neighbourhood: 'Cannaregio',
      real: false,
      characterId: 'maria-mercato',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood produce market in a campo, warm earth tones and fresh greens, seasonal vegetables and fruits, local vendors calling out, authentic morning market bustle',
    },
    {
      id: 'pescheria-castello',
      name: 'Pescheria Castello',
      kind: 'market',
      neighbourhood: 'Castello',
      real: false,
      characterId: 'vittorio-pesce',
      imagePrompt: 'Soft pastel sketch on white paper of a small fish market near the arsenale, silvery blue and white tones, fresh lagoon catch displayed on ice, seagulls overhead, salty morning air, maritime authenticity',
    },

    // FOOD & SHOPPING - Restaurants (2)
    {
      id: 'ristorante-antiche-carampane',
      name: 'Antiche Carampane',
      kind: 'restaurant',
      neighbourhood: 'San Marco',
      real: true,
      characterId: 'lorenzo-carampane',
      imagePrompt: 'Soft pastel sketch on white paper of a hidden traditional restaurant in a quiet calle, warm russet and cream tones, white tablecloths glimpsed through windows, intimate dining room, classic Venetian elegance',
    },
    {
      id: 'ristorante-da-alvise',
      name: 'Ristorante da Alvise',
      kind: 'restaurant',
      neighbourhood: 'Cannaregio',
      real: false,
      characterId: 'alvise-costa',
      imagePrompt: 'Soft pastel sketch on white paper of a family-run restaurant with canal-side terrace, soft blue-grey and white tones, gondolas passing, set tables with wine glasses, romantic evening atmosphere',
    },

    // FOOD & SHOPPING - Specialty Food (3)
    {
      id: 'osteria-al-squero',
      name: 'Osteria Al Squero',
      kind: 'osteria',
      neighbourhood: 'Dorsoduro',
      real: true,
      characterId: 'michele-squero',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy osteria overlooking a gondola repair yard, warm amber and wood tones, cicchetti displayed on counter, locals with wine glasses, authentic Venetian charm',
    },
    {
      id: 'trattoria-alla-madonna',
      name: 'Trattoria alla Madonna',
      kind: 'trattoria',
      neighbourhood: 'San Marco',
      real: true,
      characterId: 'isabella-madonna',
      imagePrompt: 'Soft pastel sketch on white paper of a bustling traditional trattoria, warm yellow and terracotta tones, crowded tables, fresh seafood platters, old photographs on walls, lively Venetian dining',
    },
    {
      id: 'bacaro-del-vin',
      name: 'Bacaro del Vin',
      kind: 'bacaro',
      neighbourhood: 'Castello',
      real: false,
      characterId: 'nicolo-bacaro',
      imagePrompt: 'Soft pastel sketch on white paper of a tiny wine bar with standing room only, deep wine red and wood tones, cicchetti platters, wine bottles lining walls, intimate local gathering spot',
    },

    // CULTURAL/LANDMARK (6)
    {
      id: 'basilica-san-marco',
      name: 'Basilica di San Marco',
      kind: 'church',
      neighbourhood: 'San Marco',
      real: true,
      characterId: 'padre-giovanni',
      imagePrompt: 'Soft pastel sketch on white paper of the magnificent Byzantine basilica with golden mosaics, warm gold and azure tones, ornate domes and arches, pigeons in piazza, majestic and iconic',
    },
    {
      id: 'ponte-rialto',
      name: 'Ponte di Rialto',
      kind: 'landmark',
      neighbourhood: 'San Marco',
      real: true,
      characterId: 'carlo-gondoliere',
      imagePrompt: 'Soft pastel sketch on white paper of the famous white stone bridge arching over the Grand Canal, soft ivory and blue-green water tones, gondolas passing beneath, shops on bridge, timeless Venetian icon',
    },
    {
      id: 'giardini-pubblici',
      name: 'Giardini Pubblici',
      kind: 'park',
      neighbourhood: 'Castello',
      real: true,
      characterId: 'beatrice-giardini',
      imagePrompt: 'Soft pastel sketch on white paper of public gardens with tree-lined paths, soft green and dappled light, benches overlooking lagoon, rare Venice greenery, peaceful afternoon retreat',
    },
    {
      id: 'campo-santa-margherita',
      name: 'Campo Santa Margherita',
      kind: 'piazza',
      neighbourhood: 'Dorsoduro',
      real: true,
      characterId: 'giovanna-campo',
      imagePrompt: 'Soft pastel sketch on white paper of a lively rectangular campo with market stalls, warm ochre building facades, students and families, outdoor café tables, vibrant community heart',
    },
    {
      id: 'chiesa-madonna-orto',
      name: 'Chiesa della Madonna dell\'Orto',
      kind: 'church',
      neighbourhood: 'Cannaregio',
      real: true,
      characterId: 'suora-teresa',
      imagePrompt: 'Soft pastel sketch on white paper of a Gothic brick church in quiet neighborhood, warm rose-brick and cream tones, peaceful campo in front, Tintoretto paintings within, serene spiritual beauty',
    },
    {
      id: 'campo-dei-mori',
      name: 'Campo dei Mori',
      kind: 'piazza',
      neighbourhood: 'Cannaregio',
      real: true,
      characterId: 'dante-mori',
      imagePrompt: 'Soft pastel sketch on white paper of a charming small campo with statue of Moorish merchant, warm terracotta and weathered stone, historic well, quiet residential square, mysterious Venetian character',
    },

    // SOCIAL/EVENING (3)
    {
      id: 'enoteca-mascareta',
      name: 'Enoteca Mascareta',
      kind: 'enoteca',
      neighbourhood: 'Castello',
      real: false,
      characterId: 'matteo-vino',
      imagePrompt: 'Soft pastel sketch on white paper of an intimate wine bar with exposed brick, deep burgundy and warm wood tones, wine bottles glowing, small tables with candles, romantic evening atmosphere',
    },
    {
      id: 'cantina-do-spade',
      name: 'Cantina Do Spade',
      kind: 'enoteca',
      neighbourhood: 'San Marco',
      real: true,
      characterId: 'sandra-spade',
      imagePrompt: 'Soft pastel sketch on white paper of a historic wine tavern near Rialto, warm amber and copper tones, hanging copper pots, locals gathering for ombra, centuries of Venetian wine tradition',
    },
    {
      id: 'libreria-acqua-alta',
      name: 'Libreria Acqua Alta',
      kind: 'bookshop',
      neighbourhood: 'Castello',
      real: true,
      characterId: 'luigi-libri',
      imagePrompt: 'Soft pastel sketch on white paper of the famous bookshop with books in gondola and bathtub, soft faded paper tones and blues, cats lounging, stacks reaching ceiling, whimsical Venetian eccentricity',
    },

    // PRACTICAL (2)
    {
      id: 'farmacia-morelli',
      name: 'Farmacia Morelli',
      kind: 'pharmacy',
      neighbourhood: 'Dorsoduro',
      real: false,
      characterId: 'dottoressa-morelli',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional pharmacy with antique wooden cabinets, soft green and cream tones, glass bottles on shelves, professional neighborhood care',
    },
    {
      id: 'stazione-santa-lucia',
      name: 'Stazione Santa Lucia',
      kind: 'station',
      neighbourhood: 'Cannaregio',
      real: true,
      characterId: 'pietro-stazione',
      imagePrompt: 'Soft pastel sketch on white paper of the modernist train station where land meets water, soft grey and blue tones, vaporetti waiting outside, travelers with luggage, Venice\'s gateway',
    },

    // CITY CHARACTER (3)
    {
      id: 'squero-san-trovaso',
      name: 'Squero San Trovaso',
      kind: 'gondola-workshop',
      neighbourhood: 'Dorsoduro',
      real: true,
      characterId: 'andrea-gondola',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional gondola boatyard with wooden boats under construction, warm wood and black lacquer tones, craftsmen at work, timeless Venetian artistry',
    },
    {
      id: 'atelier-maschera',
      name: 'Atelier della Maschera',
      kind: 'mask-shop',
      neighbourhood: 'San Marco',
      real: false,
      characterId: 'valentina-maschera',
      imagePrompt: 'Soft pastel sketch on white paper of a mask-making atelier with Carnival masks displayed, soft gold and jewel tones, feathers and decorations, artisan at work, mysterious Venetian tradition',
    },
    {
      id: 'fondaco-spezie',
      name: 'Fondaco delle Spezie',
      kind: 'specialty-shop',
      neighbourhood: 'Dorsoduro',
      real: false,
      characterId: 'emilia-spezie',
      imagePrompt: 'Soft pastel sketch on white paper of a spice and specialty foods shop, warm saffron and crimson tones, sacks of spices, preserved seafood, exotic merchant heritage, aromatic atmosphere',
    },
  ],
  characters: [
    {
      id: 'marco-timon',
      name: 'Marco Zanon',
      age: 42,
      role: 'bar owner',
      placeId: 'bar-al-timon',
      personality: ['gregarious', 'storyteller', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a friendly man in his forties with slightly greying curly hair, warm smile lines around eyes, casual button-down shirt, minimal warm sepia watercolor wash, detailed cross-hatching, welcoming expression',
    },
    {
      id: 'antonio-florian',
      name: 'Antonio Bianchi',
      age: 38,
      role: 'head waiter',
      placeId: 'caffe-florian',
      personality: ['elegant', 'professional', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man in his late thirties with neat dark hair, bow tie and formal vest, subtle blue-grey watercolor wash, refined pen strokes, dignified bearing',
    },
    {
      id: 'giulia-leoni',
      name: 'Giulia Leoni',
      age: 29,
      role: 'barista',
      placeId: 'bar-ai-do-leoni',
      personality: ['energetic', 'warm', 'chatty'],
      portraitPrompt: 'Pen and ink portrait on white paper of a lively young woman with dark hair pulled back, bright eyes, apron over casual clothes, minimal golden watercolor wash, expressive linework, friendly smile',
    },
    {
      id: 'stefano-rosso',
      name: 'Stefano Rosso',
      age: 35,
      role: 'bartender',
      placeId: 'caffe-rosso',
      personality: ['artistic', 'laid-back', 'philosophical'],
      portraitPrompt: 'Pen and ink portrait on white paper of a bohemian man in his mid-thirties with tousled hair, slight stubble, casual t-shirt, minimal burgundy watercolor wash, loose confident lines, contemplative expression',
    },
    {
      id: 'elena-toletta',
      name: 'Elena Vidal',
      age: 52,
      role: 'bar owner',
      placeId: 'bar-alla-toletta',
      personality: ['motherly', 'observant', 'wise'],
      portraitPrompt: 'Pen and ink portrait on white paper of a kind woman in her fifties with salt-and-pepper hair in a bun, gentle eyes, cardigan over blouse, minimal soft blue watercolor wash, careful detailed lines, nurturing expression',
    },
    {
      id: 'roberto-doge',
      name: 'Roberto Martini',
      age: 45,
      role: 'coffee roaster',
      placeId: 'caffe-del-doge',
      personality: ['perfectionist', 'passionate', 'intense'],
      portraitPrompt: 'Pen and ink portrait on white paper of a focused man in his mid-forties with strong features, serious expression, work apron, minimal brown watercolor wash, bold confident strokes, expert concentration',
    },
    {
      id: 'chiara-ormesini',
      name: 'Chiara Ormesini',
      age: 31,
      role: 'barista',
      placeId: 'bar-ai-ormesini',
      personality: ['efficient', 'humorous', 'down-to-earth'],
      portraitPrompt: 'Pen and ink portrait on white paper of a practical young woman with short dark hair, quick smile, simple work clothes, minimal yellow watercolor wash, energetic linework, capable expression',
    },
    {
      id: 'gino-battaglia',
      name: 'Gino Battaglia',
      age: 68,
      role: 'bar owner',
      placeId: 'bar-da-gino',
      personality: ['traditional', 'gruff-but-kind', 'loyal'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly man with weathered face, white hair, strong Venetian features, vest and shirt, minimal terracotta watercolor wash, detailed wrinkles, dignified character',
    },
    {
      id: 'luciana-caffe',
      name: 'Luciana Ferro',
      age: 39,
      role: 'coffee specialist',
      placeId: 'torrefazione-cannaregio',
      personality: ['knowledgeable', 'precise', 'enthusiastic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a woman in her late thirties with glasses, hair tied back, professional attire, minimal coffee-brown watercolor wash, fine detailed lines, intelligent expression',
    },
    {
      id: 'angela-volpe',
      name: 'Angela Volpe',
      age: 56,
      role: 'baker',
      placeId: 'panificio-volpe',
      personality: ['hardworking', 'proud', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy woman in her fifties with strong hands, flour-dusted apron, warm smile, minimal golden watercolor wash, solid linework, satisfied expression',
    },
    {
      id: 'tommaso-dalmas',
      name: 'Tommaso Dal Mas',
      age: 33,
      role: 'pastry chef',
      placeId: 'pasticceria-dal-mas',
      personality: ['creative', 'meticulous', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young chef with neat appearance, chef\'s whites, focused eyes, minimal pink watercolor wash, precise delicate lines, artistic concentration',
    },
    {
      id: 'francesca-pane',
      name: 'Francesca Pane',
      age: 44,
      role: 'baker',
      placeId: 'panificio-san-marco',
      personality: ['busy', 'cheerful', 'accommodating'],
      portraitPrompt: 'Pen and ink portrait on white paper of a energetic woman in her forties with hair covered, friendly face, work apron, minimal wheat-gold watercolor wash, quick expressive lines, welcoming smile',
    },
    {
      id: 'paolo-rizzardini',
      name: 'Paolo Rizzardini',
      age: 61,
      role: 'master pastry chef',
      placeId: 'pasticceria-rizzardini',
      personality: ['traditional', 'exacting', 'respected'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished older man with white hair, chef\'s jacket, authoritative bearing, minimal cream watercolor wash, careful classical lines, master craftsman dignity',
    },
    {
      id: 'sergio-rialto',
      name: 'Sergio Foscarini',
      age: 55,
      role: 'fish vendor',
      placeId: 'mercato-rialto',
      personality: ['boisterous', 'knowledgeable', 'theatrical'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust man in his fifties with ruddy complexion, rubber boots and apron, animated expression, minimal blue watercolor wash, bold energetic strokes, market vendor vitality',
    },
    {
      id: 'maria-mercato',
      name: 'Maria Cadore',
      age: 48,
      role: 'produce vendor',
      placeId: 'mercato-cannaregio',
      personality: ['forthright', 'fair', 'neighborhood-matriarch'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy woman in her late forties with capable hands, market apron, direct gaze, minimal green watercolor wash, strong confident lines, authoritative warmth',
    },
    {
      id: 'vittorio-pesce',
      name: 'Vittorio Scarpa',
      age: 59,
      role: 'fishmonger',
      placeId: 'pescheria-castello',
      personality: ['quiet', 'expert', 'reliable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a weathered man in his late fifties with sea-worn face, fisherman\'s sweater, thoughtful eyes, minimal silver-blue watercolor wash, textured detailed lines, maritime character',
    },
    {
      id: 'lorenzo-carampane',
      name: 'Lorenzo Carampane',
      age: 47,
      role: 'chef-owner',
      placeId: 'ristorante-antiche-carampane',
      personality: ['perfectionist', 'traditional', 'passionate'],
      portraitPrompt: 'Pen and ink portrait on white paper of a serious chef in his late forties with strong features, chef\'s whites, intense gaze, minimal russet watercolor wash, bold assured strokes, culinary dedication',
    },
    {
      id: 'alvise-costa',
      name: 'Alvise Costa',
      age: 52,
      role: 'restaurant owner',
      placeId: 'ristorante-da-alvise',
      personality: ['hospitable', 'family-oriented', 'storytelling'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warmhearted man in his fifties with greying temples, dress shirt, welcoming smile, minimal blue-grey watercolor wash, flowing expressive lines, generous host',
    },
    {
      id: 'michele-squero',
      name: 'Michele Squero',
      age: 36,
      role: 'osteria owner',
      placeId: 'osteria-al-squero',
      personality: ['relaxed', 'wine-loving', 'sociable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a casual man in his mid-thirties with easy smile, untucked shirt, wine glass nearby, minimal amber watercolor wash, loose comfortable lines, convivial nature',
    },
    {
      id: 'isabella-madonna',
      name: 'Isabella Trevisan',
      age: 41,
      role: 'head waitress',
      placeId: 'trattoria-alla-madonna',
      personality: ['no-nonsense', 'efficient', 'commanding'],
      portraitPrompt: 'Pen and ink portrait on white paper of a capable woman in her early forties with hair pulled back, professional attire, direct expression, minimal yellow watercolor wash, sharp confident lines, take-charge presence',
    },
    {
      id: 'nicolo-bacaro',
      name: 'Nicolò Bacaro',
      age: 28,
      role: 'wine bar owner',
      placeId: 'bacaro-del-vin',
      personality: ['enthusiastic', 'knowledgeable', 'modern-traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with stylish beard, casual but neat clothes, wine-stained apron, minimal wine-red watercolor wash, energetic contemporary lines, passionate expression',
    },
    {
      id: 'padre-giovanni',
      name: 'Padre Giovanni Mocenigo',
      age: 64,
      role: 'priest',
      placeId: 'basilica-san-marco',
      personality: ['scholarly', 'serene', 'guardian'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly priest with kind face, clerical collar, gentle eyes behind glasses, minimal gold watercolor wash, reverent detailed lines, spiritual calm',
    },
    {
      id: 'carlo-gondoliere',
      name: 'Carlo Dandolo',
      age: 43,
      role: 'gondolier',
      placeId: 'ponte-rialto',
      personality: ['proud', 'skilled', 'charming'],
      portraitPrompt: 'Pen and ink portrait on white paper of a fit man in his forties with striped gondolier shirt, straw hat, strong arms, minimal blue-green watercolor wash, dynamic fluid lines, Venetian pride',
    },
    {
      id: 'beatrice-giardini',
      name: 'Beatrice Giardini',
      age: 37,
      role: 'gardener',
      placeId: 'giardini-pubblici',
      personality: ['peaceful', 'nurturing', 'nature-loving'],
      portraitPrompt: 'Pen and ink portrait on white paper of a serene woman in her late thirties with sun-touched skin, gardening clothes, calm smile, minimal green watercolor wash, gentle organic lines, earthy tranquility',
    },
    {
      id: 'giovanna-campo',
      name: 'Giovanna Rizzo',
      age: 26,
      role: 'student',
      placeId: 'campo-santa-margherita',
      personality: ['lively', 'social', 'optimistic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with long dark hair, casual university clothes, bright expression, minimal ochre watercolor wash, free spirited lines, youthful energy',
    },
    {
      id: 'suora-teresa',
      name: 'Suora Teresa Venier',
      age: 58,
      role: 'nun',
      placeId: 'chiesa-madonna-orto',
      personality: ['contemplative', 'artistic', 'gentle'],
      portraitPrompt: 'Pen and ink portrait on white paper of a nun in her late fifties with habit, peaceful face, kind eyes, minimal rose-brick watercolor wash, delicate reverent lines, quiet devotion',
    },
    {
      id: 'dante-mori',
      name: 'Dante Mori',
      age: 72,
      role: 'local historian',
      placeId: 'campo-dei-mori',
      personality: ['eccentric', 'knowledgeable', 'nostalgic'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly man with wild white hair, tweedy jacket, animated expression, minimal terracotta watercolor wash, character-filled expressive lines, storyteller spirit',
    },
    {
      id: 'matteo-vino',
      name: 'Matteo Vino',
      age: 34,
      role: 'sommelier',
      placeId: 'enoteca-mascareta',
      personality: ['sophisticated', 'romantic', 'discerning'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant man in his mid-thirties with refined features, crisp shirt, wine key around neck, minimal burgundy watercolor wash, sophisticated flowing lines, wine expertise',
    },
    {
      id: 'sandra-spade',
      name: 'Sandra Spade',
      age: 50,
      role: 'cantina owner',
      placeId: 'cantina-do-spade',
      personality: ['traditional', 'witty', 'keeper-of-secrets'],
      portraitPrompt: 'Pen and ink portrait on white paper of a woman in her fifties with knowing eyes, traditional dress, copper jewelry, minimal amber watercolor wash, confident assured lines, Venetian wisdom',
    },
    {
      id: 'luigi-libri',
      name: 'Luigi Frizzo',
      age: 66,
      role: 'bookseller',
      placeId: 'libreria-acqua-alta',
      personality: ['eccentric', 'literary', 'whimsical'],
      portraitPrompt: 'Pen and ink portrait on white paper of an quirky older man with reading glasses on chain, rumpled clothes, cat on shoulder, minimal faded-blue watercolor wash, playful detailed lines, bookish charm',
    },
    {
      id: 'dottoressa-morelli',
      name: 'Dottoressa Clara Morelli',
      age: 45,
      role: 'pharmacist',
      placeId: 'farmacia-morelli',
      personality: ['professional', 'caring', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a composed woman in her mid-forties with neat appearance, white coat, intelligent eyes, minimal green watercolor wash, precise professional lines, trusted healer',
    },
    {
      id: 'pietro-stazione',
      name: 'Pietro Bellini',
      age: 53,
      role: 'station master',
      placeId: 'stazione-santa-lucia',
      personality: ['helpful', 'organized', 'patient'],
      portraitPrompt: 'Pen and ink portrait on white paper of a uniformed man in his fifties with cap, official vest, calm demeanor, minimal grey-blue watercolor wash, neat orderly lines, gateway guardian',
    },
    {
      id: 'andrea-gondola',
      name: 'Andrea Tramontin',
      age: 58,
      role: 'master gondola builder',
      placeId: 'squero-san-trovaso',
      personality: ['masterful', 'perfectionist', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a skilled craftsman in his late fifties with calloused hands, work clothes, wood shavings in hair, minimal wood-tone watercolor wash, expert detailed strokes, artisan pride',
    },
    {
      id: 'valentina-maschera',
      name: 'Valentina Maschera',
      age: 32,
      role: 'mask artisan',
      placeId: 'atelier-maschera',
      personality: ['artistic', 'mysterious', 'creative'],
      portraitPrompt: 'Pen and ink portrait on white paper of a creative woman in her early thirties with paint-stained fingers, bohemian style, half-smile, minimal gold watercolor wash, delicate artistic lines, Carnival mystery',
    },
    {
      id: 'emilia-spezie',
      name: 'Emilia Spezie',
      age: 40,
      role: 'spice merchant',
      placeId: 'fondaco-spezie',
      personality: ['exotic', 'knowledgeable', 'merchant-heritage'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elegant woman in her forties with worldly bearing, colorful scarf, knowing smile, minimal saffron watercolor wash, rich textured lines, merchant heritage',
    },
  ],
  food: [
    'sarde in saor',
    'baccalà mantecato',
    'risi e bisi',
    'fegato alla veneziana',
    'bigoli in salsa',
    'moleche fritte',
    'seppie al nero',
    'fritole',
    'galani',
    'baicoli',
    'bussolai',
    'cicchetti',
    'tramezzini',
    'spritz',
    'ombra de vin',
  ],
  customs: [
    'Standing at the bar for coffee (never sitting for espresso)',
    'Aperitivo hour with cicchetti and spritz',
    'Buying an ombra (small glass of wine) at bacari',
    'Shopping daily at Rialto market',
    'Evening passeggiata in the campi',
    'Carnevale mask traditions',
    'Festa del Redentore with boats and fireworks',
    'Regata Storica rowing competitions',
  ],
  localTouches: [
    'Ciao bèo!',
    'Àndiamo per un\'ombra?',
    'Ostrega!',
    'Sensa spini (without worries)',
    'Tòcio (a small piece)',
    'Ciacole (gossip/chat)',
    'In giro per calli (wandering the streets)',
  ],
};
