import { CityPantry } from '@/lib/types';

export const verona: CityPantry = {
  id: 'verona',
  name: 'Verona',
  neighbourhoods: ['Centro Storico', 'Veronetta', 'Borgo Trento', 'San Zeno'],
  places: [
    // BARS & CAFÉS (3)
    {
      id: 'caffe-wallner',
      name: 'Caffè Wallner',
      kind: 'bar',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'stefano-wallner',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant historic café with red awning and marble-topped tables, warm golden morning light streaming through tall windows, brass espresso machine gleaming at the bar, delicate pastries in glass cases, textured stone street visible outside, inviting atmospheric colors in cream, gold and soft red',
    },
    {
      id: 'bar-ai-scalzi',
      name: 'Bar ai Scalzi',
      kind: 'bar',
      neighbourhood: 'Veronetta',
      real: false,
      characterId: 'lucia-scalzi',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy neighborhood bar with worn wooden counter, locals reading newspapers, vintage Campari poster on ochre walls, old-fashioned coffee grinder, morning sunlight creating warm shadows, textured and inviting in earth tones of terracotta, cream and coffee brown',
    },
    {
      id: 'caffe-dante',
      name: 'Caffè Dante',
      kind: 'bar',
      neighbourhood: 'San Zeno',
      real: false,
      characterId: 'giovanni-dante',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional corner bar with green awning, outdoor tables on cobblestones, views of old church tower, espresso cups lined up at counter, warm morning atmosphere in soft greens, warm grays and butter yellow',
    },
    // BAKERIES (2)
    {
      id: 'panificio-mariga',
      name: 'Panificio Mariga',
      kind: 'bakery',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'alberta-mariga',
      imagePrompt: 'Soft pastel sketch on white paper of an artisan bakery with wooden shelves laden with golden bread loaves, flour dust in the air catching sunlight, baskets of fresh ciabatta and focaccia, warm oven glow from the back, inviting textures in wheat gold, cream and warm brown tones',
    },
    {
      id: 'pasticceria-cordioli',
      name: 'Pasticceria Cordioli',
      kind: 'bakery',
      neighbourhood: 'Borgo Trento',
      real: true,
      characterId: 'fabio-cordioli',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant pastry shop with glass display cases full of colorful pastries, delicate torta delle rose, cream-filled bomboloni, pink and white striped boxes, soft pink and cream decor with touches of gold, warm inviting light',
    },
    // MARKETS (3)
    {
      id: 'mercato-piazza-erbe',
      name: 'Mercato di Piazza delle Erbe',
      kind: 'market',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'marco-verdure',
      imagePrompt: 'Soft pastel sketch on white paper of a vibrant open-air market in historic square, colorful produce stalls with striped awnings, piles of radicchio rosso, fresh vegetables, ancient buildings in background, market umbrellas creating dappled shade, lively atmosphere in rich greens, reds, ochre and cream',
    },
    {
      id: 'mercato-stadio',
      name: 'Mercato di Stadio',
      neighbourhood: 'Veronetta',
      kind: 'market',
      real: true,
      characterId: 'rosa-mercato',
      imagePrompt: 'Soft pastel sketch on white paper of a bustling neighborhood market with vendor stalls, crates of seasonal produce, hanging cured meats, wheels of Monte Veronese cheese, locals with shopping bags, authentic working-class atmosphere in earthy greens, terracotta and warm neutrals',
    },
    {
      id: 'bottega-saporiti',
      name: 'Bottega Saporiti',
      kind: 'market',
      neighbourhood: 'San Zeno',
      real: false,
      characterId: 'enrico-saporiti',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional alimentari shop with hanging salami, shelves of local wines, jars of mostarda, fresh pasta, wooden crates of produce, neighborhood charm in warm amber, deep red and cream tones with textured detail',
    },
    // RESTAURANTS (2)
    {
      id: 'ristorante-dodici-apostoli',
      name: 'Ristorante Dodici Apostoli',
      kind: 'ristorante',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'pietro-apostoli',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant traditional restaurant with vaulted ceilings, crisp white tablecloths, wine bottles lining ancient stone walls, soft candlelight, refined Renaissance atmosphere in warm cream, burgundy and gold tones',
    },
    {
      id: 'trattoria-ponte-pietra',
      name: 'Trattoria al Ponte Pietra',
      kind: 'trattoria',
      neighbourhood: 'Veronetta',
      real: false,
      characterId: 'angela-ponte',
      imagePrompt: 'Soft pastel sketch on white paper of a cozy family trattoria with checked tablecloths, copper pots on walls, handwritten menu board, view of Roman bridge through window, homey atmosphere in warm reds, cream and rustic brown',
    },
    // SPECIALTY FOOD (2)
    {
      id: 'osteria-sottoriva',
      name: 'Osteria Sottoriva',
      kind: 'osteria',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'massimo-sottoriva',
      imagePrompt: 'Soft pastel sketch on white paper of a rustic osteria under stone arches, wooden tables, local diners sharing wine, plates of bigoli pasta, riverside medieval atmosphere in deep ochre, stone gray and warm candlelight tones',
    },
    {
      id: 'pizzeria-vesuvio',
      name: 'Pizzeria Vesuvio',
      kind: 'pizzeria',
      neighbourhood: 'Borgo Trento',
      real: false,
      characterId: 'tommaso-vesuvio',
      imagePrompt: 'Soft pastel sketch on white paper of a neighborhood pizzeria with wood-fired oven glowing orange, pizza maker tossing dough, simple wooden tables, tomato red walls, flour-dusted counter, warm inviting atmosphere in terracotta, cream and warm red',
    },
    // LANDMARKS (1 major)
    {
      id: 'arena-verona',
      name: 'Arena di Verona',
      kind: 'landmark',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'silvia-arena',
      imagePrompt: 'Soft pastel sketch on white paper of the magnificent Roman amphitheater with pink Verona marble arches, ancient weathered stone, people gathering in the piazza, opera posters, afternoon light creating warm shadows, majestic yet inviting in rose-pink, cream and warm gray tones',
    },
    // CHURCHES/CULTURAL (2)
    {
      id: 'basilica-san-zeno',
      name: 'Basilica di San Zeno Maggiore',
      kind: 'church',
      neighbourhood: 'San Zeno',
      real: true,
      characterId: 'padre-matteo',
      imagePrompt: 'Soft pastel sketch on white paper of a magnificent Romanesque basilica with bronze doors, rose window, striped marble façade, peaceful cloister garden visible to the side, serene spiritual atmosphere in warm stone tones, bronze green and soft cream',
    },
    {
      id: 'casa-giulietta',
      name: 'Casa di Giulietta',
      kind: 'landmark',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'valentina-giulietta',
      imagePrompt: 'Soft pastel sketch on white paper of the famous medieval house with romantic balcony, ivy-covered walls, courtyard full of love locks and letters, bronze statue gleaming with touch, atmospheric in warm ochre, romantic rose and aged bronze tones',
    },
    // PARKS/GARDENS (1)
    {
      id: 'giardino-giusti',
      name: 'Giardino Giusti',
      kind: 'park',
      neighbourhood: 'Veronetta',
      real: true,
      characterId: 'carlo-giusti',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant Renaissance garden with sculpted hedges, cypress trees, classical statues, gravel paths, views over city, peaceful green sanctuary in soft sage green, warm cream and dappled gold sunlight',
    },
    // PIAZZAS (2)
    {
      id: 'piazza-bra',
      name: 'Piazza Bra',
      kind: 'piazza',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'francesco-bra',
      imagePrompt: 'Soft pastel sketch on white paper of the grand main piazza with Arena looming, outdoor café tables, street performers, people strolling, grand palatial buildings, evening passeggiata atmosphere in warm pink stone, gold streetlight glow and soft shadows',
    },
    {
      id: 'piazza-signori',
      name: 'Piazza dei Signori',
      kind: 'piazza',
      neighbourhood: 'Centro Storico',
      real: true,
      characterId: 'alessandra-signori',
      imagePrompt: 'Soft pastel sketch on white paper of an elegant enclosed square with Dante statue, medieval palaces, outdoor tables under arches, locals meeting for aperitivo, refined civic atmosphere in warm cream, terracotta and soft gold tones',
    },
    // WINE BARS/APERITIVO (2)
    {
      id: 'enoteca-cangrande',
      name: 'Enoteca Cangrande',
      kind: 'enoteca',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'riccardo-cangrande',
      imagePrompt: 'Soft pastel sketch on white paper of a sophisticated wine bar with floor-to-ceiling wine racks, warm wood paneling, small tasting tables, glasses of Amarone glowing ruby red in candlelight, intimate atmosphere in deep burgundy, warm wood and golden light',
    },
    {
      id: 'osteria-vino-vino',
      name: "Osteria al Vin Bon (Vino Vino)",
      kind: 'enoteca',
      neighbourhood: 'Veronetta',
      real: false,
      characterId: 'greta-vino',
      imagePrompt: 'Soft pastel sketch on white paper of a casual wine bar with exposed brick, wine barrels as tables, chalkboard listing local Valpolicella wines, plates of salumi, convivial neighborhood atmosphere in brick red, warm amber and cream',
    },
    // BOOKSHOP (1)
    {
      id: 'libreria-rinascimento',
      name: 'Libreria Rinascimento',
      kind: 'bookshop',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'beatrice-libri',
      imagePrompt: 'Soft pastel sketch on white paper of an intimate bookshop with floor-to-ceiling shelves, stacks of Italian literature, reading nook by window, Shakespeare and Dante volumes displayed, literary atmosphere in warm sepia, cream and soft gold tones',
    },
    // PHARMACY (1)
    {
      id: 'farmacia-centrale',
      name: 'Farmacia Centrale',
      kind: 'pharmacy',
      neighbourhood: 'Centro Storico',
      real: false,
      characterId: 'dottoressa-marta',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional pharmacy with dark wood cabinets, ceramic apothecary jars, green cross sign, organized shelves of remedies, professional yet welcoming in deep green, cream and warm wood tones',
    },
    // SPECIALTY SHOPS (2)
    {
      id: 'salumeria-albertini',
      name: 'Salumeria Albertini',
      kind: 'specialty-food',
      neighbourhood: 'San Zeno',
      real: false,
      characterId: 'bruno-albertini',
      imagePrompt: 'Soft pastel sketch on white paper of a traditional cured meat shop with hanging soppressa and pancetta, aged prosciutto on the slicer, wheels of cheese, the scent of tradition visible in the air, artisan atmosphere in deep rose-red, cream and aged wood tones',
    },
    {
      id: 'pasticceria-perlini',
      name: 'Pasticceria Perlini',
      kind: 'pasticceria',
      neighbourhood: 'Borgo Trento',
      real: false,
      characterId: 'irene-perlini',
      imagePrompt: 'Soft pastel sketch on white paper of a charming pastry boutique with display of pandoro cakes, nadalin cookies, chocolate-covered mandorlato nougat, delicate glass cases, Christmas specialties year-round, sweet atmosphere in gold, cream and soft pink',
    },
    // GELATERIA (1)
    {
      id: 'gelateria-ponte-pietra',
      name: 'Gelateria Ponte Pietra',
      kind: 'gelateria',
      neighbourhood: 'Veronetta',
      real: false,
      characterId: 'luca-gelato',
      imagePrompt: 'Soft pastel sketch on white paper of an artisan gelato shop with colorful tubs of gelato, fresh fruit displayed, people with cones walking toward the Roman bridge, summer atmosphere in pistachio green, strawberry pink, lemon yellow and cream',
    },
    // TRANSPORTATION (1)
    {
      id: 'stazione-porta-nuova',
      name: 'Stazione di Verona Porta Nuova',
      kind: 'station',
      neighbourhood: 'Borgo Trento',
      real: true,
      characterId: 'paolo-stazione',
      imagePrompt: 'Soft pastel sketch on white paper of a grand railway station with Art Nouveau details, travelers with luggage, departure boards, ticket windows, pigeons on the forecourt, gateway to the city atmosphere in warm stone, railway gray and soft gold',
    },
    // TEATRO (1) - City Character
    {
      id: 'teatro-romano',
      name: 'Teatro Romano',
      kind: 'landmark',
      neighbourhood: 'Veronetta',
      real: true,
      characterId: 'emilia-teatro',
      imagePrompt: 'Soft pastel sketch on white paper of ancient Roman theater carved into hillside, semicircular stone seating, stage ruins, view over terracotta roofs and Adige river, summer evening performance atmosphere in warm stone, sunset gold and deep shadow',
    },
    // PONTE (1) - City Character
    {
      id: 'ponte-pietra',
      name: 'Ponte Pietra',
      kind: 'landmark',
      neighbourhood: 'Veronetta',
      real: true,
      characterId: 'davide-ponte',
      imagePrompt: 'Soft pastel sketch on white paper of the ancient Roman bridge with mismatched stone arches spanning green Adige river, medieval tower at one end, people crossing, reflection in water, timeless atmosphere in warm stone, river green and soft golden light',
    },
    // ACETAIA (1) - City Character
    {
      id: 'acetaia-veneta',
      name: 'Acetaia Veneta',
      kind: 'specialty-food',
      neighbourhood: 'San Zeno',
      real: false,
      characterId: 'ornella-acetaia',
      imagePrompt: 'Soft pastel sketch on white paper of a specialty shop dedicated to local vinegars and condiments, wooden barrels, bottles of aged vinegar, olive oils, traditional balsamic tastings, artisan craft atmosphere in deep amber, wood brown and gold',
    },
  ],
  characters: [
    {
      id: 'stefano-wallner',
      name: 'Stefano Wallner',
      age: 52,
      role: 'proprietario',
      placeId: 'caffe-wallner',
      personality: ['refined', 'knowledgeable', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man in his fifties with silver-streaked dark hair, warm brown eyes, wearing crisp white shirt and dark vest, holding espresso cup, gentle smile showing pride in his historic café, detailed crosshatching with subtle watercolor wash in warm sepia tones',
    },
    {
      id: 'lucia-scalzi',
      name: 'Lucia Scalzi',
      age: 38,
      role: 'barista',
      placeId: 'bar-ai-scalzi',
      personality: ['friendly', 'chatty', 'neighborhood-oriented'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warm woman in her late thirties with dark curly hair pulled back, bright hazel eyes, wearing casual shirt and apron, laughing mid-conversation, detailed pen work with watercolor wash in warm ochre and soft pink',
    },
    {
      id: 'giovanni-dante',
      name: 'Giovanni Dante',
      age: 61,
      role: 'proprietario',
      placeId: 'caffe-dante',
      personality: ['philosophical', 'well-read', 'observant'],
      portraitPrompt: 'Pen and ink portrait on white paper of a thoughtful elderly man with gray beard, kind eyes behind reading glasses, wearing worn cardigan, slight knowing smile, detailed linework with minimal watercolor in soft gray and warm cream tones',
    },
    {
      id: 'alberta-mariga',
      name: 'Alberta Mariga',
      age: 45,
      role: 'fornaia',
      placeId: 'panificio-mariga',
      personality: ['hardworking', 'precise', 'maternal'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy woman in her forties with flour-dusted apron, dark hair in practical bun, strong capable hands, warm smile with flour on her cheek, detailed crosshatching with watercolor wash in wheat gold and warm cream',
    },
    {
      id: 'fabio-cordioli',
      name: 'Fabio Cordioli',
      age: 34,
      role: 'pasticciere',
      placeId: 'pasticceria-cordioli',
      personality: ['artistic', 'perfectionist', 'sweet-natured'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with neat dark hair, focused brown eyes, wearing white pastry chef jacket, piping bag in hand, concentrated artistic expression, detailed pen lines with soft watercolor in cream and pale pink',
    },
    {
      id: 'marco-verdure',
      name: 'Marco Verdure',
      age: 48,
      role: 'fruttivendolo',
      placeId: 'mercato-piazza-erbe',
      personality: ['jovial', 'loud', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a robust man in his forties with weathered face, bright expressive eyes, wearing work apron, hands gesturing animatedly, big genuine smile, detailed ink work with watercolor wash in sun-bronzed tones and green',
    },
    {
      id: 'rosa-mercato',
      name: 'Rosa Mercato',
      age: 67,
      role: 'venditrice',
      placeId: 'mercato-stadio',
      personality: ['wise', 'no-nonsense', 'community-minded'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly woman with silver hair in bun, sharp intelligent eyes, wearing practical work clothes and apron, weathered hands counting change, dignified expression, detailed linework with subtle watercolor in warm earth tones',
    },
    {
      id: 'enrico-saporiti',
      name: 'Enrico Saporiti',
      age: 56,
      role: 'proprietario',
      placeId: 'bottega-saporiti',
      personality: ['traditional', 'exacting', 'family-proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a serious middle-aged man with dark hair touched with gray, intense dark eyes, wearing traditional shopkeeper apron, slicing salami with expert hands, proud but warm expression, detailed pen work with watercolor in burgundy and cream',
    },
    {
      id: 'pietro-apostoli',
      name: 'Pietro Apostoli',
      age: 43,
      role: 'sommelier',
      placeId: 'ristorante-dodici-apostoli',
      personality: ['elegant', 'knowledgeable', 'diplomatic'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined man in his forties with styled dark hair, intelligent eyes, wearing formal vest and tie, holding wine bottle with expertise, sophisticated smile, detailed crosshatching with watercolor wash in burgundy and gold',
    },
    {
      id: 'angela-ponte',
      name: 'Angela Ponte',
      age: 58,
      role: 'cuoca',
      placeId: 'trattoria-ponte-pietra',
      personality: ['nurturing', 'passionate', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a warm-faced woman in her fifties with graying hair, kind brown eyes, wearing chef apron over simple dress, wooden spoon in hand, motherly smile, detailed ink with watercolor in terracotta and cream',
    },
    {
      id: 'massimo-sottoriva',
      name: 'Massimo Sottoriva',
      age: 39,
      role: 'oste',
      placeId: 'osteria-sottoriva',
      personality: ['convivial', 'storyteller', 'wine-loving'],
      portraitPrompt: 'Pen and ink portrait on white paper of an animated man in his late thirties with expressive face, lively eyes, casual shirt with sleeves rolled up, holding wine glass mid-story, infectious grin, detailed pen lines with watercolor in wine red and warm tones',
    },
    {
      id: 'tommaso-vesuvio',
      name: 'Tommaso Vesuvio',
      age: 31,
      role: 'pizzaiolo',
      placeId: 'pizzeria-vesuvio',
      personality: ['energetic', 'skilled', 'proud'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young man with short dark hair, bright eyes, wearing flour-dusted white t-shirt, muscular forearms from kneading dough, confident smile, detailed linework with watercolor wash in warm terracotta and cream',
    },
    {
      id: 'silvia-arena',
      name: 'Silvia Arena',
      age: 29,
      role: 'guida turistica',
      placeId: 'arena-verona',
      personality: ['enthusiastic', 'educated', 'theatrical'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with elegant features, bright intelligent eyes, dark hair in professional style, wearing smart casual clothes, gesture of explanation, passionate expression, detailed pen work with watercolor in rose and cream tones',
    },
    {
      id: 'padre-matteo',
      name: 'Padre Matteo',
      age: 64,
      role: 'sacerdote',
      placeId: 'basilica-san-zeno',
      personality: ['serene', 'scholarly', 'welcoming'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly priest with gentle face, wise gray eyes behind glasses, receding gray hair, wearing simple black clergy shirt, hands clasped peacefully, benevolent smile, detailed crosshatching with watercolor in soft grays and warm cream',
    },
    {
      id: 'valentina-giulietta',
      name: 'Valentina Giulietta',
      age: 26,
      role: 'custode',
      placeId: 'casa-giulietta',
      personality: ['romantic', 'multilingual', 'patient'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with long dark hair, dreamy brown eyes, wearing simple elegant dress, holding love letter, gentle romantic smile, detailed pen work with watercolor wash in soft rose and cream',
    },
    {
      id: 'carlo-giusti',
      name: 'Carlo Giusti',
      age: 71,
      role: 'giardiniere',
      placeId: 'giardino-giusti',
      personality: ['patient', 'knowledgeable', 'peaceful'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly man with weathered kind face, silver hair, gentle blue eyes, wearing garden work clothes, pruning shears in hand, serene smile, detailed linework with watercolor in sage green and earth tones',
    },
    {
      id: 'francesco-bra',
      name: 'Francesco Bra',
      age: 42,
      role: 'musicista di strada',
      placeId: 'piazza-bra',
      personality: ['artistic', 'free-spirited', 'charming'],
      portraitPrompt: 'Pen and ink portrait on white paper of a bohemian man in his forties with shoulder-length dark hair, expressive eyes, wearing casual artistic clothes, holding violin, creative spirit visible in smile, detailed pen work with watercolor in warm gold and burgundy',
    },
    {
      id: 'alessandra-signori',
      name: 'Alessandra Signori',
      age: 36,
      role: 'architetta',
      placeId: 'piazza-signori',
      personality: ['intellectual', 'precise', 'elegant'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sophisticated woman in her mid-thirties with sleek dark hair, sharp intelligent eyes, wearing professional attire, holding architectural drawings, confident composed expression, detailed crosshatching with watercolor in cool gray and cream',
    },
    {
      id: 'riccardo-cangrande',
      name: 'Riccardo Cangrande',
      age: 49,
      role: 'sommelier',
      placeId: 'enoteca-cangrande',
      personality: ['refined', 'passionate', 'educator'],
      portraitPrompt: 'Pen and ink portrait on white paper of a distinguished man in his late forties with salt-and-pepper hair, discerning eyes, wearing smart casual attire, swirling wine glass professionally, knowing smile, detailed pen lines with watercolor in burgundy and warm tones',
    },
    {
      id: 'greta-vino',
      name: 'Greta Vino',
      age: 33,
      role: 'proprietaria',
      placeId: 'osteria-vino-vino',
      personality: ['unpretentious', 'welcoming', 'knowledgeable'],
      portraitPrompt: 'Pen and ink portrait on white paper of a casual young woman with wavy shoulder-length hair, bright friendly eyes, wearing jeans and simple top, pouring wine with ease, genuine warm smile, detailed linework with watercolor wash in wine red and warm cream',
    },
    {
      id: 'beatrice-libri',
      name: 'Beatrice Libri',
      age: 54,
      role: 'librai',
      placeId: 'libreria-rinascimento',
      personality: ['literary', 'thoughtful', 'cultured'],
      portraitPrompt: 'Pen and ink portrait on white paper of an intellectual woman in her fifties with gray-streaked dark hair in loose bun, intelligent eyes behind stylish glasses, wearing elegant simple clothes, holding vintage book tenderly, contemplative smile, detailed crosshatching with watercolor in sepia and cream',
    },
    {
      id: 'dottoressa-marta',
      name: 'Dottoressa Marta Fontana',
      age: 41,
      role: 'farmacista',
      placeId: 'farmacia-centrale',
      personality: ['professional', 'caring', 'efficient'],
      portraitPrompt: 'Pen and ink portrait on white paper of a competent woman in her forties with neat dark hair, attentive brown eyes, wearing white pharmacist coat, holding prescription with care, reassuring professional smile, detailed pen work with watercolor in white and soft green',
    },
    {
      id: 'bruno-albertini',
      name: 'Bruno Albertini',
      age: 63,
      role: 'salumiere',
      placeId: 'salumeria-albertini',
      personality: ['traditional', 'expert', 'generous'],
      portraitPrompt: 'Pen and ink portrait on white paper of a sturdy man in his sixties with thick gray mustache, twinkling eyes, wearing traditional butcher apron, sharp knife in expert hands, proud warm expression, detailed crosshatching with watercolor in rose-red and cream',
    },
    {
      id: 'irene-perlini',
      name: 'Irene Perlini',
      age: 28,
      role: 'pasticciera',
      placeId: 'pasticceria-perlini',
      personality: ['creative', 'cheerful', 'detail-oriented'],
      portraitPrompt: 'Pen and ink portrait on white paper of a young woman with bright eyes, neat ponytail, wearing pink-striped pastry apron, decorating pandoro with precision, delighted smile, detailed pen lines with watercolor wash in soft pink and gold',
    },
    {
      id: 'luca-gelato',
      name: 'Luca Gelato',
      age: 37,
      role: 'gelatiere',
      placeId: 'gelateria-ponte-pietra',
      personality: ['cheerful', 'innovative', 'passionate'],
      portraitPrompt: 'Pen and ink portrait on white paper of a friendly man in his late thirties with warm smile, bright eyes, wearing casual gelato shop uniform, holding gelato scoop, enthusiastic expression, detailed linework with watercolor in pistachio green and cream',
    },
    {
      id: 'paolo-stazione',
      name: 'Paolo Stazione',
      age: 55,
      role: 'capostazione',
      placeId: 'stazione-porta-nuova',
      personality: ['punctual', 'helpful', 'organized'],
      portraitPrompt: 'Pen and ink portrait on white paper of a neat man in his fifties with graying hair, alert eyes, wearing railway uniform with cap, checking pocket watch, professional efficient expression, detailed crosshatching with watercolor in railway blue and gray',
    },
    {
      id: 'emilia-teatro',
      name: 'Emilia Teatro',
      age: 44,
      role: 'regista',
      placeId: 'teatro-romano',
      personality: ['dramatic', 'visionary', 'passionate'],
      portraitPrompt: 'Pen and ink portrait on white paper of an expressive woman in her forties with flowing dark hair, intense artistic eyes, wearing bohemian scarf and artistic clothing, gesturing dramatically, creative fire in expression, detailed pen work with watercolor in deep purple and gold',
    },
    {
      id: 'davide-ponte',
      name: 'Davide Ponte',
      age: 69,
      role: 'storico locale',
      placeId: 'ponte-pietra',
      personality: ['nostalgic', 'storyteller', 'wise'],
      portraitPrompt: 'Pen and ink portrait on white paper of an elderly gentleman with full gray beard, kind weathered face, bright blue eyes, wearing comfortable casual clothes, leaning on walking stick, gentle knowing smile, detailed crosshatching with watercolor in warm stone gray and cream',
    },
    {
      id: 'ornella-acetaia',
      name: 'Ornella Acetaia',
      age: 51,
      role: 'proprietaria',
      placeId: 'acetaia-veneta',
      personality: ['meticulous', 'passionate', 'traditional'],
      portraitPrompt: 'Pen and ink portrait on white paper of a refined woman in her fifties with elegant upswept hair, discerning eyes, wearing stylish apron over good clothes, holding vintage vinegar bottle, proud cultured expression, detailed pen lines with watercolor in amber and deep brown',
    },
  ],
  food: [
    'risotto all\'Amarone',
    'bigoli con le sarde',
    'pastissada de caval',
    'pearà',
    'bollito misto',
    'lesso con la pearà',
    'soppressa veneta',
    'Monte Veronese DOP',
    'radicchio rosso di Verona',
    'riso Vialone Nano',
    'pandoro di Verona',
    'nadalin',
    'torta delle rose',
    'mandorlato',
    'offelle',
    'fritole',
    'brasato all\'Amarone',
    'polenta e osei',
    'baccalà alla vicentina',
    'tortellini di Valeggio',
    'gnocchi di malga',
    'asparagi di Arcole'
  ],
  customs: [
    'Summer opera season at the Arena',
    'Passeggiata in Piazza Bra at sunset',
    'Aperitivo at 6pm with spritz and cicchetti',
    'Writing love letters at Casa di Giulietta',
    'Shopping at Piazza delle Erbe market',
    'Sunday mass at San Zeno',
    'Walking along the Adige river',
    'Wine tasting in Valpolicella hills',
    'Carnival celebrations with gnocchi',
    'Estate Teatrale Veronese summer festival',
    'Coffee at historic cafés in the morning',
    'Evening stroll across Ponte Pietra',
    'Visiting family Sunday lunch traditions',
    'Buying pandoro for Christmas',
    'Watching sunset from Castel San Pietro'
  ],
  localTouches: [
    'Bòn dì - Good morning (Veronese dialect)',
    'Ciao bèlo/bèla - Hello dear (local)',
    'Ció - used for emphasis',
    'Magnar e bever - eating and drinking well',
    'Far filò - evening gathering to chat',
    'Gnanca par gnente - not at all',
    'Amore mio - my love (Romeo & Juliet heritage)',
    'Baco - typical Veronese greeting',
    'Ostrega - expression of surprise',
    'Varda - look (dialect)',
    'Putèo/putèla - boy/girl (dialect)',
    'Ndare par òstarie - going to osterias',
    'S-ciopòn - loud, boisterous person',
    'In Arena - referring to the amphitheater',
    'Pearà e bollito - classic combo phrase'
  ],
};
